-- Business foundations pack: Introduction to Business (course 1 of the business track).
-- A first tour of how businesses work: a diagnostic quiz, template-driven
-- reading lessons (objective + retrieval warm-up, hook, worked examples,
-- practice with answers, misconceptions + exit tickets), two checkpoints,
-- a vocabulary lesson, an applied one-page business plan project, and a
-- scenario-based final assessment. Original content; the topic sequence is
-- adapted from OpenStax Introduction to Business (CC BY 4.0).
-- Fixed UUIDs and guarded inserts make the file idempotent: safe to re-run at any time.

-- ============ Introduction to Business ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0003-0000-4000-8000-000000000001',
  'en', null,
  'Introduction to Business',
  'See how a business really works, from the economy it swims in to the financial statements that keep score: economic foundations, entrepreneurship and forms of ownership, management and leadership, the marketing 4 Ps, operations and supply chains, and accounting basics. Every lesson teaches through realistic company scenarios with fully worked examples and self-checks, and the course ends with your own one-page business plan. Structure adapted from OpenStax Introduction to Business (CC BY 4.0).',
  null, 'foundations', 1, true, 'business', '{}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0003-0000-4000-8000-000000000001', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"A food truck owner has $500 and must choose between a new fryer and a social media ad campaign. She buys the fryer. In economics, the value of the ad campaign she gave up is called the…","options":["sunk cost","opportunity cost","fixed cost","marginal revenue"],"answer":1,"explanation":"Every choice has an opportunity cost: the value of the best alternative you did not pick. If this felt new, start with Lesson 2: Economic foundations & the business environment."},
      {"prompt":"A late frost destroys much of the world coffee crop while cafes keep buying as before. What does supply and demand predict for coffee bean prices?","options":["They fall","They stay the same, because demand is unchanged","They rise","They drop to zero"],"answer":2,"explanation":"Supply shrank while demand held steady, so buyers compete for fewer beans and the price rises. Covered in Lesson 2: Economic foundations & the business environment."},
      {"prompt":"Two friends want to open a design studio, and their top priority is protecting their personal savings if the business is ever sued. Which form of ownership fits best?","options":["sole proprietorship","general partnership","limited liability company (LLC)","an informal handshake agreement"],"answer":2,"explanation":"An LLC separates business debts from the owners'' personal assets; sole proprietors and general partners are personally liable. Covered in Lesson 3: Entrepreneurship & forms of ownership."},
      {"prompt":"A store manager sets quarterly sales targets and decides which product lines each team will focus on next season. Which management function is she performing?","options":["controlling","leading","organizing","planning"],"answer":3,"explanation":"Setting goals and deciding how to reach them is planning, the first of the four management functions. Covered in Lesson 4: Management & leadership."},
      {"prompt":"In the marketing 4 Ps, deciding whether to sell through your own website, a retail chain, or both is a question of…","options":["product","price","place","promotion"],"answer":2,"explanation":"Place covers distribution: how the product physically reaches the customer. Covered in Lesson 6: Marketing fundamentals: the 4 Ps."},
      {"prompt":"A bicycle factory orders parts so they arrive only days before assembly, keeping almost no stock on hand. This approach is called…","options":["economies of scale","just-in-time inventory","outsourcing","benchmarking"],"answer":1,"explanation":"Just-in-time inventory times deliveries to production, trading storage costs for a dependence on reliable suppliers. Covered in Lesson 7: Operations & supply chains."},
      {"prompt":"A candle company had revenue of $8,000 and total expenses of $6,500 last month. Its net income was…","options":["$14,500","$8,000","$1,500","−$1,500"],"answer":2,"explanation":"Net income is revenue minus expenses: 8,000 − 6,500 = $1,500. Covered in Lesson 8: Accounting & financial statements basics."},
      {"prompt":"A startup proudly reports $2 million in revenue. What does that number alone tell you about its profit?","options":["Profit is exactly $2 million","Profit is at least $1 million","Nothing — you also need its expenses","Revenue and profit are the same thing"],"answer":2,"explanation":"Revenue is money coming in before any costs; profit is what remains after expenses, which could even be negative. Key terms like this are collected in Lesson 10: Key terms."}
   ]}',
   null, 10),
  (2, 'Economic foundations & the business environment', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will explain scarcity and opportunity cost, predict how supply and demand move prices, and describe the wider environment — competitors, ethics, and global trade — that every business operates in. A 60-second warm-up from everyday life: (1) A concert sells out in three minutes; were tickets priced above or below what fans were willing to pay? (2) Name two things a lemonade stand must pay for before selling a single cup. Answers: below (that is why they vanished instantly), and things like lemons, cups, sugar, and a permit. If both felt easy, you already think economically."},
      {"heading":"Every business swims in an economy","text":"Mia runs a taco truck. She has $500 left this month and two good uses for it: a faster fryer or an ad campaign a friend swears doubled her own sales. Money, time, and ingredients are all scarce — there is never enough to do everything — so every choice closes a door. The value of the best door she closes is her opportunity cost. Worked example: Mia buys the fryer. Her opportunity cost is not $500; it is the extra sales the ad campaign would have brought. A business is any organization that takes inputs like labor, materials, and money and turns them into goods or services people will pay for, and it makes good decisions by comparing what it gains against what it gives up — including the invisible alternative it said no to."},
      {"heading":"Worked examples","text":"Example 1 — demand shifts: a food blogger raves about Mia''s tacos and the lunch line doubles at the same price. Demand (how much people want to buy at each price) rose, so Mia can raise prices a little or expand. Example 2 — supply shifts: a drought ruins the avocado harvest, so every truck in town pays more for the same crate. Supply fell, the market price of avocados rises, and Mia''s costs climb even though her customers changed nothing. Example 3 — the wider environment: a rival truck parks across the street (competition pushes Mia to differentiate or trim prices); the city raises food-permit fees (government and legal forces); and Mia sources her tortillas from abroad, so a tariff — a tax on imported goods — or a weaker home currency makes them cost more. Businesses also answer to stakeholders beyond owners: customers, employees, suppliers, and the community, which is why acting ethically is not just decoration but part of staying in business."},
      {"heading":"Your turn","text":"Answer, then check. (1) You skip a $15-per-hour shift to study for an exam; what is the opportunity cost of one hour of studying? Answer: $15 in wages, the best alternative you gave up. (2) A heat wave hits and demand for iced drinks jumps; with supply unchanged, what happens to iced-coffee prices? Answer: they tend to rise. (3) A new machine lets every candle maker produce twice as fast; supply rises — what happens to candle prices? Answer: they tend to fall. (4) Is a tariff paid on goods leaving the country or entering it? Answer: entering — it is a tax on imports. (5) Name two stakeholders of a neighborhood gym besides its owner. Answer: examples include members, staff, equipment suppliers, and neighbors. (6) A rival opens next door to Mia and prices tacos $1 cheaper; name one response other than cutting price. Answer: differentiate — better recipes, faster service, loyalty cards, a distinct brand."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: opportunity cost is only about money. Time counts too: a founder working 70-hour weeks is spending hours that had other uses, and honest decisions price those hours in. Misconception 2: businesses can charge whatever they want. Price is a negotiation with the market — charge above what buyers value, and they walk to a competitor or simply keep their money; competition and demand set the ceiling. Exit ticket: (1) Define scarcity in one sentence. Answer: resources are limited while wants are not, so every choice costs an alternative. (2) Demand for a product falls while supply stays the same; what happens to its price? Answer: it tends to fall."}
   ]}',
   'Study tip: when a price moves, always ask which side shifted — did buyers change (demand) or did producers change (supply)? Naming the side first prevents most errors.', 13),
  (3, 'Entrepreneurship & forms of ownership', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will describe what entrepreneurs do, explain why a business plan matters, and choose among sole proprietorships, partnerships, LLCs, corporations, and franchises. Warm-up from Lesson 2: (1) A founder quits a $60,000 job to launch a startup; what is her yearly opportunity cost before the startup earns a cent? (2) If demand for home-office desks surges, what happens to desk prices? Answers: $60,000 in forgone salary, and prices tend to rise. Entrepreneurship is the art of betting that the opportunity is worth its opportunity cost."},
      {"heading":"From idea to legal reality","text":"Dev spends his weekends fixing bicycles for friends. Requests keep coming, and he wonders whether Spoke & Sprocket could be a real business. An entrepreneur is someone who spots an opportunity, accepts the risk, and organizes the resources to chase it. Before spending money, Dev writes a business plan: a short document naming his target customer, what makes his service different, his prices, his costs, and how much cash he needs to survive the first year. Worked example: Dev''s plan reveals that rent for a shop would eat every peso of projected profit, so he starts as a mobile repair service instead — the plan just saved him from a bad lease. Plans rarely survive contact with real customers unchanged, but writing one forces every fuzzy assumption into the open where it can be tested."},
      {"heading":"Worked examples","text":"Example 1 — sole proprietorship: Dev registers nothing special and operates alone. It is cheap and instant, he keeps all profits, and taxes flow through his personal return; but he is personally liable, meaning a lawsuit or debt can reach his savings and his car. Example 2 — partnership and LLC: Dev''s friend Rosa joins with $10,000 and mechanical skills. As a general partnership they share profits, losses, and unlimited personal liability — including for each other''s mistakes — so they instead form a limited liability company (LLC), which keeps the easy pass-through taxes but builds a legal wall between business debts and personal assets, and they sign a written operating agreement covering who owns what and how a breakup would work. Example 3 — corporation and franchise: years later, growth needs serious money. A corporation is a separate legal entity that sells shares of ownership to investors, offers the strongest liability shield, and outlives its founders, at the price of more paperwork and, for standard C corporations, taxation at the company level and again on dividends. The shortcut path some entrepreneurs pick instead is a franchise: buying the right to run a proven brand''s playbook, trading fees and independence for a tested formula."},
      {"heading":"Your turn","text":"Answer, then check. (1) Elena sells pottery at markets under her own name with no formal registration; what form is her business? Answer: a sole proprietorship. (2) What is the single biggest risk of a general partnership? Answer: unlimited personal liability, including for a partner''s business decisions. (3) Which form lets a company raise money by selling shares to many investors? Answer: a corporation. (4) Name two things a business plan should state about customers. Answer: who the target customer is and why they would pay — the problem being solved. (5) Maria opens a unit of a national coffee chain, paying an upfront fee plus a share of sales; what is this arrangement? Answer: a franchise. (6) Why might two founders choose an LLC over a general partnership even though both share profits? Answer: the LLC protects each founder''s personal assets from business debts and lawsuits."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: a great product sells itself, so planning is a waste of time. Most failed startups built something before confirming anyone would pay; the plan''s job is to expose that assumption early and cheaply. Misconception 2: corporation means big company. A one-person business can incorporate, and some huge firms are private partnerships — the form is about liability, taxes, and fundraising, not size. Exit ticket: (1) Which forms leave owners personally liable for business debts? Answer: sole proprietorships and general partnerships. (2) Give one advantage and one disadvantage of buying a franchise. Answer: a proven brand and playbook, but ongoing fees and limited freedom to change the formula."}
   ]}',
   'Study tip: to memorize the ownership forms, rank them twice — once by liability protection and once by paperwork. Notice the two rankings almost mirror each other.', 13),
  (4, 'Management & leadership', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will name the four functions of management, compare leadership styles, and explain what actually motivates people at work. Warm-up from Lesson 3: (1) Which ownership form gives founders pass-through taxes plus a personal-liability shield? (2) What document forces a founder''s assumptions into the open before launch? Answers: an LLC, and a business plan. A plan on paper changes nothing by itself — management is how plans become results through other people."},
      {"heading":"The day the best barista became the boss","text":"Sofia was the fastest barista at Harbor Coffee, so the owner promoted her to manager of the new second location — and her job changed completely. Her output is no longer perfect lattes; it is a team that produces them without her touching a cup. Management runs on four functions. Planning: set goals and decide how to reach them. Organizing: arrange people, money, and equipment so the plan can happen. Leading: motivate and guide people to do the work. Controlling: measure results against the goals and correct course. Worked example: Sofia plans a launch-month target of 300 customers per day, organizes the schedule so two baristas always cover the morning rush, leads by training everyone on the espresso machine herself and celebrating small wins, and controls by checking daily sales — when Tuesdays lag at 210, she shifts a promotion to Tuesdays. All four functions, one week."},
      {"heading":"Worked examples","text":"Example 1 — structure: with 12 employees, Sofia cannot personally direct everyone, so she names two shift leads. Her span of control (how many people report to one manager) shrinks to something workable, and the shop gains a second layer — a slightly taller structure trades speed for order, while flat structures with wide spans stay nimble but stretch each manager thin. Example 2 — leadership styles: during a morning-rush equipment failure Sofia is autocratic, issuing quick orders because seconds matter; choosing the winter menu she is democratic, putting it to a team vote because buy-in matters; with her experienced weekend lead she is free-rein, setting the goal and stepping back. The skill is matching the style to the situation, not owning one style. Example 3 — motivation: Sofia gives a raise to a barista who was underpaid and the grumbling stops, but effort barely changes — fair pay and decent conditions mostly prevent dissatisfaction. What lifts performance is different fuel: recognition, growing skills, and real responsibility. So she starts a latte-art contest and lets the winner design a seasonal special, and the extrinsic reward (prize) plus intrinsic reward (pride and ownership) do what money alone did not. Hiring the right people, training them, and reviewing them fairly — human resources — is what makes all of this possible."},
      {"heading":"Your turn","text":"Answer, then check. (1) A warehouse manager compares this week''s shipping errors to the target rate and retrains one crew; which function is that? Answer: controlling. (2) Designing who reports to whom on a new project is which function? Answer: organizing. (3) During a kitchen fire drill, which leadership style fits best? Answer: autocratic — clear, fast orders in an emergency. (4) A manager with 40 direct reports has what kind of span of control? Answer: a very wide one, likely too wide to give anyone real attention. (5) Which is the intrinsic motivator: a $50 gift card, or mastering the espresso machine well enough to train others? Answer: the mastery — it satisfies from the inside. (6) Sofia''s sales target of 300 customers a day belongs to which function? Answer: planning."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: managing means telling people what to do. Commanding is a sliver of one function; most management hours go to planning, arranging resources, removing obstacles, and measuring — the quiet functions that make commands rarely necessary. Misconception 2: money is the only motivator that works. Unfair pay demotivates powerfully, but beyond a fair level, recognition, growth, and ownership move performance more per dollar than raises alone. Exit ticket: (1) List the four functions of management in order. Answer: planning, organizing, leading, controlling. (2) Which leadership style hands an experienced team the goal and gets out of the way? Answer: free-rein (laissez-faire)."}
   ]}',
   'Study tip: tag every workplace anecdote you hear with one of the four functions — P, O, L, or C. The habit turns stories into flashcards.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"In a market economy, prices are mainly set by…","options":["government agencies","the interaction of buyers and sellers","the largest company in each industry","tradition"],"answer":1,"explanation":"Markets set prices through supply and demand — countless buyers and sellers negotiating, not a central authority."},
      {"prompt":"A tariff is best described as…","options":["a tax on imported goods","a limit on how much may be exported","a subsidy paid to local firms","a fee for registering a trademark"],"answer":0,"explanation":"A tariff taxes imports, raising their price to shield local producers — and raising costs for businesses that buy foreign inputs."},
      {"prompt":"Elena runs her shop alone with no legal paperwork beyond a local license. She keeps all profits but is personally responsible for all business debts. Her business is a…","options":["corporation","limited liability company","sole proprietorship","franchise"],"answer":2,"explanation":"One owner, easy setup, full profits, and unlimited personal liability define the sole proprietorship."},
      {"prompt":"Compared with a general partnership, the biggest advantage of forming a corporation is…","options":["less paperwork","limited liability for its owners","paying no taxes at all","being guaranteed a bank loan"],"answer":1,"explanation":"A corporation is a separate legal entity, so owners'' personal assets are shielded from business debts. It costs more paperwork, not less."},
      {"prompt":"Before launching, an entrepreneur writes down her target customer, pricing, projected costs, and funding needs. This document is a…","options":["mission statement","business plan","balance sheet","press release"],"answer":1,"explanation":"A business plan lays out the who, what, and how much before real money is spent, exposing weak assumptions early."},
      {"prompt":"A supervisor checks weekly output against targets and adjusts staffing when the numbers slip. Which management function is this?","options":["planning","organizing","leading","controlling"],"answer":3,"explanation":"Measuring results against goals and correcting course is controlling — the feedback loop of management."},
      {"prompt":"Which of these is an intrinsic motivator?","options":["a quarterly bonus","a reserved parking spot","pride in mastering a difficult new skill","a gift card"],"answer":2,"explanation":"Intrinsic motivation comes from inside — mastery, purpose, ownership. The other three are external rewards handed to you."}
   ]}',
   null, 9),
  (6, 'Marketing fundamentals: the 4 Ps', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will define marketing as delivering value to a chosen customer, segment a market, and design a marketing mix using the 4 Ps: product, price, place, and promotion. Warm-up from earlier lessons: (1) From Lesson 2 — if two taco trucks sell identical tacos on the same corner, what happens to their prices? (2) From Lesson 3 — what document states who your target customer is before launch? Answers: competition pushes prices down toward cost, and the business plan. Marketing is how a business escapes that identical-taco trap: by being deliberately different for a deliberately chosen customer."},
      {"heading":"Nobody buys a candle — they buy a cozy evening","text":"Priya''s candle company, Wick & Whistle, makes wonderful candles that barely sell, while an inferior competitor thrives. The difference is marketing: the whole process of figuring out who your customer is, what they value, and how to deliver and communicate that value — not just ads slapped on at the end. Priya starts with segmentation, dividing the big vague market into groups with shared needs: budget shoppers buying scent by the kilo, gift buyers wanting beautiful packaging, and eco-conscious buyers who read every label. She cannot win them all, so she targets the gift buyers — her hand-poured look fits them best — and positions Wick & Whistle in their minds as the effortless, impressive gift under $25. Worked example: everything now flows from that choice. A target customer plus a clear value proposition turns every later decision — packaging, price, stores, ads — from a guess into a checklist item: does this serve the gift buyer, yes or no?"},
      {"heading":"Worked examples","text":"Example 1 — product and price: for gift buyers, the product is more than wax: gift box, ribbon, a scent card — the whole experience. Pricing has strategies, not just numbers. Cost-plus starts from her $6 cost and adds a markup; price skimming launches high to capture eager buyers of something new, then drops over time; penetration pricing launches low to grab market share fast, then rises. Priya picks $24 with premium packaging — under the gift-budget ceiling she observed, far above cost-plus, because gift buyers read a too-cheap price as a too-cheap gift. Example 2 — place: her gift buyer shops in boutiques and museum shops, not supermarkets, so Priya sells through those channels plus her website, accepting that each boutique takes a cut in exchange for reaching customers she never could alone. Distribution is a trade: margin for reach. Example 3 — promotion is a mix of four tools: advertising (paid messages — her Instagram ads), personal selling (conversations at craft fairs), sales promotion (short-term nudges — a holiday two-for-one), and public relations (earned attention — a local magazine features her studio after she sends a press release). The free article outperforms every paid ad that month, because readers trust a journalist more than a promotion."},
      {"heading":"Your turn","text":"Answer, then check. (1) A university gym offers a 6 a.m. class for staff and an afternoon class for students; what marketing practice is that? Answer: segmentation — serving different groups with tailored offers. (2) A software firm launches at $9.99 to build a huge user base fast, planning increases later; which pricing strategy? Answer: penetration pricing. (3) Which of the 4 Ps is at stake when a hot-sauce brand debates farmers'' markets versus supermarket shelves? Answer: place. (4) A jeweler''s booth conversation that ends in a sale is which promotion tool? Answer: personal selling. (5) Why might a luxury watch brand refuse to cut prices even when sales dip? Answer: a high price is part of its positioning — cutting it would cheapen the brand''s meaning to its segment. (6) Write a one-sentence value proposition for a bike-repair service that visits offices. Answer: for example — for commuting cyclists, we fix your bike at your workplace the same day, so you never lose a riding day to a shop queue."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: marketing means advertising. Advertising is one tool inside one P; choosing the customer, designing the product, setting the price, and picking the channels are all marketing, and they happen long before any ad runs. Misconception 2: the lowest price always wins. Price signals meaning — a $3 birthday gift candle feels wrong to Priya''s segment; customers buy the best value for their need, and value can mean quality, convenience, or status as easily as cheapness. Exit ticket: (1) Name the 4 Ps. Answer: product, price, place, promotion. (2) Which promotion tool earned Priya coverage she did not pay for? Answer: public relations."}
   ]}',
   'Study tip: for any product you see today, name its target customer and its 4 Ps in one breath — the mix only makes sense once you know who it is for.', 14),
  (7, 'Operations & supply chains', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will describe operations as a transformation process, trace a supply chain, weigh just-in-time against just-in-case inventory, and spot the bottleneck in a process. Warm-up from Lesson 6: (1) Which of the 4 Ps covers how a product reaches the customer? (2) Setting a low launch price to win customers fast is called what? Answers: place, and penetration pricing. Place promises the product will be there — operations is how a business keeps that promise."},
      {"heading":"Follow one burrito through the machine","text":"Lunch rush at Rollo''s Burritos: a line of 20 people, and somehow everyone is fed in 15 minutes. Operations management designs and runs the process that turns inputs (tortillas, rice, labor, the grill) into outputs (finished burritos) — a transformation every business performs, whether it makes goods or delivers services. Worked example: Rollo maps his process into stations: order taking, filling, wrapping, payment. Timing each station shows filling takes 45 seconds while every other station takes 20. Filling is the bottleneck — the slowest step that sets the pace of the whole line — so a second filling station, not a faster cashier, is what shortens the line. Improving anything except the bottleneck improves nothing."},
      {"heading":"Worked examples","text":"Example 1 — the supply chain is every organization a product touches on its way to the customer: a farm grows tomatoes, a salsa maker processes them, a distributor trucks jars to Rollo''s supplier, and Rollo serves the final burrito. A delay at any link — the farm floods, the trucker strikes — ripples all the way downstream, which is why businesses map their chains and keep backup suppliers. Example 2 — inventory strategy: Rollo could hold just-in-time inventory, receiving produce daily so nothing wilts and no money sits on shelves, but one missed delivery halts lunch; or just-in-case buffer stock, which survives hiccups but ties up cash and risks spoilage. He lands on JIT for produce and a buffer for foil and napkins — matching the strategy to how perishable and how critical each input is. Example 3 — quality and technology: instead of inspecting finished burritos and discarding failures, Rollo builds quality into the process — portion scoops, a wrapping checklist, and the rule that anyone may halt the line on spotting a problem. His point-of-sale system quietly logs every order, so data, not memory, tells him Tuesdays need less rice prepped and which salsa is fading; modern operations run on exactly this kind of information."},
      {"heading":"Your turn","text":"Answer, then check. (1) A car wash''s drying station takes 6 minutes while washing takes 4; which station limits cars per hour? Answer: drying — it is the bottleneck. (2) Name the links in the supply chain of a cotton T-shirt, farm to shopper. Answer: cotton farm, spinner/fabric mill, garment factory, distributor or wholesaler, retailer, customer. (3) A hospital keeps 90 days of critical medicines despite the storage cost; JIT or just-in-case, and why? Answer: just-in-case — a stockout could cost lives, so the buffer is worth it. (4) Rollo''s new grill cooks twice as fast, but the line moves no quicker; what does that tell you? Answer: the grill was not the bottleneck — the constraint is elsewhere. (5) What is one advantage and one risk of JIT? Answer: less cash and space tied up in stock, but a single supply hiccup stops production. (6) Is a haircut an operations process? Answer: yes — inputs (stylist time, tools) transform a shaggy customer into the output, a finished cut; services are operations too."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: more inventory is always safer. Stock ties up cash, fills space, spoils, and goes out of style; safety has a price, and good operations buy exactly as much safety as each input deserves. Misconception 2: quality is the inspector''s job at the end of the line. Inspection finds defects after the money is spent making them; building quality into each step — checklists, standard portions, stop-the-line authority — prevents them at the source. Exit ticket: (1) Define bottleneck in one sentence. Answer: the slowest step in a process, which sets the maximum pace of the whole process. (2) Which inventory approach has almost no buffer stock? Answer: just-in-time."}
   ]}',
   'Study tip: to find any bottleneck, time each step separately and circle the slowest — the whole system can never run faster than that circle.', 13),
  (8, 'Accounting & financial statements basics', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will read an income statement and a balance sheet, tell profit apart from cash flow, and compute a margin and a break-even point. Warm-up from Lesson 7: (1) What is the slowest step of a process called? (2) Which inventory strategy trades buffer stock for lower storage costs? Answers: the bottleneck, and just-in-time. Operations produces the value; accounting keeps the score."},
      {"heading":"The month Wick & Whistle finally kept score","text":"Priya''s candle business, Wick & Whistle, felt busy all month, but is it actually making money? Accounting answers with the income statement, which covers a period of time: revenue (money earned from sales) at the top, then costs subtracted in layers. Worked example: Priya sold 400 candles at $20, so revenue is $8,000. Wax, wicks, and jars cost $6 per candle, so cost of goods sold is $2,400, leaving gross profit of $5,600 — a gross margin of 5,600 ÷ 8,000 = 70%. Then operating expenses (booth fees, website, packaging, her part-time helper) total $4,100, leaving net income of $1,500. Busy was real, but the layers show where the money went — and margin, profit as a share of revenue, lets her compare a $8,000 month against a $80,000 one fairly."},
      {"heading":"Worked examples","text":"Example 1 — the balance sheet is a snapshot at one moment, built on one equation: assets = liabilities + owners'' equity. Wick & Whistle owns $9,000 of assets (cash, equipment, inventory) and owes a $4,000 small-business loan, so Priya''s equity — the owners'' true stake — is $5,000. The equation always balances, because everything a business owns was financed either by borrowing or by its owners. Example 2 — profit is not cash: a hotel orders 500 candles in March, taking delivery now and paying in May. March revenue and profit look wonderful, but March cash actually falls, since Priya paid for wax up front. Profitable companies can die waiting for customers to pay, which is why the cash flow statement tracks money actually moving, and why Priya watches her cash balance weekly no matter what the income statement says. Example 3 — break-even: Priya considers a mall kiosk costing $1,400 per month in fixed costs. Each candle contributes $20 − $6 = $14 toward those costs, so she breaks even at 1,400 ÷ 14 = 100 candles per month; the 101st candle is where profit begins. To grow beyond kiosks she can raise money the way most firms do: borrow from a bank or bondholders (debt, which must be repaid with interest) or sell shares of ownership (equity, which costs a slice of control and future profits instead)."},
      {"heading":"Your turn","text":"Answer, then check. (1) Revenue is $12,000 and total expenses are $9,000; what is net income? Answer: $3,000. (2) A firm has assets of $90,000 and liabilities of $60,000; what is owners'' equity? Answer: $30,000, from the accounting equation. (3) Which statement covers a period, and which is a snapshot of a single day? Answer: the income statement covers a period; the balance sheet is the snapshot. (4) Gross profit is $5,000 on revenue of $20,000; what is the gross margin? Answer: 25%. (5) Fixed costs are $2,000 a month and each unit contributes $8; how many units to break even? Answer: 250 units. (6) A bakery lands its biggest order ever but must buy flour today and wait 60 days for payment; what should it check before celebrating? Answer: its cash flow — whether cash on hand covers the gap until the customer pays."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: profit means cash in the bank. Profit counts sales when earned, not when paid; a profitable month can drain cash if customers pay slowly while suppliers demand money now. Misconception 2: high revenue means a healthy business. Revenue is the top line only — a company can sell millions at a loss on every unit, so always read down to margin and net income before judging. Exit ticket: (1) State the accounting equation. Answer: assets = liabilities + owners'' equity. (2) Revenue $10,000, cost of goods sold $4,000; what is gross profit? Answer: $6,000."}
   ]}',
   'Study tip: read any income statement top to bottom as a story — revenue, minus making it, minus running the business — and pause to compute the margin at each subtraction.', 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"A gym markets a 6 a.m. bootcamp to commuters and a mid-morning stretch class to retirees. Dividing customers into groups like this is called…","options":["market segmentation","price skimming","benchmarking","franchising"],"answer":0,"explanation":"Segmentation splits a market into groups with shared needs so each can be served with a tailored offer."},
      {"prompt":"A streaming service launches at a deliberately low price to attract subscribers quickly, planning to raise prices later. This strategy is…","options":["price skimming","prestige pricing","penetration pricing","cost-plus pricing"],"answer":2,"explanation":"Penetration pricing sacrifices early margin to win market share fast; skimming does the opposite, starting high."},
      {"prompt":"A local newspaper runs a free news story about a bakery''s charity drive after receiving its press release. In the promotion mix, the story is…","options":["advertising","public relations","personal selling","sales promotion"],"answer":1,"explanation":"Earned media from press outreach is public relations — unpaid and therefore more credible, but not fully controlled."},
      {"prompt":"In a T-shirt supply chain, the company that buys fabric from a mill, sews the shirts, and sells them to retailers is the…","options":["wholesaler","retailer","manufacturer","end consumer"],"answer":2,"explanation":"The manufacturer transforms raw inputs (fabric) into finished goods; wholesalers and retailers move them onward."},
      {"prompt":"At a sandwich shop, orders pile up at the single toaster while every other station waits. The toaster is the process''s…","options":["buffer","bottleneck","supply chain","fixed cost"],"answer":1,"explanation":"The slowest step paces the whole process. Adding toaster capacity — not a faster cashier — speeds the line."},
      {"prompt":"A firm has assets of $150,000 and liabilities of $90,000. Its owners'' equity is…","options":["$240,000","$90,000","$60,000","$150,000"],"answer":2,"explanation":"Assets = liabilities + equity, so equity is 150,000 − 90,000 = $60,000."},
      {"prompt":"Which financial statement reports revenues and expenses over a period of time?","options":["the balance sheet","the income statement","the cash flow statement","the operating agreement"],"answer":1,"explanation":"The income statement covers a period (a month, a quarter, a year); the balance sheet is a snapshot of one moment."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"revenue","translation":"the money a business earns from selling its goods or services, before any costs are subtracted","example":"Wick & Whistle sold 400 candles at $20 each, so its revenue was $8,000 — the top line, not the profit."},
      {"term":"margin","translation":"profit expressed as a percentage of revenue, showing how much of each sales dollar the business keeps","example":"Gross profit of $5,600 on revenue of $8,000 is a 70% gross margin — 70 cents of every dollar survives the cost of making the candles."},
      {"term":"equity","translation":"the owners'' stake in a business: what would remain if all assets were sold and all debts paid","example":"With $9,000 in assets and a $4,000 loan, Priya''s equity in her candle business is $5,000."},
      {"term":"supply chain","translation":"the whole sequence of organizations and steps that moves a product from raw materials to the final customer","example":"A T-shirt''s supply chain runs from cotton farm to fabric mill to garment factory to retailer before it ever reaches you."},
      {"term":"value proposition","translation":"a clear statement of why a customer should buy from you instead of anyone else","example":"We deliver fresh groceries to night-shift workers within 30 minutes is a value proposition: a specific promise to a specific customer."},
      {"term":"fixed cost","translation":"a cost that stays the same no matter how much you sell, such as rent or insurance","example":"The mall kiosk costs $1,400 a month whether Priya sells one candle or one thousand — that is a fixed cost."},
      {"term":"break-even point","translation":"the sales level at which total revenue exactly covers total costs, so profit is zero","example":"With $1,400 in fixed costs and $14 of contribution per candle, the kiosk breaks even at 100 candles a month."},
      {"term":"cash flow","translation":"the actual movement of money into and out of a business, as opposed to profit on paper","example":"The hotel order was profitable in March, but cash flow was negative until the customer finally paid in May."}
   ]}',
   null, 8),
  (11, 'Applied project: one-page business plan', 'writing',
   '{"sections":[
      {"heading":"Objective & setup","text":"In this project you will write a one-page business plan for an idea of your own, using everything from Lessons 2 through 8. Quick retrieval before you draft: (1) What is a value proposition? (2) What is a fixed cost? (3) What does break-even mean? Answers: a clear statement of why your customer should buy from you; a cost that does not change with sales, like rent; the sales level where revenue exactly covers costs. Pick any idea — a repair service, a snack brand, an app, a tutoring service. Small and concrete beats grand and vague: Dev''s mobile bike repair made a better plan than a vague global platform ever would. Write your plan in eight short blocks, following the parts below."},
      {"heading":"Part 1: Idea, customer & value proposition","text":"Block 1 — Idea: describe your product or service in two sentences a stranger would understand. Name what it is, not just what it dreams of being. Block 2 — Customer: name your target segment as specifically as you can. Not everyone who eats — office workers within three blocks who have 20 minutes for lunch. Recall from Lesson 6 that a segment you can picture is a segment you can reach. Block 3 — Value proposition: one sentence in the form: for [customer], we do [what] better than [alternative] because [reason]. Example: for commuting cyclists, we repair bikes at their office parking lot the same day, so they never lose a riding day to a shop queue. If your sentence could describe any competitor, sharpen it until it could not."},
      {"heading":"Part 2: Revenue model & costs","text":"Block 4 — Revenue model: state what you charge, per what unit, and estimate a realistic monthly volume. Example: $45 per standard tune-up, 60 tune-ups a month, so about $2,700 in monthly revenue. Say where the number comes from — even a rough count of nearby cyclists beats a guess. Block 5 — Costs: split them the way Lesson 8 did. Fixed costs per month (tools lease, insurance, website) and variable cost per unit (parts, transport per job). Then compute your break-even: fixed costs divided by the contribution each sale makes. Example: $900 fixed, $15 variable per $45 tune-up, so contribution is $30 and break-even is 30 tune-ups a month. Write the arithmetic into the plan — a plan with numbers can be wrong, which means it can be fixed; a plan without numbers can only be hoped about."},
      {"heading":"Part 3: Risks & your pitch paragraph","text":"Block 6 — Risks: list your three biggest, drawn from the whole course: a demand risk (Lesson 2 — what if the market shrinks or a rival undercuts you?), an operations risk (Lesson 7 — which supplier or bottleneck could halt you?), and a cash risk (Lesson 8 — what gap between paying costs and collecting revenue could sink you?). For each, add one sentence on how you would respond. Block 7 — Pitch paragraph: close with five to seven sentences you could say aloud in one minute: the customer and their problem, your solution and value proposition, your price and break-even, why you are the right person, and what you need next (money, a permit, a first customer). No new facts here — the pitch is your plan compressed, and if something will not compress, it was probably decoration."},
      {"heading":"Self-check rubric","text":"Before you call the plan done, score each line yes or no. (1) Idea: could a stranger repeat what you sell after one reading? (2) Customer: did you name a specific segment rather than everyone? (3) Value proposition: does it name customer, benefit, and why-you, and fail to fit your competitors? (4) Revenue model: are price, unit, and estimated volume all stated with a source? (5) Costs: are fixed and variable costs separated, and is the break-even computed correctly — check the division. (6) Risks: do you cover demand, operations, and cash, each with a response? (7) Pitch: does it stay under one minute aloud with no facts that are absent from the plan? (8) Whole page: does it fit on one page? Seven or eight yes answers: ready to share. Five or six: revise the weakest two blocks. Fewer: pick a smaller, more concrete idea and rebuild — that is not failure, it is the plan doing its job before real money was involved."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"During a storm, a ride-share app raises prices and more drivers log on to work. In this scenario the higher price acted as…","options":["a tariff on riders","an incentive that increased supply","a fixed cost","a form of advertising"],"answer":1,"explanation":"Prices carry signals: the higher fare pulled more drivers onto the road, increasing supply exactly when demand spiked."},
      {"prompt":"A US candle maker imports glass jars, and the dollar weakens against the supplier''s currency. What happens to the maker''s jar costs?","options":["They fall","They are unaffected, because the contract is in jars","They rise","They drop to zero"],"answer":2,"explanation":"A weaker home currency buys less foreign currency, so imported inputs cost more — a global-environment risk from Lesson 2."},
      {"prompt":"Marco wants outside investors who buy ownership shares they can later resell, and he hopes to list the company publicly one day. Which form of ownership fits?","options":["sole proprietorship","general partnership","corporation","franchise"],"answer":2,"explanation":"Corporations raise money by selling transferable shares and can go public; the other forms cannot offer that path."},
      {"prompt":"A new team leader spends her week rallying staff around a revised mission and coaching two struggling employees one-on-one. Which management function dominates her week?","options":["planning","organizing","leading","controlling"],"answer":2,"explanation":"Motivating, guiding, and developing people is leading. No targets were set (planning) or measured (controlling) here."},
      {"prompt":"A headphone brand launches its flagship at a deliberately high price to signal quality and recover research costs from eager early buyers, planning cuts later. This is…","options":["penetration pricing","cost-plus pricing","price skimming","break-even pricing"],"answer":2,"explanation":"Skimming starts high for the eager segment, then lowers the price in waves — the mirror image of penetration pricing."},
      {"prompt":"A toy company expects holiday demand to spike tenfold, so it abandons just-in-time and builds up inventory from September. What is the main cost of that choice?","options":["its products become lower quality","cash and storage are tied up in stock that may not sell","its supply chain gets shorter","its fixed costs disappear"],"answer":1,"explanation":"Buffer stock buys safety against a stockout, but the price is cash locked in inventory, storage costs, and leftover-stock risk."},
      {"prompt":"A studio has revenue of $120,000, cost of goods sold of $70,000, and operating expenses of $30,000. Its net income is…","options":["$50,000","$20,000","$90,000","$100,000"],"answer":1,"explanation":"Gross profit is 120,000 − 70,000 = $50,000; subtracting $30,000 of operating expenses leaves $20,000 of net income."},
      {"prompt":"In an investor pitch, the sentence We deliver fresh groceries to night-shift nurses within 30 minutes is the company''s…","options":["mission statement about employees","value proposition","balance sheet","span of control"],"answer":1,"explanation":"It names a specific customer, the benefit, and what beats the alternatives — the definition of a value proposition."}
   ]}',
   null, 10)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0003-0000-4000-8000-000000000001' and l.position = v.pos
);
