-- Math foundations pack: Introductory Statistics (course 5 of the math track).
-- Takes learners from raw data to inference intuition with a diagnostic quiz,
-- template-driven reading lessons (objective + retrieval warm-up, hook,
-- worked examples, practice with answers, misconceptions + exit tickets),
-- two checkpoints, a vocabulary lesson, an applied data project, and a final
-- assessment. Lesson sequence adapted from the chapter structure of OpenStax
-- Introductory Statistics 2e (CC BY 4.0); all lesson text is original.
-- Prerequisite: course bbbb0001-...-0003. Fixed UUIDs and guarded inserts
-- make the file idempotent: safe to re-run at any time.

-- ============ Introductory Statistics ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0001-0000-4000-8000-000000000005',
  'en', null,
  'Introductory Statistics',
  'Learn to think like a data detective: gather trustworthy samples, summarize data with centers, spreads, and honest graphs, reason with probability, meet the normal curve and the Central Limit Theorem, and build real intuition for confidence intervals and hypothesis tests. Every lesson teaches through polls, games, commutes, and everyday measurements with fully worked examples, self-checks, and a hands-on data project. Structure adapted from OpenStax Introductory Statistics 2e (CC BY 4.0).',
  null, 'foundations', 5, true, 'math', '{bbbb0001-0000-4000-8000-000000000003}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0001-0000-4000-8000-000000000005', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"A university has 12,000 students. A researcher interviews 200 of them about sleep habits. The 200 students are called the…","options":["population","sample","parameter","census"],"answer":1,"explanation":"The whole group of 12,000 is the population; the 200 actually measured are the sample. If this felt hard, start with Lesson 2: Sampling & data."},
      {"prompt":"Find the mean of 4, 8, 9, 15.","options":["8","9","10","12"],"answer":1,"explanation":"Total 36 divided by 4 values gives 9. Centers and spreads are covered in Lesson 3: Descriptive statistics."},
      {"prompt":"A fair six-sided die is rolled once. What is the probability of rolling a number greater than 4?","options":["1/6","1/3","1/2","2/3"],"answer":1,"explanation":"Two outcomes qualify (5 and 6) out of six equally likely outcomes: 2/6 = 1/3. Covered in Lesson 4: Probability basics."},
      {"prompt":"Test scores have mean 75 and standard deviation 5. What is the z-score of a score of 85?","options":["0.5","1","2","10"],"answer":2,"explanation":"z = (85 − 75) ÷ 5 = 2, meaning two standard deviations above the mean. Covered in Lesson 6: Distributions & the normal curve."},
      {"prompt":"As the sample size grows, the distribution of sample means becomes…","options":["exactly the same shape as the population","approximately normal","more spread out than the population","uniform"],"answer":1,"explanation":"That is the Central Limit Theorem: averages pile up in a bell shape around the population mean. Covered in Lesson 7."},
      {"prompt":"A 95% confidence interval for a population mean is (48, 52). The best reading is:","options":["95% of all data values fall between 48 and 52","the population mean is definitely 50","we are 95% confident the population mean lies between 48 and 52","the sample mean has a 95% chance of being in the interval"],"answer":2,"explanation":"The interval targets the unknown population mean, and the 95% describes how often the method succeeds. Covered in Lesson 8."},
      {"prompt":"A study reports a p-value of 0.01. This means:","options":["the null hypothesis is true","data this extreme would be very surprising if the null hypothesis were true","the alternative hypothesis is proven","the sample was too small"],"answer":1,"explanation":"A small p-value says the observed data would rarely happen under the null hypothesis, which is evidence against it. Covered in Lesson 8 and the Key terms lesson."},
      {"prompt":"A histogram of household incomes shows most bars piled on the left with a long tail stretching right. Which is larger?","options":["the median","the mean","they must be equal","neither can be compared"],"answer":1,"explanation":"A long right tail drags the mean above the median — the classic sign of right skew. Covered in Lesson 3: Descriptive statistics."}
   ]}',
   null, 10),
  (2, 'Sampling & data', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will tell populations from samples, classify data types, and judge sampling methods for bias. Warm-up from earlier math courses — compute each: (1) What is 20% of 60? (2) Find the mean of 6, 10, 14. (3) Find the median of 3, 9, 5. Answers: 12, 10, and 5. If the mean or median felt shaky, review them before continuing, because this whole course is built on summarizing collected numbers."},
      {"heading":"Who does your data speak for?","text":"A cook does not drink the whole pot to check the soup — one well-stirred spoonful is enough. Statistics works the same way. The population is the entire group you want to know about (every adult in a country, every battery off a production line); the sample is the smaller group you actually measure. A number describing the population is a parameter; the same kind of number computed from the sample is a statistic, your best guess at the parameter. Data come in flavors: qualitative (categorical) data are labels, like favorite genre or eye color; quantitative data are counts or measurements. Quantitative data split again: discrete values come from counting (number of shows watched: 0, 1, 2, …), while continuous values come from measuring (hours watched: 3.75 is possible). Worked example: a streaming survey records favorite genre (qualitative), number of shows finished this month (quantitative discrete), and total hours watched (quantitative continuous)."},
      {"heading":"Worked examples","text":"Example 1 — simple random sampling: to sample 50 students from a roster of 900, number everyone and let a random number generator pick 50. Every group of 50 has an equal chance; this is the gold standard the word random actually means. Example 2 — other fair designs: split the school by grade level and randomly pick students within each grade (stratified — guarantees every grade a voice); randomly pick 3 whole classrooms and survey everyone inside them (cluster — cheaper when groups are scattered); survey every 10th customer through the door (systematic). Example 3 — how sampling goes wrong: standing outside a gym to ask people how much they exercise is a convenience sample, and it overstates exercise badly because gym-goers were the easiest people to reach. An online poll where volunteers opt in has voluntary response bias: people with strong feelings answer, everyone else scrolls past. A biased method stays biased no matter how many people it reaches."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) A quality inspector tests 40 batteries from a shipment of 5,000; name the sample. Answer: the 40 tested batteries — the 5,000 are the population. (2) Classify: number of pets in a household. Answer: quantitative discrete, since pets are counted. (3) Classify: zip code. Answer: qualitative — the digits are a label, and averaging zip codes is meaningless. (4) A pollster surveys every 15th shopper leaving a store; name the method. Answer: systematic sampling. (5) A researcher randomly selects 5 entire apartment buildings and interviews every resident; name the method. Answer: cluster sampling. (6) The average height of the 40 sampled players is 190 cm; is that a parameter or a statistic? Answer: a statistic, because it comes from the sample."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: a bigger sample fixes a biased method. Ten thousand gym-goers still tell you nothing about people who never go — size multiplies a bias, it does not cancel it. Misconception 2: anything written with digits is quantitative. Jersey numbers, zip codes, and phone numbers are labels; player 30 is not three times player 10. Exit ticket: (1) A city wants the average commute of all its workers and surveys 500 of them; which group is the population? Answer: all workers in the city. (2) Classify: temperature of a cup of coffee. Answer: quantitative continuous."}
   ]}',
   'Study tip: before trusting any statistic, ask two questions — who was actually measured, and who never had a chance to be measured?', 12),
  (3, 'Descriptive statistics: center, spread & displays', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will compute and interpret measures of center and spread and read the standard data displays. Warm-up from Lesson 2 — (1) Classify: number of siblings. (2) Every 15th shopper is surveyed; name the method. (3) Is the average of a sample a parameter or a statistic? Answers: quantitative discrete, systematic sampling, and a statistic. Now that you can collect data honestly, it is time to summarize it honestly."},
      {"heading":"Same average, different story","text":"Two bus routes both average 26 minutes, yet riders swear one is reliable and the other is chaos. One number cannot tell that story; you need a center and a spread. The mean is the total divided by the count; the median is the middle of the sorted values; the mode is the most frequent value. Worked example: commute times 18, 20, 21, 23, 48. The mean is 130 ÷ 5 = 26 minutes, but the median is 21 — the single terrible day of 48 minutes drags the mean up while barely touching the median. Values far from the rest, like that 48, are called outliers, and they are exactly why the median often describes a typical day better than the mean."},
      {"heading":"Worked examples","text":"Example 1 — quartiles and the box plot: sorted data 4, 7, 8, 10, 12, 15, 21. The median is 10; the first quartile Q1 (median of the lower half) is 7; the third quartile Q3 is 15. The interquartile range IQR = Q3 − Q1 = 8 spans the middle 50% of the data, and the five numbers minimum, Q1, median, Q3, maximum draw a box plot. Example 2 — standard deviation: quiz sets A = 8, 9, 10, 11, 12 and B = 2, 6, 10, 14, 18 both have mean 10, but B is far more spread out. The standard deviation measures the typical distance of values from the mean: deviations for 8, 10, 12 (mean 10) are −2, 0, and 2, and squaring, averaging, and square-rooting those deviations turns them into one spread number. Bigger standard deviation means values scatter farther from the mean; it is never negative. Example 3 — shape: a histogram with a long right tail is skewed right and its mean sits above its median (a few huge values inflate the total); a symmetric histogram has mean and median together. For qualitative data like favorite genre, use a bar chart of counts instead — histograms are for quantitative data."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Mean of 5, 9, 10, 16. Answer: 10, from 40 ÷ 4. (2) Median of 12, 3, 8, 20, 7. Answer: 8, the middle of the sorted list 3, 7, 8, 12, 20. (3) Q1 = 14 and Q3 = 30; find the IQR. Answer: 16. (4) Apartment rents are 900, 950, 1000, 1050, 5000; which center describes a typical rent better? Answer: the median (1000), because the 5000 outlier pulls the mean up to 1780. (5) Which display suits the favorite-color answers of 80 students? Answer: a bar chart, since the data are qualitative. (6) A histogram of reaction times has a long tail to the right; compare mean and median. Answer: the mean is larger, dragged by the slow-outlier tail."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: the mean is always the best summary. One billionaire moving into a small town makes the mean income soar while the median barely moves; report the median (with the IQR) when data are skewed or have outliers. Misconception 2: a standard deviation of 0 is impossible, or a standard deviation can be negative. It is never negative, and it equals 0 exactly when every value is identical — no scatter at all. Exit ticket: (1) Mean of 10 and 16. Answer: 13. (2) Data sets A and B share the same mean, but A has standard deviation 3 and B has 12; which is more consistent? Answer: A — its values hug the mean."}
   ]}',
   'Study tip: never report a center without its spread — mean with standard deviation, or median with IQR, always travel as a pair.', 14),
  (4, 'Probability basics', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will compute probabilities for equally likely outcomes and use the complement, addition, and multiplication rules. Warm-up from Lesson 3 — (1) Median of 2, 4, 9. (2) Write 3/4 as a decimal. (3) Can a standard deviation be negative? Answers: 4, 0.75, and no. Fractions and decimals are the language probability speaks, so keep them close."},
      {"heading":"What 70% chance of rain really means","text":"A forecast of 70% rain does not promise rain for 70% of the day. It means that on many days with conditions like these, about 70 out of 100 end up wet — probability is long-run relative frequency. Every probability lives between 0 (impossible) and 1 (certain). The sample space is the list of all possible outcomes; when outcomes are equally likely, the probability of an event is favorable outcomes divided by total outcomes. Worked example: rolling a fair six-sided die, the sample space is 1 through 6, and P(number greater than 4) counts the favorable outcomes 5 and 6, giving 2/6 = 1/3. Fair dice and shuffled cards earn the equally-likely shortcut; real-world events like rain need long-run data instead."},
      {"heading":"Worked examples","text":"Example 1 — the complement: the complement of an event is everything else in the sample space, so P(not A) = 1 − P(A). P(not rolling a 6) = 1 − 1/6 = 5/6. The complement shines on at-least-one questions: P(at least one six in two rolls) = 1 − P(no six twice) = 1 − 25/36 = 11/36. Example 2 — OR with an overlap: P(even OR greater than 4) on one die roll. Evens are 2, 4, 6 (3 outcomes) and greater-than-4 is 5, 6 (2 outcomes), but 6 belongs to both, so count it once: 3/6 + 2/6 − 1/6 = 4/6 = 2/3. Forgetting to subtract the overlap double-counts. Example 3 — AND with independence: two events are independent when one happening tells you nothing about the other. Two fair coin flips are independent, so P(heads then heads) = 1/2 × 1/2 = 1/4. A die has no memory: even after five sixes in a row, the next roll still has P(six) = 1/6."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) One card is drawn from a shuffled 52-card deck; find P(heart). Answer: 13/52 = 1/4. (2) P(rain) = 0.3; find P(no rain). Answer: 0.7, the complement. (3) One die roll: P(odd OR greater than 3). Answer: 5/6 — odds are 1, 3, 5 and greater-than-3 is 4, 5, 6, overlapping only at 5, so 3/6 + 3/6 − 1/6. (4) A spinner lands red with probability 0.2; find P(red on both of two independent spins). Answer: 0.04, from 0.2 × 0.2. (5) P(at least one head in two fair flips). Answer: 3/4, from 1 − 1/4 chance of two tails. (6) A quiz has one four-option question; you guess at random. P(correct)? Answer: 1/4."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: streaks change the odds. After five heads in a row, tails is not due — fair coins have no memory, and the next flip is still 1/2. Believing otherwise is how casinos pay their electric bills. Misconception 2: OR always means add. Adding P(even) + P(greater than 4) = 3/6 + 2/6 counts the 6 twice; overlapping events need the overlap subtracted, and any answer above 1 is a certain sign something was double-counted. Exit ticket: (1) P(not drawing a heart) from a full deck. Answer: 3/4. (2) Two independent free throws each succeed with probability 0.8; find P(both score). Answer: 0.64."}
   ]}',
   'Study tip: when a question says at least one, reach for the complement — 1 minus the probability of none is almost always the fast lane.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"A school splits students by grade level, then randomly selects 20 students from each grade. This method is…","options":["simple random sampling","stratified sampling","cluster sampling","convenience sampling"],"answer":1,"explanation":"Dividing into subgroups (strata) and sampling within each one is stratified sampling — it guarantees every grade is represented."},
      {"prompt":"Classify the data: number of goals a team scores in a match.","options":["qualitative","quantitative discrete","quantitative continuous","a parameter"],"answer":1,"explanation":"Goals are counted in whole numbers, so the data are quantitative discrete."},
      {"prompt":"House prices on a street (in thousands) are 200, 300, 300, 400, 4000. Which center best describes a typical house?","options":["the mean, 1040","the median, 300","the maximum, 4000","the range, 3800"],"answer":1,"explanation":"The 4000 outlier drags the mean to 1040, far above four of the five houses; the median of 300 is the honest summary."},
      {"prompt":"A data set has Q1 = 10 and Q3 = 22. What is the IQR?","options":["32","16","12","median"],"answer":2,"explanation":"IQR = Q3 − Q1 = 22 − 10 = 12, the width of the middle half of the data."},
      {"prompt":"A histogram shows a long tail stretching to the left. The distribution is…","options":["skewed left, mean below median","skewed left, mean above median","skewed right, mean above median","symmetric"],"answer":0,"explanation":"The tail names the skew, and the mean gets dragged toward the tail — so left skew puts the mean below the median."},
      {"prompt":"P(a flight departs on time) = 0.85. What is the probability it does not depart on time?","options":["0.85","0.15","0.5","cannot be found"],"answer":1,"explanation":"The complement rule: 1 − 0.85 = 0.15."},
      {"prompt":"A fair coin is flipped twice. What is P(heads both times)?","options":["1/2","1/3","1/4","1"],"answer":2,"explanation":"The flips are independent, so multiply: 1/2 × 1/2 = 1/4."}
   ]}',
   null, 9),
  (6, 'Distributions & the normal curve', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will describe distributions, use the normal curve with the 68-95-99.7 rule, and compute and interpret z-scores. Warm-up from Lesson 4 — (1) P(even) on one die roll. (2) The complement of an event with probability 0.85. (3) P(heads twice) in two fair flips. Answers: 1/2, 0.15, and 1/4. Probability told you about single outcomes; distributions describe all outcomes at once."},
      {"heading":"The bell that keeps showing up","text":"Measure the height of 1,000 adults and draw the histogram: a mound in the middle, thinning symmetrically toward rare very-short and very-tall values. A distribution lists the possible values of a variable and how likely each one is, and this particular bell shape — the normal distribution — appears everywhere from heights to measurement errors. A normal curve is completely described by two numbers: its mean (the center, where the peak sits and where mean and median coincide) and its standard deviation (how wide the bell spreads). The empirical rule pins numbers to the picture: about 68% of values fall within 1 standard deviation of the mean, about 95% within 2, and about 99.7% within 3. Worked example: adult heights with mean 170 cm and standard deviation 8 cm put about 68% of people between 162 and 178 cm, and about 95% between 154 and 186 cm."},
      {"heading":"Worked examples","text":"Example 1 — the z-score converts any value into standard-deviation units: z = (value − mean) ÷ standard deviation. A test score of 85 with mean 75 and standard deviation 5 gives z = (85 − 75) ÷ 5 = 2: two standard deviations above the mean. A negative z simply means below the mean. Example 2 — comparing across different scales: you scored 82 in math (mean 70, standard deviation 8) and 90 in reading (mean 85, standard deviation 10). Math z = 1.5; reading z = 0.5. The math score is the rarer achievement even though 90 is the bigger number — z-scores make apples and oranges comparable. Example 3 — tail areas from the empirical rule: IQ-style scores with mean 100 and standard deviation 15. About 95% lie between 70 and 130, leaving 5% split between the two tails, so about 2.5% score above 130 and about 2.5% below 70."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Compute z for a value of 60 when the mean is 50 and the standard deviation is 5. Answer: z = 2. (2) Battery life is normal with mean 40 hours and standard deviation 2; between which lifetimes do about 68% of batteries fall? Answer: 38 to 42 hours. (3) A value has z = −1.5; is it above or below the mean, and by how much? Answer: below the mean by 1.5 standard deviations. (4) With mean 100 and standard deviation 15, about what percent score between 85 and 115? Answer: about 68%. (5) Which is more unusual: z = 2.4 or z = −2.9? Answer: z = −2.9, since 2.9 standard deviations is farther from the mean in either direction. (6) In a normal distribution, how do the mean and median compare? Answer: they are equal, sitting together at the center of symmetry."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: all data are normal. Incomes, house prices, and waiting times are usually skewed right; the empirical rule misleads badly when the bell assumption fails, so look at the histogram first. Misconception 2: a negative z-score means something is wrong or impossible. It only means below the mean — a z of −1 for golf strokes or race times can be excellent news. Exit ticket: (1) Compute z for 35 with mean 50 and standard deviation 10. Answer: −1.5. (2) About what percent of a normal distribution lies within 2 standard deviations of the mean? Answer: about 95%."}
   ]}',
   'Study tip: sketch the bell and shade the region before computing anything — a ten-second drawing catches most z-score sign and direction errors.', 14),
  (7, 'The Central Limit Theorem', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will explain what a sampling distribution is, state the Central Limit Theorem, and compute the standard error of a sample mean. Warm-up from Lesson 6 — (1) z for a value of 60 with mean 50 and standard deviation 5. (2) About what percent of a normal distribution lies within 1 standard deviation of the mean? Answers: 2 and about 68%. Both tools are about to be pointed at averages instead of individuals."},
      {"heading":"Averages tame the extremes","text":"Roll one die and every face 1 through 6 is equally likely — a flat, boring distribution with mean 3.5. Now roll five dice and record the average. To average 6 you need five sixes in a row, but there are many ways to average near 3.5, so the averages pile up in the middle: repeat the experiment hundreds of times and their histogram forms a bell. That histogram of many sample means is called the sampling distribution of the sample mean. The Central Limit Theorem (CLT) says: for a large enough sample size n, the sampling distribution of the mean is approximately normal, centered at the population mean, with standard deviation equal to the population standard deviation divided by the square root of n — no matter what shape the population has. That shrunken spread is called the standard error. Worked example: a population has standard deviation 12; samples of n = 36 give a standard error of 12 ÷ 6 = 2."},
      {"heading":"Worked examples","text":"Example 1 — how fast the error shrinks: with population standard deviation 10, samples of n = 25 give standard error 10 ÷ 5 = 2, while samples of n = 100 give 10 ÷ 10 = 1. Because of the square root, you must quadruple the sample size to cut the standard error in half — precision is bought at an increasing price. Example 2 — the shape rescue: individual household incomes are strongly skewed right, so no bell describes them. But take samples of 50 households and record each sample mean: the CLT says those means are approximately normal anyway. This is why normal-curve tools work for averages even when the raw data are messy. Example 3 — a probability for an average: test scores have mean 500 and standard deviation 100. For samples of n = 25, the standard error is 100 ÷ 5 = 20, so a sample mean of 540 has z = (540 − 500) ÷ 20 = 2. By the empirical rule, a sample mean that high or higher happens only about 2.5% of the time — surprising, in a way a single student scoring 540 (z = 0.4) never would be."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Population standard deviation 8, sample size 16; find the standard error of the mean. Answer: 8 ÷ 4 = 2. (2) The sampling distribution of the mean is centered at what value? Answer: the population mean. (3) Sample size rises from 25 to 100; what happens to the standard error? Answer: it halves, since the square root of the sample size doubles. (4) A population is strongly skewed; describe the shape of the distribution of sample means for n = 60. Answer: approximately normal, by the CLT. (5) Waiting times have mean 10 minutes and standard deviation 6; for n = 36, what is the z-score of a sample mean of 12 minutes? Answer: standard error 1, so z = 2. (6) Which varies less: one random measurement, or the mean of 50 random measurements? Answer: the mean of 50 — averaging cancels out extremes."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: the CLT makes the data normal. It never touches the raw data — incomes stay skewed forever; only the distribution of sample means turns bell-shaped. Misconception 2: bigger samples make results more variable because more can happen. The opposite is true: the standard error shrinks as n grows, which is exactly why large polls are trusted more than small ones. Exit ticket: (1) Population standard deviation 20, n = 100; find the standard error. Answer: 2. (2) State the CLT in one sentence. Answer: for large samples, the distribution of sample means is approximately normal, centered at the population mean, with spread equal to the population standard deviation divided by the square root of n."}
   ]}',
   'Study tip: keep two spreads apart in your notes — the standard deviation describes one observation, the standard error describes a sample mean — and label every z-score with which one you used.', 13),
  (8, 'Confidence intervals & hypothesis tests', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will build and interpret a basic confidence interval and follow the logic of a hypothesis test and its p-value. Warm-up from Lesson 7 — (1) Standard error for population standard deviation 8 and n = 16. (2) What shape does the distribution of sample means take for large n? Answers: 2, and approximately normal. The standard error is about to become the star of the show."},
      {"heading":"From one guess to an honest range","text":"A news poll reports: 52% support the proposal, margin of error plus or minus 3 points. The pollster knows one sample cannot nail the true value, so they publish a range: the point estimate (52%) plus and minus a margin of error. A confidence interval does exactly this for any estimate. For a sample mean, a 95% confidence interval is approximately the sample mean plus or minus 2 standard errors — the 2 comes straight from the empirical rule, because about 95% of sample means land within 2 standard errors of the truth. Worked example: a sample of 36 coffee orders has mean wait 4.6 minutes, and the standard error works out to 0.2, so the 95% confidence interval is 4.6 plus or minus 0.4, or (4.2, 5.0) minutes. The 95% describes the method, not this one interval: if you repeated the sampling many times, about 95% of the intervals built this way would capture the true mean."},
      {"heading":"Worked examples","text":"Example 1 — what moves the width: a larger sample shrinks the standard error, so the interval narrows; demanding 99% confidence instead of 95% stretches the interval wider, because more certainty requires casting a bigger net. Precision and confidence pull in opposite directions, and only more data relaxes the trade-off. Example 2 — the courtroom logic of a hypothesis test: the null hypothesis is the presumption of innocence — no effect, no difference, nothing new (a delivery service really does average 30 minutes, as it claims). The alternative hypothesis is what you suspect instead. You collect data and ask: if the null were true, how surprising would data like ours be? That surprise level is the p-value — the probability, assuming the null is true, of results at least as extreme as observed. Example 3 — reading the verdict: you time 36 deliveries and the sample mean is 33 minutes, with a p-value of 0.02. Using the common significance level of 0.05, since 0.02 < 0.05 the data are too surprising to blame on chance: reject the null and conclude the true average exceeds 30. Had the p-value been 0.30, you would fail to reject the null — which is a shrug, not an acquittal: the evidence was merely insufficient."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Sample mean 50, standard error 2; give the approximate 95% confidence interval. Answer: (46, 54), from 50 plus or minus 4. (2) Name two ways to make a confidence interval narrower. Answer: increase the sample size, or accept a lower confidence level. (3) A test of a new study method yields p = 0.03; what is the decision at the 0.05 significance level? Answer: reject the null hypothesis — data this extreme would occur only 3% of the time by chance under it. (4) Write the null hypothesis for testing whether a coin is fair. Answer: the coin is fair, P(heads) = 0.5. (5) A p-value of 0.47 means… Answer: the data are entirely unsurprising under the null hypothesis, so there is no real evidence against it. (6) Does a 95% confidence interval of (46, 54) mean 95% of individual values lie in that range? Answer: no — it is a range of plausible values for the population mean, not for individuals."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: a 95% confidence interval contains 95% of the data. The interval hunts one number — the population mean — and individual values scatter far outside it; the 95% is the long-run success rate of the interval-building method. Misconception 2: the p-value is the probability that the null hypothesis is true. It cannot be — the p-value is computed by assuming the null is true, and it measures how surprising the data are under that assumption, nothing more. Exit ticket: (1) Sample mean 80, standard error 3; give the approximate 95% confidence interval. Answer: (74, 86). (2) At a significance level of 0.05, what do you do with p = 0.20? Answer: fail to reject the null hypothesis."}
   ]}',
   'Study tip: read every p-value with the same sentence — if the null were true, data like ours would appear about this often — and the conclusion writes itself.', 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"Scores are normal with mean 100 and standard deviation 15. About what percent fall between 85 and 115?","options":["50%","68%","95%","99.7%"],"answer":1,"explanation":"85 and 115 are exactly 1 standard deviation from the mean, and the empirical rule assigns that band about 68%."},
      {"prompt":"Compute the z-score of 62 when the mean is 50 and the standard deviation is 8.","options":["1.5","12","0.67","−1.5"],"answer":0,"explanation":"z = (62 − 50) ÷ 8 = 1.5, so the value is 1.5 standard deviations above the mean."},
      {"prompt":"A population has standard deviation 12. For samples of size 36, the standard error of the mean is…","options":["12","6","2","0.33"],"answer":2,"explanation":"Standard error = 12 divided by the square root of 36, which is 12 ÷ 6 = 2."},
      {"prompt":"If the sample size increases, a 95% confidence interval for the mean will…","options":["get wider","get narrower","stay the same","stop being valid"],"answer":1,"explanation":"More data shrinks the standard error, and the interval is built from it — so the interval narrows."},
      {"prompt":"Which p-value is the strongest evidence against the null hypothesis?","options":["0.65","0.20","0.05","0.001"],"answer":3,"explanation":"Smaller p-values mean the data would be rarer under the null; 0.001 says results this extreme happen 1 time in 1,000 by chance."},
      {"prompt":"The null hypothesis usually states that…","options":["the new treatment works","there is no effect or no difference","the sample is biased","the data are normal"],"answer":1,"explanation":"The null is the skeptical default — no effect, no difference — which the data must work to overturn."},
      {"prompt":"Household incomes are strongly skewed right. For random samples of 100 households, the distribution of sample means is…","options":["strongly skewed right","approximately normal","uniform","impossible to describe"],"answer":1,"explanation":"The Central Limit Theorem: with n = 100, sample means are approximately normal regardless of the population shape."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"population","translation":"the entire group you want to draw conclusions about","example":"All 12,000 students at the university form the population, even though only 200 were surveyed."},
      {"term":"sample","translation":"the subset of the population that is actually measured","example":"The 200 interviewed students are the sample — a well-stirred spoonful of the whole pot."},
      {"term":"mean","translation":"the average: the total of all values divided by how many there are","example":"Commute times 18, 20, 21, 23, 48 have mean 130 ÷ 5 = 26 minutes."},
      {"term":"median","translation":"the middle value of the sorted data, resistant to outliers","example":"The median of those same commutes is 21 minutes — the one 48-minute disaster barely moves it."},
      {"term":"standard deviation","translation":"the typical distance of values from their mean; never negative","example":"Quiz sets with means of 10 but standard deviations of 1 and 6 tell very different stories of consistency."},
      {"term":"outlier","translation":"a value far from the rest of the data","example":"The 5000 rent on a street of 1000s is an outlier that inflates the mean but not the median."},
      {"term":"p-value","translation":"assuming the null hypothesis is true, the probability of data at least as extreme as observed","example":"A p-value of 0.02 says results like ours appear only 2% of the time by pure chance under the null."},
      {"term":"confidence interval","translation":"a range of plausible values for a population parameter, built so the method succeeds a stated percent of the time","example":"The 95% confidence interval (4.2, 5.0) offers a plausible range for the true mean wait, not for individual waits."}
   ]}',
   null, 8),
  (11, 'Applied project: analyze a real dataset', 'writing',
   '{"sections":[
      {"heading":"Pick a dataset & pose one question","text":"This project turns the whole course into one deliverable: a short written report on real data. First, choose a dataset of roughly 30 to 200 rows that genuinely interests you — a public open-data portal (city weather, transit delays, air quality), a sports site (points per game across a season), or your own life (daily screen-time minutes, sleep hours from a phone app). Then pose exactly one sharp question a number can answer, and write it as the title of your report. Weak: something about my sleep. Strong: is my median sleep on weekends at least one hour longer than on weekdays? State who or what the population is, what your rows are a sample of, and classify each variable you will use as qualitative, quantitative discrete, or quantitative continuous."},
      {"heading":"Clean & describe","text":"Real data arrive dirty; budget a third of your time here. Scan for duplicated rows, impossible values (a 27-hour sleep night, a negative delay), inconsistent labels (Mon versus Monday), and missing entries — and write down every fix or removal you make, because deleting inconvenient points silently is how analyses lie. Then describe: report the count n, and for each quantitative variable give the mean, median, standard deviation, and the five-number summary (minimum, Q1, median, Q3, maximum). For qualitative variables, report counts and percents per category. Compare the mean and the median and say which you trust more for your data, and why — one sentence about skew or outliers shows more understanding than a page of formulas."},
      {"heading":"Visualize honestly","text":"Choose one or two displays that answer your question, not decorate the report. Quantitative data: a histogram for shape, or side-by-side box plots to compare groups (weekday sleep versus weekend sleep). Qualitative data: a bar chart of counts. Then apply the honesty rules from this course: start bar-chart axes at zero or clearly mark any break, label both axes with units, title the chart with its message, and avoid 3-D effects that distort area. Under each chart, write two sentences: one describing what the display shows (center, spread, shape, outliers), and one connecting it to your question."},
      {"heading":"Conclude & state limitations","text":"Answer your question in the first sentence of the conclusion, with numbers attached: weekend median sleep was 7.9 hours against a weekday median of 6.8, a gap of 1.1 hours. Use calibrated language — the data suggest, is consistent with — rather than proves, because a single sample never proves. Then confess limitations like a professional: was your sample a convenience sample of one person or one season? Could a confounder explain the pattern (exam weeks shortening both sleep and mood)? Would a different time window change the story? Note explicitly that a pattern in observational data shows association, not causation. Two honest paragraphs of limitations make your conclusion stronger, not weaker."},
      {"heading":"Self-check rubric","text":"Score yourself 0, 1, or 2 on each item before submitting; 13 of 16 is a strong report. (1) The question is specific and answerable with the data. (2) The population, sample, and variable types are identified. (3) Every cleaning decision is documented. (4) Center and spread are both reported, with the appropriate pair chosen (mean with standard deviation, or median with IQR). (5) Each chart follows the honesty rules and has labeled axes. (6) The conclusion opens with a direct, numeric answer. (7) At least two genuine limitations are named. (8) No causal claim is made from observational data. Revise the weakest two items before you call the project done."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"A reporter interviews shoppers at one mall on a weekday morning about national exercise habits. The main problem is…","options":["the sample is too large","convenience sampling that misses most of the population","using the median instead of the mean","the data are quantitative"],"answer":1,"explanation":"Weekday-morning mall shoppers are just the easiest people to reach; everyone at work, school, or home had no chance to be selected."},
      {"prompt":"A box plot of delivery times shows minimum 10, Q1 20, median 30, Q3 45, and maximum 80. Which statement is true?","options":["the IQR is 25 minutes","the median is 35 minutes","the range is 60 minutes","half the deliveries took less than 20 minutes"],"answer":0,"explanation":"IQR = Q3 − Q1 = 45 − 20 = 25. The range is 70, the median is 30, and only a quarter of deliveries fall below Q1."},
      {"prompt":"Two classes both average 75 on an exam, but class A has standard deviation 3 and class B has 12. This means…","options":["class B scored higher overall","class A scores are more spread out","class B scores are more spread out","the two classes performed identically"],"answer":2,"explanation":"Equal means, but the larger standard deviation in class B says its scores scatter much farther from 75 in both directions."},
      {"prompt":"Battery life is normal with mean 40 hours and standard deviation 2. About what percent of batteries last more than 44 hours?","options":["about 16%","about 5%","about 2.5%","about 0.3%"],"answer":2,"explanation":"44 hours is z = 2. About 95% lie within 2 standard deviations, leaving 5% in the two tails — about 2.5% in the upper tail alone."},
      {"prompt":"A population has standard deviation 10. For samples of size 25, the standard error of the sample mean is…","options":["10","5","2","0.4"],"answer":2,"explanation":"Standard error = 10 divided by the square root of 25 = 10 ÷ 5 = 2."},
      {"prompt":"A sample gives mean 50 with standard error 2. The approximate 95% confidence interval for the population mean is…","options":["(48, 52)","(46, 54)","(44, 56)","(40, 60)"],"answer":1,"explanation":"Mean plus or minus about 2 standard errors: 50 ± 4 gives (46, 54)."},
      {"prompt":"A test of a new app feature returns p = 0.42 at the 0.05 significance level. The correct conclusion is…","options":["reject the null hypothesis","the null hypothesis is proven true","fail to reject the null — the evidence is insufficient","the feature works for 42% of users"],"answer":2,"explanation":"0.42 is far above 0.05: the data are unsurprising under the null. That is a lack of evidence, not proof the null is true."},
      {"prompt":"One fair die is rolled. What is P(even OR greater than 4)?","options":["5/6","2/3","1/2","1/6"],"answer":1,"explanation":"Evens are 2, 4, 6 and greater-than-4 is 5, 6, with 6 in both: 3/6 + 2/6 − 1/6 = 4/6 = 2/3."}
   ]}',
   null, 10)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0001-0000-4000-8000-000000000005' and l.position = v.pos
);
