-- Algebra I (math track, course 3 of the foundations sequence).
-- Prerequisite: Pre-Algebra (bbbb0001-0000-4000-8000-000000000002).
-- Twelve lessons: a diagnostic quiz, seven structured readings built on
-- retrieval practice + worked examples + guided practice + misconception
-- checks, two checkpoints, a key-terms vocab set, and a final assessment.
-- All content is original. Fixed UUIDs and guarded inserts make the file
-- idempotent: safe to re-run at any time.

-- ============ Algebra I ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0001-0000-4000-8000-000000000003',
  'en', null,
  'Algebra I',
  'Master the core of high-school algebra: linear equations and their graphs, systems, functions, polynomials, factoring, and quadratic equations, with exponents, radicals, and real data-modeling contexts throughout.',
  null, 'foundations', 3, true, 'math', '{bbbb0001-0000-4000-8000-000000000002}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0001-0000-4000-8000-000000000003', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"What is the slope of the line through the points (1, 2) and (3, 10)?","options":["4","2","8","1/4"],"answer":0,"explanation":"Slope = (10 - 2)/(3 - 1) = 8/2 = 4. If this felt shaky, start with Lesson 2 (Linear equations and their graphs)."},
      {"prompt":"In the system x + y = 10 and x - y = 4, what is the value of x?","options":["3","7","6","10"],"answer":1,"explanation":"Adding the two equations gives 2x = 14, so x = 7. Systems like this are the focus of Lesson 3."},
      {"prompt":"If f(x) = 3x - 5, what is f(4)?","options":["12","-1","7","17"],"answer":2,"explanation":"Substitute 4 for x: f(4) = 3(4) - 5 = 12 - 5 = 7. Function notation is taught in Lesson 4."},
      {"prompt":"Simplify (2x^2 + 3x) + (x^2 - 5x).","options":["3x^2 + 2x","3x^2 - 2x","2x^2 - 2x","3x^4 - 2x^2"],"answer":1,"explanation":"Combine like terms: 2x^2 + x^2 = 3x^2 and 3x - 5x = -2x. Polynomial operations are covered in Lesson 6."},
      {"prompt":"Which is the complete factorization of x^2 - 9?","options":["(x - 3)(x - 3)","(x - 9)(x + 1)","(x + 3)(x + 3)","(x - 3)(x + 3)"],"answer":3,"explanation":"x^2 - 9 is a difference of squares: x^2 - 3^2 = (x - 3)(x + 3). Factoring patterns are drilled in Lesson 7."},
      {"prompt":"What are the solutions of x^2 - 5x + 6 = 0?","options":["x = 2 and x = 3","x = -2 and x = -3","x = 1 and x = 6","x = -1 and x = 6"],"answer":0,"explanation":"Factor to (x - 2)(x - 3) = 0, so x = 2 or x = 3. Quadratic equations are the subject of Lesson 8."},
      {"prompt":"For a quadratic ax^2 + bx + c = 0, which quantity tells you how many real solutions it has?","options":["The vertex","The y-intercept","The discriminant, b^2 - 4ac","The leading coefficient a"],"answer":2,"explanation":"The sign of the discriminant b^2 - 4ac determines whether there are two, one, or zero real solutions. This term appears in Lesson 10 (Key terms) and Lesson 8."},
      {"prompt":"Simplify (x^3)(x^4).","options":["x^12","x^7","2x^7","x^34"],"answer":1,"explanation":"When multiplying powers with the same base, add the exponents: 3 + 4 = 7. Exponent rules are reviewed in Lesson 11."}
   ]}',
   null, 12),
  (2, 'Linear equations & their graphs (slope, intercepts)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: write and interpret linear equations in slope-intercept form y = mx + b, compute slope from two points, and find both intercepts of a line. Retrieval warm-up from Pre-Algebra: (1) Solve 2x + 5 = 17. Answer: subtract 5 to get 2x = 12, divide by 2 to get x = 6. (2) Evaluate 4n - 7 when n = -3. Answer: 4(-3) - 7 = -12 - 7 = -19. If either took more than a minute, review one-step and two-step equations before continuing."},
      {"heading":"The hook: pricing a ride","text":"A rideshare app charges a base fee of 2.50 dollars plus 1.75 dollars per mile. The total cost C for m miles is C = 1.75m + 2.50. This equation is linear: the graph is a straight line. The number multiplying the variable, 1.75, is the slope: the constant rate of change, here dollars per mile. The constant 2.50 is the y-intercept: the value when m = 0, here the cost before the car moves. Worked example: how much is an 8-mile ride? C = 1.75(8) + 2.50 = 14.00 + 2.50 = 16.50 dollars. Every line can be written as y = mx + b, where m is the slope and b is the y-intercept, and both numbers mean something in a real context."},
      {"heading":"Worked examples","text":"Example 1 (slope from two points): find the slope of the line through (2, 3) and (6, 11). Slope m = (change in y)/(change in x) = (11 - 3)/(6 - 2) = 8/4 = 2. The line rises 2 units for every 1 unit right. Example 2 (equation from a point and slope): find the line with slope 4 through (2, 3). Start with y = 4x + b, substitute the point: 3 = 4(2) + b, so 3 = 8 + b and b = -5. The equation is y = 4x - 5. Example 3 (both intercepts): find the intercepts of 3x + 2y = 12. For the x-intercept set y = 0: 3x = 12, so x = 4, giving the point (4, 0). For the y-intercept set x = 0: 2y = 12, so y = 6, giving (0, 6). Plotting the two intercepts and connecting them is the fastest way to graph a line in standard form."},
      {"heading":"Your turn","text":"(1) Find the slope of the line through (0, 5) and (4, 13). Answer: 2, because (13 - 5)/(4 - 0) = 8/4 = 2. (2) State the slope and y-intercept of y = -3x + 7. Answer: slope -3, y-intercept 7, read directly from y = mx + b. (3) Write the equation of the line with slope -2 through (0, 9). Answer: y = -2x + 9, since (0, 9) is the y-intercept itself. (4) Find both intercepts of 5x - 2y = 10. Answer: x-intercept (2, 0) from 5x = 10; y-intercept (0, -5) from -2y = 10. (5) A phone plan costs 20 dollars plus 0.10 dollars per text: write the cost equation and the cost of 150 texts. Answer: C = 0.10t + 20, and C = 0.10(150) + 20 = 35 dollars."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: the slope is always the number next to x. Only in slope-intercept form. In 2y = 6x + 4, first divide by 2 to get y = 3x + 2: the slope is 3, not 6. Misconception 2: a vertical line has slope 0. A horizontal line like y = 4 has slope 0; a vertical line like x = 3 has an undefined slope, because the run is 0 and division by 0 is undefined. Exit ticket: (1) What are the slope and y-intercept of y = (1/2)x - 4? Answer: slope 1/2, y-intercept -4. (2) A line passes through (0, 3) with slope -2: what is its equation? Answer: y = -2x + 3."}
   ]}',
   'Study tip: whenever you see a linear equation, say out loud what the slope and intercept mean in the context before doing any computation.', 14),
  (3, 'Systems of linear equations (substitution, elimination)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: solve systems of two linear equations by substitution and by elimination, and recognize systems with no solution or infinitely many. Retrieval warm-up from Lesson 2: (1) What is the slope of y = 5x - 2? Answer: 5. (2) Find the y-intercept of 2x + y = 8. Answer: set x = 0, so y = 8, the point (0, 8). A solution of a system is a point (x, y) that makes BOTH equations true at once: graphically, where the two lines cross."},
      {"heading":"The hook: which gym is cheaper?","text":"Gym A charges 30 dollars to join plus 25 dollars per month: y = 25x + 30. Gym B has no joining fee but costs 35 dollars per month: y = 35x. After how many months do they cost the same? Set the costs equal, which is substitution in disguise: 25x + 30 = 35x. Subtract 25x: 30 = 10x, so x = 3. At 3 months both cost 105 dollars; before that Gym B is cheaper, after that Gym A wins. Worked example done: the solution of the system is (3, 105), and the break-even interpretation is what the algebra is for."},
      {"heading":"Worked examples","text":"Example 1 (substitution): solve y = 2x - 1 and 3x + y = 14. The first equation already isolates y, so substitute 2x - 1 for y in the second: 3x + (2x - 1) = 14, so 5x - 1 = 14, 5x = 15, x = 3. Back-substitute: y = 2(3) - 1 = 5. Solution: (3, 5). Check in both equations: 3(3) + 5 = 14, true. Example 2 (elimination): solve 2x + 3y = 12 and 4x - 3y = 6. The y-coefficients are already opposites, so add the equations: 6x = 18, x = 3. Then 2(3) + 3y = 12 gives 3y = 6, y = 2. Solution: (3, 2). Example 3 (scaling first): solve 3x + 2y = 16 and 2x + 5y = 18. Multiply the first by 5 and the second by 2 to match the y terms: 15x + 10y = 80 and 4x + 10y = 36. Subtract: 11x = 44, so x = 4, and 3(4) + 2y = 16 gives y = 2. Solution: (4, 2)."},
      {"heading":"Your turn","text":"(1) Solve y = x + 4 and 2x + y = 13. Answer: (3, 7); substituting gives 2x + x + 4 = 13, so 3x = 9. (2) Solve x + y = 9 and x - y = 5. Answer: (7, 2); adding the equations gives 2x = 14. (3) Solve 3x + y = 10 and 6x + 2y = 20. Answer: infinitely many solutions; the second equation is exactly twice the first, so they are the same line. (4) Solve 2x + y = 5 and 2x + y = 9. Answer: no solution; the left sides are identical but the right sides differ, so the lines are parallel. (5) Tickets: 2 adult and 3 child tickets cost 31 dollars, while 1 adult and 2 child cost 17 dollars. Find each price. Answer: adult 11, child 3; doubling the second equation and subtracting gives child = 3, then adult = 11."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: when eliminating by subtraction, students subtract only some of the terms. Subtract EVERY term of the second equation, including the constant on the right side, or add the opposite of the whole equation. Misconception 2: finding x finishes the problem. A solution of a system is a pair (x, y); always back-substitute to find the other variable and check the pair in BOTH original equations. Exit ticket: (1) Solve y = 3x and x + y = 8. Answer: (2, 6). (2) Without solving, what does it mean if elimination produces the statement 0 = 7? Answer: the system has no solution; the lines are parallel."}
   ]}',
   'Study tip: before choosing a method, scan the system — an isolated variable suggests substitution, matching or opposite coefficients suggest elimination.', 14),
  (4, 'Functions: notation, domain, range', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: use function notation f(x), evaluate functions, and determine the domain and range of a function. Retrieval warm-up from Lesson 3: solve the system y = 2x and x + y = 9. Answer: substituting gives 3x = 9, so x = 3 and y = 6; the solution is (3, 6). Now a shift in viewpoint: instead of asking where two rules agree, we study a single rule as a machine."},
      {"heading":"The hook: a rule as a machine","text":"A function is a rule that assigns to each input exactly one output. Think of a drink machine: press B4 (input) and exactly one drink comes out (output). If pressing B4 sometimes gave cola and sometimes water, the machine would be broken, and the rule would not be a function. We write f(x) = 3x - 5 to name the rule f and describe what it does to an input x. The notation f(4) means: run the input 4 through the machine. Worked example: f(4) = 3(4) - 5 = 7. Two more words: the DOMAIN is the set of all allowed inputs, and the RANGE is the set of all outputs the rule actually produces."},
      {"heading":"Worked examples","text":"Example 1 (evaluating with negatives): let g(x) = x^2 - 3x. Find g(-2). Substitute carefully with parentheses: g(-2) = (-2)^2 - 3(-2) = 4 + 6 = 10. Example 2 (domain with a square root): let h(x) = sqrt(x - 4). Square roots of negative numbers are not real, so we need x - 4 >= 0, meaning x >= 4. Domain: all real numbers x with x >= 4. Example 3 (domain with a fraction): let r(x) = 1/(x + 1). Division by zero is undefined, so x + 1 cannot be 0: the domain is all real numbers except x = -1. Example 4 (range): let f(x) = x^2. Any real input is allowed, but squaring never produces a negative, and every value y >= 0 is hit (by sqrt(y)). Domain: all real numbers; range: y >= 0."},
      {"heading":"Your turn","text":"(1) If f(x) = 2x + 9, find f(-3). Answer: 3, since 2(-3) + 9 = 3. (2) If g(t) = t^2 + 1, find g(5). Answer: 26, since 25 + 1 = 26. (3) State the domain of f(x) = sqrt(x + 2). Answer: x >= -2, because the expression under the root must be nonnegative. (4) State the domain of f(x) = 7/(x - 3). Answer: all real numbers except x = 3, which would divide by zero. (5) A ball machine charges f(b) = 0.25b + 2 dollars for b balls: what does f(20) = 7 mean in words? Answer: 20 balls cost 7 dollars total. (6) What is the range of f(x) = x^2 + 3? Answer: y >= 3, because x^2 >= 0 always, and shifting up by 3 moves the minimum output to 3."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: reading f(x) as f times x. It is not multiplication; f(x) names the output of rule f at input x, so f(4) means evaluate, never multiply. Misconception 2: every graph is a function. A circle is a graph but not a function, because some inputs have two outputs; the vertical line test says a graph is a function only if no vertical line crosses it twice. Exit ticket: (1) If f(x) = 4x - 1, what is f(0)? Answer: -1. (2) What is the domain of f(x) = sqrt(x)/(x - 5)? Answer: x >= 0 and x not equal to 5, combining the root condition with the no-division-by-zero condition."}
   ]}',
   'Study tip: whenever you meet a new function, ask two questions before anything else — which inputs are legal, and which outputs are possible.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"What is the slope of the line through (-1, 4) and (3, -4)?","options":["2","-2","1/2","-8"],"answer":1,"explanation":"Slope = (-4 - 4)/(3 - (-1)) = -8/4 = -2 (Lesson 2)."},
      {"prompt":"Which equation describes a line with y-intercept 6 and slope -1?","options":["y = 6x - 1","y = -x + 6","y = x - 6","y = -6x + 1"],"answer":1,"explanation":"In y = mx + b, m = -1 and b = 6 gives y = -x + 6 (Lesson 2)."},
      {"prompt":"What is the x-intercept of 4x + 3y = 24?","options":["(0, 8)","(8, 0)","(6, 0)","(0, 6)"],"answer":2,"explanation":"Set y = 0: 4x = 24, so x = 6, the point (6, 0). Option (0, 8) is the y-intercept (Lesson 2)."},
      {"prompt":"Solve the system y = x - 2 and 2x + y = 13.","options":["(5, 3)","(3, 5)","(4, 2)","(5, 8)"],"answer":0,"explanation":"Substitute: 2x + (x - 2) = 13, so 3x = 15 and x = 5, then y = 3 (Lesson 3)."},
      {"prompt":"Elimination on 3x + 2y = 7 and 3x - 2y = 5 gives which first step and result?","options":["Subtract to get 4y = 2","Add to get 6x = 12","Add to get 4y = 12","Multiply the first by 2"],"answer":1,"explanation":"The 2y terms are opposites, so adding eliminates y: 6x = 12, x = 2, then y = 1/2 (Lesson 3)."},
      {"prompt":"If f(x) = x^2 - 2x, what is f(-3)?","options":["3","-15","15","-3"],"answer":2,"explanation":"f(-3) = (-3)^2 - 2(-3) = 9 + 6 = 15; keep the parentheses around -3 (Lesson 4)."},
      {"prompt":"What is the domain of f(x) = sqrt(2x - 10)?","options":["x >= 5","x > 10","x >= -5","all real numbers"],"answer":0,"explanation":"Require 2x - 10 >= 0, so x >= 5 (Lesson 4)."}
   ]}',
   null, 10),
  (6, 'Polynomials: operations', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: add, subtract, and multiply polynomials, and identify degree and like terms. Retrieval warm-up from Lesson 4: if f(x) = x^2 + 2x, find f(3). Answer: 9 + 6 = 15. A polynomial is a sum of terms of the form (number) times (variable to a whole-number power), such as 4x^3 - 2x + 7. Its degree is the largest exponent, here 3. Like terms have exactly the same variable part: 5x^2 and -3x^2 are like terms; 5x^2 and 5x are not."},
      {"heading":"The hook: a growing garden","text":"A square garden has side length x meters. You extend one side by 5 meters and the other by 2 meters. The new area is (x + 5)(x + 2) square meters. Multiplying it out with the distributive property: (x + 5)(x + 2) = x*x + x*2 + 5*x + 5*2 = x^2 + 2x + 5x + 10 = x^2 + 7x + 10. That expansion, each term of the first factor times each term of the second, is the single skill behind all polynomial multiplication. For two binomials the four products are often remembered as FOIL: First, Outer, Inner, Last."},
      {"heading":"Worked examples","text":"Example 1 (adding): (3x^2 - 4x + 1) + (x^2 + 6x - 5). Group like terms: (3x^2 + x^2) + (-4x + 6x) + (1 - 5) = 4x^2 + 2x - 4. Example 2 (subtracting): (5x^2 + 2x) - (3x^2 - 7x + 4). Distribute the minus sign to EVERY term: 5x^2 + 2x - 3x^2 + 7x - 4 = 2x^2 + 9x - 4. Example 3 (monomial times polynomial): 3x(2x^2 - x + 4) = 6x^3 - 3x^2 + 12x, adding exponents when multiplying powers. Example 4 (binomial times trinomial): (x + 3)(x^2 - 2x + 4) = x^3 - 2x^2 + 4x + 3x^2 - 6x + 12 = x^3 + x^2 - 2x + 12; every one of the 2 x 3 = 6 products must appear before combining."},
      {"heading":"Your turn","text":"(1) Simplify (2x^2 + 5x - 3) + (x^2 - x + 8). Answer: 3x^2 + 4x + 5, combining like terms column by column. (2) Simplify (4x^2 - x) - (x^2 + 3x - 2). Answer: 3x^2 - 4x + 2; the minus distributes to all three terms. (3) Expand (x + 6)(x - 4). Answer: x^2 + 2x - 24, since 6x - 4x = 2x and 6 times -4 is -24. (4) Expand (2x - 3)(3x + 5). Answer: 6x^2 + x - 15, from 10x - 9x = x. (5) Expand (x + 4)^2. Answer: x^2 + 8x + 16; square means multiply (x + 4)(x + 4), producing the middle term 8x. (6) A rectangle has sides (x + 1) and (2x + 3): write its area as a polynomial. Answer: 2x^2 + 5x + 3 square units."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: (x + y)^2 = x^2 + y^2. False: squaring a binomial produces a middle term, (x + y)^2 = x^2 + 2xy + y^2; test with x = 1, y = 1: (2)^2 = 4 but 1 + 1 = 2. Misconception 2: adding unlike terms, such as 3x^2 + 2x = 5x^3. Addition only combines like terms; 3x^2 + 2x is already fully simplified, and exponents add only when MULTIPLYING powers. Exit ticket: (1) Expand (x - 5)(x + 5). Answer: x^2 - 25; the middle terms cancel. (2) What is the degree of the product of (x^2 + 1) and (x^3 - x)? Answer: 5, because the leading terms multiply to x^5."}
   ]}',
   'Study tip: after every expansion, count the products before combining — a binomial times a trinomial must yield exactly six terms.', 13),
  (7, 'Factoring (GCF, trinomials, difference of squares)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: factor polynomials by pulling out the greatest common factor, factoring trinomials, and recognizing the difference of squares. Retrieval warm-up from Lesson 6: expand (x + 3)(x + 4). Answer: x^2 + 7x + 12. Factoring is exactly that multiplication run backwards: starting from x^2 + 7x + 12 and recovering (x + 3)(x + 4). Notice the pattern that makes reversal possible: 3 + 4 = 7, the middle coefficient, and 3 times 4 = 12, the constant."},
      {"heading":"The hook: recovering the dimensions","text":"A landscaper knows a rectangular patio has area x^2 + 9x + 20 square feet and that both side lengths are of the form x plus a whole number. What are the sides? We need two numbers that multiply to 20 and add to 9: they are 4 and 5. So x^2 + 9x + 20 = (x + 4)(x + 5), and the sides are x + 4 and x + 5 feet. Factoring answers the question: which simpler expressions multiply to give this one? Always check by expanding: (x + 4)(x + 5) = x^2 + 9x + 20, confirmed."},
      {"heading":"Worked examples","text":"Example 1 (GCF first, always): factor 6x^3 + 9x^2. Each term contains 3x^2, so 6x^3 + 9x^2 = 3x^2(2x + 3). Example 2 (trinomial, negative constant): factor x^2 + 3x - 10. Two numbers multiplying to -10 and adding to 3: 5 and -2. So x^2 + 3x - 10 = (x + 5)(x - 2). Example 3 (leading coefficient not 1): factor 2x^2 + 7x + 3. Look for (2x + a)(x + b) with ab = 3 and outer plus inner equal to 7x: try (2x + 1)(x + 3) = 2x^2 + 6x + x + 3 = 2x^2 + 7x + 3, which works. Example 4 (difference of squares): factor 25x^2 - 16. Both terms are perfect squares, (5x)^2 and 4^2, separated by a minus: 25x^2 - 16 = (5x - 4)(5x + 4). Example 5 (combining moves): factor 3x^2 - 27. GCF first: 3(x^2 - 9), then difference of squares: 3(x - 3)(x + 3)."},
      {"heading":"Your turn","text":"(1) Factor 8x^2 + 12x. Answer: 4x(2x + 3); the GCF of the terms is 4x. (2) Factor x^2 + 8x + 15. Answer: (x + 3)(x + 5), since 3 + 5 = 8 and 3 times 5 = 15. (3) Factor x^2 - 5x - 24. Answer: (x - 8)(x + 3), since -8 + 3 = -5 and -8 times 3 = -24. (4) Factor x^2 - 49. Answer: (x - 7)(x + 7), a difference of squares. (5) Factor 3x^2 + 10x + 8. Answer: (3x + 4)(x + 2); check the middle: 6x + 4x = 10x. (6) Factor 2x^3 - 18x completely. Answer: 2x(x - 3)(x + 3); pull out 2x, then split x^2 - 9."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: skipping the GCF. Factoring 4x^2 - 16 as (2x - 4)(2x + 4) is incomplete; pulling out the GCF first gives 4(x - 2)(x + 2), the complete factorization. Misconception 2: factoring a SUM of squares. x^2 + 9 does not factor over the real numbers; only the DIFFERENCE of squares splits as (a - b)(a + b). Exit ticket: (1) Factor x^2 + 11x + 24. Answer: (x + 3)(x + 8). (2) Factor 9x^2 - 1. Answer: (3x - 1)(3x + 1), reading the terms as (3x)^2 and 1^2."}
   ]}',
   'Study tip: every factoring problem starts the same way — ask for the GCF first, then look for a pattern in what remains.', 13),
  (8, 'Quadratic equations (factoring, formula, graphs)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: solve quadratic equations by factoring and by the quadratic formula, use the discriminant to count solutions, and connect solutions to the graph of a parabola. Retrieval warm-up from Lesson 7: factor x^2 - 2x - 15. Answer: (x - 5)(x + 3), since -5 + 3 = -2 and -5 times 3 = -15. Keep that skill warm: solving by factoring is factoring plus one more idea."},
      {"heading":"The hook: when does the ball land?","text":"A ball is thrown from a 48-foot platform, and its height after t seconds is h = -16t^2 + 32t + 48. It lands when h = 0: -16t^2 + 32t + 48 = 0. Divide by -16: t^2 - 2t - 3 = 0, which factors as (t - 3)(t + 1) = 0. The zero product property says a product is zero only when a factor is zero, so t = 3 or t = -1. Time cannot be negative, so the ball lands after 3 seconds. The graph of h against t is a downward parabola, and the landing time is where it crosses the horizontal axis: solutions of a quadratic are the x-intercepts of its graph."},
      {"heading":"Worked examples","text":"Example 1 (solve by factoring): x^2 + 6x + 8 = 0 factors as (x + 2)(x + 4) = 0, so x = -2 or x = -4. Example 2 (quadratic formula): solve 2x^2 + 3x - 2 = 0. With a = 2, b = 3, c = -2, the formula x = (-b +/- sqrt(b^2 - 4ac))/(2a) gives x = (-3 +/- sqrt(9 + 16))/4 = (-3 +/- 5)/4, so x = 1/2 or x = -2. Example 3 (irrational solutions): solve x^2 - 2x - 5 = 0. The trinomial does not factor nicely, so use the formula: x = (2 +/- sqrt(4 + 20))/2 = (2 +/- sqrt(24))/2 = 1 +/- sqrt(6), since sqrt(24) = 2*sqrt(6). Example 4 (counting solutions with the discriminant): for x^2 + 4x + 5 = 0 the discriminant is b^2 - 4ac = 16 - 20 = -4, which is negative, so there are no real solutions and the parabola never touches the x-axis. Positive discriminant means two real solutions; zero means exactly one, where the vertex sits on the axis."},
      {"heading":"Your turn","text":"(1) Solve x^2 - 7x + 10 = 0. Answer: x = 2 or x = 5, from (x - 2)(x - 5) = 0. (2) Solve x^2 = 9x. Answer: x = 0 or x = 9; move everything to one side, x^2 - 9x = 0, and factor x(x - 9) = 0 rather than dividing by x, which loses the solution x = 0. (3) Solve 3x^2 - 12 = 0. Answer: x = 2 or x = -2; isolate x^2 = 4 and take both square roots. (4) Use the formula on x^2 + 4x - 3 = 0. Answer: x = -2 +/- sqrt(7), from (-4 +/- sqrt(16 + 12))/2. (5) How many real solutions does 4x^2 - 12x + 9 = 0 have? Answer: exactly one, x = 3/2, since the discriminant is 144 - 144 = 0. (6) A rectangular banner has length 3 feet more than its width and area 40 square feet: find the width. Answer: 5 feet; w(w + 3) = 40 gives w^2 + 3w - 40 = (w + 8)(w - 5) = 0, and the negative root is rejected."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: applying the zero product property to a nonzero product. From (x - 1)(x + 2) = 6 you may NOT conclude x - 1 = 6 or x + 2 = 6; the property only works when the product equals zero, so expand and rearrange to ... = 0 first. Misconception 2: writing only the positive square root. The equation x^2 = 25 has two solutions, x = 5 and x = -5; dropping the negative root is the most common lost point on quadratic problems. Exit ticket: (1) Solve x^2 + x - 12 = 0. Answer: x = 3 or x = -4. (2) Without solving, how many real solutions does x^2 - 6x + 9 = 0 have, and why? Answer: one, because the discriminant 36 - 36 = 0, so the parabola touches the axis at a single point."}
   ]}',
   'Study tip: before reaching for the quadratic formula, spend 20 seconds trying to factor — but if the numbers resist, switch without guilt; the formula always works.', 15),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"Simplify (x^2 - 3x + 2) - (2x^2 - 5x - 4).","options":["-x^2 + 2x + 6","3x^2 - 8x - 2","-x^2 - 8x - 2","-x^2 + 2x - 2"],"answer":0,"explanation":"Distribute the minus to all three terms: x^2 - 2x^2 = -x^2, -3x + 5x = 2x, 2 + 4 = 6 (Lesson 6)."},
      {"prompt":"Expand (3x - 2)(x + 4).","options":["3x^2 + 12x - 8","3x^2 + 10x - 8","3x^2 - 10x - 8","3x^2 + 10x + 8"],"answer":1,"explanation":"First and last give 3x^2 and -8; the middle is 12x - 2x = 10x (Lesson 6)."},
      {"prompt":"Which is the complete factorization of 6x^2 - 24?","options":["6(x^2 - 4)","(6x - 12)(x + 2)","6(x - 2)(x + 2)","(3x - 6)(2x + 4)"],"answer":2,"explanation":"Pull the GCF 6 first, then factor the difference of squares x^2 - 4 = (x - 2)(x + 2) (Lesson 7)."},
      {"prompt":"Factor x^2 - x - 20.","options":["(x - 4)(x + 5)","(x - 10)(x + 2)","(x + 4)(x - 5)","(x - 2)(x + 10)"],"answer":2,"explanation":"Need factors of -20 summing to -1: 4 and -5, so (x + 4)(x - 5) (Lesson 7)."},
      {"prompt":"Solve x^2 + 2x - 8 = 0.","options":["x = 2 or x = -4","x = -2 or x = 4","x = 1 or x = -8","x = 8 or x = -1"],"answer":0,"explanation":"Factor as (x - 2)(x + 4) = 0, giving x = 2 or x = -4 (Lesson 8)."},
      {"prompt":"What is the discriminant of 2x^2 - 4x + 5 = 0, and how many real solutions follow?","options":["36; two solutions","-24; no real solutions","-24; one solution","24; two solutions"],"answer":1,"explanation":"b^2 - 4ac = 16 - 40 = -24; a negative discriminant means no real solutions (Lesson 8)."},
      {"prompt":"A rectangle has area x^2 + 5x + 6 and one side of length x + 2. What is the other side?","options":["x + 6","x + 3","x - 3","x + 5"],"answer":1,"explanation":"Factor the area: (x + 2)(x + 3), so the missing side is x + 3 (Lessons 7 and 6)."}
   ]}',
   null, 10),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"slope","translation":"the constant rate of change of a line: rise over run, the change in y divided by the change in x","example":"The line through (0, 1) and (2, 7) has slope (7 - 1)/(2 - 0) = 3, so y grows 3 units per unit of x."},
      {"term":"y-intercept","translation":"the point where a graph crosses the y-axis: the output value when the input x equals 0","example":"In the cost model C = 1.75m + 2.50, the y-intercept 2.50 is the base fee before any miles are driven."},
      {"term":"function","translation":"a rule that assigns to each input exactly one output","example":"f(x) = x^2 is a function, but the rule that sends 4 to both 2 and -2 is not, because one input has two outputs."},
      {"term":"domain","translation":"the set of all inputs for which a function is defined","example":"The domain of f(x) = sqrt(x - 4) is x >= 4, since the expression under the root must be nonnegative."},
      {"term":"polynomial","translation":"a sum of terms, each a number times a variable raised to a whole-number power","example":"4x^3 - 2x + 7 is a polynomial of degree 3; its leading coefficient is 4."},
      {"term":"discriminant","translation":"the quantity b^2 - 4ac inside the quadratic formula; its sign tells how many real solutions a quadratic equation has","example":"For x^2 - 6x + 9 = 0 the discriminant is 36 - 36 = 0, so the equation has exactly one real solution."}
   ]}',
   null, 10),
  (11, 'Exponents, radicals & modeling data with lines', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"Objective: apply the exponent rules, simplify radicals, and fit a linear model to real data points. Retrieval warm-up from Lesson 8: how many real solutions does x^2 + 2x + 5 = 0 have? Answer: none, because the discriminant is 4 - 20 = -16, which is negative. Warm-up from Lesson 2: what is the slope of the line through (0, 10) and (5, 30)? Answer: 20/5 = 4. Both skills return in this lesson."},
      {"heading":"The hook: numbers too big to write","text":"A biologist counts bacteria doubling every hour: after n hours a single cell becomes 2^n cells, and after one day that is 2^24, about 16.7 million. Powers compress huge calculations, and three rules govern them. Product rule: x^a * x^b = x^(a+b), so x^3 * x^4 = x^7. Quotient rule: x^a / x^b = x^(a-b), so x^9 / x^2 = x^7. Power rule: (x^a)^b = x^(ab), so (x^2)^5 = x^10. Two consequences follow: x^0 = 1 for any nonzero x (from x^n / x^n = x^0 = 1), and x^(-n) = 1/x^n, so 2^(-3) = 1/8. Worked example: simplify (3x^2)^3 * x^(-4) = 27x^6 * x^(-4) = 27x^2."},
      {"heading":"Worked examples","text":"Example 1 (mixed exponent rules): simplify (2x^3 y)^2 * (x^2)/(4y). Square first: 4x^6 y^2; multiply by x^2 and divide by 4y: (4x^8 y^2)/(4y) = x^8 y. Example 2 (simplifying radicals): simplify sqrt(72). Find the largest perfect-square factor: 72 = 36 * 2, so sqrt(72) = sqrt(36) * sqrt(2) = 6*sqrt(2). Similarly sqrt(50x^2) = 5x*sqrt(2) for x >= 0. Example 3 (modeling with a line): a coffee cart logs (cups sold, profit): (40, 10) and (100, 100). Treat profit P as a linear function of cups c. Slope = (100 - 10)/(100 - 40) = 90/60 = 1.5 dollars of profit per cup. Then P = 1.5c + b, and the point (40, 10) gives 10 = 60 + b, so b = -50: P = 1.5c - 50. The intercept -50 is the daily fixed cost, and the break-even point is P = 0 at c = 50/1.5, about 34 cups. A fitted line turns two observations into predictions: at 80 cups the model predicts P = 1.5(80) - 50 = 70 dollars."},
      {"heading":"Your turn","text":"(1) Simplify x^5 * x^(-2). Answer: x^3; add the exponents, 5 + (-2) = 3. (2) Simplify (2x^4)^3. Answer: 8x^12; cube the 2 and multiply the exponents. (3) Evaluate 5^0 + 2^(-2). Answer: 1 + 1/4 = 5/4. (4) Simplify sqrt(48). Answer: 4*sqrt(3), since 48 = 16 * 3. (5) A plant measures 12 cm in week 2 and 21 cm in week 5: assuming linear growth, write the model and predict week 8. Answer: slope = 9/3 = 3 cm per week, model h = 3w + 6, prediction h = 30 cm. (6) In that plant model, what does the intercept 6 mean? Answer: the modeled height at week 0, the starting height of about 6 cm."},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: x^0 = 0. Any nonzero base to the zero power is 1, because dividing x^n by itself must give 1. Misconception 2: sqrt(a + b) = sqrt(a) + sqrt(b). False: sqrt(9 + 16) = sqrt(25) = 5, but sqrt(9) + sqrt(16) = 3 + 4 = 7; roots do not distribute over addition, only over multiplication. Exit ticket: (1) Simplify x^10 / x^4. Answer: x^6. (2) A linear model of temperature is T = -2h + 68 with h in hours after noon: what do the slope and intercept mean? Answer: the temperature falls 2 degrees per hour, starting from 68 degrees at noon."}
   ]}',
   'Study tip: when a radical or exponent expression looks scary, rewrite every piece as prime factors and powers — the rules then apply themselves.', 14),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"A line passes through (2, 1) and (6, 13). Which equation describes it?","options":["y = 3x - 5","y = 3x + 1","y = 4x - 7","y = 2x - 3"],"answer":0,"explanation":"Slope = (13 - 1)/(6 - 2) = 3; then 1 = 3(2) + b gives b = -5, so y = 3x - 5."},
      {"prompt":"Solve the system 2x + 3y = 4 and 4x - y = 22.","options":["(4, -2)","(5, -2)","(5, 2)","(-5, 2)"],"answer":1,"explanation":"From the second equation y = 4x - 22; substitute: 2x + 12x - 66 = 4, so 14x = 70, x = 5 and y = -2."},
      {"prompt":"What is the domain of f(x) = sqrt(x + 3)/(x - 2)?","options":["x >= -3","x >= -3 and x != 2","x > 2","all real numbers except 2"],"answer":1,"explanation":"The radicand needs x + 3 >= 0 and the denominator forbids x = 2; both conditions must hold."},
      {"prompt":"Which is the complete factorization of 3x^2 - 12?","options":["3(x - 2)(x + 2)","(3x - 6)(x + 2)","3(x^2 - 4)","(x - 2)(3x + 6)"],"answer":0,"explanation":"GCF first: 3(x^2 - 4); then the difference of squares gives 3(x - 2)(x + 2). The other forms are incomplete or not fully factored."},
      {"prompt":"What are the exact solutions of x^2 - 2x - 5 = 0?","options":["x = 1 +/- sqrt(5)","x = 2 +/- sqrt(6)","x = 1 +/- sqrt(6)","x = -1 +/- sqrt(6)"],"answer":2,"explanation":"The quadratic formula gives x = (2 +/- sqrt(4 + 20))/2 = (2 +/- 2*sqrt(6))/2 = 1 +/- sqrt(6)."},
      {"prompt":"For which value of k does x^2 + kx + 16 = 0 have exactly one real solution?","options":["k = 4","k = 16","k = 8 or k = -8","k = 2 or k = -2"],"answer":2,"explanation":"One solution requires discriminant zero: k^2 - 64 = 0, so k = 8 or k = -8."},
      {"prompt":"Simplify (2x^3)^2 * x^(-2).","options":["4x^4","2x^4","4x^8","4x^3"],"answer":0,"explanation":"(2x^3)^2 = 4x^6, and multiplying by x^(-2) subtracts 2 from the exponent: 4x^4."},
      {"prompt":"A theater sells 200 tickets for a total of 2160 dollars. Adult tickets cost 12 dollars and child tickets cost 8 dollars. How many adult tickets were sold?","options":["120","150","60","140"],"answer":3,"explanation":"Let a be adult tickets: a + c = 200 and 12a + 8c = 2160. Substitute c = 200 - a: 12a + 1600 - 8a = 2160, so 4a = 560 and a = 140. Check: 140(12) + 60(8) = 1680 + 480 = 2160."}
   ]}',
   null, 15)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0001-0000-4000-8000-000000000003' and l.position = v.pos
);
