-- Mathematics: Arithmetic Foundations (English, subject 'math').
-- A mastery-based arithmetic course modeled on Khan Academy progression:
-- diagnostic first, short teaching cycles (objective, instruction, worked
-- examples, practice, misconceptions, exit ticket), checkpoints after each
-- unit cluster, and a cumulative final assessment. All content is original.
-- Fixed UUIDs and guarded inserts make the file idempotent: safe to re-run.

-- ============ Arithmetic Foundations ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0001-0000-4000-8000-000000000001',
  'en', null,
  'Arithmetic Foundations',
  'Build rock-solid arithmetic from place value to percentages and ratios. Every lesson teaches with worked examples, real-life practice problems, and exit tickets, with checkpoints along the way so you only move on once you have mastered the step before.',
  null, 'foundations', 1, true, 'math', '{}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0001-0000-4000-8000-000000000001', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"In the number 4,872, what is the value of the digit 8?","options":["8","80","800","8,000"],"answer":2,"explanation":"The 8 sits in the hundreds place, so it is worth 8 hundreds, or 800. If this felt shaky, start with Lesson 2: Number sense and place value."},
      {"prompt":"What is 297 + 456?","options":["743","753","763","653"],"answer":1,"explanation":"A quick strategy: move 3 from 456 to 297 to make 300 + 453 = 753. Lesson 3 teaches strategies like this for fast, accurate addition and subtraction."},
      {"prompt":"What is 14 x 6?","options":["74","82","84","96"],"answer":2,"explanation":"Split 14 into 10 + 4: (10 x 6) + (4 x 6) = 60 + 24 = 84. Lesson 4 covers multiplication and division, including this splitting strategy."},
      {"prompt":"What is 132 divided by 12?","options":["9","10","11","12"],"answer":2,"explanation":"12 x 11 = 132, so 132 / 12 = 11. Division as the reverse of multiplication is taught in Lesson 4."},
      {"prompt":"Which fraction is larger: 3/4 or 2/3?","options":["3/4","2/3","They are equal","It cannot be determined"],"answer":0,"explanation":"Rewrite both with denominator 12: 3/4 = 9/12 and 2/3 = 8/12, so 3/4 is larger. Comparing fractions with common denominators is in Lesson 6."},
      {"prompt":"Which fraction equals 0.25?","options":["1/5","1/4","2/5","1/3"],"answer":1,"explanation":"0.25 means 25 hundredths, and 25/100 simplifies to 1/4. Converting between decimals and fractions is covered in Lesson 7."},
      {"prompt":"What is 20% of 45?","options":["9","11","20","5"],"answer":0,"explanation":"20% is one fifth, and 45 / 5 = 9. Percentages, including quick benchmark percents, are taught in Lesson 7."},
      {"prompt":"A smoothie recipe uses 2 cups of strawberries for every 3 cups of milk. How many cups of strawberries do you need with 9 cups of milk?","options":["4","5","6","8"],"answer":2,"explanation":"The milk tripled from 3 to 9, so the strawberries must triple too: 2 x 3 = 6. Scaling ratios like this is the heart of Lesson 8."}
   ]}',
   null, 10),
  (2, 'Number sense & place value', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"By the end of this lesson you will be able to read, write, compare, and round whole numbers up to the millions by naming exactly what each digit is worth. Warm-up from the diagnostic: in 4,872, what is the digit 8 worth? (Answer: 800 - it sits in the hundreds place.) If you got that instantly, great; this lesson will make the why airtight."},
      {"heading":"The idea","text":"You are buying a used car and two listings catch your eye: one for $30,507 and one for $3,057. Same digits, wildly different prices - the difference is place value. Our number system is positional: a digit''s value depends on where it stands. Read $30,507 digit by digit from the left: 3 is in the ten-thousands place (30,000), 0 is in the thousands place (0), 5 is in the hundreds place (500), 0 is in the tens place (0), 7 is in the ones place (7). Add the values: 30,000 + 500 + 7 = 30,507. That sum is called expanded form, and the zeros are not decoration - they are placeholders that keep every other digit in its correct column. Delete them and 30,507 collapses to 357, a different number entirely."},
      {"heading":"Worked examples","text":"Example 1 - expanded form. Write 68,209 in expanded form. Work left to right: 6 ten-thousands = 60,000; 8 thousands = 8,000; 2 hundreds = 200; 0 tens = 0; 9 ones = 9. So 68,209 = 60,000 + 8,000 + 200 + 9. Example 2 - comparing. Which is larger, 61,532 or 61,489? Compare digit by digit from the left: ten-thousands match (6 = 6), thousands match (1 = 1), hundreds differ: 5 > 4. Stop there - 61,532 is larger, no matter what the remaining digits are. Example 3 - rounding. Round 4,872 to the nearest hundred. The hundreds digit is 8, so the two candidates are 4,800 and 4,900. Look one place to the right: the tens digit is 7, which is 5 or more, so round up. Answer: 4,900."},
      {"heading":"Your turn","text":"Solve, then check below. 1) What is the value of the 5 in 251,304? 2) Write 40,032 in expanded form. 3) Which is larger: 89,940 or 90,104? 4) Round 36,481 to the nearest thousand. 5) Round 749 to the nearest hundred. Answers: 1) 50,000 - the 5 is in the ten-thousands place. 2) 40,000 + 30 + 2 - the thousands and hundreds places hold zeros. 3) 90,104 - its ten-thousands digit is 9 versus 8. 4) 36,000 - the hundreds digit is 4, less than 5, so round down. 5) 700 - the tens digit is 4, so 749 stays with 700 even though it feels close to 750."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: treating zeros as skippable. Students write thirty thousand five hundred seven as 3,057 or 30,057, dropping or misplacing the placeholder zeros. Cure: draw the place-value columns first, then fill digits in. Mistake 2: rounding by feel. For 749 to the nearest hundred, it is tempting to answer 750 or 800 because 749 feels big - but the rule looks only at the tens digit (4), so the answer is 700. Exit ticket: A) Write the number 205,060 in expanded form. (Answer: 200,000 + 5,000 + 60.) B) Round 15,509 to the nearest thousand. (Answer: 16,000 - the hundreds digit is 5, so round up.)"}
   ]}',
   'Study tip: say big numbers out loud in words - hearing "two hundred five thousand" makes missing-zero mistakes almost impossible.', 13),
  (3, 'Addition & subtraction strategies', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will add and subtract multi-digit numbers accurately with the column method, and faster in your head with two strategies: making round numbers and counting up. Warm-up from Lesson 2: round 3,462 to the nearest hundred. (Answer: 3,500 - the tens digit is 6, so round up.) Rounding matters here because it is how you estimate an answer before trusting a calculation."},
      {"heading":"The idea","text":"You are at the register with items costing $297 and $456, and you want to know the total before the cashier does. Strategy 1 - compensation: move 3 from 456 to 297. Now the problem is 300 + 453 = 753. Nothing was lost, one number just became round. Strategy 2 - the column method, when numbers are awkward: write 587 + 348 with ones over ones, tens over tens. Ones: 7 + 8 = 15, write 5, carry 1 ten. Tens: 8 + 4 + 1 = 13, write 3, carry 1 hundred. Hundreds: 5 + 3 + 1 = 9. Total: 935. The carry is not a trick - 15 ones literally is 1 ten and 5 ones, so the ten moves to the tens column where it belongs. Always estimate first: 587 + 348 is roughly 600 + 350 = 950, so 935 is believable."},
      {"heading":"Worked examples","text":"Example 1 - counting up for change. You pay for a $6.35 sandwich with a $10 bill. Instead of subtracting, count up: 6.35 to 6.40 is 0.05; 6.40 to 7.00 is 0.60; 7.00 to 10.00 is 3.00. Change: 0.05 + 0.60 + 3.00 = $3.65. Example 2 - column subtraction with regrouping. Compute 703 - 268. Ones: 3 - 8 will not work, and the tens digit is 0, so go to the hundreds: regroup 7 hundreds 0 tens as 6 hundreds 10 tens, then 10 tens as 9 tens 13 ones. Now ones: 13 - 8 = 5; tens: 9 - 6 = 3; hundreds: 6 - 2 = 4. Answer: 435. Check by adding back: 435 + 268 = 703. Example 3 - compensation in subtraction. Compute 641 - 299. Subtract 300 instead (too much by 1), then give the 1 back: 641 - 300 = 341, so 641 - 299 = 342."},
      {"heading":"Your turn","text":"Solve, then check below. 1) 468 + 397, using compensation. 2) 825 - 476, using the column method. 3) You pay for a $4.15 coffee with a $20 bill; count up to find the change. 4) 5,204 + 3,896. 5) 1,000 - 387. Answers: 1) 865 - move 3: 465 + 400 = 865. 2) 349 - regroup twice and check: 349 + 476 = 825. 3) $15.85 - 0.85 gets you to 5.00, then 15.00 more to 20.00. 4) 9,100 - the ones and tens both carry; estimate 5,200 + 3,900 = 9,100 confirms it. 5) 613 - count up: 387 + 13 = 400, then + 600 = 1,000, so 13 + 600 = 613."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: forgetting the carry, so 587 + 348 becomes 825 instead of 935. Cure: estimate first - roughly 950 - and a dropped carry will jump out. Mistake 2: in subtraction, flipping the digits instead of regrouping - faced with 3 - 8 in the ones column, writing 5 by computing 8 - 3. Subtraction is not symmetric; you must regroup from the next column. Exit ticket: A) Compute 902 - 458. (Answer: 444 - regroup through the zero.) B) Use compensation for 356 + 498. (Answer: 854 - add 500, then take 2 back.)"}
   ]}',
   'Study tip: estimate every answer before you compute - a wrong carry can survive careless checking, but it rarely survives a good estimate.', 13),
  (4, 'Multiplication & division', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will multiply multi-digit numbers by splitting them into friendly parts, and divide with long division, interpreting remainders sensibly. Warm-up from Lesson 3: use compensation to compute 499 + 499. (Answer: 998 - it is 500 + 500 - 2.) Multiplication builds directly on addition: 499 + 499 is exactly 2 x 499."},
      {"heading":"The idea","text":"A school hall has 14 rows of 6 chairs, and you need to know if 90 people will fit. That is 14 x 6 - fourteen groups of six. Adding six fourteen times works but is slow; instead split 14 by place value: 14 = 10 + 4, so 14 x 6 = (10 x 6) + (4 x 6) = 60 + 24 = 84. This is the distributive property, and it is the engine inside every written multiplication method. Not enough chairs for 90! Division asks the reverse question: 84 chairs in rows of 6 means how many rows? 84 / 6: split 84 into 60 + 24, and 60 / 6 = 10, 24 / 6 = 4, so 14 rows. Multiplication and division undo each other - every fact like 6 x 14 = 84 gives you two division facts for free: 84 / 6 = 14 and 84 / 14 = 6."},
      {"heading":"Worked examples","text":"Example 1 - two-digit by two-digit. Compute 23 x 15. Split both: 23 x 15 = 23 x 10 + 23 x 5 = 230 + 115 = 345. Estimate check: 23 x 15 is near 20 x 15 = 300, so 345 is plausible. Example 2 - long division. Compute 372 / 4. Hundreds: 4 does not go into 3, so look at 37 tens. 4 x 9 = 36, so 9 tens, remainder 1 ten. Bring down the 2: 12 ones. 4 x 3 = 12, so 3 ones, remainder 0. Answer: 93. Check: 93 x 4 = 372. Example 3 - remainders in real life. 130 students are going on a trip and each bus seats 40. 130 / 40 = 3 remainder 10 - but the answer to the question is 4 buses, because the 10 leftover students still need a seat. The same division answers a different question differently: with $130 buying $40 tickets, you can buy only 3 - here the remainder is money you keep, not people you strand."},
      {"heading":"Your turn","text":"Solve, then check below. 1) 17 x 8, by splitting 17. 2) 34 x 26. 3) 456 / 6. 4) 250 / 7 - give quotient and remainder. 5) Eggs come in boxes of 12; a recipe batch uses 30 eggs. How many boxes must you buy for one batch? Answers: 1) 136 - (10 x 8) + (7 x 8) = 80 + 56. 2) 884 - 34 x 20 = 680 plus 34 x 6 = 204. 3) 76 - 45 tens / 6 = 7 tens remainder 3; 36 ones / 6 = 6. 4) 35 remainder 5 - since 7 x 35 = 245. 5) 3 boxes - 30 / 12 = 2 remainder 6, and the 6 extra eggs force a third box."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: dropping a partial product - computing 23 x 15 as 23 x 10 + 5 = 235, forgetting that the 5 must multiply all of 23. Every part of one number multiplies every part of the other. Mistake 2: writing remainders as decoration - answering the bus problem with 3 r 10 and moving on. A remainder always means something; decide whether it forces rounding up, gets discarded, or is itself the answer. Exit ticket: A) Compute 19 x 21 by splitting. (Answer: 399 - 19 x 20 + 19 x 1 = 380 + 19.) B) 200 chairs are packed in stacks of 8; how many full stacks? (Answer: 25 - 8 x 25 = 200 exactly, no remainder.)"}
   ]}',
   null, 14),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"What is the value of the digit 7 in 471,206?","options":["7,000","70,000","700","700,000"],"answer":1,"explanation":"The 7 is in the ten-thousands place: 70,000. Revisit Lesson 2 if place names feel uncertain."},
      {"prompt":"Round 68,451 to the nearest thousand.","options":["68,000","68,500","69,000","70,000"],"answer":0,"explanation":"The hundreds digit is 4, which is less than 5, so round down to 68,000. Lesson 2 covers the round-by-the-next-digit rule."},
      {"prompt":"Use compensation to compute 598 + 276.","options":["864","874","884","876"],"answer":1,"explanation":"Add 600 instead of 598, then subtract the extra 2: 600 + 276 = 876, minus 2 is 874. Lesson 3, strategy 1."},
      {"prompt":"What is 804 - 356?","options":["452","458","448","548"],"answer":2,"explanation":"Regroup through the zero: 804 - 356 = 448. Check by adding back: 448 + 356 = 804. Lesson 3 shows the regrouping steps."},
      {"prompt":"What is 27 x 14?","options":["368","378","388","358"],"answer":1,"explanation":"Split it: 27 x 10 = 270 and 27 x 4 = 108, so 270 + 108 = 378. Lesson 4 calls this the distributive property."},
      {"prompt":"A ferry carries 45 cars per trip. 260 cars are waiting. How many trips are needed to move them all?","options":["5","6","7","5 remainder 35"],"answer":1,"explanation":"260 / 45 = 5 remainder 35, and the 35 leftover cars still need a trip, so 6 trips. Lesson 4 covers interpreting remainders."}
   ]}',
   null, 8),
  (6, 'Fractions: meaning, equivalence, operations', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will read a fraction as equal parts of a whole, recognize when two fractions are the same number, compare fractions, and add, subtract, and multiply them. Warm-up from Lesson 4: what is 84 / 6? (Answer: 14.) Division and fractions are the same idea wearing different clothes - the fraction 84/6 literally means 84 divided by 6."},
      {"heading":"The idea","text":"Two friends order the same size pizza. Ana cuts hers into 4 slices and eats 3; Ben cuts his into 8 slices and eats 6. Who ate more? Neither - 3/4 and 6/8 are the same amount. The bottom number (denominator) says how many equal parts the whole is cut into; the top number (numerator) says how many of those parts you take. Cutting every slice in half doubles both numbers without changing the amount: 3/4 = 6/8. That is equivalence, and the rule is: multiply or divide the numerator and denominator by the same nonzero number and the value does not change. Equivalence is the master key - it lets you compare and add fractions by rewriting them with the same denominator, so the parts are the same size and you can just count them."},
      {"heading":"Worked examples","text":"Example 1 - comparing. Which is larger, 5/6 or 7/9? Common denominator 18: 5/6 = 15/18 and 7/9 = 14/18, so 5/6 is larger. Example 2 - adding unlike fractions. A recipe needs 1/2 cup of white sugar and 1/3 cup of brown sugar; how much sugar total? Rewrite with denominator 6: 1/2 = 3/6 and 1/3 = 2/6, so the total is 5/6 cup. You cannot add 1/2 + 1/3 as 2/5 - halves and thirds are different sized parts, so first make the parts match. Example 3 - multiplying. You have 3/4 of a chocolate bar and eat 2/3 of that. Of means multiply: 2/3 x 3/4 = 6/12 = 1/2 of the whole bar. Multiply tops together, bottoms together, then simplify by dividing both by 6."},
      {"heading":"Your turn","text":"Solve, then check below. 1) Fill in: 3/5 = ?/20. 2) Which is larger: 4/7 or 3/5? 3) 2/3 + 1/6. 4) 7/8 - 1/4. 5) 4/5 x 5/8. 6) A jug holds 3/4 liter and is 2/3 full; how much water is in it? Answers: 1) 12 - multiply top and bottom by 4. 2) 3/5 - with denominator 35, 4/7 = 20/35 and 3/5 = 21/35, so 3/5 wins by one thirty-fifth; always compute, never guess. 3) 5/6 - rewrite 2/3 as 4/6. 4) 5/8 - rewrite 1/4 as 2/8. 5) 1/2 - 20/40 simplifies. 6) 1/2 liter - 2/3 x 3/4 = 6/12 = 1/2."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: adding straight across - 1/2 + 1/3 = 2/5. Test it with sense: 2/5 is less than 1/2, but adding sugar to sugar cannot give you less than you started with. Unlike denominators must be made equal first. Mistake 2: believing a bigger denominator means a bigger fraction. 1/8 is smaller than 1/4 - cutting a pizza into more slices makes each slice smaller. Exit ticket: A) Compute 5/6 - 1/2. (Answer: 1/3 - rewrite as 5/6 - 3/6 = 2/6 = 1/3.) B) Which is larger, 2/3 or 7/12? (Answer: 2/3 - it equals 8/12.)"}
   ]}',
   'Study tip: when a fraction answer surprises you, redraw it as a pizza or a measuring cup - a ten-second sketch catches most fraction errors.', 15),
  (7, 'Decimals & percentages', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will read decimals as place value continued past the ones, convert fluently between fractions, decimals, and percents, and compute percentages of real quantities. Warm-up from Lesson 6: which is larger, 3/10 or 1/4? (Answer: 3/10 - with denominator 20 it is 6/20 versus 5/20.) Keep that pair in mind; in a moment you will compare them again as decimals with far less work."},
      {"heading":"The idea","text":"A supermarket shelf shows the same juice in two bottles: 0.5 liter for $1.20 and 0.75 liter for $1.60. Decimals are place value continuing rightward past the ones: in 0.75, the 7 is in the tenths place (7/10) and the 5 is in the hundredths place (5/100), so 0.75 = 75/100 = 3/4. Percent means per hundred, so the same number has a third name: 75%. One quantity, three costumes: 3/4 = 0.75 = 75%. To move between them: a percent is the decimal times 100 (0.75 becomes 75%), and a decimal is the percent divided by 100 (40% becomes 0.40). The warm-up comparison is now instant: 3/10 = 0.30 and 1/4 = 0.25, and 0.30 > 0.25 because 3 tenths beats 2 tenths - compare decimals digit by digit from the left, exactly like whole numbers."},
      {"heading":"Worked examples","text":"Example 1 - percent of a number. A $60 pair of sneakers is 25% off. 25% = 1/4, and 60 / 4 = 15, so you save $15 and pay $45. Example 2 - building percents from 10%. Find 35% of 80. First 10% of 80 = 8 (just divide by 10). Then 30% = 3 x 8 = 24, and 5% = half of 8 = 4. So 35% of 80 = 24 + 4 = 28. Example 3 - which discount is better? A $50 jacket has two offers: 20% off, or $12 off. 20% of 50: 10% is 5, so 20% is 10 - a $10 discount. The $12 coupon wins. Percentages are relative; dollars are absolute - always convert to the same units before comparing."},
      {"heading":"Your turn","text":"Solve, then check below. 1) Write 0.6 as a fraction in simplest form. 2) Write 7/20 as a percent. 3) Which is larger: 0.45 or 0.5? 4) Find 15% of 240. 5) A $32 book is 50% off, then an extra 10% off the sale price - what do you pay? 6) A quiz score is 18 out of 24; what percent is that? Answers: 1) 3/5 - 0.6 = 6/10, divide both by 2. 2) 35% - 7/20 = 35/100. 3) 0.5 - it is 0.50, and 5 tenths beats 4 tenths. 4) 36 - 10% is 24, 5% is 12. 5) $14.40 - half of 32 is 16, then 10% of 16 is 1.60 off. 6) 75% - 18/24 = 3/4."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: longer decimal means bigger - reading 0.45 as larger than 0.5 because 45 beats 5. Compare place by place: 0.5 has 5 tenths, 0.45 has only 4 tenths. Padding helps: 0.50 versus 0.45. Mistake 2: stacking percents by adding - assuming 50% off then 10% off equals 60% off. The second discount applies to the already-reduced price, so the combined discount is 55%, not 60%. Exit ticket: A) Write 4% as a decimal. (Answer: 0.04 - not 0.4, which is 40%.) B) Find 90% of 70. (Answer: 63 - take 10% of 70, which is 7, off the top.)"}
   ]}',
   'Study tip: memorize the benchmark trio 1/2 = 0.5 = 50%, 1/4 = 0.25 = 25%, 1/10 = 0.1 = 10% - nearly every mental percent calculation is built from them.', 14),
  (8, 'Ratios & proportional thinking', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will describe how two quantities relate with a ratio, scale ratios up and down with ratio tables, and use unit rates to compare deals and solve for unknowns. Warm-up from Lesson 7: what is 10% of 350? (Answer: 35 - divide by 10.) Percentages are actually ratios in disguise - a comparison to 100 - so this lesson generalizes what you already know."},
      {"heading":"The idea","text":"You are mixing paint: the tin says 2 parts blue to 3 parts yellow makes the perfect green. The ratio 2:3 does not tell you amounts - it tells you a relationship that must hold at every size. Want a bigger batch? Multiply both parts by the same number, exactly like equivalent fractions: 2:3 = 4:6 = 6:9 = 20:30. A ratio table keeps this organized - blue: 2, 4, 6, 20; yellow: 3, 6, 9, 30. The other essential tool is the unit rate: how much of one thing per exactly one of the other. If 5 kg of apples cost $12, the unit rate is 12 / 5 = $2.40 per kg, and from that single number you can price any amount: 8 kg costs 8 x 2.40 = $19.20."},
      {"heading":"Worked examples","text":"Example 1 - scaling a recipe. Pancakes for 4 people use 2 cups of flour and 3 eggs. For 10 people, the scale factor is 10 / 4 = 2.5, so you need 2 x 2.5 = 5 cups of flour and 3 x 2.5 = 7.5 eggs - round up to 8 eggs in practice. Example 2 - comparing deals by unit price. Brand A sells 6 yogurts for $4.50; Brand B sells 8 for $5.60. A: 4.50 / 6 = $0.75 each. B: 5.60 / 8 = $0.70 each. Brand B is the better deal, even though its pack costs more. Example 3 - solving a proportion. A cyclist rides 24 km in 90 minutes at a steady pace. How far in 60 minutes? Unit rate: 24 / 90 = 4/15 km per minute is ugly - so scale smartly instead: 60 is two thirds of 90, so the distance is two thirds of 24 = 16 km. Choose the tool that keeps the numbers friendly."},
      {"heading":"Your turn","text":"Solve, then check below. 1) Simplify the ratio 12:18. 2) Orange squash mixes 1 part concentrate to 4 parts water; how much water for 3 cups of concentrate? 3) 5 pens cost $6.25 - what is the unit price? 4) A car travels 180 km on 12 liters of fuel; how far on 20 liters? 5) A map scale is 1 cm : 5 km; two towns are 7.5 cm apart on the map - what is the real distance? 6) Which is faster: 150 km in 2 hours, or 200 km in 2.5 hours? Answers: 1) 2:3 - divide both by 6. 2) 12 cups - multiply both parts by 3. 3) $1.25 per pen - 6.25 / 5. 4) 300 km - unit rate 15 km per liter, times 20. 5) 37.5 km - 7.5 x 5. 6) They are equally fast - both are 75 km per hour."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: scaling by adding. If 2:3 becomes 4:?, the answer is 6 (both doubled), not 5 (both plus 2). Additive thinking breaks the relationship; ratios scale by multiplication only. Mistake 2: comparing pack prices instead of unit prices - the bigger pack is often but not always cheaper per item, and only the unit rate can tell you. Exit ticket: A) A ratio of teachers to students is 1:12; how many teachers for 84 students? (Answer: 7 - 84 / 12.) B) 3 kg of rice cost $7.50; what do 5 kg cost? (Answer: $12.50 - unit rate $2.50 per kg.)"}
   ]}',
   null, 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"Which fraction is equivalent to 4/6?","options":["6/8","8/12","3/4","2/4"],"answer":1,"explanation":"Multiply the numerator and denominator of 4/6 by 2 to get 8/12; both simplify to 2/3. Lesson 6 covers equivalence."},
      {"prompt":"What is 3/8 + 1/4?","options":["4/12","1/3","5/8","4/8"],"answer":2,"explanation":"Rewrite 1/4 as 2/8, then add same-size parts: 3/8 + 2/8 = 5/8. Adding straight across (4/12) is the classic error - see Lesson 6."},
      {"prompt":"Write 0.35 as a fraction in simplest form.","options":["35/100","7/20","3/5","5/7"],"answer":1,"explanation":"0.35 = 35/100; divide top and bottom by 5 to get 7/20. Lesson 7 covers decimal-fraction conversion."},
      {"prompt":"A $48 game is 25% off. What do you pay?","options":["$12","$36","$40","$44"],"answer":1,"explanation":"25% of 48 is 12 (a quarter), so the price is 48 - 12 = $36. Read carefully: the question asks what you pay, not what you save. Lesson 7."},
      {"prompt":"A ratio of 3:5 is scaled so the first number becomes 12. What is the second?","options":["14","15","20","17"],"answer":2,"explanation":"3 was multiplied by 4, so 5 must be too: 5 x 4 = 20. Adding 9 to both (giving 14) breaks the ratio - Lesson 8, mistake 1."},
      {"prompt":"4 avocados cost $5.00 at one stall and 6 cost $7.20 at another. Which is the better deal?","options":["The 4-pack","The 6-pack","They cost the same per avocado","It cannot be compared"],"answer":1,"explanation":"Unit prices: 5.00 / 4 = $1.25 each versus 7.20 / 6 = $1.20 each. The 6-pack is cheaper per avocado. Lesson 8 covers unit rates."}
   ]}',
   null, 8),
  (10, 'Key terms & number facts', 'vocab',
   '{"items":[
      {"term":"place value","translation":"the value a digit has because of its position in a number - each place is worth ten times the place to its right","example":"In 4,872 the 8 has a place value of 800, because it sits in the hundreds place."},
      {"term":"numerator and denominator","translation":"the top and bottom numbers of a fraction: the denominator says how many equal parts the whole is cut into, the numerator says how many parts you take","example":"In 3/4 of a pizza, the denominator 4 means four equal slices and the numerator 3 means you take three of them."},
      {"term":"percent","translation":"per hundred - a way of writing a fraction with denominator 100, marked with the % sign","example":"Scoring 45 out of 50 on a test is 90/100, or 90 percent."},
      {"term":"ratio","translation":"a comparison of two quantities that must keep the same multiplicative relationship when scaled","example":"A paint mix of 2:3 blue to yellow stays the same green whether you use 2 and 3 cups or 20 and 30."},
      {"term":"quotient and remainder","translation":"the result of a division and whatever is left over when the division is not exact","example":"130 / 40 gives a quotient of 3 and a remainder of 10, so 130 students need 4 buses of 40 seats."},
      {"term":"unit rate","translation":"how much of one quantity corresponds to exactly one unit of another - the fair way to compare deals or speeds","example":"If 5 kg of apples cost $12, the unit rate is $2.40 per kilogram."}
   ]}',
   null, 8),
  (11, 'Negative numbers, measurement & multi-step word problems', 'reading',
   '{"sections":[
      {"heading":"What you''ll be able to do","text":"You will work confidently with numbers below zero, convert between common metric units, and take apart word problems that need several operations in a row. Warm-up from Lesson 7: what is 25% of 80? (Answer: 20 - a quarter of 80.) You will need percent skills again inside today''s word problems."},
      {"heading":"The idea","text":"The weather app says the temperature will drop from 3 degrees to -4 degrees overnight. How big is the drop? Picture the number line: negative numbers continue it to the left of zero, mirror images of the positives. From 3 down to 0 is 3 degrees; from 0 down to -4 is 4 more; total drop: 7 degrees. Two rules cover most situations. Adding a negative moves you left: 5 + (-8) = -3, exactly like spending $8 when you have $5 leaves you $3 in debt. Subtracting moves you left too, even past zero: -2 - 3 = -5. And comparisons flip below zero: -7 < -2, because -7 is further left, just as owing $7 is worse than owing $2. Measurement uses the same place-value muscle: metric units scale by tens - 1 m = 100 cm, 1 km = 1,000 m, 1 kg = 1,000 g, 1 L = 1,000 mL - so converting is just multiplying or dividing by 10, 100, or 1,000."},
      {"heading":"Worked examples","text":"Example 1 - bank balance. Your account holds $40. You spend $65, then your friend repays $30. Step by step: 40 - 65 = -25 (overdrawn by $25), then -25 + 30 = 5. Final balance: $5. Example 2 - unit conversion. A recipe needs 1.5 L of stock and you have three 400 mL cartons. Convert to one unit first: 1.5 L = 1,500 mL, and 3 x 400 = 1,200 mL. You are 300 mL short. Example 3 - a full multi-step problem. Tickets cost $12 for adults and $8 for children; a family of 2 adults and 3 children pays with a $100 bill after a 10% group discount - what change do they get? Plan before computing: (1) adults: 2 x 12 = 24; (2) children: 3 x 8 = 24; (3) subtotal: 48; (4) discount: 10% of 48 = 4.80, so they pay 43.20; (5) change: 100 - 43.20 = $56.80. Five small steps, each one easy - that is the whole secret."},
      {"heading":"Your turn","text":"Solve, then check below. 1) Compute -6 + 10. 2) The temperature falls from -2 to -9 degrees; how many degrees did it fall? 3) Convert 2.4 km to meters. 4) Which is colder: -3 or -11 degrees? 5) A runner does 5 laps of a 400 m track; how many kilometers is that? 6) You buy 3 notebooks at $2.50 each and pay with a $10 bill; you then find 25% of your change in coins fell through your pocket - how much did you lose? Answers: 1) 4 - start at -6, move 10 right. 2) 7 degrees - from -2 down to -9 is 7 steps left. 3) 2,400 m - multiply by 1,000. 4) -11 - it is further left on the number line. 5) 2 km - 5 x 400 = 2,000 m. 6) $0.625, about 63 cents - change is 10 - 7.50 = 2.50, and a quarter of that is 0.625."},
      {"heading":"Common mistakes & exit ticket","text":"Mistake 1: treating -11 as bigger than -3 because 11 beats 3. Below zero the comparison flips: more negative means smaller and colder. Mistake 2: solving a word problem with the first operation that comes to mind. Cure: read, list the steps in plain words, solve each step, then reread the question to confirm you answered what was asked - many students compute the discount correctly and then forget to give the change. Exit ticket: A) Compute -5 - 4. (Answer: -9 - subtracting moves further left.) B) A 2 L bottle fills how many 250 mL glasses? (Answer: 8 - 2,000 / 250.)"}
   ]}',
   'Study tip: for any problem with negatives, sketch a quick number line - direction errors vanish when you can see left and right.', 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"A charity counts donations of $4,875, $12,060, and $9,308. Rounding each to the nearest thousand first, which is the best estimate of the total?","options":["$25,000","$26,000","$27,000","$24,000"],"answer":1,"explanation":"Round: 5,000 + 12,000 + 9,000 = 26,000. (Exact total: 26,243.) Rounding and estimation are from Lessons 2 and 3."},
      {"prompt":"A theater has 38 rows of 26 seats. 950 tickets were sold. How many seats remain empty?","options":["38","48","28","58"],"answer":0,"explanation":"38 x 26 = 988 seats (38 x 20 = 760, plus 38 x 6 = 228). Then 988 - 950 = 38. A two-step problem combining Lessons 3 and 4."},
      {"prompt":"What is 2/3 of 5/8... wait - which is it: the calculation 2/3 x 5/8, or 2/3 + 5/8? A recipe says: use 2/3 of the 5/8 cup of butter you have left. How much butter do you use?","options":["5/12 cup","31/24 cup","7/11 cup","5/24 cup"],"answer":0,"explanation":"Of means multiply: 2/3 x 5/8 = 10/24 = 5/12 cup. Adding (31/24) answers a different question. Lesson 6."},
      {"prompt":"A $250 bike is discounted 20%, and then the sale price is discounted a further 15%. What do you pay?","options":["$162.50","$170.00","$165.00","$212.50"],"answer":1,"explanation":"20% off 250 leaves 200; 15% of 200 is 30, leaving $170. Adding the percents to get 35% off ($162.50) is the stacking error from Lesson 7."},
      {"prompt":"Trail mix uses nuts and raisins in the ratio 5:3. You want 2.4 kg of mix in total. How many kilograms of nuts do you need?","options":["1.2 kg","0.9 kg","1.5 kg","1.6 kg"],"answer":2,"explanation":"The ratio has 5 + 3 = 8 parts, so each part is 2.4 / 8 = 0.3 kg, and nuts take 5 parts: 1.5 kg. Lesson 8, plus a whole-into-parts twist."},
      {"prompt":"At dawn the temperature was -8 degrees; by noon it had risen 15 degrees, and by midnight it had fallen 11 degrees from the noon value. What was the midnight temperature?","options":["-4 degrees","4 degrees","-3 degrees","-11 degrees"],"answer":0,"explanation":"Dawn to noon: -8 + 15 = 7. Noon to midnight: 7 - 11 = -4 degrees. Track each move on the number line, as in Lesson 11."},
      {"prompt":"Water bottles hold 750 mL. A sports team needs at least 20 L of water for a tournament. What is the minimum number of bottles they must bring?","options":["26","27","28","25"],"answer":1,"explanation":"20 L = 20,000 mL, and 20,000 / 750 = 26 remainder 500 - so 26 bottles are not enough and they need 27. Units from Lesson 11, remainders from Lesson 4."},
      {"prompt":"A shop sells 6 muffins for $9.30 or 10 muffins for $15.00. You need exactly 30 muffins for a bake sale. How much do you save by choosing the cheaper pack for the whole order?","options":["$1.50","$0.50","$3.00","$2.10"],"answer":0,"explanation":"Unit prices: 9.30 / 6 = $1.55 versus 15.00 / 10 = $1.50 per muffin. Thirty muffins cost 5 x 9.30 = $46.50 one way and 3 x 15.00 = $45.00 the other - a $1.50 saving. Lesson 8 unit rates inside a multi-step problem."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0001-0000-4000-8000-000000000001' and l.position = v.pos
);
