-- Math foundations pack: Pre-Algebra (course 2 of the math track).
-- Builds the bridge from arithmetic to algebra with a diagnostic quiz,
-- template-driven reading lessons (objective + retrieval warm-up, hook,
-- worked examples, practice with answers, misconceptions + exit tickets),
-- two checkpoints, a vocabulary lesson, and a final assessment.
-- Prerequisite: Arithmetic Foundations. Fixed UUIDs and guarded inserts
-- make the file idempotent: safe to re-run at any time.

-- ============ Pre-Algebra ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, school, prerequisite_ids)
values (
  'bbbb0001-0000-4000-8000-000000000002',
  'en', null,
  'Pre-Algebra',
  'Cross the bridge from arithmetic to algebra: variables and expressions, equations, inequalities, proportions and percent, the coordinate plane, exponents, and a first look at statistics. Every lesson teaches through everyday money, travel, and game scenarios with fully worked examples and self-checks.',
  null, 'foundations', 2, true, 'math', '{bbbb0001-0000-4000-8000-000000000001}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0001-0000-4000-8000-000000000002', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"A gym charges $20 to join plus $8 per visit. Which expression gives the total cost in dollars for v visits?","options":["20v + 8","8v + 20","28v","20 − 8v"],"answer":1,"explanation":"The $8 fee repeats once per visit (8v) and the $20 is paid once. If this felt hard, start with Lesson 2: Variables & expressions."},
      {"prompt":"Solve for x: 3x + 5 = 20","options":["5","15","3","45"],"answer":0,"explanation":"Subtract 5 from both sides (3x = 15), then divide by 3. Covered in Lesson 3: Solving one- and two-step equations."},
      {"prompt":"Solve the inequality −2x < 6.","options":["x < −3","x > −3","x < 3","x > 3"],"answer":1,"explanation":"Dividing both sides by −2 flips the inequality sign: x > −3. Covered in Lesson 4: Inequalities on the number line."},
      {"prompt":"What is 30% of 250?","options":["25","83","75","750"],"answer":2,"explanation":"30% means 0.30, and 0.30 × 250 = 75. Covered in Lesson 6: Proportions & percent problems."},
      {"prompt":"In which quadrant does the point (−3, 2) lie?","options":["Quadrant I","Quadrant II","Quadrant III","Quadrant IV"],"answer":1,"explanation":"Negative x and positive y means left and up: Quadrant II. Covered in Lesson 7: The coordinate plane."},
      {"prompt":"Evaluate: 2 + 3 × 4²","options":["50","80","100","38"],"answer":0,"explanation":"Exponent first (4² = 16), then multiply (3 × 16 = 48), then add 2 to get 50. Covered in Lesson 8: Exponents & order of operations."},
      {"prompt":"In the expression 7x + 3, the number 7 is called the…","options":["exponent","constant","variable","coefficient"],"answer":3,"explanation":"A coefficient is the number multiplying a variable. Key terms like this are collected in Lesson 10: Key terms."},
      {"prompt":"What is the median of the data set 3, 7, 8, 12, 40?","options":["8","12","14","40"],"answer":0,"explanation":"With five ordered values the median is the third one: 8. The big value 40 pulls the mean up but not the median. Covered in Lesson 11: Intro statistics."}
   ]}',
   null, 10),
  (2, 'Variables & expressions', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will read, write, evaluate, and simplify algebraic expressions. First, a 60-second warm-up from Arithmetic Foundations — compute each one: (1) 6 × 9 + 4. (2) 45 ÷ 5 − 3. (3) What number added to 17 gives 25? Answers: 58, 6, and 8. If any of those felt shaky, review order of operations and fact families before continuing, because algebra is arithmetic with one number hidden."},
      {"heading":"From numbers to letters","text":"Your streaming service costs $9 per month plus $2 for each movie you rent. Some months you rent one movie, some months five — the bill changes, but the pattern does not. Algebra captures the pattern: let m stand for the number of movies, and the monthly bill is 9 + 2m. The letter m is a variable: a symbol that stands for a number that can change or is not yet known. The whole phrase 9 + 2m is an expression: numbers, variables, and operations combined, with no equals sign. Worked example: in a month where you rent 4 movies, substitute m = 4, giving 9 + 2 × 4 = 9 + 8 = 17, so the bill is $17. Substituting means replacing the letter with a number, then following the normal order of operations."},
      {"heading":"Worked examples","text":"Example 1 — evaluate 5x − 4 when x = 6. Substitute: 5 × 6 − 4. Multiply before subtracting: 30 − 4 = 26. Writing 5x means 5 times x; the multiplication sign is invisible but real. Example 2 — translate words into symbols: three more than twice a number. Twice a number is 2n; three more than that is 2n + 3. Order matters in translation: seven less than a number is n − 7, not 7 − n, because you start with the number and take 7 away. Example 3 — simplify 4a + 7 + 2a − 3. Like terms have the exact same variable part, so 4a and 2a combine to 6a, and the plain numbers 7 and −3 combine to 4. Result: 6a + 4. The number multiplying a variable (the 6 in 6a) is called its coefficient."},
      {"heading":"Your turn","text":"Solve, then check the answers. (1) Evaluate 3x + 8 when x = 5. Answer: 23, because 15 + 8 = 23. (2) Evaluate 2(n + 3) when n = 7. Answer: 20, because parentheses first gives 2 × 10. (3) A fair charges $15 to enter plus $4 per ride; write the cost for r rides. Answer: 15 + 4r, since only the ride fee repeats. (4) Simplify 9y − 2y + 5. Answer: 7y + 5, combining only the y-terms. (5) Translate: seven less than a number. Answer: n − 7, because the 7 is removed from the number. (6) What is the coefficient of x in x + 12? Answer: 1, since x means 1x."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: reading 2x as a two-digit number. If x = 5, then 2x is 2 × 5 = 10, never 25 — a coefficient always multiplies. Misconception 2: combining unlike terms, as in 3a + 2b = 5ab. Wrong: 3a and 2b count different things, like 3 apples and 2 bananas, so 3a + 2b is already as simple as it gets. Exit ticket — answer before moving on: (1) Evaluate 4t + 1 when t = 3. Answer: 13. (2) Simplify 5x + 2 + x. Answer: 6x + 2."}
   ]}',
   'Study tip: whenever you substitute a value, write the multiplication sign back in (5x becomes 5 × 6) — it prevents nearly every substitution error.', 12),
  (3, 'Solving one- and two-step equations', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will solve one- and two-step equations and verify your solutions. Warm-up from Lesson 2: (1) Evaluate 2x + 3 when x = 4. (2) Simplify 3n + n. Answers: 11 and 4n. Evaluating expressions is the skill you will now run in reverse: instead of plugging a number in, you will hunt for the number that makes an equation true."},
      {"heading":"The balance idea","text":"You are saving for a $150 game console. You already have $30 and you save $20 every week. When will you get there? The situation is the equation 30 + 20w = 150, where w is the number of weeks. An equation says two amounts are equal — picture an old-fashioned balance scale with 30 + 20w on one pan and 150 on the other. The golden rule: whatever you do to one side, do to the other, or the scale tips and the equality is destroyed. To find a hidden number, undo the operations around it using inverse operations: subtraction undoes addition, division undoes multiplication. Worked example: x + 12 = 30. The x has 12 added to it, so subtract 12 from both sides: x = 18. Check by substituting back: 18 + 12 = 30. True, so x = 18 is the solution."},
      {"heading":"Worked examples","text":"Example 1 — one step: 4x = 52. The x is multiplied by 4, so divide both sides by 4: x = 13. Check: 4 × 13 = 52. Example 2 — two steps: 2x − 7 = 19. Undo operations in reverse order of operations: the subtraction is outermost, so first add 7 to both sides (2x = 26), then divide by 2 (x = 13). Check: 2 × 13 − 7 = 19. Example 3 — the console: 30 + 20w = 150. Subtract 30 from both sides: 20w = 120. Divide by 20: w = 6. Six weeks of saving. Notice the rhythm in every two-step equation: clear the added or subtracted number first, then clear the coefficient."},
      {"heading":"Your turn","text":"Solve each equation, then check the answers. (1) x − 9 = 14. Answer: x = 23, by adding 9 to both sides. (2) 6x = 42. Answer: x = 7, by dividing both sides by 6. (3) 3x + 4 = 25. Answer: x = 7, subtract 4 then divide by 3. (4) x/2 − 5 = 1. Answer: x = 12, add 5 then multiply by 2. (5) 8 = 2x − 6. Answer: x = 7, add 6 to both sides then divide by 2 — the variable being on the right changes nothing. (6) A taxi charges $3 plus $2 per mile, and the ride costs $15; how many miles? Answer: 6 miles, from 3 + 2m = 15."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: operating on only one side, as in turning x + 5 = 12 into x = 12 by just deleting the 5. The 5 must be subtracted from both sides, giving x = 7. Misconception 2: undoing in the wrong order. In 2x + 6 = 10, students who divide only the 2x by 2 get x + 6 = 5, which is false; either subtract 6 first (the reliable path), or divide every single term by 2. Exit ticket: (1) Solve 5x − 3 = 22. Answer: x = 5. (2) Is x = 4 a solution of 3x + 1 = 13? Answer: yes, because 12 + 1 = 13."}
   ]}',
   'Study tip: checking a solution takes ten seconds and catches almost every mistake — substitute your answer back in before calling an equation done.', 13),
  (4, 'Inequalities on the number line', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will solve inequalities and graph their solutions on a number line. Warm-up from Lesson 3 — solve both: (1) 2x + 1 = 9. (2) x − 6 = −2. Answers: x = 4 and x = 4. Good news: solving an inequality uses the exact same moves as solving an equation, with one dramatic twist you will meet below."},
      {"heading":"When the answer is a range","text":"A freight elevator has a sign: maximum load 1000 kg. You need to load a 120 kg pallet plus boxes weighing 80 kg each. How many boxes are safe? The condition is 80b + 120 ≤ 1000 — not an equation, because any sufficiently small number of boxes is fine. The four symbols: < less than, > greater than, ≤ less than or equal to, ≥ greater than or equal to. An inequality has a whole range of solutions, so we picture them on a number line: a closed (filled) circle when the boundary number counts (≤ or ≥), an open circle when it does not (< or >), with shading toward every solution. Worked example: x + 3 ≤ 7. Subtract 3 from both sides: x ≤ 4. Graph: closed circle at 4, shading left, because 4 works and so does everything below it."},
      {"heading":"Worked examples","text":"Example 1 — 2x − 1 > 9. Add 1 to both sides (2x > 10), divide by 2 (x > 5). Graph with an open circle at 5, shaded right; 5 itself is not a solution because 2 × 5 − 1 = 9 is not greater than 9. Example 2 — the twist: −3x ≥ 12. Dividing both sides by −3 gives x ≤ −4, with the symbol flipped. Why? Multiplying or dividing by a negative mirrors the number line: 2 < 5 is true, but multiply both by −1 and −2 > −5. Test the answer: x = −5 gives −3 × −5 = 15 ≥ 12, true. Example 3 — the elevator: 80b + 120 ≤ 1000. Subtract 120 (80b ≤ 880), divide by 80 (b ≤ 11). Eleven boxes at most, and since b counts boxes, the solutions in context are 0 through 11."},
      {"heading":"Your turn","text":"Solve each inequality; answers follow. (1) x − 5 > 2. Answer: x > 7, add 5 to both sides. (2) 4x ≤ 20. Answer: x ≤ 5, divide by positive 4, no flip. (3) 3x + 2 < 11. Answer: x < 3, subtract 2 then divide by 3. (4) −2x < 10. Answer: x > −5, dividing by −2 flips the symbol. (5) Is 4 a solution of 2x + 1 ≥ 9? Answer: yes, because 9 ≥ 9 is true when the symbol allows equality. (6) You have $50; a game costs $18 and arcade tokens are $8 each. How many tokens can you buy? Answer: at most 4, from 18 + 8t ≤ 50, so t ≤ 4."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: flipping the symbol whenever a negative number appears anywhere. Only multiplying or dividing both sides by a negative flips it: x − 3 > 1 becomes x > 4 with no flip, because you added 3. Misconception 2: mixing up circle types. x > 2 excludes 2 (open circle); x ≥ 2 includes it (closed circle) — the difference decides whether a boundary case like exactly 1000 kg is allowed. Exit ticket: (1) Solve −x ≤ 3. Answer: x ≥ −3, flip when multiplying by −1. (2) Describe the graph of x < 1. Answer: open circle at 1, shaded to the left."}
   ]}',
   'Study tip: after solving any inequality, test one easy number from your answer range in the original — it instantly reveals a missed sign flip.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"Simplify: 4x + 7 − x + 2","options":["3x + 9","4x + 9","3x + 5","5x + 9"],"answer":0,"explanation":"Combine like terms: 4x − x = 3x and 7 + 2 = 9. Unlike terms never merge."},
      {"prompt":"Evaluate 3(n − 2) when n = 6.","options":["16","10","12","18"],"answer":2,"explanation":"Parentheses first: n − 2 = 4, then 3 × 4 = 12."},
      {"prompt":"Solve: x/4 = 9","options":["2.25","36","13","5"],"answer":1,"explanation":"Multiply both sides by 4: x = 36. Division is undone by multiplication."},
      {"prompt":"Solve: 2x + 5 = 17","options":["11","6","5","24"],"answer":1,"explanation":"Subtract 5 (2x = 12), then divide by 2: x = 6."},
      {"prompt":"Which value is a solution of x + 5 < 9?","options":["4","6","3","5"],"answer":2,"explanation":"The inequality simplifies to x < 4, and only 3 is below 4. Note that 4 itself fails because the symbol is strict."},
      {"prompt":"Solve: −5x < 20","options":["x < −4","x > −4","x < 4","x > 4"],"answer":1,"explanation":"Divide both sides by −5 and flip the symbol: x > −4."},
      {"prompt":"A number line shows a closed circle at 2 with shading to the right. Which inequality is it?","options":["x > 2","x < 2","x ≥ 2","x ≤ 2"],"answer":2,"explanation":"Closed circle means 2 is included (≥ or ≤); shading right means greater: x ≥ 2."}
   ]}',
   null, 9),
  (6, 'Proportions & percent problems', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will set up and solve proportions and handle the three classic percent problems. Warm-up from Lesson 3 — solve: (1) 4x = 36. (2) 5x = 30. Answers: x = 9 and x = 6. Keep that skill warm: cross-multiplying a proportion always produces exactly this kind of equation."},
      {"heading":"Ratios that must match","text":"A recipe that feeds 4 people uses 3 cups of flour. You are cooking for 10. A ratio compares two quantities (3 cups per 4 people); a proportion is an equation saying two ratios are equal: 3/4 = f/10, where f is the flour you need. The cross-products rule says the diagonal products of a true proportion match, so 4 × f = 3 × 10, giving 4f = 30 and f = 7.5 cups. Percent is a special ratio: per cent means per hundred, so 30% = 30/100 = 0.30. Worked example: a $40 board game is marked 25% off. The discount is 0.25 × 40 = $10, so you pay $30."},
      {"heading":"Worked examples","text":"Example 1 — unit rates for smart shopping: 5 kg of rice for $12.00 versus 3 kg for $7.80. Divide price by amount: $2.40 per kg versus $2.60 per kg, so the 5 kg bag wins. A unit rate is a ratio scaled down to 1. Example 2 — percent of a number: a $42 dinner with a 15% tip. Tip = 0.15 × 42 = $6.30, total $48.30. Quick mental path: 10% is 4.20, half of that is 2.10, together 6.30. Example 3 — finding the whole: a jacket on sale for $18 is 30% of its original price during a clearance event; what was the original? Let w be the whole: 0.30 × w = 18, so w = 18 ÷ 0.30 = 60 dollars. The three percent problems only differ in which of part, percent, and whole is hidden."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Solve 2/5 = x/20. Answer: x = 8, since cross products give 5x = 40. (2) Find 25% of 84. Answer: 21, because 0.25 × 84 = 21, or a quarter of 84. (3) A map scale says 2 cm = 5 km; how far is 7 cm? Answer: 17.5 km, from 2/5 = 7/d. (4) 12 is 40% of what number? Answer: 30, from 0.40w = 12. (5) $60 jeans are 35% off; what do you pay? Answer: $39, since the discount is $21. (6) If 3 pens cost $2.40, what do 7 pens cost? Answer: $5.60, using the unit rate of $0.80 per pen."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: multiplying by the raw percent number. 20% of 50 is 0.20 × 50 = 10, not 20 × 50 = 1000 — convert to a decimal or fraction first. Misconception 2: assuming percent changes cancel. A 50% drop followed by a 50% rise does not restore the price: $100 falls to $50, then rises 50% of 50 to $75, because each percent acts on a new whole. Exit ticket: (1) 10% of 250? Answer: 25. (2) Solve 3/4 = 9/x. Answer: x = 12."}
   ]}',
   'Study tip: before computing any percent, say out loud what the whole is — most percent errors are really wrong-whole errors.', 14),
  (7, 'The coordinate plane', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will plot points, name quadrants, and read simple graphs on the coordinate plane. Warm-up from Lesson 2 — evaluate y = 2x + 1 at x = 3, and from Lesson 4 — solve x + 2 ≤ 6. Answers: y = 7, and x ≤ 4. Tables of x and y values are exactly what you are about to turn into pictures."},
      {"heading":"Two numbers, one location","text":"In a strategy game, telling a teammate the treasure is over there is useless; telling them sector (3, −2) wins the round. The coordinate plane is two number lines crossed at right angles: the horizontal x-axis and the vertical y-axis, meeting at the origin (0, 0). Every point gets an ordered pair (x, y): the x-coordinate says how far right (positive) or left (negative), the y-coordinate says how far up or down. Order is everything, and x comes first — alphabetical, like the axes. Worked example: to plot (3, −2), start at the origin, move 3 right, then 2 down. That lands in Quadrant IV, the lower-right of the four regions the axes create."},
      {"heading":"Worked examples","text":"Example 1 — quadrants by signs, counted counterclockwise from the upper right: Quadrant I is (+, +), II is (−, +), III is (−, −), IV is (+, −). So (−4, 5) is left and up: Quadrant II. Example 2 — points on the axes: (0, 3) has no left-right movement, so it sits on the y-axis; (5, 0) sits on the x-axis; axis points belong to no quadrant. Example 3 — distance along a grid line: from (−2, 4) to (6, 4), the y-coordinates match, so the points sit on the same horizontal line, and the distance is the gap in x-values: 6 − (−2) = 8 units. This is how you find side lengths of shapes drawn on the plane."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Which quadrant holds (−3, −7)? Answer: Quadrant III, both coordinates negative. (2) Starting at the origin you move 4 left and 2 up; name the point. Answer: (−4, 2). (3) Find the distance from (1, 5) to (1, −3). Answer: 8 units, same x, so subtract y-values: 5 − (−3). (4) Does (2, 7) lie on the line y = 3x + 1? Answer: yes, because 3 × 2 + 1 = 7. (5) Three corners of a rectangle are (0, 0), (6, 0), and (6, 4); find the fourth. Answer: (0, 4), directly above (0, 0) and level with (6, 4). (6) Which axis contains (0, −9)? Answer: the y-axis, since x = 0."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: treating (3, 5) and (5, 3) as the same point. They are different locations — the first coordinate is always the horizontal move. Misconception 2: assigning axis points to a quadrant. A point like (5, 0) is on the boundary between quadrants, so it belongs to none. Exit ticket: (1) What are the coordinates of the origin? Answer: (0, 0). (2) Which quadrant holds (7, −1)? Answer: Quadrant IV."}
   ]}',
   'Study tip: whisper right-then-up (or left-then-down) every time you plot — locking in the x-first habit now prevents graphing errors for years.', 12),
  (8, 'Exponents & order of operations', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will evaluate expressions with exponents and apply the full order of operations without traps. Warm-up from Lesson 2 — (1) evaluate 3x − 4 when x = 5; (2) simplify 2n + 3n. Answers: 11 and 5n. From Lesson 7, recall that checking whether a point fits an equation also required careful operation order."},
      {"heading":"Repeated multiplication, compressed","text":"A rumor starts with one person who tells 3 friends; each of them tells 3 more, and so on. After 4 rounds the newest group has 3 × 3 × 3 × 3 = 81 people. Exponents compress that: 3⁴, read three to the fourth power, where 3 is the base and 4 is the exponent counting how many copies of the base are multiplied. The order of operations ranks every calculation: parentheses (grouping) first, then exponents, then multiplication and division together from left to right, then addition and subtraction together from left to right. Worked example: 2 + 3 × 4². Exponent first: 4² = 16. Multiply: 3 × 16 = 48. Add: 50. Working left to right blindly gives 80 — wrong, because addition must wait."},
      {"heading":"Worked examples","text":"Example 1 — the left-to-right rule: 24 ÷ 4 × 2. Division and multiplication have equal rank, so go left to right: 24 ÷ 4 = 6, then 6 × 2 = 12. Doing the multiplication first gives 3, which is wrong. Example 2 — grouping changes everything: (2 + 3)² = 5² = 25, but 2² + 3² = 4 + 9 = 13. Squaring a sum is not the same as summing the squares. Example 3 — a full expression: 5 × 2³ − (7 − 3). Parentheses: 7 − 3 = 4. Exponent: 2³ = 8. Multiply: 5 × 8 = 40. Subtract: 40 − 4 = 36. One clean pass through the ranking, one correct answer."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) 6². Answer: 36, six times six. (2) 4 + 2 × 3². Answer: 22, since 3² = 9 and 2 × 9 = 18. (3) (10 − 4)² ÷ 9. Answer: 4, because 6² = 36 and 36 ÷ 9 = 4. (4) 36 ÷ 6 ÷ 2. Answer: 3, dividing left to right: 6 then 3. (5) 2³ + 3 × 5. Answer: 23, from 8 + 15. (6) 100 − 4 × 5². Answer: 0, since 4 × 25 = 100."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: multiplying base by exponent, as in 3² = 6. An exponent counts factors, not a multiplication by itself: 3² = 3 × 3 = 9. Misconception 2: believing multiplication always beats division (a too-literal reading of PEMDAS). They are the same rank, resolved left to right: 12 ÷ 2 × 3 = 18, not 2. Exit ticket: (1) 5 + 10 ÷ 5. Answer: 7. (2) 2 × 3². Answer: 18, exponent before multiplication."}
   ]}',
   'Study tip: rewrite PEMDAS as four lines — P, E, MD, AS — so the equal-rank pairs are visible before the next quiz exploits them.', 13),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"Solve the proportion: 2/5 = x/30","options":["12","15","10","6"],"answer":0,"explanation":"Cross products: 5x = 60, so x = 12."},
      {"prompt":"45 is what percent of 180?","options":["40%","25%","45%","20%"],"answer":1,"explanation":"45 ÷ 180 = 0.25 = 25%. The whole is 180, the part is 45."},
      {"prompt":"A $60 shirt is 30% off. What do you pay?","options":["$18","$30","$42","$48"],"answer":2,"explanation":"The discount is 0.30 × 60 = $18, leaving $42."},
      {"prompt":"Where does the point (0, −5) lie?","options":["Quadrant IV","the x-axis","the y-axis","Quadrant III"],"answer":2,"explanation":"An x-coordinate of 0 means no horizontal movement, so the point sits on the y-axis and belongs to no quadrant."},
      {"prompt":"Which point lies on the line y = 2x − 3?","options":["(4, 5)","(5, 4)","(2, 7)","(3, 9)"],"answer":0,"explanation":"Test each pair: 2 × 4 − 3 = 5, so (4, 5) fits. The others fail the substitution check."},
      {"prompt":"Evaluate: 6 + 4 × 3² ÷ 2","options":["45","24","51","21"],"answer":1,"explanation":"Exponent first (9), then multiply and divide left to right (4 × 9 = 36, 36 ÷ 2 = 18), then add 6 for 24."},
      {"prompt":"What is (−3)²?","options":["−9","9","−6","6"],"answer":1,"explanation":"The parentheses square the whole number: (−3) × (−3) = 9. A negative times a negative is positive."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"variable","translation":"a letter that stands for a number that is unknown or can change","example":"In the expression 3x + 5, the variable is x — it could be your number of taxi miles or movie rentals."},
      {"term":"coefficient","translation":"the number that multiplies a variable","example":"In 7y the coefficient is 7; in plain y the coefficient is an invisible 1."},
      {"term":"inequality","translation":"a statement comparing two amounts with <, >, ≤, or ≥ instead of an equals sign","example":"The elevator limit 80b + 120 ≤ 1000 is an inequality whose solutions form a whole range, not a single number."},
      {"term":"origin","translation":"the point (0, 0) where the x-axis and y-axis cross on the coordinate plane","example":"Every plotting journey starts at the origin: move right or left first, then up or down."},
      {"term":"exponent","translation":"a raised number that tells how many copies of the base to multiply together","example":"In 2⁵ the exponent is 5, so 2⁵ = 2 × 2 × 2 × 2 × 2 = 32."},
      {"term":"proportion","translation":"an equation stating that two ratios are equal","example":"The recipe proportion 3/4 = f/10 scales 3 cups of flour for 4 people up to 10 people."}
   ]}',
   null, 8),
  (11, 'Intro statistics: mean, median, spread, misleading graphs', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will compute mean, median, and range, choose the honest measure of center, and spot a misleading graph. Warm-up from Lesson 6: (1) What is 20% of 45? (2) 12 is 50% of what number? Answers: 9 and 24. Percents and statistics travel together in every news headline you will fact-check with this lesson."},
      {"heading":"One number for a whole season","text":"Two friends argue about who had the better basketball season, waving whole score sheets at each other. Statistics settles it by compressing many numbers into one. The mean (average) is the total divided by the count. Worked example: game scores 8, 10, 12, 6, 14 have total 50 across 5 games, so the mean is 50 ÷ 5 = 10 points per game. The mean is the fair-share number: if every game had gone identically, each would have scored 10."},
      {"heading":"Worked examples","text":"Example 1 — the median is the middle of the sorted data. For 3, 7, 8, 12, 40 the middle of five values is 8. With an even count, average the two middle values: for 4, 6, 10, 12 the median is (6 + 10) ÷ 2 = 8. Always sort first. Example 2 — outliers and honesty: five salaries in thousands are 30, 32, 34, 36, 200. The mean is 332 ÷ 5 = 66.4, but the median is 34. The single outlier of 200 drags the mean far above what a typical worker earns, so the median describes this group more honestly; range = maximum − minimum = 170 warns you the data are widely spread. Example 3 — misleading graphs: a bar chart compares sales of 50 and 52 units, but its vertical axis starts at 48, so the second bar looks twice as tall. The numbers are true; the picture lies. Check where the axis starts before trusting any bar chart."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Mean of 4, 9, 11. Answer: 8, from 24 ÷ 3. (2) Median of 2, 5, 7, 10, 100. Answer: 7, the middle of five sorted values; the 100 does not move it. (3) Range of 15, 22, 8, 30. Answer: 22, from 30 − 8. (4) For house prices 1, 2, 2, 3, 42 (in hundred thousands), which center is more honest? Answer: the median (2), because the 42 outlier inflates the mean to 10. (5) A chart shows bars for 100 and 104 with the axis starting at 98, making one look four times taller; what is the fix? Answer: start the axis at 0 (or clearly mark the break). (6) The data 4, 9, 11 gain a new value of 20; what is the new mean? Answer: 11, from 44 ÷ 4."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: taking the median without sorting. The median of 9, 3, 7 is 7 (sorted: 3, 7, 9), not 3 just because 3 sits in the middle as written. Misconception 2: assuming accurate numbers make an honest graph. Truncated axes, stretched scales, and 3-D bars can all mislead while every printed value stays true. Exit ticket: (1) Median of 5, 1, 9. Answer: 5. (2) Mean of 10 and 16. Answer: 13."}
   ]}',
   'Study tip: when a headline quotes an average, ask which one — mean or median — and whether an outlier could be doing the talking.', 14),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"Solve: 5 − 2x = 17","options":["−6","6","−11","11"],"answer":0,"explanation":"Subtract 5 from both sides (−2x = 12), then divide by −2: x = −6. Check: 5 − 2 × (−6) = 17."},
      {"prompt":"Solve: −4x + 3 ≤ 15","options":["x ≤ −3","x ≥ −3","x ≤ 3","x ≥ 3"],"answer":1,"explanation":"Subtract 3 (−4x ≤ 12), then divide by −4 and flip: x ≥ −3."},
      {"prompt":"An $80 jacket is discounted 25%, then the sale price is raised 10%. Final price?","options":["$66","$68","$88","$60"],"answer":0,"explanation":"25% off gives $60; a 10% rise on the new whole adds $6, giving $66. Percent changes never simply cancel."},
      {"prompt":"Three vertices of a rectangle are (1, 2), (5, 2), and (5, 7). Where is the fourth?","options":["(7, 1)","(2, 5)","(1, 7)","(5, 1)"],"answer":2,"explanation":"The fourth corner shares x = 1 with (1, 2) and y = 7 with (5, 7), so it is (1, 7)."},
      {"prompt":"Evaluate: 2³ + 3 × (10 − 4) ÷ 2","options":["17","33","21","15"],"answer":0,"explanation":"Parentheses (6), exponent (8), then multiply and divide left to right (3 × 6 = 18, 18 ÷ 2 = 9), then add: 8 + 9 = 17."},
      {"prompt":"Apples cost $7.50 for 3 kg. At the same rate, what do 8 kg cost?","options":["$18.00","$20.00","$22.50","$24.00"],"answer":1,"explanation":"The unit rate is $2.50 per kg, so 8 kg cost $20.00. As a proportion: 7.5/3 = c/8."},
      {"prompt":"Your first three test scores are 78, 85, and 91. What must the fourth score be for a mean of exactly 85?","options":["85","90","81","86"],"answer":3,"explanation":"A mean of 85 over 4 tests needs a total of 340; you have 254, so you need 340 − 254 = 86."},
      {"prompt":"A phone plan costs $25 per month plus $0.10 for each text over 100. For t texts in a month (with t > 100), which expression gives the bill?","options":["25 + 0.10t","25 + 0.10(t − 100)","25.10t − 100","(25 + 0.10)t"],"answer":1,"explanation":"Only the texts beyond 100 are billed, so the per-text charge applies to (t − 100), added to the flat $25."}
   ]}',
   null, 10)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0001-0000-4000-8000-000000000002' and l.position = v.pos
);
