-- Math foundations pack: Geometry (course 4 of the math track).
-- Develops geometric reasoning from proof basics through angles and lines,
-- triangle congruence and similarity, right triangles with the Pythagorean
-- theorem and introductory trigonometry, circles and measurement, and
-- coordinate geometry with transformations. Template-driven reading lessons
-- (objective + retrieval warm-up, hook, worked examples, practice with
-- answers, misconceptions + exit tickets), two checkpoints, a vocabulary
-- lesson, and a final assessment. Prerequisite: Pre-Algebra. Fixed UUIDs and
-- guarded inserts make the file idempotent: safe to re-run at any time.

-- ============ Geometry ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0001-0000-4000-8000-000000000004',
  'en', null,
  'Geometry',
  'Learn to think like a geometer: reasoning and proof, angles and parallel lines, triangle congruence and similarity, right triangles with the Pythagorean theorem and a first taste of trigonometry, circles, area and volume, and coordinate geometry with transformations. Every lesson teaches through buildings, maps, games, and gadgets with fully worked examples and self-checks. Structure informed by the CK-12 Geometry FlexBook (CC BY-NC).',
  null, 'foundations', 4, true, 'math', '{bbbb0001-0000-4000-8000-000000000002}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0001-0000-4000-8000-000000000004', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"Given: if a shape is a square, then it has four equal sides. The tile on your desk is a square. What can you logically conclude?","options":["It has four equal sides","It must be a rectangle too","Nothing can be concluded","Its sides are longer than 1 cm"],"answer":0,"explanation":"Deductive reasoning applies a general rule to a specific case: square, therefore four equal sides. If this felt hard, start with Lesson 2: Reasoning, proof & the building blocks."},
      {"prompt":"Two parallel lines are cut by a transversal. One angle measures 65 degrees. What is the measure of its alternate interior partner?","options":["65 degrees","115 degrees","25 degrees","130 degrees"],"answer":0,"explanation":"Alternate interior angles between parallel lines are congruent, so the partner is also 65 degrees. Covered in Lesson 3: Angles, parallel lines & triangles."},
      {"prompt":"Two angles of a triangle measure 48 and 71 degrees. The third angle measures…","options":["59 degrees","61 degrees","69 degrees","71 degrees"],"answer":1,"explanation":"Triangle angles sum to 180: 180 − 48 − 71 = 61. Covered in Lesson 3: Angles, parallel lines & triangles."},
      {"prompt":"Two triangles have two pairs of equal sides, and the angles between those sides are also equal. Which shortcut proves the triangles congruent?","options":["SSS","SAS","ASA","AAS"],"answer":1,"explanation":"Two sides and the included angle is exactly the Side-Angle-Side (SAS) shortcut. Covered in Lesson 4: Triangle congruence."},
      {"prompt":"A triangle with sides 3, 4, and 5 is similar to a larger triangle whose shortest side is 9. What is the longest side of the larger triangle?","options":["12","15","18","20"],"answer":1,"explanation":"The scale factor is 9 ÷ 3 = 3, so the longest side is 5 × 3 = 15. Covered in Lesson 6: Similarity & scale."},
      {"prompt":"A right triangle has legs 6 and 8. How long is the hypotenuse?","options":["10","14","48","sqrt(28)"],"answer":0,"explanation":"By the Pythagorean theorem, 6^2 + 8^2 = 36 + 64 = 100, and sqrt(100) = 10. Covered in Lesson 7: Right triangles & the Pythagorean theorem."},
      {"prompt":"A circular table has a radius of 5 ft. Using pi ≈ 3.14, its area is about…","options":["31.4 sq ft","78.5 sq ft","15.7 sq ft","157 sq ft"],"answer":1,"explanation":"Area = pi × r^2 = 3.14 × 25 ≈ 78.5 square feet; 31.4 is the circumference. Covered in Lesson 8: Circles, area & volume."},
      {"prompt":"The point (3, −2) is reflected across the x-axis. Where does it land?","options":["(−3, −2)","(3, 2)","(−3, 2)","(2, −3)"],"answer":1,"explanation":"Reflecting across the x-axis keeps x and flips the sign of y: (3, −2) becomes (3, 2). Covered in Lesson 11: Coordinate geometry & transformations."}
   ]}',
   null, 10),
  (2, 'Reasoning, proof & the building blocks', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will name the basic objects of geometry, tell inductive from deductive reasoning, and read and test if-then statements. First, a 60-second warm-up from Pre-Algebra — geometry constantly borrows these moves: (1) Solve 2x + 10 = 34. (2) Evaluate x^2 when x = 5. (3) Solve x + 40 = 90. Answers: x = 12, 25, and x = 50. If any felt shaky, review equation solving first, because most angle problems end as small equations."},
      {"heading":"Geometry is a game with rules","text":"Every game needs pieces and rules. The pieces of geometry are almost too simple to define: a point is a location with no size, a line extends forever in two directions, and a plane is a flat surface extending forever. From these come a segment (a piece of a line with two endpoints), a ray (one endpoint, one direction), and an angle (two rays sharing an endpoint called the vertex, measured in degrees). The rules come from reasoning. Inductive reasoning spots a pattern and predicts: the sun rose every day so far, so it will rise tomorrow. Deductive reasoning applies an accepted rule to a case and is airtight. Rules usually wear if-then clothing: in the conditional statement — if an angle measures 90 degrees, then it is a right angle — the if-part is the hypothesis and the then-part is the conclusion. Worked example: rule — if a shape is a square, then it has four equal sides; fact — this tile is a square; deduction — this tile has four equal sides. No measuring needed; the logic alone forces it."},
      {"heading":"Worked examples","text":"Example 1 — inductive reasoning and its limits: the sequence 3, 6, 12, 24 doubles each time, so you predict 48 next. Reasonable — but a prediction, not a proof. Patterns can break, which is why geometry demands deduction for its theorems. Example 2 — the converse trap: swapping hypothesis and conclusion makes the converse, and truth does not automatically survive the swap. True: if a figure is a square, then it is a rectangle. Converse: if a figure is a rectangle, then it is a square — false, and a single counterexample kills it: a 3 by 5 rectangle. Example 3 — a mini two-column proof, the formal way to write deduction. Claim: if 2x − 5 = 11, then x = 8. Statement 1: 2x − 5 = 11 (given). Statement 2: 2x = 16 (addition property of equality: add 5 to both sides). Statement 3: x = 8 (division property of equality: divide both sides by 2). Every line has a reason — that is all a proof is."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Name the vertex of the angle formed by rays BA and BC. Answer: B, the shared endpoint. (2) The sequence 5, 10, 15, 20 continues with what number, and by which kind of reasoning? Answer: 25, by inductive reasoning — a pattern prediction. (3) In the statement — if two angles are vertical, then they are congruent — what is the hypothesis? Answer: two angles are vertical (the if-part). (4) Write the converse of: if it is raining, then the street is wet. Answer: if the street is wet, then it is raining — and it may be false (a burst pipe also wets streets). (5) Find a counterexample to: all rectangles are squares. Answer: any rectangle with unequal sides, such as 2 by 7. (6) Point M sits on segment AC between A and C with AM = 4 and MC = 9; find AC. Answer: 13, because the parts of a segment add to the whole (segment addition)."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: believing a statement and its converse must match in truth. If a figure is a square, then it is a rectangle is true while its converse is false — always test the swapped version separately. Misconception 2: proving by example. Checking that the rule works for three triangles proves nothing about all triangles; examples can only disprove (one counterexample) — never prove. Exit ticket: (1) Which kind of reasoning is airtight when its rule and fact are true — inductive or deductive? Answer: deductive. (2) State the conclusion of: if a shape has three sides, then it is a triangle. Answer: it is a triangle."}
   ]}',
   'Study tip: whenever you meet an if-then statement, immediately say its converse out loud and hunt for a counterexample — it builds the skepticism proofs are made of.', 12),
  (3, 'Angles, parallel lines & triangles', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will name angle pairs, use parallel-line angle rules, and apply the triangle angle sum. Warm-up from Lesson 2: (1) In the statement — if two angles form a line, then they add to 180 degrees — name the conclusion. (2) Solve 2x + 30 = 180. Answers: they add to 180 degrees, and x = 75. That equation shape appears in nearly every angle puzzle below."},
      {"heading":"Angles hiding in the crosswalk","text":"Stand at an intersection where a road crosses two parallel avenues: the crossing road is a transversal, and it manufactures angles with strict relationships. First the basic pairs anywhere: complementary angles add to 90 degrees, supplementary angles add to 180 degrees, and vertical angles — the opposite pair formed by two crossing lines — are always congruent. When the two lines being crossed are parallel, more rules switch on: corresponding angles (same corner position at each intersection) are congruent, alternate interior angles (opposite sides of the transversal, between the parallels) are congruent, and same-side interior angles are supplementary. Worked example: the transversal makes a 62 degree angle with the first avenue. Its vertical partner is 62, its neighbor on the line is 180 − 62 = 118, and at the second avenue the corresponding angle is again 62. One measurement unlocks all eight angles."},
      {"heading":"Worked examples","text":"Example 1 — vertical angles with algebra: two crossing lines form angles of 3x degrees and 96 degrees opposite each other. Vertical angles are congruent, so 3x = 96 and x = 32. Example 2 — same-side interior: two parallel fences are crossed by a path; one interior angle on the right of the path is 70 degrees. The other interior angle on that same side is 180 − 70 = 110 degrees, because same-side interior angles are supplementary. Example 3 — the triangle angle sum: the three angles of any triangle add to exactly 180 degrees. A triangle has angles 2x, 3x, and 4x. Then 2x + 3x + 4x = 180, so 9x = 180 and x = 20, giving angles of 40, 60, and 80 degrees. A bonus rule rides along: an exterior angle of a triangle (formed by extending one side) equals the sum of the two remote interior angles — here the exterior angle next to the 80 equals 40 + 60 = 100."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Two angles are complementary and one measures 34 degrees; find the other. Answer: 56 degrees, since they total 90. (2) An angle measures 125 degrees; find its supplement. Answer: 55 degrees. (3) Two parallel lines are cut by a transversal and one angle is 100 degrees; find its alternate interior partner. Answer: 100 degrees — alternate interior angles are congruent. (4) A right triangle has an acute angle of 37 degrees; find the other acute angle. Answer: 53 degrees, because 90 + 37 + x = 180. (5) Two crossing lines make an angle of 5x degrees vertical to a 75 degree angle; find x. Answer: x = 15. (6) An exterior angle of a triangle is 130 degrees and one remote interior angle is 55; find the other remote interior angle. Answer: 75 degrees, since 55 + x = 130."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: applying parallel-line rules to lines that merely look parallel in a sketch. Corresponding and alternate interior rules require parallel lines — the problem must say so or mark it. Misconception 2: swapping complementary and supplementary. Anchor them alphabetically and numerically together: c comes before s, and 90 comes before 180. Exit ticket: (1) Two parallel lines are cut by a transversal; one angle is 82 degrees — find its corresponding angle. Answer: 82 degrees. (2) Two angles of a triangle are 65 and 65; find the third. Answer: 50 degrees."}
   ]}',
   'Study tip: in any parallel-line figure, write the one given angle in every position it forces before reading the question — the answer is usually already on the page.', 13),
  (4, 'Triangle congruence', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will decide when two triangles are congruent using the SSS, SAS, ASA, and AAS shortcuts, and use CPCTC to squeeze extra facts out of a congruence. Warm-up from Lesson 3: (1) Two angles of a triangle are 40 and 60 degrees; find the third. (2) Two lines cross and one angle is 118 degrees; find its vertical angle. Answers: 80 degrees and 118 degrees. Vertical angles will quietly star in a proof below."},
      {"heading":"Identical parts, guaranteed","text":"A bicycle factory stamps out thousands of triangular frame plates, and every plate must fit every bike. Two figures are congruent when they have exactly the same size and shape — one can be slid, flipped, or turned to land perfectly on the other. For triangles, checking all six parts (three sides, three angles) is wasteful; a few well-chosen parts force all the rest. The shortcuts: SSS (three pairs of equal sides), SAS (two sides and the angle between them), ASA (two angles and the side between them), and AAS (two angles and a non-included side). For right triangles only, HL (hypotenuse and one leg) also works. Worked example: quality control measures two plates and finds sides of 30 cm and 45 cm with a 40 degree angle between them on each plate. That is two sides and the included angle — SAS — so the plates are congruent, and every other side and angle matches automatically."},
      {"heading":"Worked examples","text":"Example 1 — SSS with a shared side: triangles ABD and CBD sit back to back along the common side BD, with AB = CB and AD = CD given. The third pair is BD = BD — a side is always congruent to itself (the reflexive property). Three pairs of sides: congruent by SSS. Example 2 — ASA with vertical angles: segments AE and BD cross at point C, with angle A = angle E and AC = EC given. The angles at C are vertical, hence congruent, so triangles ACB and ECD have angle-side-angle in a row: congruent by ASA. Example 3 — cashing in with CPCTC: once triangles are congruent, Corresponding Parts of Congruent Triangles are Congruent. In Example 2 you may now conclude BC = DC, a fact nobody handed you. Two warnings close the toolbox: AAA fixes only the shape, not the size (a triangle and its photo enlargement), and SSA is not a shortcut at all — the swinging unfixed side can often form two different triangles."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Two triangles have all three pairs of sides equal; which shortcut applies? Answer: SSS. (2) Two triangles share two pairs of angles and the sides between those angles are equal; which shortcut? Answer: ASA. (3) Triangles share two pairs of equal sides and one pair of equal angles NOT between those sides; is congruence guaranteed? Answer: no — that is SSA, which is not a valid shortcut. (4) Triangles ABC and DEF are congruent with AB matching DE; what does CPCTC say about angle C and angle F? Answer: they are congruent, since corresponding parts match. (5) Two right triangles have equal hypotenuses of 13 and one pair of equal legs of 5; congruent? Answer: yes, by HL. (6) Two triangles have all three pairs of angles equal; congruent? Answer: not necessarily — AAA gives the same shape but possibly different sizes."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: trusting SSA. Fix two sides and a non-included angle, and the loose side can swing like a door to close the triangle in two different places — no guarantee, no shortcut. Misconception 2: ignoring the word included in SAS. The equal angle must sit between the two equal sides; an angle elsewhere turns the evidence into SSA. Exit ticket: (1) Name the shortcut for two angles and a non-included side. Answer: AAS. (2) What does the reflexive property let you claim about a side two triangles share? Answer: it is congruent to itself, giving you one pair for free."}
   ]}',
   'Study tip: before naming a shortcut, physically trace the given parts around the triangle in order — side, angle, side — so included and non-included angles cannot fool you.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"You notice the sequence 4, 8, 16, 32 doubling and predict 64 next. Which kind of reasoning is this?","options":["Inductive","Deductive","CPCTC","A two-column proof"],"answer":0,"explanation":"Predicting from a pattern is inductive reasoning — persuasive but not a proof."},
      {"prompt":"What is the converse of: if a figure is a square, then it is a rectangle?","options":["If a figure is not a square, then it is not a rectangle","If a figure is not a rectangle, then it is not a square","If a figure is a rectangle, then it is a square","Every square is a rectangle"],"answer":2,"explanation":"The converse swaps hypothesis and conclusion — and here it is false: a 3 by 5 rectangle is a counterexample."},
      {"prompt":"Two lines cross and one of the angles measures 115 degrees. What does its vertical angle measure?","options":["65 degrees","115 degrees","75 degrees","25 degrees"],"answer":1,"explanation":"Vertical angles are always congruent, so the opposite angle is also 115 degrees."},
      {"prompt":"Two parallel lines are cut by a transversal. A same-side interior angle partner of a 70 degree angle measures…","options":["70 degrees","20 degrees","110 degrees","290 degrees"],"answer":2,"explanation":"Same-side interior angles between parallel lines are supplementary: 180 − 70 = 110."},
      {"prompt":"A right triangle has one acute angle of 37 degrees. The other acute angle measures…","options":["43 degrees","47 degrees","53 degrees","63 degrees"],"answer":2,"explanation":"The angles sum to 180 and the right angle uses 90, so 180 − 90 − 37 = 53."},
      {"prompt":"Which of these is NOT a valid triangle congruence shortcut?","options":["SSS","ASA","SSA","AAS"],"answer":2,"explanation":"SSA fails because the non-included side can swing to close the triangle in two different ways."},
      {"prompt":"After proving two triangles congruent, CPCTC lets you conclude that…","options":["the triangles are also similar to a third triangle","every pair of corresponding sides and angles is congruent","the triangles are isosceles","only the sides used in the proof are equal"],"answer":1,"explanation":"Corresponding Parts of Congruent Triangles are Congruent — all six pairs match, including parts never mentioned in the proof."}
   ]}',
   null, 9),
  (6, 'Similarity & scale', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will recognize similar figures, use scale factors and the AA shortcut, and measure tall objects with shadows. Warm-up: from Lesson 4, name the shortcut that uses two sides and the included angle. From Pre-Algebra, solve the proportion 3/5 = x/20. Answers: SAS, and x = 12. Proportions are the engine of this whole lesson."},
      {"heading":"Same shape, new size","text":"Pinch-zoom a photo on your phone: every length grows, every angle stays put, and the picture never distorts. That is similarity. Two figures are similar when corresponding angles are equal and corresponding sides are proportional — same shape, possibly different size. The single number multiplying every length is the scale factor. For triangles there is a wonderfully cheap test: AA — if two pairs of corresponding angles are equal, the triangles are similar (the third pair is forced by the 180 degree sum). Worked example: a triangle has sides 4, 6, and 8, and a similar triangle has shortest side 10. The scale factor is 10 ÷ 4 = 2.5, so the other sides are 6 × 2.5 = 15 and 8 × 2.5 = 20."},
      {"heading":"Worked examples","text":"Example 1 — AA in the wild: a line drawn across a triangle parallel to its base creates a smaller triangle on top. The top triangle shares the apex angle and gets a corresponding-angle match from the parallel line, so the two triangles are similar by AA, and every pair of matching sides sits in the same ratio. Example 2 — indirect measurement: a 1.5 m student casts a 2 m shadow while a flagpole casts an 8 m shadow at the same moment. Sun rays are parallel, so the two triangles are similar by AA: height/shadow = 1.5/2 = h/8, and cross-multiplying gives 2h = 12, so h = 6 m. No ladder required. Example 3 — how perimeter and area scale: enlarge a triangle by scale factor k = 3. Perimeter is a length, so it triples. Area grows in two directions at once, so it multiplies by k^2 = 9: a triangle of area 5 becomes a triangle of area 45."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Two triangles have angles 50 and 60 degrees each; similar? Answer: yes, by AA — the third angles are both 70. (2) Rectangles 4 by 6 and 10 by 15: similar? Answer: yes, both side ratios equal 2.5. (3) Similar triangles have sides 4 and 6; the side matching 4 in the larger triangle is 10. Find the side matching 6. Answer: 15, from 4/10 = 6/x. (4) A 2 m sign casts a 3 m shadow while a tower casts a 45 m shadow. Find the tower height. Answer: 30 m, from 2/3 = h/45. (5) A blueprint uses scale factor 1/50; a wall drawn 12 cm long is really… Answer: 600 cm, or 6 m. (6) A logo is enlarged by scale factor 4; its area multiplies by… Answer: 16, since area scales by k^2."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: scaling by adding. If side 3 matches side 5, the rule is multiply by 5/3, not add 2 — a side of 9 matches 15, never 11. Similarity is multiplicative. Misconception 2: scaling area by k. Doubling every side quadruples the area; a pizza with twice the diameter is four times the pizza. Exit ticket: (1) Triangles with two equal angle pairs are similar by which shortcut? Answer: AA. (2) Scale factor 5 multiplies perimeter by what, and area by what? Answer: perimeter by 5, area by 25."}
   ]}',
   'Study tip: set up every similarity proportion in words first — small height over small shadow equals big height over big shadow — then drop in numbers; mismatched ratios cannot sneak past words.', 13),
  (7, 'Right triangles: Pythagorean theorem & a first look at trig', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will find missing sides of right triangles with the Pythagorean theorem, test whether a triangle is right, use the two special right triangles, and meet the three trig ratios. Warm-up: from Pre-Algebra, evaluate 9^2 and sqrt(49); from Lesson 6, solve 3/5 = x/20. Answers: 81, 7, and x = 12. Squares, roots, and ratios all clock in today."},
      {"heading":"The most famous theorem","text":"TV screens are measured along the diagonal — a 50 inch TV is 50 inches corner to corner. How do the width and height relate to that diagonal? In any right triangle, the two sides forming the right angle are the legs (a and b) and the side opposite the right angle — always the longest — is the hypotenuse (c). The Pythagorean theorem says a^2 + b^2 = c^2. Worked example: a gate needs a diagonal brace; the gate is 9 dm wide and 12 dm tall. The brace is the hypotenuse: c^2 = 9^2 + 12^2 = 81 + 144 = 225, so c = sqrt(225) = 15 dm. Notice the theorem only ever applies to right triangles — the right angle is its license."},
      {"heading":"Worked examples","text":"Example 1 — finding a leg: a 13 ft ladder leans against a wall with its foot 5 ft from the base. How high does it reach? Here the ladder is the hypotenuse: 5^2 + b^2 = 13^2, so b^2 = 169 − 25 = 144 and b = 12 ft. Example 2 — the converse as a right-angle detector: a triangle with sides 6, 8, 10 satisfies 36 + 64 = 100, so it IS a right triangle; for sides 4, 5, 6, always test against the largest side: 4^2 + 5^2 = 41 but 6^2 = 36, no match, so that triangle is NOT right. Builders use this in reverse: a 3-4-5 rope triangle forces a perfect corner. Two special right triangles are worth memorizing: in a 45-45-90 triangle the sides are x, x, and x × sqrt(2); in a 30-60-90 triangle they are x, x × sqrt(3), and 2x (short leg opposite 30, hypotenuse double it). Example 3 — trigonometry in one breath: for an acute angle in a right triangle, sine = opposite/hypotenuse, cosine = adjacent/hypotenuse, tangent = opposite/adjacent (remember SOH-CAH-TOA). In a 3-4-5 triangle, the angle opposite the side 3 has sin = 3/5 = 0.6, cos = 4/5 = 0.8, and tan = 3/4 = 0.75. These ratios depend only on the angle — similarity is the reason trig works."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Legs 5 and 12; find the hypotenuse. Answer: 13, since 25 + 144 = 169. (2) Hypotenuse 25, one leg 7; find the other leg. Answer: 24, since 625 − 49 = 576. (3) Is a triangle with sides 9, 12, 15 a right triangle? Answer: yes — 81 + 144 = 225 = 15^2. (4) A 45-45-90 triangle has legs of 7; find the hypotenuse. Answer: 7 × sqrt(2), about 9.9. (5) A 30-60-90 triangle has hypotenuse 12; find the short leg. Answer: 6 — the short leg is half the hypotenuse. (6) A ramp rises 3 m over a horizontal run of 4 m; find the tangent of its angle of elevation. Answer: 0.75, from opposite/adjacent = 3/4."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: dropping the squares — believing c = a + b. A 3-4 right triangle has hypotenuse 5, not 7; square first, add, then take the root. Misconception 2: letting the hypotenuse play as a leg. The hypotenuse is always c, always opposite the right angle, always the longest side; writing 13^2 + 5^2 = b^2 for the ladder gives nonsense. Exit ticket: (1) Legs 8 and 15; hypotenuse? Answer: 17. (2) In SOH-CAH-TOA, which ratio is cosine? Answer: adjacent over hypotenuse."}
   ]}',
   'Study tip: before touching the formula, label the hypotenuse with a c — it is always opposite the right angle — and the two legs a and b; most Pythagorean errors die at the labeling step.', 14),
  (8, 'Circles, area & volume: measuring the world', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will compute circumference and area of circles, areas of composite shapes, and volumes of prisms and cylinders. Warm-up from Lesson 7: (1) Legs 5 and 12 — find the hypotenuse. (2) Evaluate 4^2 and 6^2. Answers: 13, 16, and 36. Squared lengths are about to become areas."},
      {"heading":"The pizza problem","text":"Which is more pizza: one 12 inch pizza or two 8 inch pizzas? Circles first. The radius r runs from center to edge; the diameter d = 2r crosses through the center; a chord connects any two edge points; an arc is a piece of the edge. The distance around is the circumference C = 2 × pi × r = pi × d, and the space inside is the area A = pi × r^2, where pi ≈ 3.14. Worked example: the 12 inch pizza (r = 6) has area pi × 36 ≈ 113 sq in; each 8 inch pizza (r = 4) has area pi × 16 ≈ 50.2, so two of them total about 100.5 sq in. One 12 inch pizza beats two 8 inch pizzas — because area grows with the square of the radius. Slices work by fractions: a slice with a 90 degree central angle is 90/360 = 1/4 of the circle, in both arc length and area."},
      {"heading":"Worked examples","text":"Example 1 — arc length: a circular running track has radius 6 m, and you jog along an arc with a central angle of 60 degrees. Arc length = (60/360) × 2 × pi × 6 = (1/6) × 12 × pi = 2 × pi ≈ 6.28 m. Example 2 — composite area: a barn wall is an 8 m by 5 m rectangle topped by a triangle of base 8 m and height 3 m. Rectangle: 8 × 5 = 40. Triangle: (1/2) × 8 × 3 = 12. Total: 52 sq m. Complicated shapes are just simple shapes glued together — cut, compute, add. Example 3 — volume: a cylindrical water tank has radius 3 m and height 10 m. Volume of any prism or cylinder = area of the base × height, so V = pi × 3^2 × 10 = 90 × pi ≈ 282.7 cubic meters. Contrast this with surface area, the total area of all outside faces — the sheet metal to build the tank, not the water it holds. A box 4 by 3 by 2 has volume 24 cubic units but surface area 2(4 × 3) + 2(4 × 2) + 2(3 × 2) = 52 square units."},
      {"heading":"Your turn","text":"Answers follow each problem, using pi ≈ 3.14. (1) Circumference of a circle with diameter 10 cm. Answer: about 31.4 cm, from pi × d. (2) Area of a circle with radius 4 m. Answer: about 50.2 sq m, from pi × 16. (3) Area of a triangle with base 10 and height 7. Answer: 35, from (1/2) × 10 × 7. (4) An L-shaped room is a 6 by 4 rectangle plus a 2 by 3 rectangle; find its area. Answer: 30 sq units, from 24 + 6. (5) Volume of a rectangular box 5 by 4 by 3. Answer: 60 cubic units. (6) A slice of a radius-6 circle has a 90 degree central angle; find its area. Answer: about 28.3 sq units — one quarter of pi × 36."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: squaring the diameter in the area formula. A = pi × r^2 uses the radius; for a diameter of 10, the radius is 5 and the area is pi × 25, not pi × 100. Misconception 2: mixing up the measures and their units. Perimeter is a length (cm), area is squared (cm^2), volume is cubed (cm^3) — if your paint estimate has cm^3 in it, a formula went wrong. Exit ticket: (1) Circumference of a circle with radius 5. Answer: 10 × pi ≈ 31.4. (2) Volume of a cylinder with radius 2 and height 7. Answer: 28 × pi ≈ 87.9."}
   ]}',
   'Study tip: write the units on every intermediate number — cm, cm^2, cm^3 — and let them argue; wrong units flag a wrong formula before you finish the problem.', 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"Two similar triangles have sides 4 and 6 in the smaller one. The side matching 4 in the larger triangle is 10. What is the side matching 6?","options":["12","15","8","20"],"answer":1,"explanation":"The scale factor is 10 ÷ 4 = 2.5, so the matching side is 6 × 2.5 = 15."},
      {"prompt":"A figure is enlarged by scale factor 3. Its perimeter multiplies by 3; its area multiplies by…","options":["3","6","9","27"],"answer":2,"explanation":"Area grows in two directions, so it scales by k^2 = 9."},
      {"prompt":"Is a triangle with sides 5, 12, and 13 a right triangle?","options":["Yes, because 5^2 + 12^2 = 13^2","No, because 5 + 12 is not 13","Yes, because it has a long side","Cannot be determined"],"answer":0,"explanation":"25 + 144 = 169 = 13^2, so by the converse of the Pythagorean theorem the triangle is right."},
      {"prompt":"A 45-45-90 triangle has legs of length 7. Its hypotenuse is…","options":["7 × sqrt(2)","14","7 × sqrt(3)","49"],"answer":0,"explanation":"In a 45-45-90 triangle the hypotenuse is always leg × sqrt(2), here about 9.9."},
      {"prompt":"In a right triangle, the tangent of an acute angle equals…","options":["opposite ÷ hypotenuse","adjacent ÷ hypotenuse","opposite ÷ adjacent","hypotenuse ÷ opposite"],"answer":2,"explanation":"TOA in SOH-CAH-TOA: Tangent = Opposite over Adjacent."},
      {"prompt":"Using pi ≈ 3.14, the circumference of a circle with diameter 10 is about…","options":["15.7","31.4","62.8","78.5"],"answer":1,"explanation":"C = pi × d = 3.14 × 10 = 31.4. Using 2 × pi × d by mistake gives 62.8; 78.5 is the area."},
      {"prompt":"A cylinder has radius 3 and height 10. Its volume is…","options":["90 × pi","30 × pi","60 × pi","9 × pi"],"answer":0,"explanation":"V = base area × height = pi × 3^2 × 10 = 90 × pi ≈ 282.7 cubic units."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"congruent","translation":"having exactly the same size and shape, so one figure fits perfectly on the other","example":"Two frame plates cut with equal sides of 30 and 45 cm and an equal 40 degree included angle are congruent by SAS."},
      {"term":"similar","translation":"having the same shape but possibly different sizes: equal angles and proportional sides","example":"A photo and its pinch-zoomed enlargement are similar figures with a scale factor set by the zoom."},
      {"term":"transversal","translation":"a line that crosses two or more other lines, creating families of related angles","example":"A road crossing two parallel avenues is a transversal, and its alternate interior angles are congruent."},
      {"term":"hypotenuse","translation":"the longest side of a right triangle, always opposite the right angle","example":"In a 3-4-5 triangle the hypotenuse is 5, and a leaning ladder is the hypotenuse of the triangle it forms with wall and ground."},
      {"term":"scale factor","translation":"the single number that multiplies every length when a figure is enlarged or reduced","example":"A scale factor of 3 triples every side and perimeter but multiplies the area by 9."},
      {"term":"rigid motion","translation":"a move — translation, reflection, or rotation — that changes position but preserves all lengths and angles","example":"Sliding a puzzle piece across the table is a rigid motion, so the piece stays congruent to itself."}
   ]}',
   null, 8),
  (11, 'Coordinate geometry & transformations', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will compute distances and midpoints on the coordinate plane, use slopes to spot parallel and perpendicular lines, and perform the four basic transformations. Warm-up: from Lesson 7, find the hypotenuse for legs 6 and 8; from Pre-Algebra, name the quadrant of (−3, 2). Answers: 10, and Quadrant II. The Pythagorean theorem is about to grow coordinates."},
      {"heading":"Geometry meets the grid","text":"A delivery drone flies from warehouse (1, 2) to rooftop (4, 6) on the city grid. How far is the trip? Draw the horizontal and vertical legs: the changes are 4 − 1 = 3 and 6 − 2 = 4, and the straight-line path is the hypotenuse of that right triangle. This is the distance formula — the Pythagorean theorem wearing coordinates: d = sqrt((x2 − x1)^2 + (y2 − y1)^2) = sqrt(9 + 16) = sqrt(25) = 5. The midpoint of the trip averages the coordinates: ((1 + 4)/2, (2 + 6)/2) = (2.5, 4). Slope measures steepness as rise over run; parallel lines have equal slopes, and perpendicular lines have slopes that multiply to −1 (like 2 and −1/2)."},
      {"heading":"Worked examples","text":"Example 1 — verifying a right angle with slopes: a path from (0, 0) to (4, 2) has slope 2/4 = 1/2; a second path from (4, 2) to (2, 6) has slope (6 − 2)/(2 − 4) = 4/(−2) = −2. Since (1/2) × (−2) = −1, the paths meet at a right angle. Example 2 — the four transformations, applied to the point (3, 1): a translation right 2 and up 4 adds to each coordinate, giving (5, 5); a reflection across the x-axis flips the y-sign, giving (3, −1); a reflection across the y-axis flips the x-sign, giving (−3, 1); a rotation of 180 degrees about the origin flips both signs, giving (−3, −1). Translations, reflections, and rotations are rigid motions: they preserve every length and angle, so a figure and its image are congruent. Example 3 — dilation, the odd one out: a dilation centered at the origin with scale factor 2 multiplies both coordinates, sending (3, 1) to (6, 2) and a triangle to a triangle twice as large. A dilation preserves shape but not size, so the image is similar, not congruent — the coordinate version of Lesson 6."},
      {"heading":"Your turn","text":"Answers follow each problem. (1) Distance from (1, 2) to (7, 10). Answer: 10, from sqrt(36 + 64). (2) Midpoint of (−2, 5) and (6, 1). Answer: (2, 3), by averaging. (3) A line has slope 3; what slope does a parallel line have, and a perpendicular one? Answer: 3 and −1/3. (4) Translate (−1, 4) left 3 and down 2. Answer: (−4, 2). (5) Reflect (5, −2) across the y-axis. Answer: (−5, −2). (6) Dilate (2, −3) from the origin with scale factor 3; is the image figure congruent to the original? Answer: (6, −9), and no — a dilation produces a similar figure, not a congruent one."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: skipping the squares (or the root) in the distance formula. The distance from (0, 0) to (3, 4) is sqrt(9 + 16) = 5 — not 3 + 4 = 7, and not 25. Misconception 2: reflecting across the wrong axis. Reflecting across the x-axis changes y (the point jumps vertically over the horizontal axis); reflecting across the y-axis changes x. Say which axis is the mirror before touching the signs. Exit ticket: (1) Distance from (0, 0) to (5, 12). Answer: 13. (2) Rotate (2, 7) by 180 degrees about the origin. Answer: (−2, −7)."}
   ]}',
   'Study tip: sketch every transformation on a mini grid, even a sloppy one — a two-second picture catches sign errors that a page of coordinate rules lets through.', 13),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"An exterior angle of a triangle measures 130 degrees, and one remote interior angle is 55 degrees. The other remote interior angle measures…","options":["75 degrees","65 degrees","50 degrees","105 degrees"],"answer":0,"explanation":"An exterior angle equals the sum of the two remote interior angles: 55 + x = 130, so x = 75."},
      {"prompt":"Triangles ABC and DEF have AB = DE and angle A = angle D. Which single additional fact guarantees congruence by SAS?","options":["angle B = angle E","AC = DF","BC = EF","angle C = angle F"],"answer":1,"explanation":"SAS needs the angle between the two sides. Sides AB and AC include angle A, so AC = DF completes SAS; BC = EF would only give the invalid SSA."},
      {"prompt":"A 1.8 m person casts a 2.4 m shadow while a tree casts a 12 m shadow. How tall is the tree?","options":["9 m","16 m","10.8 m","7.2 m"],"answer":0,"explanation":"Similar triangles by AA: 1.8/2.4 = h/12, so h = 12 × 0.75 = 9 m."},
      {"prompt":"A 30-60-90 triangle has a hypotenuse of 12. The side opposite the 60 degree angle measures…","options":["6","6 × sqrt(3)","12 × sqrt(3)","6 × sqrt(2)"],"answer":1,"explanation":"The short leg (opposite 30) is half the hypotenuse: 6. The long leg (opposite 60) is short leg × sqrt(3) = 6 × sqrt(3) ≈ 10.4."},
      {"prompt":"A ramp rises 3 m over a horizontal run of 4 m. What is the tangent of its angle of elevation?","options":["0.6","0.75","0.8","1.33"],"answer":1,"explanation":"Tangent = opposite/adjacent = 3/4 = 0.75. The 0.6 and 0.8 are the sine and cosine of this angle."},
      {"prompt":"A circle has radius 6. Using pi ≈ 3.14, the length of an arc with a 60 degree central angle is about…","options":["6.28","3.14","12.56","18.84"],"answer":0,"explanation":"The arc is 60/360 = 1/6 of the circumference: (1/6) × 2 × pi × 6 = 2 × pi ≈ 6.28."},
      {"prompt":"What is the distance between the points (1, 2) and (7, 10)?","options":["8","10","14","sqrt(52)"],"answer":1,"explanation":"d = sqrt((7 − 1)^2 + (10 − 2)^2) = sqrt(36 + 64) = sqrt(100) = 10."},
      {"prompt":"A rectangular park measures 60 m by 80 m. Walking the straight diagonal path instead of walking along the two sides saves how many meters?","options":["40 m","100 m","20 m","60 m"],"answer":0,"explanation":"Multi-step: the diagonal is sqrt(60^2 + 80^2) = sqrt(3600 + 6400) = 100 m; the two sides total 60 + 80 = 140 m; the saving is 140 − 100 = 40 m."}
   ]}',
   null, 10)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0001-0000-4000-8000-000000000004' and l.position = v.pos
);
