-- Science foundations pack: Concepts of Biology (course 1 of the science track).
-- A non-majors tour of the living world with a diagnostic quiz, template-driven
-- reading lessons (objective + retrieval warm-up, hook, worked cases, practice
-- with answers, misconceptions + exit tickets), two checkpoints, a vocabulary
-- lesson, an applied experiment-design project, and a final assessment.
-- Structure adapted from OpenStax Concepts of Biology (CC BY 4.0). Fixed UUIDs
-- and guarded inserts make the file idempotent: safe to re-run at any time.

-- ============ Concepts of Biology ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0004-0000-4000-8000-000000000001',
  'en', null,
  'Concepts of Biology',
  'A friendly first pass through the living world: how scientists ask questions, what makes something alive, how cells are built and powered, how genes pass traits from parents to offspring, how populations evolve, and how organisms fit into ecosystems. Every lesson teaches through everyday examples and fully worked cases, and closes with a hands-on project where you design your own experiment. Structure adapted from OpenStax Concepts of Biology (CC BY 4.0).',
  null, 'foundations', 1, true, 'science', '{}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0004-0000-4000-8000-000000000001', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"Which of these is NOT one of the shared characteristics of all living things?","options":["Being made of one or more cells","Using energy and materials from the environment","Being made of metal alloys","Responding to the environment"],"answer":2,"explanation":"Living things are built from cells, use energy, grow, reproduce, and respond to their surroundings. Being made of metal is not a property of life. Covered in Lesson 2: The scientific method & characteristics of life."},
      {"prompt":"A testable, tentative explanation that a scientist sets out to support or reject is called a…","options":["law","hypothesis","conclusion","theory"],"answer":1,"explanation":"A hypothesis is a proposed, testable explanation for an observation. Covered in Lesson 2: The scientific method & characteristics of life."},
      {"prompt":"According to cell theory, the basic unit of structure and function in living things is the…","options":["atom","organ","cell","molecule"],"answer":2,"explanation":"Cell theory states that the cell is the smallest unit that can be called alive, and all cells come from existing cells. Covered in Lesson 3: Cell structure & function."},
      {"prompt":"Which structure is found in plant cells but NOT in typical animal cells?","options":["Nucleus","Cell wall","Cell membrane","Mitochondrion"],"answer":1,"explanation":"Plant cells have a rigid cellulose cell wall outside the membrane; animal cells do not. Covered in Lesson 3: Cell structure & function."},
      {"prompt":"Photosynthesis uses light energy to build sugar from which two raw materials?","options":["Oxygen and glucose","Carbon dioxide and water","Nitrogen and water","Protein and salt"],"answer":1,"explanation":"Plants take in carbon dioxide and water and use light energy to make glucose, releasing oxygen. Covered in Lesson 4: How cells get energy."},
      {"prompt":"The molecule that carries an organism''s genetic instructions is…","options":["DNA","water","glucose","chlorophyll"],"answer":0,"explanation":"DNA stores the instructions for building and running an organism, organized into genes. Covered in Lesson 6: DNA, genes & inheritance."},
      {"prompt":"In natural selection, individuals that survive and reproduce best in their environment tend to…","options":["stop passing on any traits","pass on more of their helpful traits","become a new kingdom instantly","lose their DNA"],"answer":1,"explanation":"Individuals better suited to their environment leave more offspring, so their helpful traits become more common over generations. Covered in Lesson 7: Evolution & natural selection."},
      {"prompt":"In a food chain, the organisms that make their own food from sunlight are called…","options":["decomposers","consumers","producers","predators"],"answer":2,"explanation":"Producers, such as plants and algae, capture energy from sunlight and form the base of the food chain. Covered in Lesson 8: Ecology & ecosystems."}
   ]}',
   null, 10),
  (2, 'The scientific method & characteristics of life', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will list the shared characteristics of living things and walk through the steps of the scientific method. Warm-up — think for 30 seconds about each: (1) Name three things a dog does that a rock never does. (2) If you claimed plants grow faster with music, how could you check it? Sample answers: a dog eats, grows, and reproduces; you could grow two identical groups of plants with and without music and compare. Those two instincts — spotting what life does, and testing an idea fairly — are exactly what this lesson makes precise."},
      {"heading":"What life is, and how science studies it","text":"Biology is the study of life, so it helps to agree on what counts as alive. Living things share a set of properties: they are made of one or more cells, they are organized in an ordered way, they use energy and materials (metabolism), they grow and develop, they respond to their environment, they reproduce, and over generations they evolve. A single feature is not enough — a flame uses energy and grows, but it is not made of cells and cannot reproduce or evolve, so it is not alive. Scientists study these living systems using the scientific method: observe something, ask a question, form a hypothesis (a testable, tentative explanation), make a prediction, run an experiment, then analyze the results and share them. Worked example: you notice bread grows mold faster on the counter than in the fridge (observation). Question: does temperature affect mold growth? Hypothesis: warmer temperatures speed up mold growth. Prediction: bread left warm will show mold sooner than bread kept cold."},
      {"heading":"Worked cases","text":"Case 1 — hypothesis versus theory. In everyday talk a theory is a hunch, but in science a theory is a well-tested, broad explanation supported by lots of evidence, such as the cell theory or the theory of evolution. A hypothesis is the small, testable idea you check in a single study; a theory is the big picture many studies have built. Case 2 — a fair test needs a control. To test whether a fertilizer helps tomatoes, you grow two groups that are identical in soil, water, and light; only one group gets fertilizer. The untreated group is the control, the baseline you compare against. Without it, you could not tell whether fertilizer or just good weather caused any change. Case 3 — is it alive? A virus is a tricky case: it carries genetic material and evolves, but it has no cells of its own and cannot reproduce without hijacking a host cell. Because it fails the cell and independent-reproduction criteria, most biologists do not classify viruses as fully living — a reminder that the list of life''s features is used together, not one at a time."},
      {"heading":"Your turn","text":"Answer, then check. (1) Which life property lets a plant bend toward a window? Answer: responding to the environment (a response to a stimulus). (2) You test whether sugar water keeps cut flowers fresh longer; what is the control group? Answer: identical flowers in plain water with no sugar. (3) True or false: a scientific theory is just a guess. Answer: false — it is a broad explanation backed by strong evidence. (4) Name the step that comes right after forming a hypothesis. Answer: making a prediction and designing an experiment to test it. (5) A candle flame grows and uses energy; give one reason it is not alive. Answer: it is not made of cells (and cannot reproduce or evolve). (6) Rewrite as a testable hypothesis: I think loud music bothers plants. Answer: for example, tomato plants exposed to loud music for 4 hours a day will grow shorter than identical plants kept in quiet."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: in science, theory means a shaky guess. In fact a scientific theory is one of the strongest kinds of explanation there is, supported by many independent lines of evidence. Misconception 2: a single result proves a hypothesis forever. Science supports or fails to reject a hypothesis, and results must be repeatable by others before they are trusted; one experiment is a start, not a proof. Exit ticket — answer before moving on: (1) List any three characteristics shared by all living things. Answer: for example, made of cells, use energy, and reproduce. (2) What is the purpose of a control group? Answer: it is the untreated baseline that lets you tell whether your one changed variable actually caused the effect."}
   ]}',
   'Study tip: whenever you read a claim, ask two questions — what is the hypothesis, and where is the control? Those two habits catch most bad science.', 13),
  (3, 'Cell structure & function', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will describe cell theory, compare prokaryotic and eukaryotic cells, and match key organelles to their jobs. Warm-up from Lesson 2: (1) What is the smallest thing all living organisms are built from? (2) Name one property of life a single cell can carry out. Answers: the cell; a single cell can use energy, respond, grow, or reproduce. Now we open the cell and look inside."},
      {"heading":"The cell and its compartments","text":"Cell theory has three parts: all living things are made of one or more cells, the cell is the basic unit of life, and all cells arise from pre-existing cells. Cells come in two broad types. Prokaryotic cells (bacteria) are small and have no nucleus — their DNA floats freely in the cell. Eukaryotic cells (plants, animals, fungi, protists) are larger and keep their DNA inside a membrane-bound nucleus, along with other organelles, which are specialized compartments that each do a job. Think of a eukaryotic cell as a factory: the nucleus is the office holding the master blueprints (DNA), the mitochondria are the power plants that release energy from food, the ribosomes are the assembly machines that build proteins, and the cell membrane is the security gate controlling what enters and leaves. Worked example: a muscle cell, which needs lots of energy to contract, contains many mitochondria — structure matches function."},
      {"heading":"Worked cases","text":"Case 1 — plant versus animal cell. Both are eukaryotic and share a nucleus, mitochondria, ribosomes, and a cell membrane. Plant cells add three things animal cells lack: a rigid cell wall made of cellulose for support, chloroplasts that carry out photosynthesis, and a large central vacuole that stores water and keeps the cell firm. That is why a wilted plant perks up after watering — its vacuoles refill. Case 2 — surface area and size. Cells stay small because they must exchange materials across their membrane. As a cell grows, its volume grows faster than its surface area, so a giant cell could not move enough food and waste across its membrane fast enough. Staying small keeps the surface-area-to-volume ratio high. Case 3 — matching organelle to job. A cell that secretes lots of protein, like a gland cell, is packed with ribosomes and endoplasmic reticulum, the network where proteins are folded and shipped. Counting organelles under a microscope can therefore hint at what a mystery cell does."},
      {"heading":"Your turn","text":"Answer, then check. (1) Which cell type has no nucleus? Answer: prokaryotic (bacterial) cells. (2) Name the organelle that releases energy from food. Answer: the mitochondrion. (3) Give one structure found in plant cells but not animal cells. Answer: cell wall (or chloroplast, or large central vacuole). (4) According to cell theory, where do new cells come from? Answer: from pre-existing cells that divide. (5) Why can''t cells grow to any size? Answer: volume outgrows surface area, so exchange across the membrane becomes too slow. (6) Which organelle controls what enters and leaves the cell? Answer: the cell membrane."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: all cells have a nucleus. Prokaryotic cells (bacteria) have DNA but no nucleus — the membrane-bound nucleus is a eukaryotic feature. Misconception 2: plant cells do not have mitochondria because they have chloroplasts. Plant cells have both; they make sugar in chloroplasts and still release its energy in mitochondria. Exit ticket: (1) State the three parts of cell theory in your own words. Answer: living things are made of cells, the cell is the basic unit of life, and cells come from other cells. (2) A cell is packed with chloroplasts and has a cell wall — plant or animal? Answer: plant."}
   ]}',
   'Study tip: pair every organelle with a one-word job (nucleus = blueprints, mitochondria = power, ribosomes = build) so the parts stick as a team, not a list.', 13),
  (4, 'How cells get energy: photosynthesis & respiration', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will explain photosynthesis and cellular respiration in plain terms and see how they connect. Warm-up from Lesson 3: (1) Which organelle carries out photosynthesis? (2) Which organelle releases energy from food? Answers: the chloroplast; the mitochondrion. This lesson follows the energy as it flows through those two organelles."},
      {"heading":"Two halves of one energy cycle","text":"Almost all life runs on energy that started as sunlight. Photosynthesis is how plants, algae, and some bacteria capture that energy: using chlorophyll in their chloroplasts, they take in carbon dioxide from the air and water from the soil, and use light energy to build glucose (a sugar), releasing oxygen as a by-product. In words: carbon dioxide + water + light energy give glucose + oxygen. Cellular respiration runs the process in reverse to release that stored energy: in the mitochondria, cells break down glucose using oxygen, capturing the energy in a usable form (ATP) and giving off carbon dioxide and water. In words: glucose + oxygen give carbon dioxide + water + usable energy. Worked example: the oxygen you breathe was released by photosynthesis, and the carbon dioxide you exhale can be taken up by a plant to build new sugar — the two processes feed each other."},
      {"heading":"Worked cases","text":"Case 1 — who does which. Plants do both photosynthesis and respiration; animals and fungi only do respiration and must eat food for glucose. A plant in daylight photosynthesizes faster than it respires, so it gives off net oxygen; in the dark it only respires, giving off carbon dioxide. Case 2 — following the atoms. In respiration the carbon atoms that were locked into glucose leave the cell as carbon dioxide gas. That is literally where much of the mass you lose when you exercise or diet goes — you breathe it out as carbon dioxide. Case 3 — energy currency. Cells do not use glucose directly to power tasks; respiration transfers glucose''s energy into ATP, a small molecule the cell spends like cash to contract muscles, pump ions, or build molecules. Burning glucose without this step would waste the energy as heat, so respiration is a controlled, step-by-step release."},
      {"heading":"Your turn","text":"Answer, then check. (1) Name the two raw materials a plant uses in photosynthesis. Answer: carbon dioxide and water. (2) What gas does photosynthesis release? Answer: oxygen. (3) In which organelle does cellular respiration mainly occur? Answer: the mitochondrion. (4) Do animals perform photosynthesis? Answer: no — they get glucose by eating and only perform respiration. (5) What are the waste products of cellular respiration? Answer: carbon dioxide and water. (6) A sealed jar holds a healthy plant in bright light; is the plant adding oxygen or carbon dioxide to the jar overall? Answer: oxygen, because in bright light photosynthesis outpaces respiration."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: plants only photosynthesize and never respire. Plants respire all the time, day and night, to power their own cells — they just also photosynthesize when light is available. Misconception 2: plants get their food (mass) mainly from soil. The bulk of a plant''s new material comes from carbon dioxide in the air, not from soil, built into sugar by photosynthesis. Exit ticket: (1) Write photosynthesis in words (inputs give outputs). Answer: carbon dioxide + water + light give glucose + oxygen. (2) Respiration and photosynthesis are described as opposite processes — give one reason why. Answer: one stores energy by building glucose and releasing oxygen, the other releases energy by breaking glucose down and using oxygen."}
   ]}',
   'Study tip: memorize the two word-equations back to back — the outputs of one are the inputs of the other, which is the whole cycle in a nutshell.', 14),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"Which sequence shows the scientific method in a sensible order?","options":["Hypothesis, observation, question, experiment","Observation, question, hypothesis, experiment","Experiment, hypothesis, observation, question","Conclusion, hypothesis, experiment, observation"],"answer":1,"explanation":"You observe something, ask a question about it, form a hypothesis, then test it with an experiment."},
      {"prompt":"A researcher grows two identical groups of plants and gives only one group extra light. The normal-light group is the…","options":["hypothesis","control group","variable","theory"],"answer":1,"explanation":"The untreated, baseline group is the control, used for comparison."},
      {"prompt":"Which statement is part of cell theory?","options":["All cells contain chlorophyll","Cells come only from pre-existing cells","Every cell has a nucleus","Cells are the largest unit of life"],"answer":1,"explanation":"Cell theory states that all cells arise from pre-existing cells, that cells are the basic unit of life, and that all living things are made of cells."},
      {"prompt":"A cell has a nucleus, mitochondria, a cell wall, and chloroplasts. It is most likely a…","options":["bacterial cell","plant cell","animal cell","virus"],"answer":1,"explanation":"A cell wall and chloroplasts together with a nucleus point to a plant cell."},
      {"prompt":"Which are the inputs of photosynthesis?","options":["Glucose and oxygen","Carbon dioxide and water","Oxygen and water","Carbon dioxide and glucose"],"answer":1,"explanation":"Photosynthesis takes in carbon dioxide and water and uses light energy to build glucose, releasing oxygen."},
      {"prompt":"Cellular respiration releases usable energy by breaking down glucose using which gas?","options":["Nitrogen","Oxygen","Carbon dioxide","Helium"],"answer":1,"explanation":"Respiration uses oxygen to break down glucose, giving off carbon dioxide and water and capturing energy as ATP."},
      {"prompt":"Why do most cells stay microscopically small?","options":["They run out of DNA if large","Volume grows faster than surface area, slowing exchange","Large cells cannot hold water","Small cells cannot divide"],"answer":1,"explanation":"As a cell enlarges, its volume outpaces its surface area, so materials cannot cross the membrane fast enough."}
   ]}',
   null, 9),
  (6, 'DNA, genes & inheritance', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will connect DNA, genes, and alleles, and predict simple inheritance with a Punnett square. Warm-up from Lesson 3: (1) Where in a eukaryotic cell is DNA stored? (2) Cell theory says new cells come from where? Answers: in the nucleus; from pre-existing cells. When those cells divide, they must copy their DNA — the molecule this lesson unpacks."},
      {"heading":"From DNA to traits","text":"DNA is the long molecule that stores an organism''s instructions, written in an alphabet of four bases (A, T, C, G) whose order spells out the code. A gene is a segment of DNA that carries the instructions for one particular product or trait, such as flower color or the ability to digest milk. Most organisms carry two copies of each gene, one from each parent, and the different versions of a gene are called alleles. Alleles can be dominant (their effect shows even if only one copy is present, written as a capital letter) or recessive (their effect shows only when both copies are recessive, written lowercase). Worked example: in pea plants the purple-flower allele (P) is dominant over white (p). A plant with Pp has one of each allele but looks purple, because the dominant P masks the p. Its genotype (the alleles it carries) is Pp; its phenotype (the trait you see) is purple."},
      {"heading":"Worked cases","text":"Case 1 — a Punnett square. Cross two purple Pp plants. Each parent passes on either P or p, so the offspring combinations are PP, Pp, Pp, and pp: three look purple, one looks white, a 3-to-1 ratio. The one white plant is pp because it inherited a recessive allele from each parent. Case 2 — carriers. A person can carry one recessive allele for a condition without showing it (genotype like Aa) and still pass it on. If two carriers have children, on average one in four children inherits two recessive alleles and shows the trait — the same 3-to-1 pattern as the peas. Case 3 — genotype versus phenotype. Purple plants PP and Pp look identical (same phenotype) but differ genetically (different genotypes). You often cannot read the genotype directly from the appearance of a dominant trait; you infer it from the offspring, which is exactly what breeders and geneticists do."},
      {"heading":"Your turn","text":"Answer, then check. (1) What is a gene? Answer: a segment of DNA that codes for a particular product or trait. (2) What is an allele? Answer: one of the different versions of a gene. (3) A pea plant is Pp for flower color; what color is it, and why? Answer: purple, because P (purple) is dominant and masks p. (4) Cross Pp x pp. What fraction of offspring are white (pp)? Answer: one half. (5) Distinguish genotype from phenotype in one sentence. Answer: genotype is the alleles an organism carries; phenotype is the trait you can observe. (6) Two carriers Aa x Aa have children; what fraction are expected to be aa? Answer: one quarter."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: dominant means more common or stronger in a population. Dominant only describes which allele shows when paired with a recessive one; a dominant allele can be rare, and a recessive trait can be very common. Misconception 2: a 3-to-1 ratio guarantees exactly three purple and one white in every litter of four. The ratio is a probability across many offspring, like coin flips — small families can differ from it by chance. Exit ticket: (1) In Bb, which allele''s trait appears? Answer: B, the dominant one. (2) Cross Bb x Bb; what is the expected ratio of dominant to recessive phenotypes? Answer: 3 to 1."}
   ]}',
   'Study tip: always write genotypes with a capital for dominant and lowercase for recessive — the letters do the remembering for you when you fill in a Punnett square.', 14),
  (7, 'Evolution & natural selection', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will explain natural selection and how populations evolve over time. Warm-up from Lesson 6: (1) Where do the two alleles of a gene come from? (2) Why do offspring vary from one another? Answers: one from each parent; because they inherit different combinations of alleles. That inherited variation is the raw material evolution works on."},
      {"heading":"How populations change","text":"Evolution is a change in the inherited traits of a population across generations. Its main driver, described by Charles Darwin, is natural selection, and it rests on a few simple facts. First, individuals in a population vary in their traits. Second, some of that variation is heritable — passed to offspring through genes. Third, more offspring are born than can survive on limited resources. Put together: individuals whose traits happen to suit their environment tend to survive and reproduce more, so those helpful traits become more common in the next generation. Note that individuals do not evolve; populations do, as the mix of traits shifts over time. Worked example: in a beetle population with both green and brown beetles, if birds spot green beetles more easily on brown soil, more brown beetles survive to reproduce. Over generations the population becomes mostly brown — not because any beetle changed color, but because brown beetles left more offspring."},
      {"heading":"Worked cases","text":"Case 1 — antibiotic resistance. In a population of bacteria, a few happen to carry a mutation that lets them survive an antibiotic. When the drug is applied, the susceptible bacteria die and the resistant ones reproduce, so the next generation is largely resistant. This is natural selection happening fast enough to watch, and it is why finishing a full course of antibiotics matters. Case 2 — variation must be heritable. A weightlifter builds strong arms during life, but that strength is not written into the genes and is not passed to offspring, so it cannot drive evolution. Only heritable variation — differences in genes — can. Case 3 — evidence from many sources. Evolution is supported by fossils showing change over time, by shared anatomy (the same arm bones in humans, whales, and bats), and by DNA similarities that place related species close together. Multiple independent lines of evidence make evolution one of biology''s best-supported theories."},
      {"heading":"Your turn","text":"Answer, then check. (1) What level — individual or population — evolves? Answer: the population. (2) Name the three ingredients natural selection needs. Answer: variation, heritability of that variation, and more offspring than can survive (a struggle to survive and reproduce). (3) Why must the varying trait be heritable? Answer: only traits passed to offspring through genes can become more common over generations. (4) A moth species turns mostly dark after soot darkens tree bark; explain briefly. Answer: dark moths were better camouflaged, survived and reproduced more, so their allele spread. (5) Give one line of evidence for evolution. Answer: for example, fossils, shared anatomy, or DNA similarities. (6) True or false: an animal evolves stronger muscles during its lifetime and passes them on. Answer: false — traits built during life are not heritable."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: organisms evolve on purpose because they need a trait. Natural selection has no goal; helpful variation arises by chance (mutation and recombination), and the environment simply favors whoever already has it. Misconception 2: evolution means individuals change within their lifetime. Individuals keep the genes they are born with; it is the population''s makeup that shifts across generations. Exit ticket: (1) In one sentence, define natural selection. Answer: the process by which individuals with heritable traits suited to their environment survive and reproduce more, making those traits more common. (2) Why is antibiotic resistance an example of evolution? Answer: the drug selects for resistant bacteria, so the resistant trait becomes more common in the population."}
   ]}',
   'Study tip: run any evolution story through the three-part check — is there variation, is it heritable, and does it affect survival or reproduction? If all three hold, natural selection can act.', 14),
  (8, 'Ecology & ecosystems', 'reading',
   '{"sections":[
      {"heading":"Objective & warm-up","text":"By the end of this lesson you will trace energy through a food chain and describe how matter and populations move through an ecosystem. Warm-up from Lesson 4: (1) Which organisms capture energy from sunlight? (2) What process releases that stored energy in cells? Answers: plants and other photosynthesizers; cellular respiration. Ecology zooms out from the single cell to whole communities living together."},
      {"heading":"Energy and matter in ecosystems","text":"Ecology studies how organisms interact with each other and their environment. An ecosystem includes all the living things (the community) in an area plus the non-living factors like sunlight, water, and soil. Energy enters almost every ecosystem as sunlight, which producers (plants, algae) capture through photosynthesis. Consumers eat other organisms: herbivores eat producers, and carnivores eat other consumers. Decomposers (bacteria and fungi) break down dead material, returning nutrients to the soil. A food chain traces who eats whom — grass, then grasshopper, then frog, then snake — and each step is a trophic level. Worked example: energy flows one way and shrinks at each step. Only about ten percent of the energy at one level is passed to the next, because organisms use most of their energy to live and lose much as heat. That is why food chains rarely have more than four or five links and why top predators are few."},
      {"heading":"Worked cases","text":"Case 1 — energy flows, matter cycles. Energy makes a one-way trip: it enters as sunlight and leaves as heat, so ecosystems need a constant energy supply. Matter, by contrast, cycles: the same carbon, water, and nitrogen atoms are used over and over as decomposers return them to producers. Case 2 — a food web is more realistic than a chain. Real communities are food webs — many interconnected chains — because most animals eat several kinds of food. Remove one species and the effects ripple: if frogs vanish, grasshoppers may boom and snakes may go hungry, showing how connected an ecosystem is. Case 3 — carrying capacity. A population cannot grow forever; the environment can support only so many individuals, a limit called the carrying capacity, set by food, space, water, and predators. When a population overshoots it, starvation or disease brings it back down, so numbers tend to level off rather than rise without end."},
      {"heading":"Your turn","text":"Answer, then check. (1) What is a producer? Answer: an organism that makes its own food, usually from sunlight, such as a plant or alga. (2) In grass, then rabbit, then fox, which is the herbivore? Answer: the rabbit. (3) Roughly how much energy passes from one trophic level to the next? Answer: about ten percent. (4) What do decomposers do for an ecosystem? Answer: they break down dead material and return nutrients to the soil. (5) Explain the difference between energy flow and matter cycling in one sentence. Answer: energy flows one way through the ecosystem and is lost as heat, while matter is recycled over and over. (6) What is carrying capacity? Answer: the maximum population size an environment can support over time."},
      {"heading":"Misconceptions & exit ticket","text":"Misconception 1: energy is recycled through an ecosystem the way matter is. Energy is not recycled — it enters as sunlight and is steadily lost as heat, which is why a constant energy source is required. Misconception 2: removing one species barely matters. Because species are linked in a food web, losing one can trigger booms and crashes in others. Exit ticket: (1) Put in order from base upward: fox, grass, rabbit. Answer: grass, rabbit, fox. (2) Why can''t a food chain have twenty links? Answer: only about ten percent of energy transfers at each step, so there is too little energy left to support many levels."}
   ]}',
   'Study tip: say it as a slogan — energy flows, matter cycles. Those three words separate the two ideas students most often mix up.', 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"A segment of DNA that codes for a particular trait is called a…","options":["cell","gene","ribosome","chromosome arm"],"answer":1,"explanation":"A gene is a segment of DNA carrying the instructions for a specific product or trait."},
      {"prompt":"In pea plants, purple (P) is dominant over white (p). A Pp plant will be…","options":["white","purple","half purple, half white","colorless"],"answer":1,"explanation":"With one dominant P allele, the plant shows the dominant purple phenotype."},
      {"prompt":"Cross Pp x Pp. What phenotype ratio do you expect?","options":["1 purple to 1 white","3 purple to 1 white","All purple","All white"],"answer":1,"explanation":"The Punnett square gives PP, Pp, Pp, pp — three purple to one white."},
      {"prompt":"Which is a requirement for natural selection to occur?","options":["Individuals must choose to change","Traits must be heritable","Every offspring must survive","The population must be tiny"],"answer":1,"explanation":"Selection acts only on heritable variation, which can be passed to offspring."},
      {"prompt":"The rise of antibiotic-resistant bacteria is a real-world example of…","options":["photosynthesis","natural selection","cell theory","the water cycle"],"answer":1,"explanation":"The antibiotic kills susceptible bacteria and the resistant ones reproduce, so resistance spreads — natural selection."},
      {"prompt":"In a food chain, roughly what fraction of energy passes to the next trophic level?","options":["About 90%","About 50%","About 10%","About 100%"],"answer":2,"explanation":"Only around ten percent of energy transfers up each step; the rest is used or lost as heat."},
      {"prompt":"Which statement about ecosystems is correct?","options":["Energy is recycled and matter flows away","Energy flows one way and matter cycles","Both energy and matter are recycled","Both energy and matter flow away and are never reused"],"answer":1,"explanation":"Energy enters as sunlight and is lost as heat (one-way flow), while matter such as carbon and nitrogen is recycled."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"cell","translation":"the smallest unit that can be called alive; the basic building block of every organism","example":"Your body is made of trillions of cells, and each one carries out the basic tasks of life."},
      {"term":"organelle","translation":"a specialized structure inside a cell that does a particular job","example":"The mitochondrion is the organelle that releases energy from food, so muscle cells are packed with them."},
      {"term":"gene","translation":"a segment of DNA that carries the instructions for one trait or product","example":"A gene for flower color tells a pea plant whether to make purple or white pigment."},
      {"term":"allele","translation":"one of the different versions of a gene","example":"The purple allele and the white allele are two alleles of the pea flower-color gene."},
      {"term":"natural selection","translation":"the process where individuals with helpful heritable traits survive and reproduce more, spreading those traits","example":"Natural selection made a beetle population mostly brown because brown beetles hid better and left more offspring."},
      {"term":"ecosystem","translation":"all the living things in an area together with the non-living factors they depend on","example":"A pond ecosystem includes the fish, plants, and microbes plus the water, sunlight, and dissolved oxygen."}
   ]}',
   null, 8),
  (11, 'Applied project: design a simple experiment', 'writing',
   '{"sections":[
      {"heading":"Objective & the question","text":"In this project you will plan a complete, honest experiment the way a scientist would, writing it up section by section as a virtual lab report. You do not need a laboratory — a windowsill, some cups, and seeds are enough. Start with a question you can actually test. A good question is specific and measurable, not vague. Weak: does light matter for plants? Strong: do bean seedlings grown in bright light grow taller over 14 days than identical seedlings grown in dim light? Write your own testable question now. It should name what you change (the light), what you measure (height in centimeters), and over what time. Keep it small enough to finish and simple enough to measure with a ruler."},
      {"heading":"Hypothesis & variables","text":"Turn your question into a hypothesis: a clear, testable prediction with a reason. Example: I predict bean seedlings in bright light will grow taller than those in dim light, because more light means more photosynthesis and more energy for growth. Now name your variables precisely. The independent variable is the one thing you deliberately change (amount of light: bright versus dim). The dependent variable is what you measure in response (seedling height in centimeters). The controlled variables are everything you keep the same so they cannot muddy the result: same bean type, same cup and soil, same amount of water, same temperature, same start date. Write one sentence for each of the three variable types for your own experiment. If you cannot keep something constant, name it — honest scientists list what they could not control."},
      {"heading":"Procedure & observation table","text":"Write a numbered procedure so exact that a stranger could repeat it and get comparable results. Example steps: (1) Fill ten identical cups with the same soil and plant one bean in each. (2) Place five cups in bright light and five in dim light, the control-versus-treatment split. (3) Give every cup 50 mL of water every two days. (4) Measure each seedling''s height in centimeters every two days for 14 days and record it. Using more than one cup per group (replication) matters: one plant might die or thrive by luck, so you average several to see the real pattern. Then lay out an observation table before you begin, with columns for Day, Bright-light heights, and Dim-light heights, and a row for each measurement day. Sketch that empty table in your report so your data has a home the moment you collect it."},
      {"heading":"Error sources & the honest write-up","text":"No experiment is perfect, and naming its weaknesses is a strength, not a confession. List possible sources of error and how each could bend your result. Examples: uneven watering could help one group by accident; a cold windowsill might slow one set; measuring height by eye instead of with a ruler adds random error; too few seedlings makes a single unlucky plant distort the average. For each source, note one way to reduce it — measure with the same ruler at the same time of day, use more seedlings, rotate cups to even out temperature. Finish by describing how you would analyze the data: calculate the average height of each group at day 14, compare them, and decide whether the difference supports or fails to support your hypothesis. Remember, a result that rejects your hypothesis is still a successful experiment — it taught you something true."},
      {"heading":"Self-check rubric","text":"Score your own report before calling it done — aim to answer yes to every line. (1) Question: is it specific, testable, and measurable, naming what changes and what is measured? (2) Hypothesis: is it a clear prediction with a reason, not just a restated question? (3) Variables: did you correctly identify one independent variable, one dependent variable, and at least three controlled variables? (4) Procedure: could a stranger repeat it exactly, and does it include a control group and replication (several trials per group)? (5) Observation table: is there a blank table with the right columns ready for data? (6) Error sources: did you name at least two realistic sources of error and a fix for each? (7) Honesty: did you commit to reporting the result even if it rejects your hypothesis? If any line is a no, revise that section — that is exactly what real peer review asks a scientist to do."}
   ]}',
   'Writing tip: after drafting, hand your procedure to someone else and ask them to follow it literally — every place they get confused is a step you need to make more precise.', 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"Which set correctly lists three characteristics shared by all living things?","options":["Made of cells, use energy, reproduce","Made of metal, glow, float","Have a nucleus, breathe air, walk","Contain chlorophyll, have bones, swim"],"answer":0,"explanation":"All living things are made of cells, use energy, grow, respond, and reproduce; the other options list traits many organisms lack."},
      {"prompt":"A bacterial cell differs from a plant cell mainly because a bacterial cell…","options":["has no DNA","has no nucleus","has no cell membrane","cannot reproduce"],"answer":1,"explanation":"Bacteria are prokaryotes: they have DNA and a membrane but no membrane-bound nucleus."},
      {"prompt":"During photosynthesis a plant takes in carbon dioxide and water and releases…","options":["glucose only","oxygen","nitrogen","salt"],"answer":1,"explanation":"Photosynthesis builds glucose and releases oxygen as a by-product using light energy."},
      {"prompt":"Two carrier parents are each Aa for a recessive condition (aa). What fraction of their children are expected to have the condition?","options":["None","One quarter","One half","All"],"answer":1,"explanation":"An Aa x Aa cross gives AA, Aa, Aa, aa — one in four is aa and shows the recessive condition."},
      {"prompt":"Which best describes how natural selection changes a population over time?","options":["Individuals decide to grow new traits","Helpful heritable traits become more common as their carriers reproduce more","Every trait becomes equally common","Traits gained during life are inherited"],"answer":1,"explanation":"Individuals with heritable traits suited to the environment reproduce more, so those traits spread through the population."},
      {"prompt":"In the food chain grass, then rabbit, then fox, which statement is true?","options":["The fox is a producer","The rabbit is a herbivore","Grass is a decomposer","Energy increases up the chain"],"answer":1,"explanation":"The rabbit eats the producer (grass), so it is a herbivore; energy actually decreases up the chain."},
      {"prompt":"A student grows 10 bean seedlings in bright light and 10 identical seedlings in dim light, watering all the same, and measures their height for 14 days. What is the independent variable?","options":["Height of the seedlings","Amount of water given","Amount of light","Number of days"],"answer":2,"explanation":"The independent variable is the factor the student deliberately changes — the amount of light. Height is what is measured (dependent), and water is held constant (controlled)."},
      {"prompt":"In that same experiment, the bright-light seedlings average 18 cm and the dim-light seedlings average 9 cm at day 14. The most careful conclusion is that…","options":["light has no effect on growth","the data support the idea that more light increases seedling height","dim light kills all plants","the dim-light group was the control-free error"],"answer":1,"explanation":"The taller average in bright light supports the hypothesis that more light increases growth; a good conclusion states what the data support rather than overclaiming."}
   ]}',
   null, 11)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0004-0000-4000-8000-000000000001' and l.position = v.pos
);
