-- Technology track — Web Development Foundations (course 3 of the track).
-- Prerequisite: Digital Literacy (bbbb0002-0000-4000-8000-000000000001).
-- Twelve lessons: a diagnostic quiz, six structured readings (objective +
-- retrieval warm-up, instruction with code, worked example, hands-on tasks
-- with expected results, common mistakes + exit ticket), two checkpoints,
-- a vocabulary set, an applied personal-page project, and a final assessment.
-- Fixed UUIDs and guarded inserts make the file idempotent: safe to re-run.

-- ============ Web Development Foundations ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, subject, prerequisite_ids)
values (
  'bbbb0002-0000-4000-8000-000000000003',
  'en', null,
  'Web Development Foundations',
  'Build real web pages from scratch: structure content with semantic HTML, style it with modern CSS and flexbox, and bring it to life with JavaScript. The course ends with an applied project — a personal page with a bio, photo, project list, and a working button.',
  null, 'foundations', 3, true, 'technology',
  '{bbbb0002-0000-4000-8000-000000000001}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0002-0000-4000-8000-000000000003', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"When you type an address like example.com and press Enter, which machine sends your browser the page?","options":["Your own computer builds it from scratch","A server — a computer that waits for requests and answers them","The search engine you used last","Your internet router stores every website"],"answer":1,"explanation":"The browser sends a request and a server replies with the page files. If you missed this, Lesson 2 (How the web works) covers the whole round trip."},
      {"prompt":"A page has the right words but you want to change its colors and fonts. Which language do you edit?","options":["HTML","CSS","JavaScript","HTTP"],"answer":1,"explanation":"CSS controls presentation; HTML holds structure and JavaScript holds behavior. Lessons 2 and 4 cover this division of labor."},
      {"prompt":"Which tag is the best choice to wrap a site''s main navigation links?","options":["<div>","<nav>","<b>","<table>"],"answer":1,"explanation":"<nav> is the semantic element for navigation — it tells browsers and screen readers what the block is for. Lesson 3 (HTML) covers semantic tags."},
      {"prompt":"What is the alt attribute on an <img> tag for?","options":["It sets the image width","It is a text description used by screen readers and shown if the image fails to load","It links the image to another page","It makes the image load faster"],"answer":1,"explanation":"alt text is the accessible description of an image. Lesson 3 (HTML) covers images and accessible defaults."},
      {"prompt":"In CSS, what does the selector .card match?","options":["The element with id=\"card\"","Every <card> tag","Every element with class=\"card\"","Only the first card on the page"],"answer":2,"explanation":"A leading dot means class selector, so .card matches all elements with class=\"card\". Lesson 4 (CSS) covers selectors."},
      {"prompt":"Which CSS declaration makes the direct children of a container line up in a row?","options":["display: flex;","position: absolute;","float: row;","text-align: row;"],"answer":0,"explanation":"display: flex turns a container into a flexbox whose children lay out in a row by default. Lesson 6 (Layout) covers flexbox."},
      {"prompt":"In modern JavaScript, which keyword declares a variable whose value you plan to reassign later?","options":["const","let","static","define"],"answer":1,"explanation":"let allows reassignment; const does not. Lesson 7 (JavaScript basics) covers variables."},
      {"prompt":"What does document.querySelector(\"#title\") give you?","options":["Every element on the page","The first element matching the selector #title — the element with id=\"title\"","The text of the page title only","A copy of the page you cannot change"],"answer":1,"explanation":"querySelector returns the first element matching a CSS selector, and you can then read or change it. Lesson 8 (DOM selection and updates) covers this."}
   ]}',
   null, 10),
  (2, 'How the web works: HTML, CSS, JS and what a browser does', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to describe what happens between typing a URL and seeing a finished page, and name the job of each of the web''s three languages. Retrieval warm-up — answer from memory before reading on: (1) What is the difference between a browser and a search engine? (2) What does a URL identify? (Answers: a browser is the program on your device that displays pages, while a search engine is a website that helps you find them; a URL identifies one specific resource — a page, image, or file — and where to request it.)"},
      {"heading":"One second, four steps","text":"Type a URL, press Enter, and in about a second a finished page appears. Four things just happened. (1) Your browser sent an HTTP request to a server — a short text message that essentially says ''GET /index.html''. (2) The server replied with a response: a plain-text file written in HTML. (3) Reading that HTML top to bottom, the browser discovered other files the page needs — stylesheets, scripts, images — and requested each of those too. (4) It combined everything and painted the page. Each language has exactly one job. HTML describes structure and meaning: this is a heading, this is a paragraph, this is a link. CSS describes presentation: headings are dark blue, text uses this font. JavaScript describes behavior: when this button is clicked, do something. A tiny page can use all three:\n\n```html\n<h1>Hello, web!</h1>\n<style>\n  h1 { color: darkblue; }\n</style>\n<script>\n  console.log(''The page has loaded.'');\n</script>\n```"},
      {"heading":"Worked example: watch a page assemble","text":"Build the smallest real page, one layer at a time. Step 1 — structure only. Create a file named hello.html containing:\n\n```html\n<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Hello</title>\n  </head>\n  <body>\n    <h1>Hello, web!</h1>\n    <p>This page traveled zero meters — it lives on my computer.</p>\n  </body>\n</html>\n```\n\nOpen it in a browser: you see a large bold heading and a smaller paragraph, black on white. You wrote no styling — those defaults come from the browser''s own stylesheet. Step 2 — add presentation. Inside <head>, add:\n\n```html\n<style>\n  body { font-family: system-ui, sans-serif; }\n  h1 { color: darkblue; }\n</style>\n```\n\nReload: same words, new look. The structure did not change; only the presentation layer did. Step 3 — add behavior. Just before </body>, add:\n\n```html\n<script>\n  console.log(''Loaded at '' + new Date().toTimeString());\n</script>\n```\n\nReload and open the browser console (F12, Console tab): a timestamp prints. Nothing visible changed, but the page now runs code — that is the behavior layer."},
      {"heading":"Your turn","text":"Do each task and check the expected result. (1) Create hello.html exactly as in the worked example and open it by double-clicking the file. Expected: the styled page renders — no server is needed for local files. (2) On any news site, press Ctrl+U (Cmd+Option+U on Mac) to view source. Expected: a wall of HTML text — this is literally what the server sent; the browser turned it into the page you saw. (3) Open DevTools (F12), go to the Network tab, and reload the news site. Expected: a list of dozens of requests; the first is the HTML document, followed by CSS, JavaScript, and image files it referenced. (4) In hello.html, change darkblue to crimson and reload. Expected: the heading turns crimson — you changed presentation without touching structure. (5) Break the page on purpose: delete the closing </h1> tag and reload. Expected: the page still renders (browsers are forgiving), but the paragraph may inherit heading styling — a hint of why valid structure matters."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: thinking JavaScript is Java. They are unrelated languages that share half a name for 1990s marketing reasons; the web runs JavaScript. Mistake 2: putting looks into HTML — reaching for tags or attributes to control color and size. Keep the jobs separate: structure in HTML, presentation in CSS, behavior in JavaScript, so each can change without breaking the others. Exit ticket — answer, then check: (Q1) Your page shows the right content but the layout is wrong on phones. Which of the three languages will you edit? (A1: CSS — layout is presentation.) (Q2) What does a web server actually send the browser: a picture of the page, or something else? (A2: plain-text files — HTML first, then the CSS, JS, and images it references; the browser renders them into the page.)"}
   ]}',
   null, 14),
  (3, 'HTML: structure, semantic tags, links, images, forms', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to structure a page with semantic HTML5 elements and write correct, accessible links, images, and forms. Retrieval warm-up — from Lesson 2, answer before reading: (1) Which of the three web languages is HTML, and what is its one job? (2) Name the two other files a browser typically fetches after the HTML. (Answers: HTML is the structure language — it describes what each piece of content is; the browser then fetches CSS for presentation and JavaScript for behavior.)"},
      {"heading":"Tags that mean something","text":"You could build an entire page out of <div> boxes — and the browser would render it. But a <div> says nothing about what is inside it. Semantic HTML5 elements carry meaning: <header> for the top banner, <nav> for navigation, <main> for the unique content of the page, <article> for a self-contained piece, <footer> for the bottom. Screen readers use these landmarks to let users jump straight to the content, and search engines use them to understand your page. The other essentials: a link is <a href=\"about.html\">About me</a>; an image is <img src=\"dog.jpg\" alt=\"A brown terrier catching a ball\"> — the alt text is what a screen reader speaks and what renders if the file is missing; a form collects input:\n\n```html\n<form>\n  <label for=\"email\">Email</label>\n  <input id=\"email\" type=\"email\" name=\"email\">\n  <button>Subscribe</button>\n</form>\n```\n\nThe label''s for attribute matches the input''s id — that pairing is what makes the form usable by screen readers, and it makes the label clickable for everyone."},
      {"heading":"Worked example: an About page, tag by tag","text":"Build a small About page and watch each element earn its place. Step 1 — landmarks first:\n\n```html\n<header>\n  <h1>Maya Chen</h1>\n  <nav>\n    <a href=\"index.html\">Home</a>\n    <a href=\"projects.html\">Projects</a>\n  </nav>\n</header>\n<main></main>\n<footer><p>Written by Maya, 2026.</p></footer>\n```\n\nThis renders as a heading, two default-blue underlined links, and a footer line — plain, but the skeleton is meaningful. Step 2 — fill <main> with content:\n\n```html\n<main>\n  <img src=\"maya.jpg\" alt=\"Maya smiling in front of a whiteboard\" width=\"200\">\n  <p>I am a nurse learning to build for the web.</p>\n</main>\n```\n\nThe photo renders at 200 pixels wide with the paragraph below it. Delete maya.jpg and reload: the alt text appears in its place — the page still communicates. Step 3 — add a contact form with the label/input pairing from above, plus type=\"email\": the browser now refuses to submit ''not-an-address'' and shows a validation message. You wrote zero JavaScript and already have validation."},
      {"heading":"Your turn","text":"(1) Create about.html with <header>, <main>, and <footer>, a <h1> with your name, and one paragraph. Expected: heading, paragraph, footer text render top to bottom. (2) Add a <nav> inside <header> with links to index.html and projects.html. Expected: two underlined links; clicking one shows the browser''s error page or the file, since the targets may not exist yet — the link itself works. (3) Add an <img> of any photo you have, with honest alt text, then rename the image file so the src is wrong. Expected: your alt text renders where the photo was. (4) Add the email form from the instruction section and type ''hello'' into the field, then press the button. Expected: the browser blocks submission and explains the address is invalid. (5) Click the word ''Email'' (the label). Expected: the input receives focus — proof the for/id pairing is connected. (6) Run your page through the W3C validator at validator.w3.org (upload the file). Expected: zero errors, or messages that point you at exactly what to fix."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: decorative tag choice — using <b> for headings or <div> for everything because it looks fine. It looks fine to you; to a screen-reader user the page becomes an undifferentiated soup. Choose the tag by meaning, style it later with CSS. Mistake 2: empty or lazy alt text (alt=\"image\" or alt=\"photo123\"). Describe what the image shows and why it matters; if an image is purely decorative, use alt=\"\" so screen readers skip it. Exit ticket: (Q1) A blog post on a page with other content — which element should wrap it, <div> or <article>? (A1: <article> — it is a self-contained piece of content.) (Q2) What two attributes connect a label to its input, and what do users gain? (A2: the label''s for matches the input''s id; screen readers announce the label, and clicking the label focuses the field.)"}
   ]}',
   null, 15),
  (4, 'CSS: selectors, box model, colors, typography', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to target elements with selectors, control spacing with the box model, and set colors and typography deliberately. Retrieval warm-up — from Lesson 3, answer before reading: (1) Name three semantic HTML5 landmark elements. (2) What does the alt attribute do? (Answers: any of header, nav, main, article, footer; alt provides the text description a screen reader speaks and the fallback shown if the image fails to load.)"},
      {"heading":"Select, then declare","text":"Every CSS rule has two parts: a selector (which elements) and declarations (what to change). The three selectors you will use daily: an element selector like p targets every paragraph; a class selector like .note targets every element with class=\"note\" — reusable, your workhorse; an id selector like #site-title targets the single element with that id. Once selected, every element is a rectangular box with four layers, inside out: content, padding (space inside the border), border, and margin (space outside, pushing neighbors away). Colors take names (crimson), hex codes (#1a1a2e), or rgb(); typography is set with font-family, font-size, and line-height:\n\n```css\n.note {\n  padding: 12px;\n  border: 2px solid #1a1a2e;\n  margin: 16px 0;\n  font-family: Georgia, serif;\n  line-height: 1.5;\n}\n```\n\nOne habit worth forming immediately: add box-sizing: border-box so that a declared width includes padding and border — modern stylesheets almost always start with it."},
      {"heading":"Worked example: styling a card","text":"Take this HTML and turn it into a card, one declaration at a time:\n\n```html\n<article class=\"card\">\n  <h2>First patient of the day</h2>\n  <p>Notes from the morning shift.</p>\n</article>\n```\n\nStep 1 — select and space it:\n\n```css\n.card { padding: 16px; }\n```\n\nReload: the text moves inward from the invisible edge; padding created breathing room inside the box. Step 2 — make the box visible:\n\n```css\n.card {\n  padding: 16px;\n  border: 1px solid #cccccc;\n  border-radius: 8px;\n  max-width: 400px;\n}\n```\n\nNow a rounded rectangle wraps the text, never wider than 400px. Step 3 — typography and color:\n\n```css\n.card h2 { color: #1a1a2e; font-size: 1.25rem; }\n.card p { line-height: 1.6; color: #333333; }\n```\n\nThe selector .card h2 is a descendant selector: only headings inside a card change, so the rest of the page is untouched. The card now reads comfortably — dark-on-light text, generous line spacing. Step 4 — add margin: 16px auto; to .card. The auto left and right margins split the leftover space equally: the card centers itself."},
      {"heading":"Your turn","text":"(1) Create a page with three paragraphs, give the second one class=\"note\", and write a .note rule with a yellow background (background: #fff3bf;). Expected: only the middle paragraph is highlighted. (2) Add padding: 20px to .note. Expected: the yellow area grows — padding is inside the box, so the background covers it. (3) Now add margin: 40px instead of more padding. Expected: the paragraph pushes its neighbors away but the yellow area does not grow — margin is outside the border. (4) Set border: 4px dashed crimson on .note. Expected: a dashed red frame between the padding and the margin — all four box layers are now visible. (5) Set body { font-family: system-ui, sans-serif; line-height: 1.6; } and reload. Expected: the whole page switches font and the lines of text space out — one rule on body cascades to everything inside it. (6) In DevTools, click the .note paragraph and find the box-model diagram in the Styles panel. Expected: your exact padding, border, and margin values drawn as nested rectangles."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: confusing padding and margin. Remember: padding is inside the border (background shows through it), margin is outside (transparent, pushes neighbors). When spacing looks wrong, open the DevTools box-model diagram instead of guessing. Mistake 2: styling everything with ids. An id must be unique per page, so #card1, #card2, #card3 rules multiply forever; one .card class styles them all. Reserve ids for anchors and JavaScript hooks. Exit ticket: (Q1) A box has width: 200px, padding: 10px, border: 2px solid, and default box-sizing. How wide does it render? (A1: 224px — 200 + 10 + 10 + 2 + 2; with box-sizing: border-box it would be 200px.) (Q2) What is the difference between the selectors p.note and .note p? (A2: p.note matches paragraphs that have the class note; .note p matches paragraphs inside an element with the class note.)"}
   ]}',
   null, 15),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"Put the page-load steps in order: (a) browser paints the page, (b) browser requests the URL, (c) server responds with HTML, (d) browser requests the CSS and JS files the HTML references.","options":["b, c, d, a","c, b, a, d","b, d, c, a","d, b, c, a"],"answer":0,"explanation":"Request the URL, receive the HTML, discover and fetch the linked files, then render. The HTML must arrive before the browser can know which other files it needs."},
      {"prompt":"You are marking up a self-contained blog post that also appears in a feed. The most semantic wrapper is:","options":["<div>","<span>","<article>","<footer>"],"answer":2,"explanation":"<article> means a self-contained piece of content that makes sense on its own. <div> carries no meaning; <span> is inline; <footer> is for closing matter."},
      {"prompt":"Which line is a correct, complete link to a page named projects.html?","options":["<a src=\"projects.html\">Projects</a>","<a href=\"projects.html\">Projects</a>","<link href=\"projects.html\">Projects</link>","<a>projects.html</a>"],"answer":1,"explanation":"Links use <a> with an href attribute. src belongs to <img> and <script>; <link> is a head element for stylesheets, not clickable links."},
      {"prompt":"Which alt text is best for a product photo of a red bicycle on a shop page?","options":["alt=\"image\"","alt=\"photo-final-v2.jpg\"","alt=\"Red city bicycle with a rear basket\"","No alt attribute, to keep the HTML shorter"],"answer":2,"explanation":"alt should describe what the image shows so a screen-reader user gets the same information. Filenames and the word image convey nothing; omitting alt fails accessibility checks."},
      {"prompt":"You want space between a box''s border and the text inside it. Which property?","options":["margin","padding","gap","line-height"],"answer":1,"explanation":"Padding is the space inside the border; margin is outside it, pushing neighbors away. gap spaces flex or grid children; line-height spaces lines of text."},
      {"prompt":"Which selector targets every element written as <p class=\"warning\">?","options":["#warning","warning","<p.warning>","p.warning"],"answer":3,"explanation":"p.warning means paragraphs that carry the class warning. # would be an id, a bare word would be an element name, and selectors never use angle brackets."},
      {"prompt":"With default box-sizing, a rule sets width: 300px; padding: 20px; border: 5px solid;. The rendered width is:","options":["300px","320px","340px","350px"],"answer":3,"explanation":"Default (content-box) sizing adds padding and border on both sides: 300 + 20 + 20 + 5 + 5 = 350px. This is exactly why most stylesheets set box-sizing: border-box."}
   ]}',
   null, 10),
  (6, 'Layout: flexbox and responsive design', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to arrange boxes in rows and columns with flexbox and make a layout adapt to any screen width. Retrieval warm-up — from Lesson 4, answer before reading: (1) Which box-model layer is inside the border, and which pushes neighbors away? (2) What does the selector .card h2 match? (Answers: padding is inside, margin pushes neighbors; it matches h2 elements inside any element with class card.)"},
      {"heading":"The container is in charge","text":"Old web layout fought the browser; flexbox recruits it. Set display: flex on a container and its direct children stop stacking and line up in a row. From then on you give the container instructions and it does the arithmetic: justify-content distributes children along the row (flex-start, center, space-between), align-items aligns them across it (stretch, center), gap puts even space between them, and flex-direction: column turns the row into a stack. A complete navigation bar in four declarations:\n\n```css\n.site-nav {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 16px;\n}\n```\n\nResponsive design adds one principle: the same HTML should work at every width. Three tools deliver it — the viewport meta tag <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> in <head> (without it, phones pretend to be 980px-wide desktops), flex-wrap: wrap so rows break instead of overflowing, and media queries to change the rules at a breakpoint:\n\n```css\n@media (max-width: 600px) {\n  .site-nav { flex-direction: column; }\n}\n```"},
      {"heading":"Worked example: a card row that adapts","text":"Start with three of the cards from Lesson 4 inside a wrapper:\n\n```html\n<div class=\"card-row\">\n  <article class=\"card\">…</article>\n  <article class=\"card\">…</article>\n  <article class=\"card\">…</article>\n</div>\n```\n\nStep 1 — unstyled, the cards stack vertically: block elements each take a full row. Add:\n\n```css\n.card-row { display: flex; }\n```\n\nReload: the cards snap into one row, each only as wide as its content, all stretched to equal height — flexbox aligns heights for free. Step 2 — space and balance:\n\n```css\n.card-row { display: flex; gap: 16px; }\n.card { flex: 1; }\n```\n\nflex: 1 tells every card to share the leftover width equally: three identical columns with even gutters, and no width arithmetic anywhere. Step 3 — make it responsive. Narrow the window: the cards squeeze until the text is unreadable. Fix it:\n\n```css\n.card-row { flex-wrap: wrap; }\n.card { flex: 1 1 220px; }\n```\n\nNow each card wants about 220px; when three no longer fit, one wraps to the next line, then two. Drag the window edge and watch the layout renegotiate itself continuously — that is responsive design working with the browser instead of against it."},
      {"heading":"Your turn","text":"(1) Put five links in a <nav class=\"site-nav\"> and set display: flex; gap: 24px; on it. Expected: the links line up in a row with even spacing instead of stacking. (2) Add justify-content: center, then change it to space-between. Expected: first the whole group centers; then the first and last links pin to the edges with the rest spread evenly. (3) Build the three-card row from the worked example with flex: 1 on the cards. Expected: three equal columns whose heights match even if one card has more text. (4) Add flex-wrap: wrap to the row and flex: 1 1 220px to the cards, then narrow the window slowly. Expected: three columns become two, then one — no horizontal scrollbar at any width. (5) Add the viewport meta tag, then open the page in DevTools device mode (Ctrl+Shift+M) and pick a phone. Expected: text renders at a readable size; remove the tag and reload to see the tiny zoomed-out desktop layout it prevents. (6) Write a media query at max-width: 600px that turns .site-nav into a column. Expected: on narrow screens the links stack; widen past 600px and the row returns."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: styling the children when the container is in charge. If a row will not center or space out, the fix almost always belongs on the flex container (justify-content, gap), not on each child. Mistake 2: fixed pixel widths everywhere. width: 800px overflows a 390px phone; prefer max-width, flex-basis, and percentages so boxes can shrink. Exit ticket: (Q1) What is the difference between justify-content and align-items? (A1: justify-content distributes children along the main axis — the row direction; align-items aligns them across it.) (Q2) A page looks perfect on your laptop but microscopic on a phone. What single missing line is the first suspect? (A2: the viewport meta tag — without it mobile browsers render the page at desktop width and zoom out.)"}
   ]}',
   null, 15),
  (7, 'JavaScript basics: variables, functions, events', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to store values in variables, package logic into functions, and run code when the user acts. Retrieval warm-up — from earlier lessons, answer before reading: (1) Which of the three web languages owns behavior? (2) Where does a <script> tag usually go, and why? (Answers: JavaScript; just before </body> — or with a defer attribute in <head> — so the HTML it works with exists before the code runs.)"},
      {"heading":"Values, names, and actions","text":"JavaScript stores values under names. Modern code uses two keywords: const for names that will not be reassigned (your default) and let for names that will. Never use the outdated var. Values have types — strings, numbers, booleans:\n\n```js\nconst clinicName = ''Riverside'';\nlet patientsSeen = 0;\npatientsSeen = patientsSeen + 1;\nconst isOpen = patientsSeen < 30;\n```\n\nFunctions package steps under a name so you can run them on demand:\n\n```js\nfunction greet(name) {\n  return ''Welcome, '' + name + ''!'';\n}\nconsole.log(greet(''Maya'')); // Welcome, Maya!\n```\n\nAnd events connect functions to the user. The modern pattern is addEventListener: pick an element, name the event, hand over the function to call.\n\n```js\nconst button = document.querySelector(''#hello-btn'');\nbutton.addEventListener(''click'', () => {\n  console.log(''Clicked at '' + new Date().toTimeString());\n});\n```\n\nNote what is passed: the function itself, not a call. Writing greet() would run it immediately, once, at page load — passing greet hands the browser something to run later, on every click."},
      {"heading":"Worked example: a counter, line by line","text":"Build the classic first interactive widget. Step 1 — the HTML:\n\n```html\n<p>Count: <span id=\"count\">0</span></p>\n<button id=\"add-btn\">Add one</button>\n```\n\nThis renders a line of text and a real, focusable button — <button> gives you keyboard support for free. Step 2 — state. In a script before </body>:\n\n```js\nlet count = 0;\n```\n\nlet, not const: this value will change. Step 3 — the update function:\n\n```js\nconst countSpan = document.querySelector(''#count'');\nfunction addOne() {\n  count = count + 1;\n  countSpan.textContent = count;\n}\n```\n\nThe function does two things every interactive widget does: update the state, then update the screen to match. Step 4 — wire the event:\n\n```js\nconst addBtn = document.querySelector(''#add-btn'');\naddBtn.addEventListener(''click'', addOne);\n```\n\nReload and click: 0 becomes 1, 2, 3 — each click runs addOne, which changes the number and rewrites the span. Press Tab until the button focuses, then press Enter: it also works from the keyboard, because you used a real <button>."},
      {"heading":"Your turn","text":"(1) In the browser console, run const city = ''Lima''; then city = ''Cusco'';. Expected: a TypeError — assignment to constant variable; const means it. (2) Declare let score = 10; score = score + 5; score. Expected: 15. (3) Write function double(n) { return n * 2; } and call double(21). Expected: 42; calling double(''ha'') returns ''haha'' — the * became string surprise territory, a taste of why types matter. (4) Build the counter from the worked example in a file counter.html. Expected: each click increases the number on screen by one. (5) Add a second button labeled Reset that sets count back to 0 and updates the span. Expected: after several clicks, Reset returns the display to 0. (6) Change the listener line to addBtn.addEventListener(''click'', addOne()); — with parentheses — and reload. Expected: the count may jump to 1 immediately and clicking does nothing; you called the function once instead of handing it over. Change it back."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: addEventListener(''click'', addOne()) with parentheses — this calls the function now and passes its return value instead of the function. Pass the name only. Mistake 2: confusing = with ===. One equals sign assigns; three compare. if (count = 10) assigns 10 and is always truthy — write if (count === 10). Exit ticket: (Q1) You declare const total = 0; and later need total = total + price;. What must change? (A1: declare it with let — const forbids reassignment.) (Q2) In your own words, what three things does addBtn.addEventListener(''click'', addOne) specify? (A2: which element to watch, which event to listen for, and which function to run when it happens.)"}
   ]}',
   null, 15),
  (8, 'Making pages interactive: DOM selection and updates', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to select any element on a page, change its text and classes, and combine selection with events to build real interactions. Retrieval warm-up — from Lesson 7, answer before reading: (1) Which keyword declares a variable that will be reassigned? (2) Why is addEventListener(''click'', addOne) correct but addEventListener(''click'', addOne()) a bug? (Answers: let; the version with parentheses calls the function immediately and passes its result — you must pass the function itself.)"},
      {"heading":"The page as a live object","text":"When the browser reads your HTML it builds the DOM — the Document Object Model, a live tree of objects, one per element. JavaScript never edits your HTML file; it edits this tree, and the browser repaints instantly. Two selection tools cover nearly everything: document.querySelector(sel) returns the first element matching a CSS selector — the same selectors you learned in Lesson 4 — and document.querySelectorAll(sel) returns all of them.\n\n```js\nconst title = document.querySelector(''#site-title'');\nconst cards = document.querySelectorAll(''.card'');\n```\n\nOnce you hold an element, three updates cover most needs: element.textContent = ''New text'' replaces its text (always safe — the browser treats it as plain text, never as code, so use it for anything a user typed); element.classList.add(''name''), .remove(''name''), and .toggle(''name'') switch CSS classes, which is how JavaScript changes appearance without writing styles — the styles stay in CSS where they belong; and document.createElement plus append grows the page:\n\n```js\nconst li = document.createElement(''li'');\nli.textContent = ''New item'';\ndocument.querySelector(''#list'').append(li);\n```"},
      {"heading":"Worked example: a dark-mode toggle","text":"Combine everything into the classic real-world widget. Step 1 — HTML and CSS:\n\n```html\n<button id=\"theme-btn\">Switch to dark</button>\n```\n\n```css\nbody.dark {\n  background: #1a1a2e;\n  color: #f0f0f0;\n}\n```\n\nNothing changes yet: no element has the dark class, so the rule sleeps. Step 2 — select and listen:\n\n```js\nconst themeBtn = document.querySelector(''#theme-btn'');\nthemeBtn.addEventListener(''click'', () => {\n  document.body.classList.toggle(''dark'');\n});\n```\n\nClick: the whole page inverts — toggle added the class, so the CSS rule woke up. Click again: the class is removed and the page returns to light. One line of JavaScript, and all the visual decisions stayed in the stylesheet. Step 3 — keep the button''s label honest:\n\n```js\nthemeBtn.addEventListener(''click'', () => {\n  const isDark = document.body.classList.toggle(''dark'');\n  themeBtn.textContent = isDark ? ''Switch to light'' : ''Switch to dark'';\n});\n```\n\ntoggle returns true when it just added the class, so the label always describes what the button will do next — a small courtesy that real products get wrong surprisingly often."},
      {"heading":"Your turn","text":"(1) On any of your pages, open the console and run document.querySelector(''h1'').textContent = ''I control this page now''. Expected: the heading changes instantly; reload and it reverts — you edited the DOM, not the file. (2) Run document.querySelectorAll(''p'').length. Expected: the number of paragraphs on the page. (3) Build the dark-mode toggle from the worked example. Expected: each click flips the page colors and the button label. (4) Add a text input and a button; on click, read the input with input.value and append it as a new <li> using createElement and textContent. Expected: each click adds a list item with whatever you typed. (5) Type <b>bold?</b> into your input and add it. Expected: the literal text <b>bold?</b> appears, not bold text — textContent treated it as text, which is exactly the safe behavior you want for user input. (6) Move your <script> tag into <head> without defer and reload. Expected: the console shows an error like Cannot read properties of null — the script ran before the elements existed. Restore it (or add defer) and the error disappears."},
      {"heading":"Common mistakes and exit ticket","text":"Mistake 1: running scripts before the DOM exists. A <script> in <head> without defer executes before <body> is parsed, so every querySelector returns null. Put scripts at the end of <body> or add defer. Mistake 2: using innerHTML for user-supplied text. innerHTML parses its input as HTML, so a user who types <img src=x onerror=…> runs code in your page; textContent is immune. Exit ticket: (Q1) What is the DOM — the HTML file, or something else? (A1: a live in-memory tree the browser builds from the HTML; JavaScript edits the tree and the browser repaints.) (Q2) You want clicking a card to highlight it via a CSS class .selected. Which one line inside the click handler does it, without touching style properties in JS? (A2: card.classList.toggle(''selected'') — the appearance stays defined in CSS.)"}
   ]}',
   null, 15),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"A flex row should have its first item on the left edge, its last on the right, and the rest spread evenly. Which declaration on the container?","options":["align-items: stretch;","justify-content: space-between;","justify-content: center;","gap: auto;"],"answer":1,"explanation":"space-between pins the ends and distributes the remaining space between items. center groups everything in the middle; align-items works on the cross axis; gap takes a length, not auto."},
      {"prompt":"Your three-card flex row overflows horizontally on narrow screens. The most direct fix is:","options":["flex-wrap: wrap; on the container","position: absolute; on the cards","Larger padding on the cards","Removing the viewport meta tag"],"answer":0,"explanation":"flex-wrap: wrap lets items break onto new lines when they no longer fit. Removing the viewport tag makes phones fake a desktop width — the opposite of a fix."},
      {"prompt":"What does @media (max-width: 600px) { … } mean?","options":["Apply these rules only while the viewport is 600px wide or narrower","Limit every element to 600px","Apply these rules only on screens wider than 600px","Load a different HTML file on phones"],"answer":0,"explanation":"A max-width media query activates its rules at or below the breakpoint — the standard way to adapt a layout for small screens with the same HTML."},
      {"prompt":"Which declaration will throw an error two lines later?","options":["let total = 5; total = 8;","const rate = 0.2; rate = 0.25;","let name = \"Ada\"; name = \"Grace\";","const greeting = \"hi\"; console.log(greeting);"],"answer":1,"explanation":"const forbids reassignment, so rate = 0.25 throws a TypeError. let allows reassignment, and merely reading a const is fine."},
      {"prompt":"function triple(n) { return n * 3; } — what does console.log(triple(4)) print?","options":["n * 3","12","triple(4)","undefined"],"answer":1,"explanation":"The call passes 4 into n, the function returns 4 * 3 = 12, and console.log prints it."},
      {"prompt":"Which line correctly makes sayHi run on every click of btn?","options":["btn.addEventListener(''click'', sayHi());","btn.addEventListener(sayHi, ''click'');","btn.addEventListener(''click'', sayHi);","btn.onclick = ''sayHi'';"],"answer":2,"explanation":"Pass the event name, then the function itself. With parentheses, sayHi runs once immediately; the argument order in option b is reversed; a string is not a function."},
      {"prompt":"A user typed text into an input and you display it on the page. Why prefer element.textContent over element.innerHTML?","options":["textContent is shorter to type","innerHTML cannot display text","textContent treats the value as plain text, so typed HTML or scripts cannot execute","There is no difference"],"answer":2,"explanation":"innerHTML parses its input as HTML, which lets malicious input run code in your page. textContent renders it inertly as text — the safe default for anything user-supplied."}
   ]}',
   null, 10),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"semantic HTML","translation":"choosing tags by what content means (nav, article, footer) rather than how it looks, so browsers, search engines, and screen readers understand the page","example":"Because the page used semantic HTML, her screen reader jumped straight to <main> and skipped the navigation."},
      {"term":"selector","translation":"the pattern in a CSS rule that decides which elements the declarations apply to — an element name (p), a class (.card), or an id (#title)","example":"The selector .card h2 styles only headings inside cards, leaving every other heading alone."},
      {"term":"box model","translation":"the four nested layers of every element on a page — content, padding, border, margin — that together determine its size and spacing","example":"The DevTools box-model diagram showed the mystery gap was margin on the image, not padding on its container."},
      {"term":"flexbox","translation":"a CSS layout system (display: flex) where a container arranges its children in rows or columns and handles spacing, alignment, and wrapping for you","example":"Switching the gallery to flexbox with flex-wrap: wrap made it collapse from three columns to one on phones with no extra code."},
      {"term":"DOM","translation":"the Document Object Model — the live tree of objects a browser builds from your HTML, which JavaScript reads and edits to change the page without reloading","example":"The script updated the DOM with textContent, and the new score appeared on screen instantly."},
      {"term":"event listener","translation":"a function you register with addEventListener so the browser runs it each time a specific event (click, input, submit) happens on an element","example":"An event listener on the button toggled the dark class on <body> every time it was clicked."}
   ]}',
   'Say these aloud in sentences about your own project — being able to name what you are doing (I am toggling a class on a DOM node) is half of debugging.', 10),
  (11, 'Applied project: your personal page', 'writing',
   '{"sections":[
      {"heading":"The brief","text":"Build a one-file personal page — index.html with its CSS in a <style> tag and its JavaScript in a <script> tag — that a stranger could read to learn who you are. It must contain: (1) a short bio (two or three honest sentences under a <h1> with your name); (2) a photo or avatar image with meaningful alt text; (3) a project list — at least three things you have made or want to make, as a <ul>, each item naming the project and one sentence about it; (4) one working button that does something visible using an event listener — a dark-mode toggle, a show-more-about-me reveal, or a visitor counter. Structure it with real landmarks: <header>, <main>, <footer>. This is the page where everything from lessons 2 through 8 meets."},
      {"heading":"Milestones: from guided to independent","text":"Milestone 1 (guided — follow the recipe): copy the skeleton and confirm it renders: <!doctype html>, <html lang=\"en\">, <head> with charset, viewport meta tag, and <title>, then <header> with your <h1>, <main>, and <footer>. Milestone 2 (guided): add the bio paragraph, the image with alt text, and the project <ul> inside <main>; check that the page reads sensibly with zero CSS. Milestone 3 (semi-guided): style it — a system-ui font stack, line-height 1.6, max-width around 640px with margin auto to center the column, and your own color pair for background and text. Lay out at least one part with flexbox (the header, or the project list as wrapping cards). Milestone 4 (independent): design and wire your button. Decide the behavior yourself, write the HTML, the CSS class it flips or the text it changes, and the addEventListener call — no recipe this time. Milestone 5 (independent polish): resize the window from phone-width to full screen and fix anything that overflows or squeezes; then show the page to one real person and make one change based on what confused them."},
      {"heading":"Self-check rubric","text":"Score each line 0 (missing), 1 (works), or 2 (works and you can explain how). Structure: landmarks present and the heading order is sane — one <h1>, then <h2>s, no skipped levels. Content: bio, photo, and three-item project list all present. Presentation: styles live in CSS, not scattered in HTML attributes; text column is readable on both a narrow and a wide window. Behavior: the button works from a mouse click AND from the keyboard (Tab to it, press Enter — free if you used a real <button>). Accessibility basics: every image has honest alt text; every form input (if you added any) has a paired <label>; text color has clear contrast with the background (dark gray on white passes, light gray on white fails); the page still makes sense if you disable CSS for a moment. Safety: any text that could ever come from a user reaches the page through textContent, never innerHTML. 10 or more out of 12: publish it and send someone the file. Below 10: the lines you scored 0 tell you exactly which lesson to revisit."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"A browser receives this and nothing else: ```<h1>Menu</h1><p>Soup of the day</p>```. What does the user see?","options":["Nothing, because there is no CSS","A large bold heading Menu above a normal paragraph, styled by browser defaults","An error page demanding a stylesheet","Raw HTML source text"],"answer":1,"explanation":"HTML alone renders fine: the browser''s default stylesheet makes h1 large and bold and p normal. CSS is for changing those defaults, not enabling rendering."},
      {"prompt":"```<img src=\"team.jpg\">``` — a reviewer flags this line. The correct fix is:","options":["Add width and height","Add alt text describing the image, e.g. alt=\"The five-person team on launch day\"","Rename the file to team-photo.jpg","Wrap it in a <div>"],"answer":1,"explanation":"The image has no alt attribute, so screen-reader users get nothing (or the filename). Meaningful alt text is the accessibility fix; the other options change nothing for assistive tech."},
      {"prompt":"```.box { width: 200px; padding: 10px; border: 2px solid; box-sizing: border-box; }``` — how wide does .box render?","options":["200px","224px","212px","176px"],"answer":0,"explanation":"border-box makes the declared width include padding and border, so the box renders exactly 200px wide (the content area shrinks to 176px). Without border-box it would be 224px."},
      {"prompt":"Which elements does the selector ```.alert p``` style?","options":["Paragraphs that have class=\"alert\"","All paragraphs and all elements with class=\"alert\"","Paragraphs inside any element with class=\"alert\"","The first paragraph on the page"],"answer":2,"explanation":"The space makes it a descendant selector: p elements anywhere inside a .alert element. Paragraphs that themselves carry the class would be p.alert, with no space."},
      {"prompt":"```.row { display: flex; justify-content: center; gap: 12px; }``` — what layout results for the row''s children?","options":["They stack vertically with 12px left margins","They line up in a row, grouped in the horizontal center, with 12px between each","They spread to the far edges of the container","They overlap in the center"],"answer":1,"explanation":"display: flex puts children in a row, justify-content: center groups them mid-container, and gap inserts 12px between neighbors. Edge-pinning would be space-between."},
      {"prompt":"```let count = 0;\nfunction add() { count += 2; }\nadd();\nadd();\nconsole.log(count);``` — what prints?","options":["0","2","4","An error, because count is const"],"answer":2,"explanation":"count starts at 0 and each call adds 2; two calls make 4. It was declared with let, so reassignment is legal."},
      {"prompt":"```btn.addEventListener(''click'', () => {\n  msg.textContent = ''Saved!'';\n});``` — when does Saved! appear on the page?","options":["Immediately when the script loads","Each time btn is clicked","Only the first time btn is clicked","Never — textContent is read-only"],"answer":1,"explanation":"The arrow function is registered as a click handler, so it runs on every click, and assigning textContent updates the DOM each time. Nothing runs at load; only the registration happens then."},
      {"prompt":"```const el = document.querySelector(''#status'');\nel.classList.toggle(''ok'');``` — assuming an element <p id=\"status\"> exists and does not have the class, what happens?","options":["A new element is created","The paragraph''s text becomes ok","The class ok is added to the paragraph, activating any .ok CSS rule","The id changes from status to ok"],"answer":2,"explanation":"querySelector finds the element by id, and classList.toggle adds the class since it was absent — appearance changes come from whatever the .ok rule says in CSS. Run again, it would remove it."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0002-0000-4000-8000-000000000003' and l.position = v.pos
);
