-- Technology curriculum: Digital Literacy (foundations).
-- A vendor-neutral, hands-on introduction to how computers and the internet
-- work, professional search, online safety, file management, and spreadsheets,
-- capped by an applied personal security audit. Fixed UUIDs and guarded
-- inserts make the file idempotent: safe to re-run at any time.

-- ============ Technology — Digital Literacy ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, school, prerequisite_ids)
values (
  'bbbb0002-0000-4000-8000-000000000001',
  'en', null,
  'Digital Literacy',
  'Build the practical foundations of modern computing: how hardware, software and the internet actually work, how to search and evaluate information like a professional, and how to keep your accounts, files and data safe. Finishes with a hands-on audit of your own digital security.',
  null, 'foundations', 1, true, 'technology', '{}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0002-0000-4000-8000-000000000001', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"Which of the following is hardware rather than software?","options":["A web browser","The CPU","The operating system","A PDF file"],"answer":1,"explanation":"Hardware is the physical machinery; the CPU is a chip you could hold in your hand, while browsers, operating systems and files are all software. Covered in Lesson 2: How computers actually work."},
      {"prompt":"What does DNS do when you visit a website?","options":["It encrypts your traffic","It translates a domain name like example.com into an IP address","It stores a copy of your files in the cloud","It scans the site for viruses"],"answer":1,"explanation":"DNS is the internet''s address book: it turns human-friendly names into the numeric IP addresses computers route traffic to. Covered in Lesson 3: The internet explained."},
      {"prompt":"The padlock icon (HTTPS) in your browser''s address bar means:","options":["The site is honest and trustworthy","Your connection to the site is encrypted","The site contains no advertising","The site has been verified by a government"],"answer":1,"explanation":"HTTPS only guarantees that traffic between you and the site is encrypted in transit; a scam site can have a padlock too. Covered in Lesson 3, and revisited in Lesson 6 on staying safe."},
      {"prompt":"Which search operator restricts results to a single website?","options":["Quotation marks around a phrase","site:","filetype:","A minus sign before a word"],"answer":1,"explanation":"site:example.com limits results to that domain; quotes force an exact phrase, filetype: filters by format, and minus excludes a term. Covered in Lesson 4: Search like a professional."},
      {"prompt":"You land on an unfamiliar news site making a dramatic claim. What is the most professional first move?","options":["Read the site''s About page to see how it describes itself","Read three more of its articles to judge the writing quality","Open new tabs and check what independent sources say about the site and the claim","Judge the site by how modern its design looks"],"answer":2,"explanation":"This is lateral reading: fact-checkers leave the site and consult independent sources instead of trusting a site''s self-description or looks. Covered in Lesson 4."},
      {"prompt":"Which of these is the strongest password practice?","options":["A short password with symbols, like P@ss1!","A long, unique passphrase stored in a password manager","Your pet''s name plus your birth year","One very strong password reused on every account"],"answer":1,"explanation":"Length and uniqueness beat clever symbol substitutions, and a manager makes unique passphrases practical. Covered in Lesson 6: Passwords, phishing and staying safe online."},
      {"prompt":"The 3-2-1 backup rule says you should keep:","options":["3 passwords, 2 devices, 1 cloud account","3 copies of your data, on 2 different types of storage, with 1 copy kept off-site","3 folders, 2 subfolders, 1 archive","3 backups per day, 2 per week, 1 per month"],"answer":1,"explanation":"Three copies, two different media, one off-site (for example, in the cloud) protects you against theft, fire and drive failure at once. Covered in Lesson 7: Files, folders, cloud storage and backups."},
      {"prompt":"In a spreadsheet, every formula begins with which character?","options":["=","\"","#","@"],"answer":0,"explanation":"The equals sign tells the spreadsheet to calculate rather than display text, as in =SUM(B2:B7). Covered in Lesson 8: Spreadsheets."}
   ]}',
   null, 10),
  (2, 'How computers actually work (hardware, software, OS)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to tell hardware from software, name the job of each core component (CPU, RAM, storage), and explain what the operating system does when you open an app. Warm-up from the diagnostic quiz: which layer of a computer manages the hardware on behalf of every app you run? (Answer: the operating system.) If you answered CPU or browser, this lesson will straighten that out."},
      {"heading":"The hook: is your slow laptop broken?","text":"A friend says their laptop has become unbearably slow and asks if they should buy a new one. To answer that, you need the basic split. Hardware is everything physical: the CPU (the processor that executes instructions), RAM (fast, temporary working memory that empties when power is cut), storage (the SSD or hard drive that keeps files permanently), plus the screen, keyboard and network chip. Software is the instructions that run on that hardware: apps like a browser or a spreadsheet, and beneath them the operating system (Windows, macOS, Linux, Android, iOS), which shares the hardware out among apps, draws the interface, and manages files, users and security."},
      {"heading":"Walkthrough: what happens when you open a photo","text":"You double-click a photo. The OS looks up which app handles that file type and loads that app''s instructions from storage into RAM, because the CPU can only work at speed on things held in RAM. The CPU executes the app''s instructions, the app asks the OS to read the photo file from storage into RAM too, and the graphics hardware draws the decoded image on screen. Now the slow-laptop question: if it is slow only with many apps and browser tabs open, RAM is likely full and the OS is swapping to much slower storage — closing apps or adding RAM helps. If it is slow even opening one small file, an aging hard drive or a background program hogging the CPU is more likely. Diagnosis before purchase."},
      {"heading":"Your turn","text":"1) Classify each as hardware, application software, or operating system: SSD, Android, a video editor, RAM. (Answer: hardware, OS, application, hardware.) 2) You have 47 browser tabs open and the machine crawls; which component is most likely exhausted? (Answer: RAM.) 3) True or false: a file you saved yesterday lives in RAM overnight. (Answer: false — RAM empties at power-off; the file lives in storage.) 4) Which component actually executes the instructions of a running program? (Answer: the CPU.) 5) Your phone and your laptop both have an OS — name the OS on each of your own devices. (Expected: e.g. Android or iOS on the phone; Windows, macOS or Linux on the laptop.)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: RAM and storage are the same thing because both are measured in gigabytes. They are not — RAM is a fast temporary workbench, storage is the permanent filing cabinet, and a machine can have plenty of one and too little of the other. Misconception 2: the operating system is the computer. The OS is replaceable software; the same laptop can run Windows or Linux. Exit ticket: (1) In one sentence, what does the OS do when you launch an app? (Answer: it loads the app''s instructions from storage into RAM and gives it CPU time, screen access and file access.) (2) A program is described as software you can touch — what is wrong with that sentence? (Answer: software is instructions, not a physical object; anything you can touch is hardware.)"}
   ]}',
   'Tip: when you explain tech to someone, lead with the analogy (workbench vs filing cabinet), then attach the jargon (RAM vs storage).', 14),
  (3, 'The internet explained (IP, DNS, HTTP, browsers)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to trace what happens between typing an address and seeing a page: IP addresses, DNS, HTTP/HTTPS, and the browser''s job. Warm-up from Lesson 2: when your browser loads a page, where does the page''s data have to be before the CPU can work on it — RAM or long-term storage? (Answer: RAM; the CPU works on data in memory.)"},
      {"heading":"The hook: three seconds, four technologies","text":"You type example.com and press Enter; a page appears in under three seconds. Four things just cooperated. First, every device on the internet has an IP address, a numeric label such as 93.184.216.34, and data travels in small packets addressed to it. Second, because humans remember names rather than numbers, DNS (the Domain Name System) acts as the internet''s address book, translating example.com into an IP address. Third, your browser and the server speak HTTP, a request-and-response language: your browser requests a page, the server responds with it. HTTPS is the same conversation wrapped in encryption so that networks in between cannot read or alter it. Fourth, the browser itself turns the server''s response — HTML text, styles, images, scripts — into the page you see."},
      {"heading":"Walkthrough: one page load, step by step","text":"Step 1: you enter https://example.com/menu. Step 2: your device asks a DNS server for example.com and gets back an IP address. Step 3: your browser opens an encrypted HTTPS connection to that IP and sends a request meaning GET /menu. Step 4: the server replies with the HTML for the menu page. Step 5: the browser reads the HTML, requests the images and styles it references, and renders everything. Read the URL like a pro: https is the protocol, example.com the domain, /menu the path on that server. And note what the padlock does and does not mean: it certifies the connection is encrypted to that domain — it says nothing about whether the people behind the domain are honest."},
      {"heading":"Your turn","text":"1) In https://city-library.org/events/july, name the protocol, the domain and the path. (Answer: https; city-library.org; /events/july.) 2) What does a DNS lookup take in and give back? (Answer: a domain name in, an IP address out.) 3) A café Wi-Fi owner could read your traffic to a site — under HTTP or HTTPS? (Answer: HTTP; HTTPS encrypts it in transit.) 4) One website will not load, but every other site works fine on your device. Is your internet connection the most likely problem? (Answer: no — your connection is working; the likelier causes are that site''s server or its DNS entry.) 5) True or false: the padlock icon proves a shop is legitimate. (Answer: false — it proves encryption, not honesty; scam sites use HTTPS too.)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: the web and the internet are the same thing. The internet is the global network that moves packets; the web (HTTP sites in a browser) is one service on it, alongside email, video calls and games. Misconception 2: DNS stores websites. DNS stores no pages at all — it only maps names to IP addresses; the pages live on web servers. Exit ticket: (1) Put these in the order they happen when you visit a site: HTTP request, DNS lookup, page rendering, server response. (Answer: DNS lookup, HTTP request, server response, page rendering.) (2) In one sentence, what extra protection does HTTPS add over HTTP? (Answer: it encrypts the conversation so networks in between cannot read or tamper with it.)"}
   ]}',
   'Tip: read URLs right to left around the domain — the registered domain just before the first slash is who you are really talking to.', 13),
  (4, 'Search like a professional (operators, evaluating sources, spotting misinformation)', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to build precise search queries with operators, evaluate an unfamiliar source by reading laterally, and spot the standard signatures of misinformation. Warm-up from Lesson 3: when you click a search result, what system translates the result''s domain name into an address your device can reach? (Answer: DNS.)"},
      {"heading":"The hook: 2,400,000 results, 20 minutes","text":"You need reliable numbers on teen screen time for a presentation due tomorrow, and a naive search returns millions of results of wildly mixed quality. Professionals do two things differently. First, they search with keywords, not sentences: screen time teenagers statistics 2026, not what is the average screen time. Second, they use operators to cut the pile: quotation marks force an exact phrase (\"screen time\"); site: limits results to one domain (site:who.int); filetype: finds documents (filetype:pdf); a minus sign excludes a word (jaguar -car); OR accepts alternatives (teens OR adolescents). Operators combine, and each one you add shrinks and sharpens the results."},
      {"heading":"Walkthrough: from vague need to verified source","text":"Query 1: \"screen time\" teenagers site:who.int filetype:pdf — official health-organization documents only. Suppose it returns a promising report, but you also find a viral article claiming screens cause a 40 percent drop in attention. Now evaluate laterally: instead of trusting that article''s About page or polished design, open new tabs and search the publication''s name, the author, and the claim itself. You find the 40 percent figure traces to a small unpublished survey misquoted by an ad-funded site — while the original report is peer-reviewed with named authors, a publication date and a methods section. Signals that raise trust: primary sources linked, dates, named authors, corrections policy. Signals of misinformation: outrage-bait headlines, no sources, screenshots of screenshots, urgency to share before you think."},
      {"heading":"Your turn","text":"1) Write a query for official PDF reports about food waste from the UN. (Answer: food waste site:un.org filetype:pdf — wording may vary; the two operators are what matter.) 2) You get recipe results while researching the Python language — fix the query. (Answer: add an exclusion or context, e.g. python -snake tutorial, or \"python programming\".) 3) Force results containing the exact phrase circular economy. (Answer: put it in quotation marks: \"circular economy\".) 4) A stranger''s post cites a study with no link. List two lateral-reading moves. (Answer: search the study''s title or author to find the original; check whether independent, credible outlets report the same finding.) 5) Which URL more likely hosts the primary source for national employment statistics: a government statistics agency domain, or a blog aggregating job tips? (Answer: the government statistics agency — it produces the data; the blog is at best secondary.)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: the first result is the most trustworthy. Ranking mixes relevance, popularity and advertising — the top spots are often paid placements, not verdicts on truth. Misconception 2: a professional design means a reliable site. Templates make any site look credible in an afternoon; judge sources by their evidence and reputation elsewhere, not their looks. Exit ticket: (1) What does the query budget travel site:reddit.com -flights do? (Answer: finds budget-travel results only on reddit.com, excluding those mentioning flights.) (2) In one sentence, what is lateral reading? (Answer: leaving a site to check what independent sources say about it and its claims, instead of judging it from the inside.)"}
   ]}',
   'Tip: operators work in most search engines, but check each engine''s syntax page — support for minus and filetype varies.', 13),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"Your document open on screen suddenly vanishes when the power cuts out, but the saved version from an hour ago survives. Which explains this?","options":["The CPU deleted the file","Unsaved work lives in RAM, which empties without power; saved work lives in storage","The operating system crashed and took the file with it","DNS failed during the power cut"],"answer":1,"explanation":"RAM is volatile working memory; storage is permanent. Saving copies your work from RAM to storage — which is why you save."},
      {"prompt":"Which component executes the instructions of every running program?","options":["RAM","The SSD","The CPU","The router"],"answer":2,"explanation":"The CPU is the processor that carries out instructions; RAM holds them ready, the SSD stores them long-term, and a router moves network traffic."},
      {"prompt":"Which of these is an operating system?","options":["A web browser","Windows 11","A spreadsheet app","Wi-Fi"],"answer":1,"explanation":"Windows 11 manages hardware on behalf of all apps. Browsers and spreadsheets are applications that run on an OS; Wi-Fi is a wireless networking technology."},
      {"prompt":"An IP address is best described as:","options":["A website''s password","The numeric network address that identifies a device so packets can reach it","A type of encrypted file","The name you type into a browser"],"answer":1,"explanation":"IP addresses are the numeric labels the internet routes traffic to; the names you type are domains, which DNS translates into IP addresses."},
      {"prompt":"You type a site''s name and press Enter. Which happens first?","options":["The server sends the page","The browser renders the page","A DNS lookup turns the name into an IP address","The images are downloaded"],"answer":2,"explanation":"Nothing can be requested until the browser knows the server''s IP address, so the DNS lookup comes first, then request, response and rendering."},
      {"prompt":"What does the query \"renewable energy\" site:iea.org filetype:pdf return?","options":["Any page mentioning renewable or energy anywhere on the web","PDF documents on iea.org containing the exact phrase renewable energy","Pages about the IEA on other websites","Only pages published this year"],"answer":1,"explanation":"Quotes force the exact phrase, site: restricts to the iea.org domain, and filetype:pdf keeps only PDF documents. The operators stack."},
      {"prompt":"A slick website you have never heard of claims a common food causes cancer. The most professional check is to:","options":["Trust it — the article has a confident, scientific tone","See if the site''s About page mentions experts","Search independent, credible sources for the claim and for the site''s reputation","Share it and let your friends judge"],"answer":2,"explanation":"That is lateral reading: verification comes from independent sources, not from the site''s own tone or self-description. Design and confidence are cheap."}
   ]}',
   null, 9),
  (6, 'Passwords, phishing & staying safe online', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to build passwords that survive modern attacks, recognize phishing before you click, and switch on two-factor authentication where it counts. Warm-up from Lesson 4: a message urges you to act before you think and cites no sources — which two misinformation signatures is it showing? (Answer: manufactured urgency and absence of evidence — the same pair powers most scams.)"},
      {"heading":"The hook: the email that looks exactly right","text":"An email arrives: Your account will be suspended in 24 hours. Verify now. The logo is perfect, the tone is official, the button is right there. This is phishing — an attempt to trick you into handing over credentials or installing malware — and it works because it manufactures urgency. Your defenses are three layers. One: passwords with length and uniqueness — a four-word passphrase like plum-orbit-window-taxi beats P@ss1!, and no password is reused across accounts, because attackers take passwords stolen from one breached site and try them everywhere (credential stuffing). Two: a password manager, which generates and remembers unique passwords so you only memorize one strong master passphrase. Three: two-factor authentication (2FA), which requires something you have (an authenticator app''s codes or a hardware key) in addition to something you know, so a stolen password alone is not enough."},
      {"heading":"Walkthrough: dissecting a phish in 30 seconds","text":"Take that suspension email apart. Check 1 — the real sender address: it says the name of your bank, but the address is alerts@secure-bank-notify.example-mail.com, not the bank''s own domain. Check 2 — hover over (do not click) the button: the link''s domain is not the bank''s either. Check 3 — the pressure: legitimate organizations rarely threaten a 24-hour deadline out of nowhere. Check 4 — the ask: it wants you to enter credentials via its link. The professional response: never authenticate through a link you were sent. Open the bank''s app or type its address yourself; if something is genuinely wrong, it will be visible there. The same anatomy applies to texts about parcel deliveries, calls from tech support, and messages from a boss urgently needing gift cards."},
      {"heading":"Your turn","text":"1) Rank strongest to weakest: (a) river-magnet-pillow-seven, (b) Summer2026!, (c) 9k#Q2vB!mZ4$pL7w stored in a password manager. (Answer: c, then a, then b — c has maximum length and randomness with zero memorization cost; a is strong and memorable; b follows a guessable pattern.) 2) A text says your parcel is held, tap the link and pay a small fee. Two red flags? (Answer: unexpected demand for payment via a sent link; urgency — verify in the courier''s own app or site instead.) 3) Your email password appears in a data breach and you reused it on three sites. First moves? (Answer: change it everywhere it was used, making each new password unique, and enable 2FA — starting with the email account itself.) 4) Which 2FA method resists a thief who has hijacked your phone number: SMS codes or an authenticator app? (Answer: the authenticator app — SMS codes go wherever the number goes, which is what SIM-swap attacks exploit.) 5) Why does one strong reused password fail against credential stuffing? (Answer: one breach anywhere unlocks every account that shares it.)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: symbol-stuffed short passwords are stronger than long plain ones. Cracking difficulty grows with length far faster than with symbols, and attackers'' software already tries the classic substitutions like @ for a. Misconception 2: I am not important enough to be targeted. Most attacks are automated and aimed at everyone; your email account alone is valuable because password resets for all your other accounts flow through it. Exit ticket: (1) In one sentence, what does 2FA add over a password? (Answer: a second, different kind of proof — something you have — so a stolen password alone cannot open the account.) (2) The safest way to respond to any log in to fix a problem message is what? (Answer: ignore the sent link and go to the service directly via its official app or a typed address.)"}
   ]}',
   'Tip: the single highest-impact upgrade for most people is 2FA on their primary email account — start there.', 15),
  (7, 'Files, folders, cloud storage & backups', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to organize files so you can find them in seconds, explain the difference between cloud sync and a real backup, and set up a 3-2-1 backup for anything you cannot afford to lose. Warm-up from Lesson 6: your cloud storage account guards years of files — which two protections from the last lesson should it have? (Answer: a unique passphrase from your password manager, and 2FA.)"},
      {"heading":"The hook: the thesis in the Downloads folder","text":"A student keeps every version of their thesis in Downloads: thesis.docx, thesis2.docx, thesisFINAL.docx, thesisFINALreal.docx. One spilled coffee later, all of it is gone. Two habits would have saved them. First, structure: files live in folders, folders form a hierarchy, and a file''s path — Documents/Thesis/drafts/2026-07-10_thesis_v3.docx — tells you exactly where and what it is. Name files so they sort and search well: dates as YYYY-MM-DD so alphabetical order is chronological order, real words instead of final2, and extensions left visible (.docx, .pdf, .jpg) because the extension tells you and the OS what kind of file it is. Second, redundancy: any file that exists in exactly one place is one accident away from not existing."},
      {"heading":"Walkthrough: sync is not backup, and 3-2-1","text":"Cloud storage that syncs a folder across devices feels like a backup, but it mirrors your mistakes: delete the file on your laptop, and the sync service faithfully deletes it in the cloud and on your other devices too. It also mirrors damage — if ransomware scrambles your files, the scrambled versions sync. (Many services keep a trash folder and version history, which softens this — learn where yours are.) A real backup is a separate copy your everyday actions do not touch. The professional standard is 3-2-1: three copies of the data, on two different types of storage, one of them off-site. Worked example for the thesis: copy 1 is the working file on the laptop; copy 2 is an automatic backup to an external drive at home; copy 3 is in a cloud service — off-site, so a burglary or fire that takes the laptop and the drive still leaves a copy. Test the plan once: actually restore one file from each backup."},
      {"heading":"Your turn","text":"1) Rewrite the file name finalreport(2).docx following this lesson''s conventions for a client report finished 2026-07-13. (Answer: something like 2026-07-13_client-report_v2.docx — date first in YYYY-MM-DD, descriptive words, version explicit.) 2) You delete a synced file on your phone; what happens on your laptop, and what feature might still save you? (Answer: it is deleted there too; the service''s trash or version history may allow recovery.) 3) Design a 3-2-1 setup for a lifetime of family photos. (Answer: e.g. photos on the computer, an external drive backup at home, and a cloud backup off-site — three copies, two media, one off-site.) 4) Which counts as off-site: an external drive in the same desk drawer as the laptop, or a cloud copy? (Answer: the cloud copy; the drawer shares every fire, flood and burglary with the laptop.) 5) What does the .csv extension on data-export.csv tell you? (Answer: the file''s type — plain-text comma-separated data that a spreadsheet can open.)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: my files are in the cloud, so they are backed up. Sync replicates deletions and corruption; only a separate copy insulated from your daily actions (or explicit version history) is a backup. Misconception 2: emptying the trash is the same as organizing. A searchable structure with consistent names saves more time than deleting ever will — storage is cheap, your time is not. Exit ticket: (1) Recite the 3-2-1 rule from memory. (Answer: three copies, two different types of storage, one copy off-site.) (2) Why does naming dates YYYY-MM-DD beat naming them 13-07-2026? (Answer: alphabetical sorting then matches chronological order, and the format is unambiguous internationally.)"}
   ]}',
   'Tip: schedule backups to run automatically — a backup that depends on you remembering it is a wish, not a system.', 13),
  (8, 'Spreadsheets: formulas, sorting, simple charts', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will be able to write basic formulas, use relative and absolute cell references, sort data without destroying it, and choose a sensible chart. Warm-up from Lesson 7: before building the budget spreadsheet below, where should the file live and how should it be protected? (Answer: in a sensibly named folder path with a dated file name, covered by your 3-2-1 backup.)"},
      {"heading":"The hook: the club budget that adds itself","text":"You volunteer to manage a small club''s budget. A spreadsheet is a grid: columns have letters, rows have numbers, and each cell has an address like B2 — a cell reference. Column A holds item names (Hall rental, Snacks, Prizes...), column B holds costs (B2 down to B7). The magic is that cells can contain formulas: type =SUM(B2:B7) in B8 and it displays the total of the range B2 through B7. Every formula starts with = — without it, the spreadsheet treats your typing as mere text. Change any cost and the total updates itself; that live recalculation is the entire point of spreadsheets over paper."},
      {"heading":"Walkthrough: references, filling, sorting, charting","text":"Add column C for cost including 8 percent tax. In C2 write =B2*1.08 and drag the fill handle down: the reference adjusts row by row (C3 becomes =B3*1.08) because plain references are relative. Better: put the tax rate itself in F1 and write =B2*(1+$F$1). The dollar signs make $F$1 an absolute reference — it stays pinned to F1 wherever the formula is copied, so changing the rate in one cell updates every row. Other workhorses: =AVERAGE(B2:B7), =MIN(B2:B7), =MAX(B2:B7), =COUNT(B2:B7). Sorting: to see the priciest items first, select the entire table (headers included) and sort by the cost column descending — selecting only column B would reorder the numbers while the names stay put, silently scrambling which cost belongs to which item. Charts: bar charts compare categories (cost per item), line charts show change over time (spending per month), and pie charts show shares of a whole — legible only with a handful of slices."},
      {"heading":"Your turn","text":"1) Write the formula for the total of cells D2 through D12. (Answer: =SUM(D2:D12).) 2) You type SUM(B2:B7) into a cell and see the literal text instead of a number — why? (Answer: no leading equals sign, so it is treated as text; =SUM(B2:B7) fixes it.) 3) =B2*$F$1 is copied from C2 down to C5 — what does it become? (Answer: =B5*$F$1; the relative part B2 slides to B5, the absolute $F$1 stays.) 4) You want items ordered cheapest first without corrupting the table — describe the safe procedure. (Answer: select the whole table including headers, then sort ascending by the cost column so entire rows move together.) 5) Pick the chart: (a) monthly membership over a year, (b) comparing six items'' costs, (c) share of budget by category. (Answer: a — line, b — bar, c — pie.) 6) Which formula finds the average cost in B2:B7? (Answer: =AVERAGE(B2:B7).)"},
      {"heading":"Misconceptions and exit ticket","text":"Misconception 1: if the total looks wrong, type the correct number over it. Overwriting the formula with a constant kills recalculation — the total is now frozen and silently wrong forever after the next edit; fix the inputs or the formula instead. Misconception 2: sorting one selected column sorts the table. It reorders that column alone and corrupts every row''s meaning; always select the whole table. Exit ticket: (1) What is the difference between B2 and $B$2 when a formula is copied? (Answer: B2 shifts relative to where the formula moves; $B$2 stays locked on that exact cell.) (2) Why must a formula begin with =? (Answer: the equals sign tells the spreadsheet to calculate the expression rather than display it as text.)"}
   ]}',
   'Tip: before sorting anything, click a single cell inside the table and let the app auto-select the whole region — then check it grabbed your headers correctly.', 15),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"An email from your bank warns your account is locked and provides a login link. The safest response is to:","options":["Click the link quickly before the account is closed","Reply asking if the email is genuine","Open the bank''s official app or type its address yourself and check there","Forward it to friends to see if they got it too"],"answer":2,"explanation":"Never authenticate through a link you were sent. Going to the service directly through its app or a typed address defeats the phishing link entirely."},
      {"prompt":"Which second factor keeps working against an attacker who has taken over your phone number?","options":["SMS text codes","An authenticator app on your device","A security question about your first pet","Email codes sent to an account with the same password"],"answer":1,"explanation":"Authenticator-app codes are generated on the device itself, so SIM-swapping the number does not capture them. SMS follows the number; the other options are weaker than 2FA."},
      {"prompt":"The main job of a password manager is to:","options":["Remove the need for passwords entirely","Generate and store a unique strong password for every account behind one master passphrase","Email you your passwords weekly","Share your passwords with trusted contacts"],"answer":1,"explanation":"Unique passwords per site defeat credential stuffing, and the manager makes uniqueness practical: you memorize one strong master passphrase and it handles the rest."},
      {"prompt":"You delete a report from a folder that syncs to the cloud. What most likely happens?","options":["The cloud copy survives untouched forever","The deletion syncs — the file disappears from the cloud and your other devices, though trash or version history may allow recovery","The file is automatically emailed to you","Sync pauses until you confirm"],"answer":1,"explanation":"Sync mirrors your actions, including deletions — which is why sync alone is not a backup. Trash and version history are the safety nets to know about."},
      {"prompt":"Which file name follows the conventions from this course best?","options":["FINALfinal2.docx","report.docx","2026-07-13_marketing-report_v2.docx","New Document (3).docx"],"answer":2,"explanation":"YYYY-MM-DD sorts chronologically, the descriptive name is searchable, and the version is explicit. The others say nothing about content, date or version."},
      {"prompt":"What does =AVERAGE(B2:B5) display?","options":["The sum of B2 and B5","The mean of the values in cells B2 through B5","The largest value in the range","The text AVERAGE(B2:B5)"],"answer":1,"explanation":"AVERAGE computes the mean of the range B2:B5. It would only show as literal text if the leading equals sign were missing."},
      {"prompt":"To sort a table of names and scores by score without corrupting it, you should:","options":["Select only the score column and sort it","Select the entire table so whole rows move together, then sort by the score column","Delete the names first","Retype the rows in the order you want"],"answer":1,"explanation":"Sorting one column reorders it alone, detaching every score from its name. Selecting the whole table keeps each row intact while rows change order."}
   ]}',
   null, 9),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"operating system (OS)","translation":"The software layer that manages a device''s hardware and files and lets applications run — for example Windows, macOS, Linux, Android or iOS.","example":"After the update, the operating system restarted before any of my apps could open."},
      {"term":"DNS (Domain Name System)","translation":"The internet''s address book: the system that translates human-friendly names like example.com into the numeric IP addresses computers actually connect to.","example":"The site was up, but a DNS problem meant our office computers could not translate its name into an address."},
      {"term":"phishing","translation":"A scam message — email, text or call — that impersonates a trusted organization to trick you into revealing passwords, paying money or installing malware.","example":"The phishing email copied the bank''s logo perfectly, but the sender''s address belonged to a completely different domain."},
      {"term":"two-factor authentication (2FA)","translation":"A login safeguard requiring a second proof besides your password — typically a code from an authenticator app or a hardware key — so a stolen password alone cannot open the account.","example":"The attacker had her password, but 2FA blocked the login because they could not produce the code from her authenticator app."},
      {"term":"cell reference","translation":"The address of a spreadsheet cell, like B2. Relative references (B2) shift when a formula is copied; absolute references ($B$2) stay locked to one cell.","example":"He used the absolute cell reference $F$1 for the tax rate so every copied formula pointed at the same cell."},
      {"term":"passphrase","translation":"A long password built from several words, such as river-magnet-pillow-seven — easier for a human to remember and far harder for software to crack than a short symbol-heavy password.","example":"She replaced her old eight-character password with a four-word passphrase generated by her password manager."}
   ]}',
   null, 8),
  (11, 'Applied project: your digital security audit', 'writing',
   '{"sections":[
      {"heading":"The project","text":"You will audit your own digital life — accounts, passwords, devices and backups — and write a one-page security report about yourself, for yourself. This applies everything from Lessons 6 and 7 to the accounts you actually own. Ground rules: work on your own accounts only, write the report in a private local document (never in a shared or public one), and record the state of things (weak, reused, no 2FA) rather than the passwords themselves — the report must never contain an actual password."},
      {"heading":"Step-by-step audit","text":"Step 1 — Inventory: list your 8-10 most important accounts, starting with primary email (it can reset all the others), then banking, cloud storage, social media, shopping. Step 2 — Passwords: for each account mark U (unique), R (reused somewhere) or W (weak or guessable); if you are not using a password manager, note that first. Step 3 — 2FA: for each account record whether two-factor authentication is on, and whether it uses an authenticator app or key (strong) or SMS (weaker). Step 4 — Devices: check that your phone and computer have a screen lock and that their operating systems are up to date. Step 5 — Backups: name the files you could not afford to lose and test them against the 3-2-1 rule — three copies, two types of storage, one off-site. Step 6 — Phishing exposure: search your email for the word verify and skim the results; note how many real phishing attempts you received recently and whether you would have caught them with Lesson 6''s checks."},
      {"heading":"Report template","text":"Write four short sections. 1. Inventory: a table of account, password status (U/R/W), and 2FA status (app/SMS/off). 2. Findings: the three most serious weaknesses you found, each in one sentence — for example, my primary email shares its password with two shopping sites and has no 2FA. 3. Fixes: for each finding, one concrete action with a deadline — e.g., tonight: enable app-based 2FA on email; this week: move all passwords into a manager, replacing reused ones as I go; this month: set up an automatic cloud backup for the photos folder. 4. Verification: how you will confirm each fix worked, such as performing a test restore of one file from the new backup, or logging in once to confirm the 2FA prompt appears."},
      {"heading":"Self-check rubric","text":"Score yourself 1-4 on each axis before calling the project done. Coverage: every account in your top 8-10 has a password status and a 2FA status recorded — no blanks. Honesty: reused and weak passwords are recorded as such; an audit that flatters you protects nobody. Prioritization: the fix list starts with primary email and anything holding money, not with the easiest items. Actionability: every fix has a deadline and a verification step, and at least one fix — ideally 2FA on your email — is already done before you finish the report. A total of 12 or higher means your audit would pass review at a professional help desk; below that, revisit the axis where you scored lowest."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"Your laptop crawls whenever you have many browser tabs and apps open, but runs fine with one app at a time. The most likely bottleneck is:","options":["The screen resolution","RAM — memory is full and the OS is swapping to slower storage","The keyboard drivers","DNS"],"answer":1,"explanation":"Many simultaneous programs compete for RAM; when it runs out, the OS pages to storage and everything slows. One-app-at-a-time performance being fine points away from the CPU or drive failing."},
      {"prompt":"A colleague says our website is down, but it loads fine on your phone''s mobile data and fails only on the office network. The most reasonable suspicion is:","options":["The website''s server has crashed","Something on the office network — its connection or its DNS — is failing","The site was deleted","Your phone is showing a cached fake"],"answer":1,"explanation":"If the server were down, it would fail everywhere. Failing on one network while succeeding on another points at that network''s connectivity or DNS."},
      {"prompt":"You need official PDF guidance on food safety from the European Food Safety Authority (efsa.europa.eu). The sharpest query is:","options":["food safety rules please","\"food safety\" site:efsa.europa.eu filetype:pdf","food safety -pdf","site:pdf food filetype:efsa"],"answer":1,"explanation":"Exact phrase plus site: plus filetype: stacks three operators to reach official PDFs directly. Option d has the operators'' values swapped; option c excludes what you want."},
      {"prompt":"A text from a courier says a parcel is held pending a small customs fee, with a payment link. You are actually expecting a parcel. Best move:","options":["Pay — the timing matches your real order","Reply with your card details instead of clicking","Check the delivery''s status in the courier''s official app or by typing its site address yourself","Click the link but pay only a small amount"],"answer":2,"explanation":"Expected-parcel timing is exactly what phishing exploits — it is a numbers game. Verifying through the official app or a typed address defeats the sent link regardless of whether the alert is real."},
      {"prompt":"A breach notification tells you a shopping site leaked your password — one you reused for your email. In what order do you act?","options":["Delete the shopping account and consider it handled","Change the email password first (unique, via a password manager), enable 2FA on email, then fix the shopping site and any other account sharing that password","Enable 2FA on the shopping site only","Wait to see whether anything bad happens"],"answer":1,"explanation":"Email is the master key — password resets for everything else flow through it — so it gets the new unique password and 2FA first, then every other account that shared the leaked password."},
      {"prompt":"Your entire photo collection lives on your laptop, which syncs to one cloud folder. Per the 3-2-1 rule, what is missing?","options":["Nothing — two copies is plenty","A third copy on a second type of storage, such as an automatic external-drive backup, keeping one copy off-site","Two more cloud accounts with the same password","Printing every photo"],"answer":1,"explanation":"Laptop plus synced cloud is two copies, and sync mirrors deletions. Adding an external-drive backup gives three copies on two media types, with the cloud copy serving as off-site."},
      {"prompt":"In a price list, C2 contains =B2*(1+$F$1) where F1 holds the tax rate. You copy C2 down to C10. What happens?","options":["Every row multiplies B2 by F1","Each row uses its own column-B price, and all rows share the single tax rate in F1","Each row uses a different tax rate from column F","The formulas turn into plain text"],"answer":1,"explanation":"B2 is relative, so it slides to B3...B10 row by row; $F$1 is absolute, so every copy stays pinned to the one tax-rate cell. Changing F1 updates the whole column."},
      {"prompt":"A shocking statistic is going viral, credited to a study nobody links. Applying this course, the strongest verification is to:","options":["Count how many people have shared it","Trust it if the graphic looks professionally designed","Search for the original study and check whether independent credible outlets report the same finding","Ask the person who shared it whether it is true"],"answer":2,"explanation":"That is lateral reading applied to a claim: trace it to its primary source and cross-check with independent reporting. Share counts and design quality are the two signals this course taught you to distrust."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0002-0000-4000-8000-000000000001' and l.position = v.pos
);
