-- Technology track: Python Foundations (course 2 of the tech pathway).
-- A complete beginner-to-confident-novice Python course built on
-- Carnegie-Mellon-style pedagogy: every lesson moves theory -> guided
-- practice -> independent practice, with worked examples traced line by
-- line, retrieval warm-ups, deliberate-practice tasks with expected
-- outputs, common-misconception debriefs, and exit tickets. Assessment is
-- layered: a diagnostic, two checkpoints, an applied project, and a final.
-- All content is original, targets Python 3.12+, and uses no external
-- libraries. Fixed UUIDs and guarded inserts make the file idempotent:
-- safe to re-run at any time.

-- ============ Python Foundations ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, school, prerequisite_ids)
values (
  'bbbb0002-0000-4000-8000-000000000002',
  'en', null,
  'Python Foundations',
  'Learn to program from zero in Python 3: variables, decisions, loops, lists, dictionaries, functions, and text, taught through traced worked examples and hands-on tasks. Finishes with an applied project where you build a complete word-guessing game.',
  null, 'foundations', 2, true, 'technology',
  '{bbbb0002-0000-4000-8000-000000000001}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0002-0000-4000-8000-000000000002', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"What does this line display when run?\n```python\nprint(\"Hello, world\")\n```","options":["Hello, world","print(\"Hello, world\")","Nothing — it stores the text","An error, because text needs no quotes"],"answer":0,"explanation":"print shows its message on the screen exactly as written between the quotes. If you were unsure, do not worry — Lesson 2 (Your first program) starts here."},
      {"prompt":"After these two lines, what is stored in x?\n```python\nx = 4\nx = x + 2\n```","options":["4","2","6","x + 2"],"answer":2,"explanation":"The second line reads the current value 4, adds 2, and stores 6 back into x. Variables and assignment are covered in Lesson 2."},
      {"prompt":"What is the value of the expression 7 > 3?","options":["7","3","True","False"],"answer":2,"explanation":"Comparisons produce a boolean: 7 is greater than 3, so the result is True. Booleans and if/elif/else are covered in Lesson 3."},
      {"prompt":"How many times does this loop print?\n```python\nfor i in range(3):\n    print(\"hi\")\n```","options":["2","3","4","Forever"],"answer":1,"explanation":"range(3) produces 0, 1, 2 — three values, so the body runs three times. Loops are covered in Lesson 4."},
      {"prompt":"What does this display?\n```python\nitems = [\"pen\", \"book\", \"cup\"]\nprint(items[0])\n```","options":["pen","book","cup","0"],"answer":0,"explanation":"List positions start at 0, so items[0] is the first element, \"pen\". Lists and dictionaries are covered in Lesson 6."},
      {"prompt":"What does this program print?\n```python\ndef double(n):\n    return n * 2\n\nprint(double(5))\n```","options":["n * 2","10","5","Nothing"],"answer":1,"explanation":"Calling double(5) sends 5 in as n, and the function returns 10, which print then displays. Functions are covered in Lesson 7."},
      {"prompt":"What does \"cat\".upper() evaluate to?","options":["Cat","CAT","cat","An error"],"answer":1,"explanation":"The upper() method builds a new string with every letter in capitals: \"CAT\". String methods are covered in Lesson 8."},
      {"prompt":"The input() function always hands your program back a value of which type?","options":["A number","A boolean","A string (text)","Whatever type the user intended"],"answer":2,"explanation":"input() always returns text, even when the user types digits — you must convert with int() to do math. This classic trap is covered in Lesson 2 and revisited throughout."}
   ]}',
   'Score yourself, but do not skip lessons: even questions you got right are re-taught with depth you will need for the project.', 10),
  (2, 'Your first program: values, variables, print, input', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will write programs that store values in named variables, display messages with print, and read what the user types with input. Retrieval warm-up — answer from memory before reading on: (1) In the diagnostic, what did print(\"Hello, world\") do? (2) If x = 4 and then x = x + 2, what is x? Say your answers out loud, then check: it displayed the text on screen, and x became 6. You will need a place to run code: open any free online Python runner in your browser (search for \"online Python 3 runner\" — no installation or account needed) and keep it open beside this lesson."},
      {"heading":"Values, variables, print, and input","text":"Programs work with values: numbers like 42 and 3.5, and text in quotes like \"hello\" (programmers call text a string). A variable is a named box that stores one value; you fill it with =, called assignment:\n```python\nage = 12\nname = \"Ada\"\n```\nprint displays values, and can show several at once separated by commas:\n```python\nprint(\"Name:\", name)\nprint(\"Age next year:\", age + 1)\n```\ninput pauses the program, shows a prompt, waits for the user to type a line, and returns what they typed — always as a string. To treat typed digits as a number, wrap the result in int():\n```python\nreply = input(\"How old are you? \")\nyears = int(reply)\n```\nThese four ideas — values, variables, print, input — are enough to build real interactive programs."},
      {"heading":"Worked example: trace it line by line","text":"Read this program, then trace it with me. Suppose the user types Ada and then 12.\n```python\nname = input(\"What is your name? \")\nage = int(input(\"How old are you? \"))\nprint(\"Hello,\", name)\nprint(\"In 10 years you will be\", age + 10)\n```\nLine 1: the prompt appears, the user types Ada, so name now stores the string \"Ada\". Line 2: the user types 12; input returns the string \"12\", int converts it to the number 12, so age stores 12. Line 3 prints the message and the variable value. Line 4 computes age + 10 = 22 first, then prints. The exact screen output (after the two typed answers) is:\n```\nHello, Ada\nIn 10 years you will be 22\n```\nNotice print added a space between the comma-separated parts automatically."},
      {"heading":"Your turn","text":"Do these in your online runner. Predict the output before running — that prediction is where the learning happens. (1) Print your name on one line and your city on the next; expected: two lines of text. (2) Store the number 8 in a variable called lucky and print lucky * 2; expected output: 16. (3) Ask the user for their favorite food with input and print the word Yum: followed by the food; if they type pizza, expected output: Yum: pizza. Sketch: food = input(\"Favorite food? \") then print(\"Yum:\", food). (4) Fix this broken line so it runs: print(Good morning) — solution: the text needs quotes, print(\"Good morning\"). (5) Create a = 7 and b = 3, then print their sum and their product on separate lines; expected output: 10 then 21. (6) Stretch: ask for two numbers with input, convert both with int, and print their sum; typing 4 and 5 should output 9, not 45 — if you got 45, you forgot int()."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — missing quotes: print(hello) crashes with NameError: name ''hello'' is not defined, because without quotes Python looks for a variable called hello. Text always needs quotes. Bug 2 — doing math on input: age = input(\"Age? \") then age + 1 crashes with a TypeError, because input returned the string \"12\", not the number 12; strings and numbers cannot be added. Fix: age = int(input(\"Age? \")). Exit ticket — answer both, then check. Q1: What does a variable do? A: It stores one value under a name so you can use and update it later. Q2: What type of value does input() always return, and how do you turn it into a whole number? A: Always a string; wrap it in int() to convert."}
   ]}',
   null, 14),
  (3, 'Making decisions: booleans, if/elif/else', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson your programs will choose between different actions using if, elif, and else. Retrieval warm-up from Lesson 2 — answer from memory: (1) What is wrong with print(Good morning)? (2) What does x = int(input(\"Number? \")) store in x if the user types 9? Check: the text needs quotes around it; and x stores the number 9, because int converts the typed string \"9\". Keep your online Python runner open — you will trace and run everything here."},
      {"heading":"Booleans and branching","text":"So far every program ran every line, top to bottom, always. Real programs decide. A comparison produces one of exactly two boolean values, True or False:\n```python\nprint(5 > 3)    # True\nprint(5 == 3)   # False  (== asks: are these equal?)\nprint(5 != 3)   # True   (!= asks: are these different?)\n```\nAn if statement runs its indented block only when its condition is True; elif offers the next test; else catches everything left over:\n```python\nscore = 72\nif score >= 90:\n    print(\"Excellent\")\nelif score >= 60:\n    print(\"Pass\")\nelse:\n    print(\"Try again\")\n```\nThe indentation (4 spaces) is not decoration — it tells Python which lines belong to which branch. Exactly one branch of an if/elif/else chain runs: Python tests conditions top to bottom and takes the first True one."},
      {"heading":"Worked example: trace it line by line","text":"Trace this program three times, once for each temperature.\n```python\ntemp = 31\nif temp > 30:\n    print(\"Hot day\")\nelif temp > 20:\n    print(\"Nice day\")\nelse:\n    print(\"Bundle up\")\nprint(\"Forecast done\")\n```\nWith temp = 31: the first test 31 > 30 is True, so Hot day prints; the elif and else are skipped entirely — Python never even tests them. Then the unindented last line runs. Exact output:\n```\nHot day\nForecast done\n```\nWith temp = 25: 25 > 30 is False, so Python tries the elif; 25 > 20 is True, so output is Nice day then Forecast done. With temp = 10: both tests fail, the else runs, output is Bundle up then Forecast done. Note that print(\"Forecast done\") runs in all three traces because it is not indented — it sits outside the whole if/elif/else chain."},
      {"heading":"Your turn","text":"Predict, then run. (1) Write an if/else that prints Even or Odd for n = 7, using n % 2 == 0 (the % operator gives the remainder after division); expected output: Odd. (2) Ask the user for a password with input and print Welcome if it equals \"otter\", otherwise print Access denied; typing otter gives Welcome. Sketch: if pw == \"otter\": ... else: .... (3) For age = 15, write a chain that prints Child for under 13, Teen for 13 to 17, and Adult for 18 up; expected output: Teen. (4) Predict without running: what does the traced temperature program print for temp = 30 exactly? Answer: Nice day then Forecast done, because 30 > 30 is False but 30 > 20 is True. (5) Fix this bug: if answer = 10: — solution: use == for comparison, if answer == 10:; a single = assigns and is a syntax error inside an if. (6) Stretch: read a number with int(input(...)) and print Positive, Zero, or Negative; typing -4 should print Negative."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — = versus ==: writing if x = 5: is a syntax error; = stores a value, == compares two values. Bug 2 — wrong branch order: in a chain that tests score >= 60 before score >= 90, a score of 95 prints Pass, because Python takes the FIRST True branch and never reaches the >= 90 test. Order your tests from most specific to least. Exit ticket — Q1: What are the only two boolean values, and what does 4 == 4 evaluate to? A: True and False; it evaluates to True. Q2: In an if/elif/else chain, how many branches run? A: Exactly one — the first branch whose condition is True, or the else if none are."}
   ]}',
   null, 14),
  (4, 'Repetition: for and while loops', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will repeat work with for loops over range and with while loops, and you will build running totals with an accumulator variable. Retrieval warm-up from Lesson 3 — from memory: (1) What does 6 >= 6 evaluate to? (2) In an if/elif/else chain, which branch runs when several conditions are True? Check: True (>= means greater than OR equal); and only the first True branch runs — the rest are skipped. Runner open? Good."},
      {"heading":"Two kinds of repetition","text":"A for loop repeats a block once for each value in a sequence. range makes number sequences: range(5) gives 0, 1, 2, 3, 4 (it stops BEFORE the end value), and range(1, 6) gives 1 through 5:\n```python\nfor i in range(1, 4):\n    print(\"lap\", i)\n```\nThis prints lap 1, lap 2, lap 3 on separate lines. A while loop repeats as long as its condition stays True — use it when you cannot know in advance how many repetitions you need:\n```python\ncount = 3\nwhile count > 0:\n    print(count)\n    count = count - 1\nprint(\"Liftoff!\")\n```\nSomething inside the loop must move the condition toward False (here, count shrinks each pass), or the loop never ends. The most useful loop pattern is the accumulator: start a variable at 0 before the loop, add to it inside the loop, use it after."},
      {"heading":"Worked example: trace it line by line","text":"Trace this accumulator program by keeping a table of n and total in your head (or on paper).\n```python\ntotal = 0\nfor n in range(1, 5):\n    total = total + n\n    print(n, total)\nprint(\"final:\", total)\n```\nBefore the loop, total is 0. Pass 1: n is 1, total becomes 0 + 1 = 1, prints 1 1. Pass 2: n is 2, total becomes 1 + 2 = 3, prints 2 3. Pass 3: n is 3, total becomes 6, prints 3 6. Pass 4: n is 4, total becomes 10, prints 4 10. range(1, 5) stops before 5, so the loop ends and the last line runs. Exact output:\n```\n1 1\n2 3\n3 6\n4 10\nfinal: 10\n```\nNow re-trace the while countdown from the previous section and confirm its exact output is 3, 2, 1, each on its own line, then Liftoff!."},
      {"heading":"Your turn","text":"Predict every output before running. (1) Print the numbers 1 to 10 with a for loop; expected: ten lines, 1 through 10 — remember range(1, 11). (2) Print the even numbers 2 to 20 using range(2, 21, 2) — the third value is the step; expected: 2, 4, 6, ... 20. (3) Use the accumulator pattern to sum 1 to 100 and print only the final total; expected output: 5050. (4) With a while loop, start n = 1 and keep doubling (n = n * 2) while n < 100, then print n; expected output: 128 — trace why: n passes 64, doubles to 128, and 128 < 100 is False so the loop exits. (5) Print the 7 times table as 7 x 1 = 7 up to 7 x 5 = 35; sketch: for i in range(1, 6): print(\"7 x\", i, \"=\", 7 * i). (6) Stretch: ask the user for a number with int(input(...)) and print a countdown from it to 1 followed by Go!."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — off-by-one with range: range(10) produces 0 through 9, never 10; to count 1 to 10 you need range(1, 11). When a loop seems one short, check both ends of your range. Bug 2 — the infinite while loop: if you forget the line that changes the loop variable (like count = count - 1), the condition stays True forever and the program hangs; most online runners have a Stop button — use it, add the update line, rerun. Exit ticket — Q1: How many times does the body of for i in range(3): run, and what values does i take? A: Three times; i takes 0, 1, 2. Q2: When does a while loop stop? A: The moment its condition is checked and found False — so something in the body must push the condition toward False."}
   ]}',
   null, 15),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"What does this print?\n```python\nx = \"5\"\nprint(x + x)\n```","options":["10","55","5 5","An error"],"answer":1,"explanation":"x is the STRING \"5\" (note the quotes), and + glues strings together, so the output is 55. Only int(\"5\") + int(\"5\") would give 10. (Lesson 2.)"},
      {"prompt":"What does print(2 + 3 * 2) display?","options":["10","12","8","232"],"answer":2,"explanation":"Multiplication happens before addition, just like in math: 3 * 2 is 6, plus 2 is 8. (Lesson 2.)"},
      {"prompt":"What does this print for score = 90?\n```python\nif score >= 60:\n    print(\"Pass\")\nelif score >= 90:\n    print(\"Excellent\")\nelse:\n    print(\"Retry\")\n```","options":["Excellent","Pass","Retry","Pass then Excellent"],"answer":1,"explanation":"Python takes the FIRST True branch: 90 >= 60 is True, so Pass prints and the elif is never tested. To ever see Excellent, the >= 90 test must come first. (Lesson 3.)"},
      {"prompt":"Which values does range(1, 4) produce?","options":["1, 2, 3, 4","1, 2, 3","0, 1, 2, 3","2, 3"],"answer":1,"explanation":"range starts at the first value and stops BEFORE the second: 1, 2, 3. (Lesson 4.)"},
      {"prompt":"What is the exact output?\n```python\nn = 8\nwhile n > 1:\n    n = n // 2\n    print(n)\n```","options":["4 2 1 (one per line)","8 4 2 1 (one per line)","4 2 (one per line)","It loops forever"],"answer":0,"explanation":"// is whole-number division. n goes 8 -> 4 (print 4) -> 2 (print 2) -> 1 (print 1); then 1 > 1 is False and the loop stops. Three lines: 4, 2, 1. (Lesson 4.)"},
      {"prompt":"The user runs age = input(\"Age? \") and types 30. What is stored in age?","options":["The number 30","The string \"30\"","The boolean True","Nothing until you print it"],"answer":1,"explanation":"input always returns a string, so age holds the text \"30\". Doing age + 1 would crash; int(age) + 1 gives 31. (Lesson 2.)"},
      {"prompt":"Which line correctly asks whether answer equals 10?","options":["if answer = 10:","if answer == 10:","if answer === 10:","if answer equals 10:"],"answer":1,"explanation":"== compares two values; a single = assigns and is a syntax error inside an if; === does not exist in Python. (Lesson 3.)"},
      {"prompt":"Using the accumulator pattern, what does this print?\n```python\ntotal = 0\nfor n in range(3):\n    total = total + 2\nprint(total)\n```","options":["2","3","6","0"],"answer":2,"explanation":"range(3) runs the body three times, adding 2 each pass: 0 -> 2 -> 4 -> 6. The print is outside the loop, so only the final 6 appears. (Lesson 4.)"}
   ]}',
   null, 10),
  (6, 'Lists & dictionaries', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will store many values in one variable — ordered collections with lists, labeled collections with dictionaries — and loop over both. Retrieval warm-up from Lesson 4 — from memory: (1) What values does range(2, 5) produce? (2) In the accumulator pattern, where do you create the total variable and where do you print it? Check: 2, 3, 4; and you create it before the loop, update it inside, print it after. Runner open."},
      {"heading":"Lists and dictionaries","text":"A list holds values in order, written in square brackets. Positions (indexes) start at 0, and -1 means the last item:\n```python\nfruits = [\"apple\", \"kiwi\", \"plum\"]\nprint(fruits[0])      # apple\nprint(fruits[-1])     # plum\nfruits.append(\"fig\")  # add to the end\nprint(len(fruits))    # 4\n```\nA for loop visits every item without you managing indexes: for f in fruits: print(f). A dictionary holds labeled values — each entry is a key: value pair in curly braces — and you look values up by key instead of by position:\n```python\nages = {\"Ana\": 12, \"Bo\": 15}\nprint(ages[\"Bo\"])   # 15\nages[\"Cy\"] = 9      # add a new pair\n```\nUse a list when order matters (a queue, a to-do list); use a dictionary when lookup-by-name matters (a phone book, a scoreboard)."},
      {"heading":"Worked example: trace it line by line","text":"Trace this program, keeping track of what each collection contains after every line.\n```python\nscores = [10, 20, 30]\nscores.append(40)\nprint(len(scores))\nprint(scores[0], scores[-1])\nages = {\"Ana\": 12, \"Bo\": 15}\nages[\"Cy\"] = 9\nprint(ages[\"Bo\"])\nfor name in ages:\n    print(name, ages[name])\n```\nLine 2 grows the list to [10, 20, 30, 40], so line 3 prints 4. Line 4 prints the first and last items: 10 40. Line 6 adds a third pair, so ages is {\"Ana\": 12, \"Bo\": 15, \"Cy\": 9}. Line 7 looks up the key \"Bo\" and prints 15. The final loop visits each KEY, and ages[name] fetches its value. Exact output:\n```\n4\n10 40\n15\nAna 12\nBo 15\nCy 9\n```\n(Dictionaries keep the order in which pairs were added.)"},
      {"heading":"Your turn","text":"Predict, then run. (1) Make a list of three colors and print the middle one; for [\"red\", \"green\", \"blue\"] expected output: green (index 1 — not 2!). (2) Append your favorite color and print the whole list with print(colors); expected: all four in brackets. (3) Loop over your list printing I like before each color; sketch: for c in colors: print(\"I like\", c). (4) Sum the list nums = [4, 9, 2, 7] with an accumulator loop and print the total; expected output: 22. (5) Build a dictionary prices = {\"tea\": 3, \"coffee\": 4}, add \"juice\" priced 5, then print prices[\"coffee\"]; expected output: 4. (6) Stretch: loop over prices printing lines like tea costs 3; expected: three such lines. Solution shape: for item in prices: print(item, \"costs\", prices[item])."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — IndexError: with a 3-item list, items[3] crashes with IndexError: list index out of range, because valid indexes are 0, 1, 2. The last index is always len(items) - 1. Bug 2 — KeyError: asking a dictionary for a key it does not hold, like ages[\"Zoe\"], crashes with KeyError: ''Zoe''. Check first with: if \"Zoe\" in ages:. Remember the model: lists are looked up by POSITION, dictionaries by KEY. Exit ticket — Q1: For pets = [\"cat\", \"dog\"], what are pets[0] and len(pets)? A: \"cat\" and 2. Q2: How do you add the pair \"Max\": 7 to a dictionary d, and how do you read it back? A: d[\"Max\"] = 7 to add; d[\"Max\"] to read, giving 7."}
   ]}',
   null, 15),
  (7, 'Functions: parameters, returns, scope', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will package code into functions you can call by name, pass information in through parameters, get results out with return, and predict which variables are visible where (scope). Retrieval warm-up from Lesson 6 — from memory: (1) What does items[-1] give you? (2) Lists are indexed by position; dictionaries are indexed by what? Check: the last item of the list; by key. Runner open."},
      {"heading":"Defining and calling functions","text":"A function is a named, reusable block of code. def defines it, parameters name the values it expects, and return hands a result back to whoever called it:\n```python\ndef area(width, height):\n    result = width * height\n    return result\n```\nDefining runs nothing — the body executes only when you CALL the function: area(3, 4). At that moment width becomes 3, height becomes 4, and the call itself becomes the returned value, 12, which you can print, store, or use in math. return and print are different jobs: return sends a value back to the program; print only shows it to a human. A function that just prints gives the caller nothing to work with — its calls evaluate to None. Also, when return runs, the function ends immediately; lines after it never execute."},
      {"heading":"Worked example: trace it line by line","text":"Trace, paying attention to when the body actually runs.\n```python\ndef area(width, height):\n    result = width * height\n    return result\n\na = area(3, 4)\nprint(a)\nprint(area(2, 5) + 1)\n```\nLines 1-3 only define area; nothing runs yet. The first real action is area(3, 4): width = 3, height = 4, result = 12, and 12 is returned, so a stores 12 and line 6 prints 12. Line 7 calls again with 2 and 5: the call evaluates to 10, plus 1 is 11. Exact output:\n```\n12\n11\n```\nNow scope: result was created INSIDE area, so it lives only during the call. Adding print(result) at the bottom of the program (outside the function) crashes with NameError: name ''result'' is not defined. Each call gets its own fresh copies of parameters and inner variables; they vanish when the call returns."},
      {"heading":"Your turn","text":"Predict, then run. (1) Write greet(name) that prints Hello, followed by the name, and call it twice with different names; expected: two greeting lines. (2) Write square(n) that RETURNS n * n, then run print(square(6)); expected output: 36. (3) Write bigger(a, b) that returns a if a > b, else b; print(bigger(4, 9)) should output 9 — this needs an if/else INSIDE the function. (4) Predict without running: define double(n): return n * 2 and then run print(double(double(3))); answer: 12, because the inner call makes 6 and the outer call doubles it. (5) Write total(nums) that loops over a list parameter with an accumulator and returns the sum; print(total([1, 2, 3, 4])) should output 10. (6) Stretch: write price_with_tip(bill) returning bill * 1.2, and use it on two different bills; for 10 expected output: 12.0."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — printing instead of returning: if square(n) does print(n * n) with no return, then print(square(5)) shows 25 followed by None — the function displayed a number but RETURNED nothing, so the outer print got None. When the caller needs the value, return it. Bug 2 — expecting inner variables outside: using a parameter or inner variable after the call (like result above) raises NameError; get values out with return, not by reaching in. Exit ticket — Q1: What is the difference between a parameter and the value you pass in a call? A: The parameter is the name in the def line (n); the call supplies the actual value for it (5), often called the argument. Q2: What does a function call evaluate to if the function has no return statement? A: None."}
   ]}',
   null, 15),
  (8, 'Strings & working with text', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will take strings apart with indexing and slicing, transform them with methods, test them with in, and build output cleanly with f-strings. Retrieval warm-up from Lesson 7 — from memory: (1) What is the difference between return and print? (2) What does print(square(3)) show if square only prints and never returns? Check: return hands a value back to the program, print only displays it; and it shows 9 then None. Runner open."},
      {"heading":"Strings are sequences","text":"A string is a sequence of characters, so the tools you know from lists work here: indexing from 0, negative indexes from the end, len, and for loops. Slicing cuts out a piece: word[start:stop] takes from start up to but NOT including stop.\n```python\nword = \"Python\"\nprint(word[0], word[-1])   # P n\nprint(word[0:3])            # Pyt\n```\nMethods are built-in transformations you call with a dot; each returns a NEW string, because strings can never be changed in place:\n```python\nshout = word.upper()        # \"PYTHON\"\ncalm = \"HeLLo\".lower()     # \"hello\"\nfixed = \"co-op\".replace(\"-\", \" \")  # \"co op\"\n```\nThe in operator tests containment: \"y\" in word is True. And f-strings build text by embedding expressions in braces inside a string prefixed with f: f\"{word} has {len(word)} letters\"."},
      {"heading":"Worked example: trace it line by line","text":"Trace this program character by character where needed.\n```python\nword = \"Python\"\nprint(word[0], word[-1])\nprint(word[0:3])\nprint(word.upper())\nprint(word)\nmsg = f\"{word} has {len(word)} letters\"\nprint(msg)\n```\nLine 2: index 0 is P and index -1 is the last letter n, printed with a space between: P n. Line 3: the slice takes indexes 0, 1, 2 — Pyt (index 3 is excluded). Line 4: upper() builds and prints PYTHON — but it returned a new string; word itself was not touched, which is why line 5 still prints Python. Line 6: the f-string fills in the braces: len(word) is 6. Exact output:\n```\nP n\nPyt\nPYTHON\nPython\nPython has 6 letters\n```"},
      {"heading":"Your turn","text":"Predict, then run. (1) Store your first name and print its first letter, last letter, and length; for \"Grace\" expected: G, e, 5. (2) Print your name in all capitals without changing the stored variable; sketch: print(name.upper()). (3) Slice \"programming\" to get gram; solution: \"programming\"[3:7] — count carefully from 0. (4) Ask the user for a sentence with input and print how many characters it has using len; typing hi there should output 8 (the space counts). (5) Check whether the letter e appears in a word with in and print Has e or No e; for \"apple\" expected: Has e. Sketch: if \"e\" in word:. (6) Stretch: loop for ch in \"abc\": print(ch.upper()) and predict the output first; answer: A, B, C on three lines."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — expecting methods to change the string: after word.upper(), word is unchanged; strings are immutable, so methods return new strings you must store: word = word.upper(). Bug 2 — slice off-by-one: word[0:3] contains indexes 0, 1, 2 — three characters, not four; the stop index is always excluded, exactly like range. Exit ticket — Q1: What are \"kayak\"[0] and \"kayak\"[-1], and what might that suggest checking? A: Both are k — comparing a string letter by letter with its reverse detects palindromes. Q2: Why does \"hi\".upper() not change the original string, and how do you keep the result? A: Strings are immutable; store the returned value, e.g. loud = \"hi\".upper()."}
   ]}',
   null, 14),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"What does this print?\n```python\nnums = [1, 2, 3]\nnums.append(nums[0])\nprint(len(nums), nums[-1])\n```","options":["3 3","4 1","4 3","An error"],"answer":1,"explanation":"append adds the value of nums[0], which is 1, making [1, 2, 3, 1]. Length is 4 and the last item is 1. (Lesson 6.)"},
      {"prompt":"stock = {\"pen\": 5, \"cup\": 2} — which line increases the pen count to 6?","options":["stock[0] = 6","stock[\"pen\"] = stock[\"pen\"] + 1","stock.append(\"pen\")","stock + 1"],"answer":1,"explanation":"Dictionaries are indexed by key: read the current value with stock[\"pen\"], add 1, assign it back. Position indexes and append belong to lists. (Lesson 6.)"},
      {"prompt":"What does this program print?\n```python\ndef mystery(n):\n    return n + 1\n    print(\"done\")\n\nprint(mystery(4))\n```","options":["5 then done","done then 5","5","An error"],"answer":2,"explanation":"return ends the function immediately, so print(\"done\") never runs. The call evaluates to 5, which the outer print displays. (Lesson 7.)"},
      {"prompt":"What does this print?\n```python\ndef shout(word):\n    print(word.upper())\n\nresult = shout(\"hey\")\nprint(result)\n```","options":["HEY then None","HEY then HEY","None then HEY","hey then HEY"],"answer":0,"explanation":"shout prints HEY but has no return, so the call evaluates to None, and the second print shows None. To get HEY back, the function must return word.upper(). (Lesson 7.)"},
      {"prompt":"Inside def f(): x = 10 — what happens if you print(x) AFTER calling f(), outside the function?","options":["It prints 10","It prints None","NameError: x is not defined","It prints x"],"answer":2,"explanation":"x was created inside the function, so it exists only during the call — that is scope. Get values out with return. (Lesson 7.)"},
      {"prompt":"What is \"banana\"[1:4]?","options":["ban","ana","anan","bana"],"answer":1,"explanation":"The slice takes indexes 1, 2, 3 (stop index 4 is excluded): a, n, a — \"ana\". (Lesson 8.)"},
      {"prompt":"What does this print?\n```python\nword = \"go\"\nword.upper()\nprint(word)\n```","options":["GO","go","Go","An error"],"answer":1,"explanation":"Strings are immutable: upper() returned the new string \"GO\", but nothing stored it, so word still holds \"go\". (Lesson 8.)"},
      {"prompt":"With name = \"Sam\", what does print(f\"Hi {name}, {len(name)} letters\") display?","options":["Hi {name}, {len(name)} letters","Hi Sam, 3 letters","Hi Sam, len(name) letters","An error"],"answer":1,"explanation":"An f-string evaluates each expression in braces: name becomes Sam and len(name) becomes 3. (Lesson 8.)"}
   ]}',
   null, 10),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"variable","translation":"A named storage box for one value; assignment with = fills it, and the name retrieves the current value anywhere after.","example":"score = 0 creates the variable; score = score + 10 updates it to 10."},
      {"term":"loop","translation":"A structure that repeats a block of code: for repeats once per item in a sequence, while repeats as long as a condition stays True.","example":"for i in range(3): print(i) prints 0, 1, 2 — three passes through the body."},
      {"term":"function","translation":"A named, reusable block of code defined with def; it runs only when called, and can hand a result back with return.","example":"def square(n): return n * n — then square(4) evaluates to 16."},
      {"term":"parameter","translation":"A name in a function definition that receives the value passed in each call (the passed value itself is the argument).","example":"In def greet(name), name is the parameter; in greet(\"Ada\"), the string \"Ada\" is the argument it receives."},
      {"term":"dictionary","translation":"A collection of key: value pairs looked up by key rather than by position; written with curly braces.","example":"ages = {\"Ana\": 12}; ages[\"Ana\"] gives 12, and ages[\"Bo\"] = 15 adds a pair."},
      {"term":"bug","translation":"A mistake in a program that makes it crash or behave wrongly; finding and fixing bugs by reading errors and tracing code is called debugging.","example":"if x = 5: is a bug — the comparison needs ==, and Python reports it as a SyntaxError."}
   ]}',
   'Say each definition aloud without looking, then write one original code example per term — production beats recognition.', 10),
  (11, 'Applied project: build a word-guessing game', 'writing',
   '{"sections":[
      {"heading":"The brief","text":"Build a complete word-guessing game (hangman without the drawing) in your online Python runner, using only what this course taught — no external libraries. Spec: the program stores a secret word; the player has 6 wrong guesses; each turn the program shows the word with unguessed letters as underscores (for \"python\" after guessing t and o: _ _ t _ o _), asks for one letter with input, and says whether the letter is in the word; a repeated guess should not cost a life; the game ends with You win! when every letter is revealed, or You lose! The word was ... when the wrong-guess count reaches 6. Before coding, write in comments: the variables you will need (secret word, list of guessed letters, wrong-guess counter) and the loop that drives the game. Planning first is the professional habit this project trains."},
      {"heading":"Milestone 1 — guided skeleton","text":"Get a minimal loop running before any polish. Copy this skeleton, run it, and make it work end to end:\n```python\nsecret = \"python\"\nguessed = []\nwrong = 0\n\nwhile wrong < 6:\n    display = \"\"\n    for ch in secret:\n        if ch in guessed:\n            display = display + ch + \" \"\n        else:\n            display = display + \"_ \"\n    print(display)\n    letter = input(\"Guess a letter: \").lower()\n    guessed.append(letter)\n    if letter in secret:\n        print(\"Yes!\")\n    else:\n        wrong = wrong + 1\n        print(\"No —\", 6 - wrong, \"guesses left\")\n```\nTrace it once by hand with the guesses p, z, y to make sure you can predict every line it prints: p reveals the first letter, z costs a life (5 left), y reveals the second letter. Notice the display loop is the accumulator pattern from Lesson 4 — building a string instead of a number."},
      {"heading":"Milestone 2 — independent features","text":"Now extend the skeleton on your own; each feature names the lesson that prepared you for it. (1) Win detection: after each guess, check whether every character of secret is in guessed; if so, print You win! and stop the loop — write a helper function all_revealed(secret, guessed) that returns True or False (Lessons 3, 7). (2) Lose message: after the loop, if the player did not win, print You lose! The word was python (Lesson 3). (3) Repeated guesses: if the letter is already in guessed, say Already tried that! and do not count a life or re-append (Lessons 3, 6). (4) Input hygiene: reject inputs that are not exactly one letter, using len (Lesson 8). (5) Stretch — scoreboard: keep a dictionary like {\"wins\": 0, \"losses\": 0}, wrap the whole game in a function, and loop asking Play again? (y/n) (Lessons 6, 7)."},
      {"heading":"Test cases","text":"Run every test against your finished game; fix failures before moving on. Test 1 — clean win: with secret \"python\", guess p, y, t, h, o, n; expect Yes! six times, then You win!, with 6 guesses still remaining. Test 2 — clean loss: guess q, w, e, r, s, x; expect the remaining-guess countdown 5, 4, 3, 2, 1, 0 and then You lose! The word was python. Test 3 — repeat: guess a, then a again; expect Already tried that! and the same lives before and after the second a. Test 4 — display: with secret \"python\", after guessing only t and o the board must show _ _ t _ o _. Test 5 — capitals: guessing P must count as p (that is why the skeleton calls .lower()). Test 6 — input hygiene: entering py or an empty line must be rejected without costing a life."},
      {"heading":"Self-check rubric","text":"Score yourself 1-4 on each axis; 12 or more overall (with no axis at 1) means the project is complete. Correctness: all six test cases pass exactly as described. Code quality: names say what they store (wrong, not w); the win check lives in its own function with a return; no copy-pasted blocks that a loop or function could replace. Robustness: repeated guesses, capital letters, and bad input are all handled without crashing or cheating the player out of a life. Understanding — the axis that matters most: without running the code, you can state what guessed and wrong contain after any given sequence of guesses, and explain aloud, line by line, how the display string gets built. If any axis scored 1, revisit the lesson named in that milestone and revise before calling it done."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"Trace this code. What is the exact output?\n```python\ntotal = 0\nfor n in [3, 1, 4]:\n    if n > 2:\n        total = total + n\nprint(total)\n```","options":["8","7","4","3"],"answer":1,"explanation":"Only 3 and 4 pass the n > 2 test (1 is skipped), so total is 3 + 4 = 7."},
      {"prompt":"What does this print?\n```python\nwords = [\"hi\", \"there\"]\nwords.append(\"friend\")\nprint(words[1], len(words))\n```","options":["hi 3","there 3","there 2","friend 3"],"answer":1,"explanation":"Indexing starts at 0, so words[1] is \"there\"; after append the list has 3 items."},
      {"prompt":"What does this print?\n```python\ncount = {\"a\": 1, \"b\": 2}\ncount[\"a\"] = count[\"a\"] + 10\nprint(count[\"a\"] + count[\"b\"])\n```","options":["3","13","12","KeyError"],"answer":1,"explanation":"count[\"a\"] becomes 1 + 10 = 11, and 11 + 2 = 13. Dictionary values update by assigning to the key."},
      {"prompt":"Trace this program. What is the output?\n```python\ndef step(n):\n    if n % 2 == 0:\n        return n // 2\n    return n * 3\n\nprint(step(step(6)))\n```","options":["3","9","18","6"],"answer":1,"explanation":"Inner call first: 6 is even, so step(6) returns 6 // 2 = 3. Outer call: 3 is odd, so the if is skipped and step(3) returns 3 * 3 = 9. The two calls exercise both branches."},
      {"prompt":"What does \"laptop\"[2:5] evaluate to?","options":["apt","pto","ptop","apo"],"answer":1,"explanation":"Indexes 2, 3, 4 of l-a-p-t-o-p are p, t, o (index 5 is excluded): \"pto\"."},
      {"prompt":"Which change fixes this infinite loop?\n```python\nn = 10\nwhile n > 0:\n    print(n)\n```","options":["Change the condition to n >= 0","Add n = n - 1 inside the loop body","Move print(n) above the loop","Change while to if"],"answer":1,"explanation":"Nothing in the body changes n, so n > 0 stays True forever. Decreasing n each pass moves the condition toward False, ending the loop."},
      {"prompt":"What is the exact output?\n```python\nfor ch in \"abc\":\n    print(ch.upper())\n```","options":["ABC on one line","A, B, C on three lines","abc on one line","a, b, c on three lines"],"answer":1,"explanation":"The loop visits each character in turn and prints its uppercase form; each print ends the line, giving A, B, C on three separate lines."},
      {"prompt":"Trace this program. What does it print?\n```python\ndef count_e(text):\n    total = 0\n    for ch in text:\n        if ch == \"e\":\n            total = total + 1\n    return total\n\nprint(count_e(\"seventeen\"))\n```","options":["3","4","2","seventeen"],"answer":1,"explanation":"s-e-v-e-n-t-e-e-n contains e at positions 2, 4, 7, 8 — four times. The function returns 4 and print displays it. This combines loops, ifs, strings, and functions — everything the course covered."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0002-0000-4000-8000-000000000002' and l.position = v.pos
);
