-- Technology track: Introduction to Computer Science (course 4 of the tech pathway).
-- Moves learners who finished Python Foundations from "I can write code" to
-- "I think like a computer scientist": what computation really is, algorithms,
-- abstraction and decomposition, recursion, algorithmic efficiency and Big-O
-- intuition, searching and sorting, and testing/debugging with exceptions.
-- Every lesson moves theory -> guided practice -> independent practice, with
-- worked examples traced line by line, retrieval warm-ups, deliberate-practice
-- tasks with expected outputs, common-misconception debriefs, and exit tickets.
-- Assessment is layered: a diagnostic, two checkpoints, an applied project
-- (implement and analyze search), and a final. All content is original and
-- targets Python 3.12+ with no external libraries. Topic sequence informed by
-- MIT OpenCourseWare's introductory programming sequence (CC BY-NC-SA); all
-- prose, code, and questions are written from scratch for this course.
-- Fixed UUIDs and guarded inserts make the file idempotent: safe to re-run.

-- ============ Introduction to Computer Science ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, school, prerequisite_ids)
values (
  'bbbb0002-0000-4000-8000-000000000004',
  'en', null,
  'Introduction to Computer Science',
  'You can write Python — now learn to think like a computer scientist. Discover what a program really is, design algorithms with guess-and-check, tame complexity with abstraction and decomposition, master recursion, build Big-O intuition for efficiency, implement searching and sorting, and debug like a professional with tests and exceptions. Finishes with an applied project where you implement linear and binary search and measure how they scale. Structure informed by MIT OpenCourseWare''s introductory programming sequence (CC BY-NC-SA).',
  null, 'foundations', 4, true, 'technology',
  '{bbbb0002-0000-4000-8000-000000000002}'
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'bbbb0002-0000-4000-8000-000000000004', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Diagnostic: where are you now?', 'quiz',
   '{"questions":[
      {"prompt":"Which of these best describes an algorithm?","options":["Any program written in Python","A step-by-step procedure that is guaranteed to finish and produce a result","A diagram of how a computer is wired","A list of numbers stored in memory"],"answer":1,"explanation":"An algorithm is a recipe: a finite sequence of simple steps, with flow control and a stopping condition, that produces a result. Programs are one way to express algorithms. Lesson 2 starts here."},
      {"prompt":"Trace this loop. What does it print?\n```python\nguess = 0\nwhile guess * guess < 16:\n    guess = guess + 1\nprint(guess)\n```","options":["3","4","5","16"],"answer":1,"explanation":"guess climbs 0, 1, 2, 3 (all squares below 16); when guess is 4, the test 16 < 16 is False and the loop exits, so 4 prints. This guess-and-check pattern is the heart of Lesson 2."},
      {"prompt":"What does this program print?\n```python\ndef triple(n):\n    return n * 3\n\nprint(triple(triple(2)))\n```","options":["6","12","18","222"],"answer":2,"explanation":"The inner call makes 6; the outer call triples that to 18. Composing functions like this is the core move of Lesson 3 on abstraction and decomposition."},
      {"prompt":"Every correct recursive function must have which of these?","options":["A base case that stops the calls","At least two parameters","A while loop inside it","A print statement"],"answer":0,"explanation":"A recursive function calls itself on a smaller problem, and a base case answers the smallest problem directly so the calls stop. Recursion is Lesson 4."},
      {"prompt":"A loop visits every item of a list exactly once. If the list becomes twice as long, roughly how does the running time change?","options":["It stays the same","It doubles","It quadruples","It halves"],"answer":1,"explanation":"One visit per item means work grows in step with the input: double the items, double the time. That is linear growth — Big-O intuition is built in Lesson 6."},
      {"prompt":"Binary search can only be trusted when...","options":["The list is sorted","The list contains only numbers","The list is short","The target is definitely in the list"],"answer":0,"explanation":"Binary search halves the region where the target could be, and that logic only holds if the list is in order. Searching and sorting are covered in Lesson 7."},
      {"prompt":"What does Python raise when a program runs 1 / 0?","options":["ValueError","ZeroDivisionError","KeyError","Nothing — it returns 0"],"answer":1,"explanation":"Dividing by zero raises a ZeroDivisionError exception, which you can catch with try/except. Exceptions and testing are covered in Lesson 8."},
      {"prompt":"What does the line assert 2 + 2 == 5 do when it runs?","options":["Prints False and continues","Raises an AssertionError and stops the program","Does nothing at all","Rounds 5 down to 4"],"answer":1,"explanation":"assert checks that its condition is True and crashes loudly with AssertionError when it is not — the smallest possible unit test. Lesson 8 turns this into a testing habit."}
   ]}',
   null, 10),
  (2, 'Computation and algorithms: what a program really is', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will explain what computation is, name the three ingredients every algorithm needs, and design guess-and-check algorithms that find answers by systematic trial. Retrieval warm-up from Python Foundations — answer from memory before reading on: (1) When does a while loop stop? (2) In the accumulator pattern, where do you create the variable, and where do you update it? Check: a while loop stops the moment its condition is checked and found False; the accumulator is created before the loop and updated inside it. Keep an online Python 3 runner open beside this lesson — every example is meant to be run."},
      {"heading":"Declarative facts versus imperative recipes","text":"There are two kinds of knowledge. Declarative knowledge states facts: the square root of 25 is the number that, multiplied by itself, gives 25. True — but it does not tell you how to FIND that number. Imperative knowledge is a recipe: start at 0, square it, too small? add 1 and try again; stop when the square is no longer below the target. Computation is running imperative recipes, and an algorithm is such a recipe made precise. Every algorithm has three ingredients: simple steps, flow control that decides which step runs next, and a stopping condition. A computer only ever does simple operations — arithmetic, comparisons, moving values — but it does billions per second, so dumb-but-fast strategies like trying every candidate become practical:\n```python\nguess = 0\nwhile guess * guess < 25:\n    guess = guess + 1\nprint(guess)\n```\nThis prints 5. Programmers call the strategy exhaustive enumeration or guess-and-check: enumerate candidates in order, test each one, stop at the first that works. It is the first real algorithm design technique in your toolbox."},
      {"heading":"Worked example: trace it line by line","text":"This program decides whether a number is a perfect cube, and finds the cube root when it is. Trace it with me for cube = 27.\n```python\ncube = 27\nguess = 0\nwhile guess ** 3 < cube:\n    guess = guess + 1\nif guess ** 3 == cube:\n    print(guess, \"is the cube root\")\nelse:\n    print(cube, \"is not a perfect cube\")\n```\nPass 1: 0 ** 3 is 0, and 0 < 27 is True, so guess becomes 1. Pass 2: 1 < 27, guess becomes 2. Pass 3: 8 < 27, guess becomes 3. Next check: 27 < 27 is False — the loop exits with guess holding 3. The if now asks whether 3 ** 3 == 27: True, so the exact output is:\n```\n3 is the cube root\n```\nNotice the division of labor: the loop is guaranteed to stop because guess ** 3 grows every pass and must eventually reach cube; the if afterward decides whether we landed exactly on the target or flew past it. Re-trace with cube = 10: guess climbs 0, 1, 2, 3 (since 8 < 10), then 27 < 10 is False; 27 == 10 is False, so it prints 10 is not a perfect cube."},
      {"heading":"Your turn","text":"Predict every output before running — the prediction is where the learning happens. (1) Change cube to 64 in the worked example; expected output: 4 is the cube root. (2) Change cube to 10 and confirm your trace from the last section: 10 is not a perfect cube. (3) Adapt the pattern to find the square root of 81: use guess * guess and the target 81; expected output: 9 is the square root. (4) For cube = 1000, how many times does the loop body run, and what prints? Answer: the body runs 10 times (guess climbs from 0 to 10, and 9 ** 3 = 729 is still below 1000), then 10 is the cube root. (5) Write an everyday algorithm — making tea, walking to school — as numbered steps, and label its three ingredients: the simple steps, the flow control, the stopping condition. (6) Stretch: add a counter variable to the cube program that counts loop passes and print it at the end; for cube = 64 it should print 4 passes of the loop."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — no progress toward the stop: if you forget guess = guess + 1, the condition never changes and the loop runs forever. Every loop in an algorithm needs a value that provably moves toward the stopping condition. Bug 2 — overshooting with <=: writing while guess ** 3 <= cube: makes the loop take one extra pass — for cube = 27, guess leaves the loop holding 4, and the program wrongly reports 27 is not a perfect cube. Fenceposts matter; trace boundary passes by hand. Exit ticket — Q1: Name the three ingredients every algorithm needs. A: simple steps, flow control, and a stopping condition. Q2: What is the difference between declarative and imperative knowledge? A: declarative states a fact about the answer; imperative gives a recipe for finding it — computation runs the recipes."}
   ]}',
   'Say the algorithm in plain numbered steps before you write any code — if you cannot say it, you cannot code it.', 14),
  (3, 'Abstraction and decomposition with functions', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will break a big problem into small named functions (decomposition) and use functions without caring how they work inside (abstraction) — the two ideas that let people build programs of millions of lines. Retrieval warm-up from Lesson 2 — from memory: (1) What are the three ingredients of an algorithm? (2) In the cube-root program, why was the while loop guaranteed to stop? Check: steps, flow control, stopping condition; and because guess ** 3 grew every pass, so it had to reach the target. Runner open."},
      {"heading":"Black boxes you already trust","text":"You have used abstraction since your first program: you call len(word) without ever reading the code inside len. You know its contract — give it a sequence, get back its length — and the implementation is a black box. That is abstraction: knowing WHAT, ignoring HOW. Decomposition is the flip side: when you face a big problem, you split it into self-contained pieces, give each piece a name and a contract, and implement them one at a time. In Python the unit of both ideas is the function:\n```python\ndef average(nums):\n    total = 0\n    for n in nums:\n        total = total + n\n    return total / len(nums)\n```\nOnce this works, you never think about its insides again — you just call average(data). Good decomposition has a test: each function does one job you can state in one sentence, and you could hand any one of them to a friend to implement using only its name, parameters, and one-sentence contract."},
      {"heading":"Worked example: trace it line by line","text":"Two helpers, then a program that composes them. Trace everything.\n```python\ndef average(nums):\n    total = 0\n    for n in nums:\n        total = total + n\n    return total / len(nums)\n\ndef spread(nums):\n    return max(nums) - min(nums)\n\ndata = [4, 8, 6]\nprint(average(data))\nprint(spread(data))\n```\nDefining the two functions runs nothing. The first real action is average(data): total accumulates 0 -> 4 -> 12 -> 18, and 18 / len(data) is 18 / 3, so the call returns 6.0 (division with / always produces a float). Then spread(data): max gives 8, min gives 4, the call returns 4. Exact output:\n```\n6.0\n4\n```\nNote how the main program reads like English — average of data, spread of data — because the complexity is hidden behind names. Also note spread itself is BUILT from two abstractions, max and min, that someone else implemented."},
      {"heading":"Your turn","text":"Predict, then run. (1) Write celsius_to_f(c) that returns c * 9 / 5 + 32; print(celsius_to_f(100)) — expected output: 212.0. (2) Write count_evens(nums) using an accumulator and an if with n % 2 == 0 inside the loop; print(count_evens([1, 2, 3, 4])) — expected output: 2. (3) Predict without running: def rect_perimeter(w, h): return 2 * (w + h), then print(rect_perimeter(3, 4)); answer: 14. (4) Reuse the worked example without editing the helpers: print(average([10, 20])) and print(spread([10, 20])); expected: 15.0 then 10. (5) Decompose this task: read three numbers with int(input(...)) and print the biggest — write a helper biggest3(a, b, c) that returns the largest using if comparisons, then a three-line main program; typing 4, 9, 2 should output 9. (6) Stretch: write describe(nums) that prints both the average and the spread by CALLING the two existing helpers — no copied loop code; describe([4, 8, 6]) should print 6.0 and 4."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — copy-paste instead of call: pasting the averaging loop into three places means three places to fix every future bug. If you paste a block twice, stop and turn it into a function. Bug 2 — printing instead of returning: if average prints its result but returns nothing, then print(average(data) + 1) crashes with a TypeError, because the call evaluated to None. A helper that others will build on must return its result; printing is for humans, returning is for programs. Exit ticket — Q1: In one sentence each, what is decomposition and what is abstraction? A: decomposition splits a problem into named single-job pieces; abstraction lets you use a piece through its contract while ignoring its insides. Q2: What is the one-sentence test of a well-decomposed function? A: you can state its single job in one sentence, and a friend could implement it from the name, parameters, and that sentence alone."}
   ]}',
   'Name functions after their one-sentence contract — a good name is the abstraction.', 14),
  (4, 'Recursion: functions that call themselves', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will read, trace, and write recursive functions — functions that solve a problem by calling themselves on a smaller version of it — and you will know exactly why they stop. Retrieval warm-up from Lesson 3 — from memory: (1) Why must a reusable helper return rather than print its result? (2) What does a call to a function with no return evaluate to? Check: because callers need the value to compute with, and None. Runner open."},
      {"heading":"Smaller and smaller until trivial","text":"A recursive definition has two parts. The base case answers the smallest version of the problem directly, with no further calls. The recursive case does one small piece of work and delegates the rest to the same function called on a SMALLER input. Because every call shrinks the input, the calls must eventually hit the base case and stop — exactly the stopping-condition guarantee from Lesson 2, in new clothes.\n```python\ndef countdown(n):\n    if n == 0:\n        print(\"Go!\")\n    else:\n        print(n)\n        countdown(n - 1)\n```\ncountdown(3) prints 3, then hands countdown(2) the rest of the job; that prints 2 and hands off countdown(1); which prints 1 and hands off countdown(0); the base case prints Go! and the chain unwinds. Four lines of output: 3, 2, 1, Go!. The classic value-returning example is the factorial, n! = n * (n-1) * ... * 1:\n```python\ndef factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n```"},
      {"heading":"Worked example: trace it line by line","text":"Trace print(factorial(4)) by writing each pending call on its own line, then resolving them bottom-up.\n```python\ndef factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(4))\n```\nGoing down: factorial(4) needs 4 * factorial(3); factorial(3) needs 3 * factorial(2); factorial(2) needs 2 * factorial(1); factorial(1) hits the base case, n <= 1, and returns 1 immediately. Now come back up: factorial(2) = 2 * 1 = 2; factorial(3) = 3 * 2 = 6; factorial(4) = 4 * 6 = 24. Exact output:\n```\n24\n```\nEvery call has its own private n — four separate n variables existed at the deepest moment, holding 4, 3, 2, 1 — which is just function scope from Python Foundations doing its normal job. Recursion is not magic; it is many small function calls, each waiting for the next."},
      {"heading":"Your turn","text":"Predict, then run. (1) Trace factorial(5) by hand with the down-then-up method, then verify; expected output: 120. (2) Write sum_to(n) that returns 0 when n == 0 and otherwise returns n + sum_to(n - 1); print(sum_to(4)) — expected output: 10. (3) Predict without running: countdown(2); answer: 2, 1, Go! on three lines. (4) Modify countdown into countup: in the else branch, make the recursive call FIRST and print n after it; countup(3) should print Go!, 1, 2, 3 — trace why the order flips: each print now waits until the deeper calls finish. (5) Write power(base, exp) that returns 1 when exp == 0 and otherwise base * power(base, exp - 1); print(power(2, 5)) — expected output: 32. (6) Stretch: write blastoff(n) that prints the countdown AND the countup in one function — print n, recurse, print n again; blastoff(2) prints 2, 1, Go!... wait, where does Go! go? Put it in the base case; expected: 2, 1, Go!, 1, 2."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — missing base case: def broken(n): return n + broken(n - 1) has no case that stops, so the calls pile up until Python halts them with RecursionError: maximum recursion depth exceeded. Every recursive function needs a base case its inputs actually reach. Bug 2 — recursing in the wrong direction: writing factorial(n + 1) grows the input instead of shrinking it, so the base case is never reached — same RecursionError, different cause. Check both: a base case exists, and every recursive call moves toward it. Exit ticket — Q1: What are the two parts of every recursive function? A: a base case answered directly, and a recursive case that does a little work and calls itself on a smaller input. Q2: In the factorial(4) trace, why did four different n variables exist at once? A: each call gets its own scope with its own parameters — the calls are separate, stacked, and each waits for the one below it to return."}
   ]}',
   'When tracing recursion, write each pending call on its own line and resolve them bottom-up from the base case.', 15),
  (5, 'Checkpoint 1', 'quiz',
   '{"questions":[
      {"prompt":"Trace this program. What does it print?\n```python\ncube = 8\nguess = 0\nwhile guess ** 3 < cube:\n    guess = guess + 1\nprint(guess)\n```","options":["1","2","3","8"],"answer":1,"explanation":"guess climbs 0 -> 1 (0 < 8) -> 2 (1 < 8); then 8 < 8 is False and the loop exits with guess = 2, the cube root of 8. (Lesson 2.)"},
      {"prompt":"In the guess-and-check cube-root program, what guarantees the while loop eventually stops?","options":["guess ** 3 grows every pass, so the condition must eventually become False","The print statement ends the loop","Python stops every loop after 100 passes","The if/else after the loop"],"answer":0,"explanation":"An algorithm needs a stopping condition, and something in the loop must provably move toward it — here guess ** 3 increases each pass until it reaches the target. (Lesson 2.)"},
      {"prompt":"You call len(\"hello\") without ever reading the code inside len. Which idea is that?","options":["Recursion","Abstraction","Enumeration","Iteration"],"answer":1,"explanation":"Abstraction means using something through its contract — give a sequence, get its length — while its implementation stays a black box. (Lesson 3.)"},
      {"prompt":"What does this program print?\n```python\ndef area(w, h):\n    return w * h\n\ndef frame(w, h):\n    return area(w, h) + 2\n\nprint(frame(3, 4))\n```","options":["12","14","24","area(3, 4) + 2"],"answer":1,"explanation":"frame delegates to area, which returns 12, then adds 2, so 14 prints. Functions building on functions is decomposition at work. (Lesson 3.)"},
      {"prompt":"Trace this recursion. What does it print?\n```python\ndef f(n):\n    if n == 0:\n        return 0\n    return n + f(n - 1)\n\nprint(f(3))\n```","options":["3","5","6","RecursionError"],"answer":2,"explanation":"Down: f(3) = 3 + f(2), f(2) = 2 + f(1), f(1) = 1 + f(0), and f(0) returns 0. Up: 1, 3, 6. (Lesson 4.)"},
      {"prompt":"What happens when you call broken(3)?\n```python\ndef broken(n):\n    return n + broken(n - 1)\n```","options":["It returns 6","It returns 0","RecursionError — there is no base case to stop the calls","SyntaxError"],"answer":2,"explanation":"Nothing ever answers a smallest case directly, so the calls descend 3, 2, 1, 0, -1, ... until Python raises RecursionError: maximum recursion depth exceeded. (Lesson 4.)"},
      {"prompt":"What is the exact output of blast(2)?\n```python\ndef blast(n):\n    if n > 0:\n        print(n)\n        blast(n - 1)\n```","options":["1 then 2","2 then 1","2 then 1 then 0","Nothing"],"answer":1,"explanation":"blast(2) prints 2 before recursing, then blast(1) prints 1; blast(0) fails the if and prints nothing. Printing BEFORE the recursive call gives descending order. (Lesson 4.)"}
   ]}',
   null, 10),
  (6, 'Algorithmic efficiency: Big-O intuition', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will judge how the running time of code GROWS as its input gets bigger, and name the growth with Big-O classes: constant, logarithmic, linear, and quadratic. Retrieval warm-up from Lesson 4 — from memory: (1) What are the two parts of a recursive function? (2) Why does factorial(n - 1) guarantee the recursion stops? Check: base case and recursive case; because the input shrinks every call, so it must reach the base case. Runner open."},
      {"heading":"Count the steps, not the seconds","text":"Two correct programs can differ wildly in speed, and the difference that matters is not seconds on your laptop — it is how the work GROWS when the input grows. So we count basic steps as a function of input size n. Look at the innermost line and ask: how many times does it run?\n```python\ndef total(nums):          # n items\n    t = 0\n    for x in nums:\n        t = t + x         # runs n times\n    return t\n```\nThe body runs once per item: double the list, double the work. That is linear growth, written O(n). By contrast, nums[0] takes the same time whatever the length — constant, O(1). A loop INSIDE a loop multiplies: n passes each doing n steps is n * n — quadratic, O(n^2), and doubling the input quadruples the work. Big-O deliberately ignores small constants and lower-order terms: 2n + 5 steps is still O(n), because for large n only the fastest-growing term matters. One more class will star in Lesson 7: a loop that HALVES the problem each pass (like the while n > 1: n = n // 2 pattern) runs only about log2(n) times — logarithmic, O(log n), the class that barely notices huge inputs."},
      {"heading":"Worked example: trace it line by line","text":"Count exactly how many times the innermost line runs.\n```python\nn = 3\ncount = 0\nfor i in range(n):\n    for j in range(n):\n        count = count + 1\nprint(count)\n```\nThe outer loop gives i the values 0, 1, 2. For EACH of those, the inner loop gives j the values 0, 1, 2 and increments count. So: i = 0 contributes 3 increments (count reaches 3), i = 1 contributes 3 more (6), i = 2 finishes the job (9). Exact output:\n```\n9\n```\nThat is n * n = 3 * 3. Predict before you run it: change n to 10 and the output is 100. The shape — every item paired with every item — is the signature of O(n^2). When n goes from 1,000 to 1,000,000 (a thousand times bigger), an O(n) algorithm does a thousand times the work, but an O(n^2) algorithm does a MILLION times the work. Growth class beats clever micro-tweaks every time."},
      {"heading":"Your turn","text":"Predict, then run. (1) Set n = 5 in the worked example; expected output: 25. (2) Classify each snippet as O(1), O(n), or O(n^2): (a) print(items[0]); (b) the total function from above; (c) the nested count loops. Answers: constant, linear, quadratic. (3) A linear search checks list items one by one. If the list doubles from 500 to 1000 items, what happens to the worst-case work? Answer: it doubles — that is what O(n) means. (4) Trace this halving loop and count its passes:\n```python\nn = 64\nwhile n > 1:\n    n = n // 2\n    print(n)\n```\nExpected output: 32, 16, 8, 4, 2, 1 — six lines, and 2 ** 6 = 64; halving loops run about log2(n) times, the O(log n) signature. (5) Write a TRIPLE-nested version of the counting example with n = 2; expected output: 8, and the class is O(n^3). (6) Stretch: rank O(1), O(log n), O(n), O(n^2), O(n^3) from slowest-growing to fastest-growing, and say which you want for big inputs. Answer: the order as listed — and you want the earliest possible."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — calling two sequential loops quadratic: one loop of n passes followed by another loop of n passes is n + n = 2n steps, which is still O(n); only NESTED loops multiply into O(n^2). Sequence adds, nesting multiplies. Bug 2 — timing once with tiny inputs: measuring a 10-item list once tells you almost nothing, because startup noise dominates; growth class only shows itself when you compare timings across sizes that grow by 10x or more — exactly what the course project will do. Exit ticket — Q1: What question does Big-O answer? A: how the work grows as the input size grows — not how many seconds one run takes. Q2: A loop halves its problem every pass; a second loop visits every item once. Name the classes. A: O(log n) and O(n)."}
   ]}',
   'To classify code, find the innermost line and ask one question: how many times does it run as n grows?', 15),
  (7, 'Searching and sorting', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will implement linear search, trace binary search step by step, explain why binary search demands a sorted list, and describe how selection sort puts a list in order. Retrieval warm-up from Lesson 6 — from memory: (1) Sequential loops add, nested loops do what? (2) Which growth class does a halving loop belong to? Check: multiply; O(log n). Runner open — you will trace and run every algorithm here."},
      {"heading":"Two searches, one big idea","text":"Linear search is guess-and-check applied to a list: walk the items left to right until you find the target or run out.\n```python\ndef linear_search(items, target):\n    for i in range(len(items)):\n        if items[i] == target:\n            return i\n    return -1\n```\nIt works on ANY list and its worst case is O(n) — the target is last, or missing. But if the list is SORTED, you can do spectacularly better. Binary search plays the number-guessing game: check the middle item; if it is too small, the target can only live in the right half; too big, only the left half. Each comparison throws away half the remaining region — a halving loop, O(log n). A million sorted items need at most about 20 comparisons.\n```python\ndef binary_search(items, target):\n    low = 0\n    high = len(items) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if items[mid] == target:\n            return mid\n        elif items[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n```\nSorting is how lists earn that superpower. Selection sort, the simplest honest sort: find the smallest item and swap it to position 0, find the smallest of the rest and swap it to position 1, and so on — n passes each scanning up to n items, so O(n^2). Sorting costs something up front; searching many times afterward is where it pays off."},
      {"heading":"Worked example: trace it line by line","text":"Trace binary_search on a sorted list, keeping a table of low, high, and mid.\n```python\nnums = [2, 5, 8, 12, 16, 23, 38]\nprint(binary_search(nums, 23))\n```\nStart: low = 0, high = 6. Pass 1: mid = (0 + 6) // 2 = 3; items[3] is 12; 12 < 23, so the target must be right of mid — low becomes 4. Pass 2: low = 4, high = 6, mid = 5; items[5] is 23 — found! The function returns 5. Exact output:\n```\n5\n```\nTwo comparisons located one value among seven. Now trace the miss: binary_search(nums, 6). Pass 1: mid = 3, 12 > 6, high becomes 2. Pass 2: mid = 1, items[1] = 5 < 6, low becomes 2. Pass 3: low = 2, high = 2, mid = 2, items[2] = 8 > 6, high becomes 1. Now low (2) > high (1), the while condition fails, and the function returns -1: a definitive not here after three looks."},
      {"heading":"Your turn","text":"Predict, then run — use nums = [2, 5, 8, 12, 16, 23, 38] throughout. (1) Trace binary_search(nums, 2) by hand with a low/high/mid table, then verify; expected trace: mid 3 (12 too big), mid 1 (5 too big), mid 0 — found, returns 0. (2) Trace binary_search(nums, 6) yourself and confirm the three passes from the worked example end in -1. (3) Type in linear_search and check both searches agree: linear_search(nums, 23) is 5 and linear_search(nums, 6) is -1. (4) Count comparisons for binary_search(nums, 38): mid 3 (12 too small), mid 5 (23 too small), mid 6 — found; 3 comparisons, where linear search would need 7. (5) Break the contract on purpose: run binary_search([12, 2, 38, 5], 5) — it returns -1 even though 5 is present, because the halving logic assumed order; no crash, just a silently wrong answer. (6) Stretch: add a counter to binary_search that counts loop passes and print it before returning; for a sorted list of 128 items built with list(range(128)), searching for a missing value like 999 should take 8 passes at most — about log2(128) + 1."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — binary search on unsorted data: it does not crash, it just returns wrong answers, which is far more dangerous. Sortedness is a precondition — guarantee it before you call. Bug 2 — forgetting the +1/-1: writing low = mid instead of low = mid + 1 can loop forever when low and high sit next to each other, because mid recomputes to the same value and nothing shrinks — the no-progress bug from Lesson 2 in disguise. Exit ticket — Q1: Worst-case growth class of linear search and of binary search? A: O(n) and O(log n). Q2: Your program searches one list thousands of times — why sort it first, given sorting costs O(n^2)? A: pay the sorting cost once, then every one of the thousands of searches drops from O(n) to O(log n); the up-front cost is repaid many times over."}
   ]}',
   'Binary search is a contract: the list must already be sorted, or the answers are silently wrong.', 15),
  (8, 'Testing, debugging, and exceptions', 'reading',
   '{"sections":[
      {"heading":"Objective and warm-up","text":"By the end of this lesson you will handle runtime errors gracefully with try/except, write miniature unit tests with assert, and debug systematically instead of by staring. Retrieval warm-up from Lesson 7 — from memory: (1) What does binary search return when the target is absent? (2) What goes wrong if you call it on an unsorted list? Check: -1; it returns wrong answers silently, because sortedness is its precondition. Runner open."},
      {"heading":"Errors are events you can plan for","text":"When something impossible happens at runtime — dividing by zero, converting \"dog\" with int, indexing past the end — Python raises an exception: ZeroDivisionError, ValueError, IndexError, KeyError. Unhandled, an exception stops the program with a traceback (read it bottom line first: it names the exception and the line). But you can catch exceptions you expect:\n```python\ntry:\n    age = int(input(\"Age? \"))\nexcept ValueError:\n    print(\"That was not a number\")\n    age = 0\n```\nThe try block runs normally; the moment a ValueError is raised, execution jumps to the except block instead of crashing. Catch only what you expect — a bare except: hides every bug, including your typos. The second tool is assert, a tripwire for things that MUST be true: assert average([2, 4]) == 3.0 passes silently when the code is right and raises AssertionError the instant it is wrong. A unit test is exactly this: one assert per fact, covering the normal case, the boundary case (empty list, zero, first and last element), and the error case. Professionals write the tests FIRST, watch them fail, then fix code until every assert passes silently."},
      {"heading":"Worked example: trace it line by line","text":"A division helper that survives bad input, plus its tests.\n```python\ndef safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n\nprint(safe_divide(10, 4))\nprint(safe_divide(3, 0))\nassert safe_divide(8, 2) == 4.0\nassert safe_divide(1, 0) == None\nprint(\"all tests passed\")\n```\nCall 1: 10 / 4 raises nothing, so the try returns 2.5. Call 2: 3 / 0 raises ZeroDivisionError; execution jumps into except, which returns None, so print shows None — no crash. The first assert calls safe_divide(8, 2), gets 4.0, compares equal: silence. The second assert confirms the error path returns None: silence. Exact output:\n```\n2.5\nNone\nall tests passed\n```\nChange the except line to return 0 and rerun: the second assert now fails with AssertionError, pointing you at exactly what broke. That is the payoff of tests — bugs announce themselves."},
      {"heading":"Your turn","text":"Predict, then run. (1) Predict safe_divide(7, 2); answer: 3.5 — the except path never runs. (2) Write safe_int(text) that returns int(text), catching ValueError to return None; safe_int(\"12\") is 12 and safe_int(\"dog\") is None. (3) Predict this output:\n```python\ntry:\n    nums = [1, 2]\n    print(nums[5])\nexcept IndexError:\n    print(\"no such index\")\n```\nAnswer: no such index — indexing raises before print finishes, and control jumps to except. (4) Write three asserts for def biggest(nums): return max(nums) — normal case biggest([3, 9, 1]) == 9, one-item case biggest([7]) == 7, negative case biggest([-5, -2]) == -2 — then print(\"tests passed\"); expected: silent asserts, then tests passed. (5) This function has a bug: def is_even(n): return n % 2 == 1 — write assert is_even(4) and watch it fail, then fix the function (== 0) and watch the same test pass. That loop — failing test, fix, passing test — is real debugging. (6) Stretch: wrap the safe_int idea in a while True loop that keeps asking until the user types a valid whole number, then breaks; typing dog, cat, 5 should scold twice and accept 5."},
      {"heading":"Common bugs and exit ticket","text":"Bug 1 — the bare except: writing except: with no exception name catches EVERYTHING, including the NameError from a typo you would want to see; your program smiles while deeply broken. Always name the exception you expect. Bug 2 — testing only the happy path: average([2, 4]) passing tells you nothing about average([]), which divides by zero. Boundary inputs — empty, zero, one item, first, last — are where bugs live; every function deserves at least one boundary assert. Exit ticket — Q1: What happens when a line inside try raises the named exception, and when it raises nothing? A: control jumps to the except block; if nothing is raised, except is skipped entirely. Q2: What three kinds of case should a minimal unit-test suite cover? A: the normal case, the boundary case, and the error case."}
   ]}',
   'Write the failing test before the fix — a bug with a test can never sneak back in.', 15),
  (9, 'Checkpoint 2', 'quiz',
   '{"questions":[
      {"prompt":"What does this print?\n```python\nn = 4\ncount = 0\nfor i in range(n):\n    for j in range(n):\n        count = count + 1\nprint(count)\n```","options":["4","8","16","24"],"answer":2,"explanation":"Nested loops multiply: the inner body runs n * n = 16 times. Sequential loops would add; nesting multiplies. (Lesson 6.)"},
      {"prompt":"Which algorithm has O(log n) worst-case growth?","options":["Linear search on any list","Binary search on a sorted list","Selection sort","Summing a list with a loop"],"answer":1,"explanation":"Binary search halves the remaining region every comparison, so a million items need only about 20 looks. Linear search and summing are O(n); selection sort is O(n^2). (Lessons 6-7.)"},
      {"prompt":"Worst case, how many items does linear search examine in a 1000-item list?","options":["1","10","500","1000"],"answer":3,"explanation":"If the target is last or absent, every one of the 1000 items is checked — the meaning of O(n). (Lesson 7.)"},
      {"prompt":"Binary search runs on [1, 3, 5, 7, 9, 11, 13] looking for 5. Which value does it compare against FIRST?","options":["1","5","7","13"],"answer":2,"explanation":"low = 0 and high = 6, so mid = (0 + 6) // 2 = 3, and items[3] is 7. Since 7 > 5, the search continues in the left half. (Lesson 7.)"},
      {"prompt":"What does this print?\n```python\ntry:\n    print(int(\"12\") + 1)\nexcept ValueError:\n    print(\"bad input\")\n```","options":["13","bad input","121","ValueError"],"answer":0,"explanation":"\"12\" converts cleanly to 12, no exception is raised, so the except block is skipped and 13 prints. except only runs when its exception actually occurs. (Lesson 8.)"},
      {"prompt":"total works correctly. What does the line assert total([1, 2]) == 3 do?","options":["Prints True","Prints 3","Nothing visible — it passes silently","Raises AssertionError"],"answer":2,"explanation":"A passing assert is silent; it only makes noise (AssertionError) when its condition is False. Silence is what test success looks like. (Lesson 8.)"},
      {"prompt":"A test shows is_teen(13) returns False but should return True.\n```python\ndef is_teen(age):\n    return age > 13 and age < 20\n```\nWhich fix is correct?","options":["Change age > 13 to age >= 13","Change age < 20 to age <= 20","Swap the two comparisons","Delete the and"],"answer":0,"explanation":"13 is a teen, but age > 13 excludes exactly 13 — a boundary bug. age >= 13 includes it; the failing test told you precisely which edge broke. (Lesson 8.)"}
   ]}',
   null, 10),
  (10, 'Key terms', 'vocab',
   '{"items":[
      {"term":"algorithm","translation":"A precise, finite recipe for solving a problem: simple steps, flow control deciding what runs next, and a stopping condition that guarantees it ends.","example":"Guess-and-check cube root: try guess = 0, 1, 2, ... while guess ** 3 < cube, then test whether the final guess cubed equals the target."},
      {"term":"abstraction","translation":"Using a piece of code through its contract — what goes in, what comes out — while ignoring how it works inside.","example":"You call len(word) every day without ever reading the implementation of len; its contract is all you need."},
      {"term":"decomposition","translation":"Splitting a big problem into small, named, single-job pieces (usually functions) that can be built and tested one at a time.","example":"A statistics program split into average(nums) and spread(nums), each implementable from its one-sentence contract."},
      {"term":"recursion","translation":"A technique where a function solves a problem by calling itself on a smaller version of the same problem.","example":"def factorial(n): return 1 if n <= 1 else n * factorial(n - 1) — factorial(4) delegates to factorial(3), and so on down."},
      {"term":"base case","translation":"The smallest version of a recursive problem, answered directly with no further calls — the reason the recursion stops.","example":"In factorial, if n <= 1: return 1 is the base case; without it the calls never end and Python raises RecursionError."},
      {"term":"complexity (Big-O)","translation":"A label for how the work an algorithm does grows as its input grows: O(1) constant, O(log n) logarithmic, O(n) linear, O(n^2) quadratic.","example":"Nested loops over a list are O(n^2): doubling the list quadruples the running time."},
      {"term":"binary search","translation":"An O(log n) search that works only on sorted lists: compare the middle item, discard the half that cannot contain the target, repeat.","example":"Finding 23 in [2, 5, 8, 12, 16, 23, 38] takes two comparisons: middle 12 (go right), then 23 — found at index 5."},
      {"term":"unit test","translation":"A small automated check, often one assert per fact, that verifies one piece of code on normal, boundary, and error cases and fails loudly when the code breaks.","example":"assert safe_divide(8, 2) == 4.0 and assert safe_divide(1, 0) == None — silent when correct, AssertionError the moment a change breaks the contract."}
   ]}',
   null, 10),
  (11, 'Applied project: implement and analyze search', 'writing',
   '{"sections":[
      {"heading":"The brief","text":"Implement both search algorithms from this course, measure them honestly, and write up what the numbers prove. Spec: (1) write linear_search(items, target) and binary_search(items, target), both returning the index of target or -1 when absent; (2) time both on sorted lists of growing size — at least 1,000, 10,000, 100,000, and 1,000,000 items — always searching for a WORST-CASE target (one that is absent, so linear search must scan everything); (3) present the timings as a small table; (4) write a short findings report (150-300 words) answering: when n grows 10x, what happens to each search time, which Big-O class does each measured pattern match, and when is it worth sorting a list first? Use only time from the standard library — no external packages. Before coding, write your plan as comments: the two function contracts, the list sizes, and how many times you will repeat each measurement. Planning first is the professional habit this project trains."},
      {"heading":"Milestone 1 — guided skeleton","text":"Get one honest measurement working end to end. Copy, run, and understand this skeleton:\n```python\nimport time\n\ndef linear_search(items, target):\n    for i in range(len(items)):\n        if items[i] == target:\n            return i\n    return -1\n\nfor n in [1000, 10000, 100000]:\n    items = list(range(n))\n    start = time.perf_counter()\n    linear_search(items, -1)\n    elapsed = time.perf_counter() - start\n    print(n, round(elapsed * 1000, 3), \"ms\")\n```\nThree things deserve a trace. The target -1 is never in list(range(n)), so every call scans ALL n items — worst case by construction. time.perf_counter() reads a high-precision clock; the difference around the call is the elapsed time, printed in milliseconds. And the sizes grow 10x per row, so a clean O(n) algorithm should show times growing roughly 10x per row — verify that in your output (exact numbers vary by machine; the RATIO between rows is the finding). One-run timings are noisy: wrap the timed call in a small loop that measures 3 times and keeps the minimum — the minimum is the least polluted by background noise."},
      {"heading":"Milestone 2 — independent features","text":"Extend on your own; each feature names the lesson that prepared you for it. (1) Implement binary_search with low/high/mid exactly as specified in Lesson 7, and confirm it returns -1 for the missing target without scanning everything (Lesson 7). (2) Time BOTH functions on the same lists in one loop, adding 1,000,000 to the sizes, and print one table row per size: n, linear ms, binary ms (Lessons 6-7). (3) Add best-of-3 timing from Milestone 1 to every measurement (Lesson 8 discipline: trust tests and repeated evidence, not single runs). (4) Add a verification pass before timing: for a small sorted list, assert both functions agree on every present element and on a missing one — never analyze an implementation you have not tested (Lesson 8). (5) Write the findings report answering the three questions in the brief, quoting your own numbers as evidence. (6) Stretch: also time Python''s built-in \"target in items\" check and place it in your table — which of your two algorithms does its growth pattern resemble?"},
      {"heading":"Test cases","text":"Run every test before you trust any timing; fix failures first. Test 1 — found: linear_search([4, 7, 1], 7) and binary_search([1, 4, 7], 4) both return 1. Test 2 — missing: both return -1 for target 9 on those lists. Test 3 — boundaries: binary_search([1, 3, 5, 7], 1) returns 0 and binary_search([1, 3, 5, 7], 7) returns 3 — first and last positions are where off-by-one bugs hide. Test 4 — empty list: both searches return -1 for [] without crashing (in binary_search, high starts at -1 so the loop never runs). Test 5 — total agreement: for items = list(range(50)), a loop asserts linear_search(items, v) == binary_search(items, v) == v for every v in the list. Test 6 — growth sanity: in your final table, linear time at n = 1,000,000 must be roughly 10x its n = 100,000 time, while binary time barely moves between those rows; if binary search grows like linear, your implementation is scanning — re-check the low/high updates."},
      {"heading":"Self-check rubric","text":"Score yourself 1-4 on each axis; 12 or more overall (with no axis at 1) means the project is complete. Correctness: all six test cases pass exactly as described, including the empty list and both boundaries. Measurement quality: worst-case (absent) targets, best-of-3 timing, sizes spanning at least three factors of 10, and a readable table. Analysis: the report quotes your own numbers, matches linear search to O(n) and binary search to O(log n) by the RATIOS between rows, and answers when sorting first pays off (many searches amortize one sort). Understanding — the axis that matters most: without running anything, you can hand-trace binary_search on a seven-item list for any target, state how many comparisons each search needs at n = 1,000,000 (about a million versus about 20), and explain why one timed run is weaker evidence than the minimum of three. If any axis scored 1, revisit the lesson named in that milestone and revise before calling it done."}
   ]}',
   null, 15),
  (12, 'Final assessment', 'quiz',
   '{"questions":[
      {"prompt":"Trace this recursion. What does it print?\n```python\ndef mystery(n):\n    if n <= 1:\n        return 1\n    return n * mystery(n - 2)\n\nprint(mystery(6))\n```","options":["720","48","36","RecursionError"],"answer":1,"explanation":"Down: mystery(6) = 6 * mystery(4), mystery(4) = 4 * mystery(2), mystery(2) = 2 * mystery(0), and mystery(0) hits the base case returning 1. Up: 2, 8, 48 — the even numbers 6 * 4 * 2."},
      {"prompt":"Which Big-O class describes pairs?\n```python\ndef pairs(nums):\n    for a in nums:\n        for b in nums:\n            print(a, b)\n```","options":["O(1)","O(n)","O(n^2)","O(log n)"],"answer":2,"explanation":"For each of the n values of a, the inner loop runs n times — nested loops multiply into n * n, the quadratic signature."},
      {"prompt":"Worst case, about how many comparisons does binary search need on a SORTED list of 1024 items?","options":["10","100","512","1024"],"answer":0,"explanation":"Each comparison halves the region: 1024 -> 512 -> 256 -> ... -> 1 is 10 halvings, since 2 ** 10 = 1024. That is O(log n) in action."},
      {"prompt":"binary_search(nums, target) returns -1. What does that mean?","options":["The list was unsorted","target is not in the list","target is at the last index","An exception was raised"],"answer":1,"explanation":"-1 is the agreed not-found signal: low passed high without ever landing on the target. (On an UNSORTED list the result would be meaningless — but -1 itself means not found.)"},
      {"prompt":"Your input sizes will be huge. Which growth class should you prefer?","options":["O(n^2)","O(n)","O(log n)","O(n^3)"],"answer":2,"explanation":"Logarithmic work barely grows: a million items cost only about 20 steps. Of the classes listed, O(log n) grows slowest as n explodes."},
      {"prompt":"What does this print?\n```python\ndef get(d, key):\n    try:\n        return d[key]\n    except KeyError:\n        return 0\n\nprint(get({\"a\": 1}, \"b\") + get({\"a\": 1}, \"a\"))\n```","options":["0","1","2","KeyError"],"answer":1,"explanation":"The first call raises KeyError inside try and returns the fallback 0; the second finds the key and returns 1. So 0 + 1 = 1 prints — exceptions handled, no crash."},
      {"prompt":"Trace this recursion. What is the exact output of echo(3)?\n```python\ndef echo(n):\n    if n == 0:\n        return\n    echo(n - 1)\n    print(n)\n```","options":["3, 2, 1 on three lines","1, 2, 3 on three lines","3, 3, 3 on three lines","Nothing"],"answer":1,"explanation":"Each call recurses BEFORE printing, so every print waits for the deeper calls to finish: echo(1) prints first (1), then 2, then 3. Printing after the recursive call gives ascending order."},
      {"prompt":"average works for most inputs:\n```python\ndef average(nums):\n    return sum(nums) / len(nums)\n```\nWhich input exposes a bug a unit test should cover?","options":["[1, 2, 3]","[]","[5]","[0, 0]"],"answer":1,"explanation":"The empty list makes len(nums) zero, so the division raises ZeroDivisionError. Boundary cases — empty, zero, one item — are exactly where tests earn their keep; [0, 0] is fine (0.0)."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'bbbb0002-0000-4000-8000-000000000004' and l.position = v.pos
);
