-- English advanced pack (dialect: US): "Seminar & Exam Mastery" — a C1 course
-- built on elite-university teaching methods, all with original content:
--   case method        — an original business case with an open decision
--   tutorial essays    — thesis–antithesis–synthesis writing with a self-check rubric
--   debate seminars    — oral argument under pushback from a demanding interlocutor
--   capstone project   — a self-directed 5-minute presentation with milestones
-- Also targets C1 Advanced / TOEFL-style reading, cloze, and inference tasks.
-- Fixed UUIDs make re-runs idempotent (insert … on conflict / where not exists).
-- The "translation" field holds a simple-English definition, since the target
-- language is English itself.

-- ============ English C1 — Seminar & Exam Mastery ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published)
values (
  'aaaa0005-0000-4000-8000-000000000004',
  'en', 'us',
  'English — Seminar & Exam Mastery',
  'Argue, write, and present at an academic level. Work through a business case using the case method, draft tutorial essays, hold your own in debate seminars, and build a capstone presentation — while sharpening the connectors, register, and inference skills tested in C1 Advanced and TOEFL-style exams.',
  'C1', 'work', 13, true
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'aaaa0005-0000-4000-8000-000000000004', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Case study: Meridian Home goes to America?', 'reading',
   '{"sections":[
      {"heading":"The facts","text":"Meridian Home is a mid-sized Dutch retailer of affordable, design-led furniture and homeware, with 214 stores across nine European countries and annual revenue of 1.8 billion euros. Its model rests on three pillars: compact urban stores rather than out-of-town warehouses, a tightly edited catalog of roughly 2,000 items, and a supply chain built around rail freight within Europe. Growth at home has slowed to 2 percent a year, and the board has asked the executive team to evaluate entry into the United States, beginning with a pilot of eight stores in either the Northeast corridor or Texas. Initial capital required: 140 million dollars over three years."},
      {"heading":"The tension","text":"The leadership team is split. The chief commercial officer argues that the American market is precisely where Meridian''s urban, small-format concept can win, since the dominant players rely on enormous suburban showrooms that younger city dwellers find inconvenient. The chief financial officer counters that Meridian''s cost advantage evaporates once its European rail logistics are replaced by trans-Atlantic shipping and American trucking, and she notes that several European retailers have retreated from the US after underestimating regional differences in taste, sizing, and service expectations. Meanwhile, a private equity firm has approached the board with an alternative: acquire a struggling 30-store American chain and convert it to the Meridian brand, which would be faster but would saddle the company with leases and staff it did not choose."},
      {"heading":"The decision — and your task","text":"The board meets in six weeks and expects a single recommendation: enter organically with the eight-store pilot, enter by acquisition, or decline to enter and return capital to shareholders. There is no hidden right answer; each path carries defensible logic and real risk. Prepare your position by working through these questions: Which two or three facts in the case do the most work in your reasoning, and why? What would have to be true for the CFO''s cost objection to sink the organic pilot? What is the strongest argument against the option you favor, and how do you answer it? Finally, draft a one-sentence recommendation you could defend aloud — you will need it in the next lesson."}
   ]}',
   null, 15),
  (2, 'Seminar: defend your recommendation', 'roleplay',
   '{"scenario":"A graduate seminar room, ten minutes into the discussion of the Meridian Home case. The professor calls on you first: state your recommendation — organic entry, acquisition, or no entry — and justify it from the facts of the case. Expect to be interrupted, quoted back to yourself, and asked what would change your mind.","persona":"Exacting seminar professor who never accepts a first answer, always asks exactly two probing follow-up questions, and expects you to cite specific facts from the case rather than general opinions","goal":"State a clear recommendation in one sentence, support it with at least two specific facts from the case, and answer both follow-up questions without abandoning your position"}',
   null, 12),
  (3, 'The language of academic argument', 'vocab',
   '{"items":[
      {"term":"nevertheless","translation":"a formal way to say but or even so, when accepting one point and then opposing it","ipa":"ˌnɛvərðəˈlɛs","example":"The pilot is expensive; nevertheless, it is the only option that limits our downside risk."},
      {"term":"it is worth noting","translation":"a phrase that introduces a relevant fact the reader may have missed","ipa":"ɪt ɪz wɜrθ ˈnoʊtɪŋ","example":"It is worth noting that several European retailers have already retreated from the US market."},
      {"term":"in essence","translation":"a phrase meaning when reduced to its most basic point","ipa":"ɪn ˈɛsəns","example":"In essence, the board must choose between speed and control."},
      {"term":"contend","translation":"to argue or claim something, especially in a debate where others disagree","ipa":"kənˈtɛnd","example":"The CFO contends that the cost advantage disappears once shipping is factored in."},
      {"term":"call into question","translation":"to make people doubt something that was accepted before","ipa":"kɔl ˈɪntu ˈkwɛstʃən","example":"The failed acquisitions of the 1990s call into question the wisdom of buying a struggling chain."},
      {"term":"compelling","translation":"so convincing or interesting that it demands attention","ipa":"kəmˈpɛlɪŋ","example":"She made a compelling case for delaying entry until the supply chain question is resolved."}
   ]}',
   'These expressions signal that you are managing an argument, not just stating opinions. *Nevertheless* and *it is worth noting* belong to formal registers — in a seminar they sound precise; in a text message they sound absurd. *Contend* implies a live dispute: you *contend* something when others might push back.', 10),
  (4, 'Connectors, inversion, and hedging', 'grammar',
   '{"sections":[
      {"heading":"Advanced connectors: managing the flow of an argument","text":"C1 writing moves beyond *however* and *therefore*. To concede before countering, use *granted* or *admittedly*: Admittedly, the acquisition is faster; the leases it drags along, however, are a ten-year commitment. To add a stronger point, use *moreover* or *what is more*. To signal consequence with weight, use *consequently* or *hence*. Two traps: *on the contrary* rejects what came before (it does not mean *on the other hand*), and *thereby* must attach to a noun-plus-ing structure: The firm cut prices, thereby triggering a war it could not win."},
      {"heading":"Inversion for emphasis","text":"When a negative or restrictive adverbial opens the sentence, subject and auxiliary invert, exactly as in a question: Not only did the pilot lose money, but it also damaged the brand. Rarely has a board faced so stark a choice. Under no circumstances should the company sign those leases. Only after the second quarter did the pattern become clear. The mechanics: move the adverbial to the front, then invert — *did the pilot lose*, not *the pilot lost*. In the *Not only… but also* pattern, inversion happens only in the first clause. Use this structure sparingly; one inversion per essay lands with force, while five sound theatrical."},
      {"heading":"Hedging: sounding cautious on purpose","text":"Academic English rewards calibrated claims. Instead of *This proves the strategy failed*, write *This would suggest that the strategy was flawed* or *The evidence points to a weakness in the strategy*. The toolkit: modal verbs (*may, might, could*), cautious verbs (*suggest, indicate, appear, tend to*), and distancing frames (*It could be argued that…, To some extent…, The data are consistent with…*). Hedging is not weakness — it is accuracy about how much your evidence can carry. The skill is matching the hedge to the claim: hedge boldly stated speculation, and state firmly what the facts genuinely establish."}
   ]}',
   null, 14),
  (5, 'Tutorial essay: the remote work question', 'writing',
   '{"sections":[
      {"heading":"The brief","text":"Write a 250-word argumentative essay on this prompt: Should companies be free to require full-time office attendance? You will build it the tutorial way — not by listing points, but by staging a controlled argument in three moves: thesis, antithesis, synthesis. Before writing, decide your genuine position; essays written against your own view tend to collapse in the final paragraph."},
      {"heading":"Thesis, antithesis, synthesis","text":"Paragraph one — thesis: state your position in one sharp sentence, then give your strongest reason with a concrete example (a company, a study, a cost). Paragraph two — antithesis: present the best opposing argument as fairly as you can, using concessive language: Admittedly… / It could be argued that… / Proponents of mandatory attendance contend that… An essay that strawmans its opposition convinces no examiner. Paragraph three — synthesis: do not simply repeat the thesis. Show what survives the collision — perhaps your position holds, but only under conditions the antithesis revealed: Companies should retain the right to require attendance, yet only where the work itself, rather than managerial habit, demands it."},
      {"heading":"Self-check rubric","text":"Before you consider the essay finished, score yourself against five questions. Position: could a stranger state your view after reading only the first sentence? Evidence: does each claim lean on something concrete, not just on adverbs? Concession: did you present the opposing view in a form its supporters would recognize? Language: did you use at least two connectors from lesson four, one hedge, and at most one inversion? Length and economy: are you within 230 to 270 words, with no sentence that merely repeats another? Revise until you can answer yes five times."}
   ]}',
   null, 15),
  (6, 'Debate: ID verification on social media', 'roleplay',
   '{"scenario":"A formal debate seminar. The motion: social media platforms should require government ID verification for all accounts. You may argue either side, but you must open with a one-minute case — a clear claim supported by two distinct arguments — and then survive cross-examination. Your opponent will attack your weakest premise first.","persona":"Sharp, fast-thinking debate opponent who listens closely, concedes nothing, and pushes back exactly twice — first with a counter-example to your main argument, then by exposing a hidden assumption in your reasoning","goal":"Deliver a structured opening case, respond to both pushbacks without contradicting yourself, and use at least three argumentation phrases such as that argument rests on the assumption that, the evidence points the other way, or granted, but"}',
   null, 12),
  (7, 'Exam reading: the op-ed on housing', 'reading',
   '{"sections":[
      {"heading":"Read: The Quiet Arithmetic of Empty Skylines","text":"Every few months, a city council somewhere unveils an affordable housing initiative with a ribbon, a rendering, and a number: five hundred units, perhaps a thousand. The applause is genuine, and so, unfortunately, is the arithmetic that follows. A metropolitan area short by two hundred thousand homes does not solve its crisis five hundred units at a time; it solves the politics of appearing to act. What such announcements rarely mention is the machinery working in the opposite direction — zoning codes that make apartment buildings illegal on most residential land, environmental review processes that can be weaponized by anyone with a lawyer and a grievance, and public consultation formats that systematically amplify those with the time and property interest to attend evening meetings. As you read, ask yourself: what is the author implying about who actually attends those meetings, and why does the word unfortunately sit where it does in the second sentence?"},
      {"heading":"Read on: the argument sharpens","text":"Defenders of the current system speak the language of neighborhood character, and it would be too easy to dismiss them as mere obstructionists. Many are sincere. Sincerity, however, is not the test of a policy; consequences are. When a city makes new housing nearly impossible to build, it does not freeze itself in amber — it quietly selects who may live there, awarding the future to those who arrived early and priced-out commutes to everyone else. The remedy is not deregulation as ideology but honesty as method: legalize modest apartment buildings near transit, set review deadlines that cannot be extended indefinitely, and measure officials by homes completed rather than initiatives announced. Inference check: the author concedes that defenders are sincere — what rhetorical purpose does that concession serve? And what does the phrase awarding the future imply about how the author views inaction: as neutral, or as a decision in itself?"},
      {"heading":"Working the questions like an examiner","text":"C1 reading tasks rarely ask what the text says; they ask what it does. Three moves to practice on this op-ed. First, tone: is the author angry, resigned, or coolly analytical? Find the two words that settle it. Second, implication: the author never states that public meetings are unrepresentative — the claim is smuggled in through the phrase those with the time and property interest to attend. Rewrite that implication as a direct sentence. Third, structure: the final paragraph pivots on the sentence Sincerity, however, is not the test of a policy; consequences are. Explain in one sentence why the entire argument depends on that pivot — and notice that being able to explain it is exactly what the exam is testing."}
   ]}',
   null, 15),
  (8, 'Register: choosing the formal twin', 'vocab',
   '{"items":[
      {"term":"obtain (vs. get)","translation":"the formal twin of get — used for acquiring something through effort or procedure","ipa":"əbˈteɪn","example":"Applicants must obtain written approval before construction begins."},
      {"term":"endeavor (vs. try)","translation":"the formal twin of try — a serious, sustained attempt","ipa":"ɪnˈdɛvər","example":"The committee will endeavor to publish its findings by March."},
      {"term":"substantial (vs. big)","translation":"the formal twin of big — large enough to matter, often for amounts and effects","ipa":"səbˈstænʃəl","example":"The merger produced substantial savings in the first year alone."},
      {"term":"ascertain (vs. find out)","translation":"the formal twin of find out — to establish a fact with certainty","ipa":"ˌæsərˈteɪn","example":"Auditors were unable to ascertain when the funds were transferred."},
      {"term":"constitute (vs. make up / be)","translation":"a formal verb meaning to be or to form the parts of something","ipa":"ˈkɑnstəˌtut","example":"Rail shipments constitute nearly half of the company''s logistics costs."},
      {"term":"notwithstanding (vs. despite)","translation":"a very formal twin of despite — used in academic and legal writing","ipa":"ˌnɑtwɪθˈstændɪŋ","example":"Notwithstanding the board''s objections, the pilot went ahead."}
   ]}',
   'Register is a dial, not a switch. In an essay or report, the formal twin usually wins: *obtain approval*, *substantial savings*. In speech — even in a seminar — the plain word often sounds more confident: *We need to find out what went wrong* beats *We must ascertain the cause*. Mixing registers in one sentence (*We shall endeavor to fix this asap*) is the error examiners catch fastest.', 10),
  (9, 'Capstone: your five-minute presentation', 'writing',
   '{"sections":[
      {"heading":"The project brief","text":"Design and outline a five-minute presentation, in English, on a professional question you genuinely care about — a decision your team faces, a trend in your field, a tool your industry should adopt or abandon. The constraint is the point: five minutes forces choices. Your deliverable for this lesson is not the talk itself but its architecture — a one-page outline containing a title, a single-sentence core claim, three supporting sections of roughly ninety seconds each, and a closing that tells the audience precisely what to do or believe differently."},
      {"heading":"Milestones","text":"Work in four stages. Milestone one — the claim: write and rewrite your core sentence until it is arguable; a claim nobody could disagree with is a topic, not a thesis. Milestone two — the skeleton: for each of the three sections, note its function (context, evidence, objection-and-answer works well), its single key fact or example, and the connector that will carry you into it. Milestone three — the open and close: script your first and last two sentences word for word; these are the only lines you should memorize. Milestone four — the rehearsal: deliver the talk aloud twice against a timer, once at natural speed and once deliberately slower, marking every place you reached for a word that was not there."},
      {"heading":"Evaluation criteria","text":"Judge the outline as an examiner would, across five dimensions. Argument: is there one claim, and does every section serve it? Structure: could a listener reconstruct your outline from the talk alone, guided by your connectors? Language range: does the outline deploy the course toolkit — two advanced connectors, one hedge, one inversion, and formal register where the content demands it? Economy: is anything decorative rather than load-bearing? Delivery readiness: do the scripted opening and closing survive being spoken aloud, not just read silently? A strong capstone scores yes on all five; a passable one fails on economy alone."}
   ]}',
   null, 15),
  (10, 'C1 checkpoint', 'quiz',
   '{"questions":[
      {"prompt":"Choose the connector: The acquisition would be faster. ___, it would bind the company to leases it never chose.","options":["On the contrary","Nevertheless","Hence","Moreover"],"answer":1,"explanation":"The second sentence concedes and counters, so *Nevertheless* fits. *On the contrary* would reject the first sentence, *Hence* signals consequence, and *Moreover* adds a point in the same direction."},
      {"prompt":"Which sentence uses inversion correctly?","options":["Rarely a board has faced such a stark choice.","Not only the pilot lost money, but it also hurt the brand.","Under no circumstances should the company sign those leases.","Only after the second quarter the pattern became clear."],"answer":2,"explanation":"After a negative or restrictive opening, subject and auxiliary must invert: *should the company sign*. The other options keep normal word order, so the inversion fails."},
      {"prompt":"Which version is the best hedge for a cautious academic claim?","options":["This proves the strategy failed.","This would suggest that the strategy was flawed.","Everyone knows the strategy failed.","The strategy failed, period."],"answer":1,"explanation":"*Would suggest* combines a modal with a cautious verb — a calibrated claim. The other options overstate what the evidence can establish."},
      {"prompt":"In the housing op-ed, the author calls announcements of five hundred units solving the politics of appearing to act. What is implied?","options":["The units are poorly built.","Officials gain credit for action without addressing the real shortage.","Five hundred units is the correct scale for most cities.","The author supports the current zoning codes."],"answer":1,"explanation":"The phrase implies the announcements serve officials'' image rather than the housing shortfall — an inference, since the text never states it directly."},
      {"prompt":"Pick the formal register for a written report: We need to ___ approval before the meeting.","options":["grab","get hold of","obtain","score"],"answer":2,"explanation":"*Obtain* is the formal twin of *get* and suits written reports. *Grab*, *get hold of*, and *score* are conversational or slang."},
      {"prompt":"Complete the concession: ___, the pilot limits risk; the acquisition, however, buys speed the market may not wait for.","options":["Admittedly","Consequently","In essence","Thereby"],"answer":0,"explanation":"*Admittedly* concedes a point before countering it. *Consequently* draws a conclusion, *In essence* summarizes, and *Thereby* must attach to a noun-plus-ing structure."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'aaaa0005-0000-4000-8000-000000000004' and l.position = v.pos
);
