-- Italian advanced course: 'Italian — Seminar & Exam Mastery' (C1, dialect 'it').
-- Implements elite-university teaching methods — case method, tutorial essays,
-- debate seminars, and a capstone project — with entirely original content.
-- Fixed UUID makes re-runs idempotent: the course uses `on conflict (id) do nothing`,
-- lessons are guarded by a `where not exists` on (course_id, position).

-- ============ Italian C1 — Seminar & Exam Mastery ============
insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published)
values (
  'aaaa0003-0000-4000-8000-000000000004',
  'it', 'it',
  'Italian — Seminar & Exam Mastery',
  'Study Italian the way top seminars are run: analyse an original business case (case method), write tutorial-style argumentative essays, hold your own in debate seminars, and build a capstone presentation — all while preparing for the CILS and CELI C1 exams.',
  'C1', 'work', 13, true
) on conflict (id) do nothing;

insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)
select 'aaaa0003-0000-4000-8000-000000000004', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins
from (values
  (1, 'Il caso Molino Serra: espandersi o restare artigiani?', 'reading',
   '{"sections":[
      {"heading":"I fatti","text":"*Il Molino Serra è un''azienda familiare di Cuneo che da tre generazioni produce pasta fresca e grissini artigianali. Fondata nel 1952 dal nonno Attilio, oggi è guidata dalla nipote Chiara Serra, trentotto anni, laureata in economia. L''azienda conta ventidue dipendenti, un unico stabilimento e tre punti vendita in Piemonte. Negli ultimi cinque anni il fatturato è cresciuto del quaranta per cento, trainato dal turismo enogastronomico e da una clientela fedele che considera il marchio sinonimo di qualità. Un fondo di investimento ha appena proposto a Chiara di trasformare il Molino Serra in un franchising nazionale: cinquanta punti vendita in tre anni, produzione parzialmente delocalizzata, capitale immediato.* Read this first section as a case analyst would: underline every number and every fact that could support — or undermine — a decision."},
      {"heading":"La tensione","text":"*Il consiglio di famiglia è spaccato. Lo zio Franco, responsabile della produzione, sostiene che il franchising snaturerebbe l''identità del marchio: \"Se la pasta non la facciamo noi, con le nostre mani, non è più il Molino Serra.\" La sorella minore, Elena, ribatte che senza crescita l''azienda rischia di essere schiacciata dalla grande distribuzione: \"O cresciamo adesso, o tra dieci anni chiudiamo.\" Chiara, dal canto suo, teme che rifiutare l''offerta significhi perdere un''occasione irripetibile, ma sa anche che il novanta per cento dei franchising alimentari perde il controllo della qualità entro il quinto anno. Il fondo aspetta una risposta entro un mese.* Note how each character embodies one strategic position — this is the classic structure of a teaching case."},
      {"heading":"La decisione aperta — domande per il seminario","text":"The case ends, deliberately, without a resolution: you must supply one. Prepare answers in Italian to these seminar questions before the next lesson. *1) Quali sono i tre fatti più rilevanti per la decisione, e perché? 2) Che cosa rischia davvero il Molino Serra se accetta? E se rifiuta? 3) Esiste una terza via tra il franchising totale e lo status quo? 4) Se lei fosse Chiara, che cosa farebbe entro il mese, e con quali argomenti convincerebbe lo zio Franco?* There is no correct answer — only well-defended and poorly-defended ones."}
   ]}',
   null, 14),
  (2, 'Seminario: difendi la tua raccomandazione', 'roleplay',
   '{"scenario":"A graduate seminar room. You have read the Molino Serra case and must open the discussion by stating your recommendation — accept the franchise offer, refuse it, or propose a third way — and defend it under close questioning. The professor will probe your weakest assumption, ask for evidence from the case, and force you to consider the strongest counterargument.","persona":"Exacting seminar professor who never accepts a claim without evidence, interrupts vague answers with \"Su quali dati si basa?\", and respects only students who concede a point gracefully and then rebuild their argument","goal":"State a clear recommendation in Italian, support it with at least three facts from the case, and survive two rounds of critical questioning without abandoning your position"}',
   null, 12),
  (3, 'Lessico accademico dell''argomentazione', 'vocab',
   '{"items":[
      {"term":"tuttavia","translation":"however, nevertheless","ipa":"tut.taˈvi.a","example":"I dati sono incoraggianti; tuttavia, il campione è troppo ristretto per trarre conclusioni."},
      {"term":"occorre sottolineare che","translation":"it must be emphasized that","ipa":"okˈkor.re sot.to.li.neˈa.re ke","example":"Occorre sottolineare che l''autore non fornisce alcuna fonte per questa affermazione."},
      {"term":"in sintesi","translation":"in summary, to sum up","ipa":"in ˈsin.te.zi","example":"In sintesi, la proposta è valida sul piano economico ma debole su quello etico."},
      {"term":"sostenere che","translation":"to argue / maintain that","ipa":"sos.teˈne.re ke","example":"L''economista sostiene che il franchising diluisca inevitabilmente il valore del marchio."},
      {"term":"mettere in discussione","translation":"to call into question, to challenge","ipa":"ˈmet.te.re in dis.kusˈsjo.ne","example":"Nessuno finora ha messo in discussione la premessa centrale del rapporto."},
      {"term":"alla luce di","translation":"in light of, given","ipa":"ˈal.la ˈlu.tʃe di","example":"Alla luce di questi risultati, la strategia iniziale va completamente ripensata."}
   ]}',
   'These connectors mark the register examiners listen for at C1. *Tuttavia* outranks *ma* in formal prose and can open a sentence, which *ma* traditionally should not. *Sostenere che* takes the **congiuntivo** when the claim is presented as debatable: *sostiene che sia...*. Impersonal *occorre* (= *è necessario*) is a hallmark of academic Italian — prefer it to *bisogna* in writing.', 10),
  (4, 'Congiuntivo avanzato e periodo ipotetico', 'grammar',
   '{"sections":[
      {"heading":"Concessive clauses — benché, sebbene, nonostante","text":"Concessive conjunctions concede a fact while denying its expected consequence, and they demand the subjunctive: *Benché l''offerta sia generosa, Chiara esita* (Although the offer is generous, Chiara hesitates). *Sebbene* and *nonostante* work the same way: *Sebbene i dati fossero chiari, il consiglio ha rinviato la decisione*. Register trap: *anche se* expresses the same idea with the indicative and is fine in speech, but in a C1 essay *benché + congiuntivo* signals command of formal syntax. Match the tense: present main clause → *sia*; past main clause → *fosse*."},
      {"heading":"Purpose and condition — affinché, purché, a patto che","text":"*Affinché* introduces purpose and always takes the subjunctive: *Ripeto i dati affinché tutti possano seguire il ragionamento* (I repeat the data so that everyone can follow the reasoning). Do not confuse it with *perché* + indicative, which gives a cause, not a goal. *Purché* and *a patto che* state a condition for the main clause to hold: *Accetterò il franchising purché la produzione resti a Cuneo* (I will accept the franchise provided production stays in Cuneo). *A meno che non* (\"unless\") also requires the subjunctive, and its *non* is expletive — it does not negate: *Firmeremo, a meno che il fondo non cambi le condizioni*."},
      {"heading":"Il periodo ipotetico — three degrees of reality","text":"Italian grades hypotheticals by likelihood. **Realtà**: *se* + indicative in both clauses — *Se accettiamo, il capitale arriva subito*. **Possibilità**: *se* + congiuntivo imperfetto, conditional in the main clause — *Se accettassimo, perderemmo il controllo della qualità* (If we accepted, we would lose quality control). **Irrealtà** (counterfactual past): *se* + congiuntivo trapassato, past conditional — *Se il nonno avesse venduto nel 1980, oggi il marchio non esisterebbe*. Exams love the mixed type: past condition, present result — *Se avessimo firmato allora, adesso saremmo una catena nazionale*. Never let the conditional invade the *se*-clause: *se avrei* is the classic error that costs a band at C1."}
   ]}',
   null, 15),
  (5, 'Saggio tutoriale: tesi, antitesi, sintesi', 'writing',
   '{"sections":[
      {"heading":"The tutorial method and the tesi-antitesi-sintesi frame","text":"In a tutorial you defend a written argument one-on-one, so the essay must anticipate objections before the tutor raises them. The classic Italian frame does exactly that. **Tesi**: state your claim and your strongest reason — *Sostengo che il lavoro da remoto vada regolato, non abolito, perché...*. **Antitesi**: present the best opposing argument honestly, introduced by a concessive — *Benché i critici sostengano che l''ufficio favorisca la creatività...*. **Sintesi**: resolve the tension with a position that absorbs the objection — *In sintesi, la vera questione non è dove si lavora, ma come si misura il risultato*. An essay without a genuine antitesi is a speech, not an argument."},
      {"heading":"Il compito — 250 parole sul lavoro da remoto","text":"Write a 250-word argumentative essay in Italian answering: *Il lavoro da remoto rende le aziende più produttive o più fragili?* Requirements: one clear tesi in the first paragraph; one antitesi introduced with *benché*, *sebbene* or *tuttavia*; one sintesi that goes beyond a simple compromise; at least two connectors from lesson 3; at least one *periodo ipotetico* of the possibility type (*se + congiuntivo imperfetto*). Draft, then read it aloud once — C1 prose that cannot be read aloud smoothly is usually overloaded."},
      {"heading":"Rubrica di autovalutazione","text":"Score yourself 1–4 on each criterion before considering the essay finished. **Argomentazione**: is the tesi arguable (not a fact) and does the antitesi represent the opposing view at its strongest? **Coesione**: does every paragraph open with a connector or a signpost (*in primo luogo*, *tuttavia*, *alla luce di quanto detto*)? **Sintassi**: at least one concessive with the subjunctive and one hypothetical, both correct? **Registro**: no colloquialisms (*un sacco di*, *tipo*), no repeated *fare* where a precise verb exists? Anything scoring below 3: revise that dimension only, and rescore. This is exactly how CILS raters segment their marks."}
   ]}',
   null, 15),
  (6, 'Dibattito: il turismo di massa nelle città d''arte', 'roleplay',
   '{"scenario":"A formal debate seminar on the motion: \"Il turismo di massa va limitato nelle città d''arte?\" You choose a side — limits (numeri chiusi, ticket d''ingresso, tetti agli affitti brevi) or open access (libertà di movimento, economia locale, rischio di città-museo per soli ricchi) — deliver a one-minute opening statement, and then defend it through two structured rebuttals before giving a closing sentence that concedes one point and wins on another.","persona":"Sharp debate opponent who argues the opposite side with real conviction and pushes back exactly twice: first attacking your weakest piece of evidence, then forcing a concrete dilemma such as \"E chi decide chi può entrare a Venezia — e chi no?\"","goal":"Deliver an opening, survive both rebuttals using concessive structures (benché, pur ammettendo che) instead of simple denial, and close by conceding one point while carrying your main argument"}',
   null, 12),
  (7, 'Lettura d''esame: l''Italia che invecchia', 'reading',
   '{"sections":[
      {"heading":"L''editoriale — parte prima","text":"*C''è un paradosso che l''Italia si ostina a non guardare in faccia: mai il Paese è stato così longevo, e mai così povero di bambini. Nel giro di una generazione, il numero medio di figli per donna è sceso sotto quota 1,2, mentre l''aspettativa di vita sfiora gli ottantaquattro anni. Le conseguenze non sono una previsione: sono già in corso. Scuole che chiudono nei paesi dell''Appennino, reparti di maternità accorpati, e un sistema pensionistico che regge soltanto perché l''età del ritiro continua, silenziosamente, a slittare in avanti.* Inference check — the author writes *si ostina a non guardare in faccia*: what does this verb choice imply about how the author judges the national debate? Is the tone neutral, alarmed, or accusatory?"},
      {"heading":"L''editoriale — parte seconda","text":"*I rimedi proposti finora somigliano a cerotti su una frattura. Gli assegni familiari, per quanto benvenuti, non hanno spostato le nascite di un decimale: nessuna coppia decide di avere un figlio per cento euro al mese. L''immigrazione, che pure compensa in parte il calo demografico, viene discussa quasi soltanto come problema di ordine pubblico, mai come politica industriale. E intanto le regioni del Mezzogiorno perdono i giovani due volte: prima verso il Nord, poi verso l''estero.* Inference check — *cerotti su una frattura* is a metaphor: what exactly is the author claiming about family allowances without saying it directly? And what does *perdono i giovani due volte* imply about internal migration?"},
      {"heading":"L''editoriale — conclusione e domande CILS","text":"*La demografia non si inverte per decreto. Ma un Paese che considera la natalità un affare privato e l''immigrazione un''emergenza permanente ha già scelto il proprio futuro: sarà più piccolo, più vecchio e più diseguale. La domanda non è se cambiare, bensì se farlo per scelta o per necessità.* Exam-style questions, in the CILS multiple-inference format: *1) L''autore ritiene che gli assegni familiari siano a) inutili in assoluto b) insufficienti da soli c) dannosi d) la soluzione principale? 2) Secondo il testo, l''immigrazione viene trattata nel dibattito pubblico soprattutto come... 3) Che cosa intende l''autore con \"per scelta o per necessità\"?* Answer in Italian, citing the exact phrase that supports each inference — CILS rewards evidence, not intuition."}
   ]}',
   null, 14),
  (8, 'Registro: quasi-sinonimi formali', 'vocab',
   '{"items":[
      {"term":"richiedere (vs chiedere)","translation":"to request, to require (formal)","ipa":"ri.kjeˈde.re","example":"Per accedere all''archivio occorre richiedere un''autorizzazione scritta."},
      {"term":"recarsi (vs andare)","translation":"to go, to proceed to a place (formal)","ipa":"reˈkar.si","example":"I candidati sono pregati di recarsi in aula magna entro le nove."},
      {"term":"auspicare (vs sperare)","translation":"to hope for, to advocate (formal)","ipa":"aus.piˈka.re","example":"Il rettore ha auspicato una collaborazione più stretta tra le due facoltà."},
      {"term":"effettuare (vs fare)","translation":"to carry out, to perform (formal)","ipa":"ef.fet.tuˈa.re","example":"Il pagamento può essere effettuato entro trenta giorni dalla notifica."},
      {"term":"pervenire (vs arrivare)","translation":"to reach, to be received (formal)","ipa":"per.veˈni.re","example":"Le domande devono pervenire alla segreteria entro il quindici settembre."},
      {"term":"comunicare (vs dire)","translation":"to inform, to notify (formal)","ipa":"ko.mu.niˈka.re","example":"Vi comunichiamo che la seduta è rinviata a data da destinarsi."}
   ]}',
   'Italian keeps a sharp line between everyday verbs and their bureaucratic-academic twins. In a CELI formal letter, *chiedere*, *andare*, *fare* are not wrong — they are simply the register examiners mark down. Two cautions: *auspicare* takes *che* + **congiuntivo** (*auspico che si trovi un accordo*), and *pervenire* uses *essere* in compound tenses (*la domanda è pervenuta ieri*). Do not import formal verbs into speech with friends — register works in both directions.', 10),
  (9, 'Capstone: la presentazione di cinque minuti', 'writing',
   '{"sections":[
      {"heading":"Il progetto","text":"The capstone integrates everything in the course: choose a real decision faced by an organization you know — a company, an association, your own team — and design a five-minute presentation in Italian that frames it as a case (facts, tension, recommendation). Deliverables: a one-page outline in Italian (scaletta), a slide plan of at most five slides described in words, and the full text of your opening and closing minute. The middle three minutes stay as bullet points — at C1 you should speak from a scaletta, not read a script."},
      {"heading":"Le tappe — milestones","text":"Work in four milestones. **Tappa 1**: choose the decision and write the case facts in ten sentences, numbers included — if there are no numbers, the case is not ready. **Tappa 2**: draft the scaletta using the tesi-antitesi-sintesi frame from lesson 5, with one slide per move plus title and conclusion. **Tappa 3**: write the opening minute (hook + tesi) and closing minute (sintesi + call to action), using at least three connectors from lesson 3 and one hypothetical of the possibility type. **Tappa 4**: rehearse aloud twice with a timer; anywhere you stumble, simplify the sentence rather than practicing the stumble."},
      {"heading":"Criteri di valutazione","text":"Assess the finished capstone against four weighted criteria, as an exam jury would. **Struttura (30%)**: does the presentation state the decision within the first thirty seconds, and does every section advance the recommendation? **Lingua (30%)**: correct subjunctives in concessive and purpose clauses, hypotheticals well-formed, formal lexicon from lesson 8 where appropriate. **Argomentazione (25%)**: is the strongest counterargument named and answered, not ignored? **Efficacia orale (15%)**: within five minutes, deliverable from the scaletta alone. A presentation scoring below 70% overall is returned for one targeted revision — exactly one, because knowing when to stop revising is itself a C1 skill."}
   ]}',
   null, 15),
  (10, 'C1 checkpoint', 'quiz',
   '{"questions":[
      {"prompt":"Choose the connector: \"___ l''offerta fosse molto generosa, il consiglio di famiglia ha deciso di rifiutarla.\"","options":["Benché","Poiché","Siccome","Perciò"],"answer":0,"explanation":"The imperfect subjunctive *fosse* signals a concessive clause: *benché* (although) is the only option that takes the subjunctive. *Poiché* and *siccome* give causes with the indicative; *perciò* introduces a consequence."},
      {"prompt":"A university notice asks students to go to the main hall. Which verb fits the register?","options":["andare","recarsi","capitare","passare"],"answer":1,"explanation":"*Recarsi* is the formal equivalent of *andare* used in official notices: *i candidati sono pregati di recarsi in aula magna*. The others are either neutral or colloquial in this context."},
      {"prompt":"\"Gli assegni familiari sono cerotti su una frattura,\" writes the editorialist. What is the implied claim?","options":["The allowances are harmful and should be abolished","The allowances treat a symptom and are far too small for the underlying problem","The allowances are the main cause of the fracture","The allowances have already solved the demographic problem"],"answer":1,"explanation":"A plaster on a fracture is a remedy that is real but absurdly inadequate to the injury. The metaphor concedes the allowances exist and help slightly while asserting they cannot address the structural problem — a classic C1 inference item."},
      {"prompt":"Complete: \"Ripeto i dati principali affinché tutti ___ seguire il ragionamento.\"","options":["possono","possa","possano","potrebbero"],"answer":2,"explanation":"*Affinché* (so that) always requires the subjunctive, and the subject *tutti* is plural: *possano*. *Possono* is indicative, *possa* is singular, and the conditional *potrebbero* never follows *affinché*."},
      {"prompt":"Complete the counterfactual: \"Se l''azienda ___ subito al fondo, non avrebbe perso l''occasione.\"","options":["risponderebbe","avesse risposto","rispondesse","aveva risposto"],"answer":1,"explanation":"The main clause has the past conditional (*non avrebbe perso*), so this is an unreal past hypothetical: the *se*-clause takes the *congiuntivo trapassato*, *avesse risposto*. A conditional inside the *se*-clause (*se risponderebbe*) is the classic error examiners penalize."},
      {"prompt":"Choose the condition: \"Accetteremo il franchising ___ la produzione resti interamente a Cuneo.\"","options":["purché","perché","affinché","poiché"],"answer":0,"explanation":"*Purché* (provided that) sets a condition and takes the subjunctive *resti*. *Affinché* would express purpose, not a condition; *perché* + subjunctive can mean purpose but not \"only if\"; *poiché* states a cause with the indicative."}
   ]}',
   null, 12)
) as v(pos, title, kind, body, notes, mins)
where not exists (
  select 1 from public.lessons l
  where l.course_id = 'aaaa0003-0000-4000-8000-000000000004' and l.position = v.pos
);
