#!/usr/bin/env node
// Curriculum Engine — normalization step.
// Reads an interchange JSON file (see schema.json), validates it hard, and
// writes an idempotent seed SQL file in the exact idiom of the existing
// supabase/seed/curriculum/*.sql files.
//
// Usage: node scripts/ingest/build-sql.mjs <interchange.json> [outfile.sql]
// No dependencies.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";

const KINDS = new Set(["vocab","grammar","listening","reading","speaking","roleplay","writing","quiz","code"]);
const SCHOOLS = new Set(["language","math","technology","business","science"]);
const CODE_LANGS = new Set(["javascript","python"]);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

function die(msg) { console.error(`✗ ${msg}`); process.exit(1); }
function q(s) { return String(s).replace(/'/g, "''"); }              // SQL string escape
function jsonLit(obj) { return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`; }

const inFile = process.argv[2];
if (!inFile) die("usage: build-sql.mjs <interchange.json> [outfile.sql]");

let data;
try { data = JSON.parse(readFileSync(inFile, "utf8")); }
catch (e) { die(`cannot parse ${inFile}: ${e.message}`); }

// ---- validate ----
const { source, course, lessons } = data;
if (!source?.id || !source?.name || !source?.license) die("source.{id,name,license} required");
if (!course) die("course required");
if (!UUID.test(course.id || "")) die(`course.id must be a uuid, got "${course.id}"`);
if (!course.title) die("course.title required");
if (!course.description) die("course.description required");
if (!course.description.toLowerCase().includes(source.name.toLowerCase().split(" ")[0].toLowerCase()))
  die(`course.description must credit the source ("${source.name}")`);
if (!SCHOOLS.has(course.school)) die(`course.school invalid: ${course.school}`);
if (!Array.isArray(lessons) || lessons.length === 0) die("lessons[] required");

const seenPos = new Set();
lessons.forEach((l, i) => {
  if (typeof l.position !== "number") die(`lesson[${i}].position must be a number`);
  if (seenPos.has(l.position)) die(`duplicate lesson position ${l.position}`);
  seenPos.add(l.position);
  if (!l.title) die(`lesson[${i}] missing title`);
  if (!KINDS.has(l.kind)) die(`lesson[${i}].kind invalid: ${l.kind}`);
  const b = l.body;
  if (!b || typeof b !== "object") die(`lesson[${i}] (${l.title}) missing body`);
  if (l.kind === "quiz") {
    if (!Array.isArray(b.questions) || b.questions.length === 0) die(`lesson[${i}] quiz needs questions[]`);
    b.questions.forEach((qq, j) => {
      if (!Array.isArray(qq.options) || qq.options.length !== 4) die(`lesson[${i}] q${j}: exactly 4 options`);
      if (!(Number.isInteger(qq.answer) && qq.answer >= 0 && qq.answer <= 3)) die(`lesson[${i}] q${j}: answer 0-3`);
    });
  } else if (l.kind === "vocab") {
    if (!Array.isArray(b.items) || b.items.length === 0) die(`lesson[${i}] vocab needs items[]`);
  } else if (l.kind === "roleplay") {
    if (!b.scenario || !b.goal) die(`lesson[${i}] roleplay needs scenario+goal`);
  } else if (l.kind === "code") {
    if (typeof b.prompt !== "string" || !b.prompt.trim()) die(`lesson[${i}] code needs a prompt`);
    if (typeof b.starter !== "string") die(`lesson[${i}] code needs a starter string`);
    if (b.language != null && !CODE_LANGS.has(String(b.language).toLowerCase()))
      die(`lesson[${i}] code language invalid: ${b.language} (use javascript or python)`);
    if (b.packages != null) {
      if (!Array.isArray(b.packages) || !b.packages.every((p) => typeof p === "string" && p.trim()))
        die(`lesson[${i}] code packages must be an array of strings`);
      if (String(b.language).toLowerCase() !== "python")
        die(`lesson[${i}] code packages are only supported for python lessons`);
    }
    if (!Array.isArray(b.tests) || b.tests.length === 0) die(`lesson[${i}] code needs tests[]`);
    b.tests.forEach((t, j) => {
      if (typeof t.label !== "string" || !t.label.trim()) die(`lesson[${i}] test${j}: label required`);
      if (typeof t.expr !== "string" || !t.expr.trim()) die(`lesson[${i}] test${j}: expr required`);
    });
  } else {
    if (!Array.isArray(b.sections) || b.sections.length === 0) die(`lesson[${i}] ${l.kind} needs sections[]`);
  }
});

// ---- emit ----
const cid = course.id;
const prereqs = (course.prerequisite_ids || []).length
  ? `'{${course.prerequisite_ids.join(",")}}'`
  : "'{}'";
const dialect = course.dialect ? `'${q(course.dialect)}'` : "null";
const cefr = course.cefr_level ? `'${course.cefr_level}'` : "null";

let sql = `-- Generated by scripts/ingest/build-sql.mjs from ${basename(inFile)}\n`;
sql += `-- Source: ${source.name} (${source.license})${source.url ? " — " + source.url : ""}\n`;
sql += `-- Original prose; structure informed by the source. Idempotent.\n\n`;

sql += `insert into public.courses (id, language, dialect, title, description, cefr_level, goal_tag, position, published, school, prerequisite_ids)\n`;
sql += `values ('${cid}', '${q(course.language)}', ${dialect}, '${q(course.title)}', '${q(course.description)}', ${cefr}, '${q(course.goal_tag || "foundations")}', ${course.position | 0}, true, '${course.school}', ${prereqs})\n`;
sql += `on conflict (id) do nothing;\n\n`;

sql += `insert into public.lessons (course_id, position, title, kind, body, grammar_notes_md, estimated_minutes)\n`;
sql += `select '${cid}', v.pos, v.title, v.kind, v.body::jsonb, v.notes, v.mins\n`;
sql += `from (values\n`;
sql += lessons
  .sort((a, b) => a.position - b.position)
  .map((l) => {
    const notes = l.grammar_note ? `'${q(l.grammar_note)}'` : "null";
    return `  (${l.position}, '${q(l.title)}', '${l.kind}', ${jsonLit(l.body)}, ${notes}, ${l.estimated_minutes || 10})`;
  })
  .join(",\n");
sql += `\n) as v(pos, title, kind, body, notes, mins)\n`;
sql += `where not exists (\n`;
sql += `  select 1 from public.lessons l\n`;
sql += `  where l.course_id = '${cid}' and l.position = v.pos\n`;
sql += `);\n`;

// slug from course title
const slug = (course.title || basename(inFile))
  .toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 40);
const outFile = process.argv[3] || join("supabase/seed/curriculum", `${slug}.sql`);
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, sql);
console.log(`✓ ${lessons.length} lessons → ${outFile}`);
